[MJ]미션: 체스판 초기화
codesquad-members-2021/java-chess pull request #101
Opened 2021-02-17 08:36 UTC by MJbae

안녕하세요~ MJ입니다.
이번 리뷰도 잘 부탁드립니다!

**Console**
- 사용자 입력(start, end or else)에 따라 startGame(), endGame() 메소드를 실행합니다.
- startGame(): 체스게임을 초기화하고 현재 상태를 출력합니다.
- endGame(): 게임의 종료 메시지를 출력합니다.

**Board**
- initialize(): 내부 메소드 initPawns()를 호출하여 List pawns에 Pawn을 추가했습니다. 이어서 StringBuilder에 Pawn의 표현문자를 합치고 String[] cellsOfBoard에 StringBuilderd의 toString() 반환값을 삽입하였습니다.
- getRowOfBlackPawns(), getRowOfWhitePawns(): 초기화한 흰색폰과 검은색폰의 초기상태를 출력합니다.

**Pawn**
- 폰의 생성자에서 폰의 색깔을 결정하는 매개변수에 따라 표현문자(representation)도 결정합니다.

**BoardTest**
- initialize() 호출에 따라 흰색과 검은색 폰의 표현문자가 8개씩 합쳐져서 출력되는 지 확인합니다.

감사합니다~

2021-02-17 15:56 UTC, LarryJung requested changes
수고하셨습니다~! 요구사항 대로 잘 구현하셨구요, 이런저런 코멘트를 좀 드렸으니 확인 부탁드립니다. :)

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    private final StringBuilder rowOfWhitePawns = new StringBuilder();
만약.. 체스게임을 진행하면서 기물(현재는 pawn)의 색깔이 바뀐다던지? 위치가 바뀌었을때? rowOfBlackPawns과 같은 출력물에 대한 것도 다시 업데이트를 해주어야겠죠? 

그런 관점에서 Board가 가지고 있어야 할 아주 코어한 데이터가 어떤 이유에서 변동이 있을때마다 관련된 필드들(rowOfBlackPawns, rowOfWhitePawns, cellsOfBoard) 들을 업데이트 하는 것은 손이 많이 갈 것 같기도 한데요,

혹시 아래 print(), getRowOfBlackPawns(), getRowOfWhitePawns() 를 호출할 때 이미 만들어놓은 값을 활용하여 심플하게 리턴하지 않고 메서드 호출 시점에 가진 기물을 가지고 프린트하는 로직을 돌리는 것은 생각해 보셨나요?

OOP는 왠지 관련된 데이터를 클래스라는 한 묶음으로 두고 최대한 일을 많이 시키는게 중요합니다.ㅎㅎ

static final 필드 제외하고 멤버 변수를 pawns 만 둘 수 밖에 없다면 어떻게 짤 수 있을지 고민해 보세요!

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
리팩토링을 해보자면.. 

```suggestion
    public void initialize() {
        initPawns(Color.WHITE);
        initPawns(Color.BLACK);
        initCellsOfBoard();
    }

    private void initPawns(Color color, int nthRow) {
        for (int i = 0; i < MAX_SIZE; i++) {
            pawns.add(new Pawn(color));
        }
    }
    
    private void initCellsOfBoard() {
      cellsOfBoard[WHITE_PAWN_ROW] = pawns.stream().filter(p -> p.isColor(Color.WHITE)).map(p -> p.getRepre()).joinString() 
      cellsOfBoard[BLACK_PAWN_ROW] = pawns.stream().filter(p -> p.isColor(Color.BLACK)).map(p -> p.getRepre()).joinString()
    }
```

코드로 직접 리뷰를 드리기보다 생각할 것을 던져드리려고 했는데.. 쓰다보니 코드를 적어버렸네요 ㅎㅎ
제가 하고 싶은 말은 initPawns메서드가 일단 두가지 일을 하고 있는 것으로 보였구요,

1. pawns을 넣는 부분
2.cells 초기화 하는 부분

기능 분리를 좀 해봤고.. (여기서 힌트는 메서드 인자가 3,4개 이상 넘어가고 있다면 어딘지 쓰이는 곳이 많다는 사인일 수도 있습니다.) 

그리고 initPawns 메서드에서 color가 지정된 Pawn의 getRepresentation() 메서드가 있음에도 initPawns에 char 를 인자로 넘겨서 pawn 객체를 충분히 활용하고 있지 못한 점이 아쉽네요 ㅠ 

제가 예시로 코드를 드렸는데 한번 살펴봐 주시고, 어떤 장,단점이 있을지 의견을 주시면 좋을것 같습니다.!

(코드는 좀 의사(psuedo)코드라 정확하지 않습니다. 정답도 아니구요!)

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
위에도 언급드렸듯이 요때 pawns를 가지고 로직을 돌린다면..? rowOfBlackPawns 멤버 변수는 없어도 되지 않을까요?

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
아 그리고 내부에서 사용하고 있으니 private으로 바꿔주세요~

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
추가 코멘트 드리면 파라미터 컨벤션을 지켜주세요!

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
print() 가 프린트를 하고 있지만, 혹시 println 은 콘솔쪽으로 위임하고, Board는 문자열만 리턴하게 하면 어떤 장점이 있을까요?

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/pieces/Pawn.java
> +        this.representation = (color == Color.BLACK) ? BLACK_REPRESENTATION : WHITE_REPRESENTATION;
현재 요구사항에서는 문제가 없지만! Board와 비슷하게 representation을 멤버 변수로 두지 않고, getRepresentation() 그때그때 계산해서 값을 반환한다면 color가 바뀌어도 다른 로직을 수정할 필요가 없다는게 장점일거라 생각이 드네요~

어떻게 하는게 더 코드관리에 용이할지 생각해봐주세요 ㅎㅎ

2021-02-17 15:56 UTC, LarryJung commented on src/main/java/mj/chess/pieces/Pawn.java
> +}
파일 끝 개행 추가해주세요!

2021-02-18 04:59 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +    private final StringBuilder rowOfWhitePawns = new StringBuilder();
리뷰에 따라 제 코드를 붙잡고 고민해보니, List pawns만으로 구현할 수 있는 로직에 불필요한 변수를 사용하는 부분이 많았습니다. 
List pawns를 기반으로 stream을 활용하여 Board getRowOfPawns()의 내부 로직을 개선하였습니다.

```java
public String getRowOfPawns(Color color) {
    return pawns.stream()
            .filter(pawn -> pawn.getColor() == color)
            .map(Pawn::getRepresentation)
            .map(Object::toString)
            .collect(joining());
}
```

2021-02-18 05:04 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +    }
본 리뷰에서 Larry가 강조하는 건 코드의 재사용성으로 이해했습니다. 코드의 재사용성을 높이는 것의 장점을 세 가지로 정리했습니다. 
1. 성능향상, JVM의 Execution Engine 중 JIT Compiler는 한 번 읽어드린 코드에 대해서는 line by line이 아니라 한 번에 실행합니다. 따라서 재사용되는 코드가 많을 수록 프로그램 전체의 성능은 향상됩니다.
2. 수정작업 시 효율성 증가, 코드의 재사용률이 높으면 수정사항이 발생해도 개발자가 일일이 변경할 코드의 양은 줄어들 것입니다.
3. 에러 발생 감소, 사람이 개발하는 이상 인간적인 실수가 발생할 수 있습니다. 사람이 일일이 건드는 변수의 양을 줄이고 반복적으로 사용하는 코드가 많아진다면 인간적인 실수도 함께 줄 것입니다.

단점은 아무래도 재사용을 하기 위해 다른 클래스의 코드를 가져와야 하기 때문에 코드의 간결성이 떨어진다는 것으로 볼 수 있습니다. 하지만 이것도 어떻게 재사용하는지에 따라서 오히려 간결해질 수 있습니다.

2021-02-18 05:06 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +    }
1. 해당 메소드를 public으로 설정한 이유는 테스트 코드에서 사용하기 때문입니다. 
2. pawns에 스트림을 활용하니까 rowOfBlackPawns가 필요 없어졌습니다! ㅎㅎ

2021-02-18 05:06 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +    }
코드관리에 이점이 있습니다. 출력도 하나의 기능이므로 출력을 전담하는 객체를 두는 것이 추후 전체적인 코드 관리면에 이롭습니다. 출력부분을 Board에서 Console로 이동했습니다.

2021-02-18 05:10 UTC, MJbae commented on src/main/java/mj/chess/pieces/Pawn.java
> +}
개행문자를 추가해야하는 이유는 POSIX 명세, 일종의 표준을 지켜서 다른 프로그램과의 호환 시 에러의 발생 가능성을 제거하기 위해서군요!

2021-02-18 05:11 UTC, MJbae commented
@LarryJung Larry의 리뷰에 진심으로 감사합니다. 덕분에 머리로 이해만 하고 있던 부분을 실제 코드로 구현해보면서 체득할 수 있었습니다.

2021-02-18 05:12 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +    }
혹시 Larry의 의도는 테스트에 사용할 메소드의 경우 package-private으로 설정하라는 것으로 이해해도 될까요?

2021-02-18 05:13 UTC, MJbae commented on src/main/java/mj/chess/pieces/Pawn.java
> +        this.representation = (color == Color.BLACK) ? BLACK_REPRESENTATION : WHITE_REPRESENTATION;
코드의 재사용성을 높이기 위해 getRepresentation()을 사용하는 것이 적절하겠네요!

2021-02-19 09:34 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +    }
아 넵 테스트에서 사용한다면 package-private으로 둬도 괜찮습니다.^^

2021-02-19 09:39 UTC, LarryJung requested changes

2021-02-19 09:39 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +                .map(Object::toString)
map 을 두번 연속으로 하게 되면 객체 생성 비용이 들기 때문에 map 은 하나도 모아주는것이 좋습니다^^

2021-02-19 09:41 UTC, LarryJung requested changes

2021-02-19 09:41 UTC, LarryJung commented on src/main/java/mj/chess/Board.java
> +        }
나중에 남몰래 Color가 추가된다면 이쪽에 원치않는 결과가 나올 수도 있는데, switch 를 통해 white, black 을 확실하게 정해주는것은 어떨까요?

2021-02-19 09:42 UTC, LarryJung commented
코드 수정하시느라 고생하셨습니다.^^ 제 기준에는 많이 간결해지고 가독성도 좋아진 느낌인데 어떻게 생각하실 지 모르겠네요 ㅎㅎ 
마이너한 리뷰 추가로 드렸으니 참고하시고 다음단계 넘어가셔도 될듯 합니다~

2021-02-19 09:43 UTC, LarryJung approved these changes

2021-02-19 12:24 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +                .map(Object::toString)
그렇군요! 스트림을 더 공부해봐야겠습니다!

2021-02-19 12:30 UTC, MJbae commented on src/main/java/mj/chess/Board.java
> +        }
else로 넘기지 말고 확실하게 조건을 걸고 처리하라는 말씀이시군요! 생각해보니 Color를 건든다면 의도치 않은 결과로 이어질 수 있겠네요! 좋은 지적 감사합니다 :)

2021-02-19 12:36 UTC, MJbae commented
> 코드 수정하시느라 고생하셨습니다.^^ 제 기준에는 많이 간결해지고 가독성도 좋아진 느낌인데 어떻게 생각하실 지 모르겠네요 ㅎㅎ
> 마이너한 리뷰 추가로 드렸으니 참고하시고 다음단계 넘어가셔도 될듯 합니다~

Larry 도움으로 이전에 고려하지 않았던 부분을 고민하면서 코드를 작성하게 되었습니다. 특히 코드의 재사용과 변경사항에 대처할 수 있는 여지를 남겨야한다는 것이 이번 리뷰에서 가장 크게 배운 부분입니다. 감사합니다~

2021-02-20 12:15 UTC, merged