[Bongf]미션 3 : 체스판초기화
codesquad-members-2021/java-chess pull request #105
Opened 2021-02-17 11:12 UTC by bong6981

안녕하세요. 백엔드반 Bongf입니다. 부족한 코드 피드백 주셔서 감사하다는 말씀 드립니다. 
코드를 계속해서 수정하다 보니 커밋이 너무 많고, 두서 없습니다. 
다음 번엔 수정도 관련있는 것들끼리 묶어 커밋하는 방식으로 시도해보겠습니다. ( 코드 처음에 작성할 때 더 깔끔하게 작성해야겠다는 생각이 들었습니다. )
---
고민 되었던 부분은 색의 representation을 어디에 작성할 것 인가 이었습니다. 
- 우선은 색에 따라 respresentation이 나뉘게 되고, 아직은 다른 말이 없어 representation이 p/P 밖에 없어 Color 클래스에서 선언해도 될 것 같아 Color에 작성하였습니다. 
- 접근제어자는 최대한 좁게 설정하여 메소드의 접근제어자도 private으로 설정하였다가, test를 위해서 default로 바꿨습니다. 
    - 관련 내용을 학습했을 때는 왜 private 메소드가 되어야 하는지 생각해 보라는 답을 얻어 이에 대해 고민하게 되었습니다.   
    - 이 메소드들이 game을 시작하면 계속 사용될 것이라 생각되어 public으로 설정했고, 다만 클래스 내부에서 사용되는 메소드들에 대해서만 private으로 설정했습니다.

2021-02-18 01:17 UTC, LarryJung requested changes
수고 많으셨습니다~ 전체적으로 코드가 눈에 잘 보이고 깔끔하게 짜려고 노력하신게 느껴졌습니다.

다만 color 의 representaion을 활용하는 부분에서 조금 아쉬웠구요! 코멘트 드렸으니 참고하셔서 수정부탁드립니다ㅎㅎ

2021-02-18 01:17 UTC, LarryJung commented on src/main/java/chess/Board.java
> +    }
if 문으로 체크하는 부분은 잘 하셨습니다! ㅎㅎ 
한마디 덧붙여보자면.. 색이 다른 경우는 exception을 발생한다던지? 아니면 올바른 add를 했다는 의미로 true, false 등을 리턴하는 식으로 정보를 추가해주어도 좋을 것 같습니다. (add 실행 후 결과처리할 때도 확실하고, 테스트할때도 써먹을 수 있고용)

2021-02-18 01:17 UTC, LarryJung commented on src/main/java/chess/Board.java
> +        System.out.println(result);
board의 print()는 String 만 리턴하고, System.out.println을 사용하는 출력기능은 ChessGame쪽에서 담당하게 하면 어떨까요?

현재 요구사항에서는 충분히 괜찮지만.. 나중에 게임화면 출력용 ui앱을 만든다고 하면.. 게임로직과 입출력은 한 클래스에 있는 것보다는 분리하는게 나을것 같네요! (당장 안하셔도 되고ㅎㅎ 나중에 복잡성이 늘어나면 입출력 로직을 떼어낼 수도 있겠다라는 생각 가지고 계시면 좋을것 같네용)

2021-02-18 01:17 UTC, LarryJung commented on src/main/java/pieces/Color.java
> +
현재는 이렇게 가셔도 깔끔하고 좋습니다 ㅎㅎ

2021-02-18 01:17 UTC, LarryJung commented on src/main/java/pieces/Pawn.java
> +    private final char Representation;
representation은 불필요한 멤버 변수입니다. (변수이름이 대문자..!)

color 객체가 representation 값을 가지고 있으니 꼭 pawn이 가지고 있어야 할 필요는 없어 보이네요.
오히려 pawn의 color가 바뀌었을때 representation을 재할당 해줘야 하는점에서 오류가 생길 수 있기도 하고요~

2021-02-18 01:17 UTC, LarryJung commented on src/main/java/pieces/Pawn.java
> +    }
`return this.color.getRepresentation()` 이면 충분하겠죠?

2021-02-18 01:17 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +        board.print();
board.print() 를 제대로 테스트하고 있지 못한 것 같네요~ 테스트코드는 print()가 어떻게 나오든 assert로 검사하는게 없으니 무조건 통과가 될 것 같은데요~ 이럴 때 board.print()가 출력물 String을 return 한다면? 테스트를 할 수 있을 것 같은데..

public void 메서드를 작성할 때 이것을 어떻게 테스트 할 수 있을지 염두하시는 것은 매우 좋은 습관입니다!

2021-02-18 01:17 UTC, LarryJung commented on src/test/java/pieces/PawnTest.java
> +        );
color 객체가 가진 정보가 있는데 verifyPawn에 representation 인자가 추가된 점이 아쉽습니다! 
OOP 하실때 객체가 가진 정보(멤버 변수)를 스스로 잘 활용하게(메서드) 하도록 신경써 주세요~! 
다소 추상적인 이야기지만 인사이트가 되었으면 좋겠습니다. ㅎㅎ

```java
verifyPawn(Color.WHITE);
verifyPawn(Color.BLACK);

void verifyPawn(Color color) {
    Pawn pawn = new Pawn(color);
    assertAll(
                () -> assertThat(pawn.getColor()).isEqualTo(color),
                () -> assertThat(pawn.getRepresentation()).isEqualTo(color.getRepresentation())
        );
}
```

2021-02-18 08:35 UTC, bong6981 commented on src/main/java/chess/Board.java
> +    }
말씀주신 대로 예외를 발생시켰고, test도 해보았습니다.!

2021-02-18 08:36 UTC, bong6981 commented on src/main/java/chess/Board.java
> +        System.out.println(result);
오! 맞는 말씀입니다.  다음단계에서 반영해보도록 하겠습니다. 지금은 우선 밑에 코멘트  test 코드에서 print를 하도록 바꾸었습니다. 그리고 수정과정에서 조건을 읽다보니 string으로 반환하고 이를 test 코드에서 출력한다는 부분이 있어 현재는 print() 메소드에는 System.out.println부분을 제거했습니다.  게임화면 출력 ui를 만들 때에는 반드시 분리해야겠다는 생각이들었습니다. 감사합니다.

2021-02-18 08:36 UTC, bong6981 commented on src/main/java/pieces/Pawn.java
> +    private final char Representation;
헉. ColorRepresentation 에서 수정을 하다 발생한 오류 같습니다. 조금 더 꼼꼼하게 작성하겠습니다.

representation을 어디에 둘 것인지에 대한 고민의 잘못된 결과로 이렇게 될 것 같습니다.
말씀해 주신 대로 생각해보니 
- Color 에 따라서 representation을 갖고 있으니
-  Pawn이 Color 값을 가지면 그에 따라 자동으로 representation을 갖게 된 것이네요 
재할당해줘야 하는 이유가 전혀 없었네요 
코드 실행 결과에만 급급하다보니 나오게된 결과 같습니다.
앞으로는 로직을 좀 더 먼저 생각해보아야 할 것 같습니다.!

2021-02-18 08:36 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +        board.print();
어떻게 test할지 더 고민해보겠습니다! 사실 처음에는 String을 return하겠다고 짰다가 가이드 코드가 위와 같이 되어 있다고 해서 이런 의도였군! 하면서 수정했습니다.  하지만 조건을 꼼꼼히 읽어보니, '테스트 코드에서 반환한 값을 System.out.println으로 출력한다.' 부분을 확인할 수 있었습니다. 앞으로는 조건을 더 꼼꼼히 읽겠습니다. 코멘트 덕분에 print 메서드는 어떻게 테스트하는지도 조금이지만 공부할 수 있었습니다. 감사합니다 : )

2021-02-18 08:36 UTC, bong6981 commented on src/test/java/pieces/PawnTest.java
> +        );
Color로 지정해 두었는데 이렇게 쓸 생각을 못했네요! 아직은 명확히 이해하지 못했지만, 'OOP 할 때 객체가 가진 정보를 스스로 잘 활용하게 하자.  test 코드에도 새로운 변수를 선언하기 보다는 객체들을 활용할 수 있도록 하자' 정도로 이해하고 적용해보겠습니다! 이해 안가는 부분도 좀 더 공부해보겠습니다 : )

2021-02-18 08:37 UTC, bong6981 commented
말씀주신대로 수정사항 반영했습니다. 
틀린 부분을 정확히(따뜻한 온도로..) 짚어 주셔서 코드가 깔끔해지고 오류도 수정된 것 같습니다. 감사합니다.
말씀주신 부분에 대해 미흡한 점이 많아 앞으로도 더 학습해보도록 하겠습니다.

---

[수정사항]
1. addWhite/BlackPawn() 에 잘못된 색 입력하였을 때, 예외 발생하도록 구현
  - 예외를 발생시키지 않으면, 해당 메소드에 잘못된 값을 입력했다는 알림(?)이 없어 이를 추가하고 이 예외 발생 부분을 test 코드에서 확인함 

2. print()메서드에서 String을 return하게 하고, 이를 test코드에서 확인
- 미션 조건을 꼼꼼히 읽어보았을 때 구현 조건에도 더 맞는 것이라는 것을 확인
-게임로직과 입출력을 분리하는 조건에 대해서도 고심해야 함. 

3. Representation 변수 삭제 
- 오타로 대문자를 갖고 있던 변수 삭제 
-  해당 변수가 사실 enum Color에 구현되어 있어 필요없는 부분이었음에도 구현한 불필요한 부분이라 삭제 
- Color를 활용

4.  test코드에도 respresentation을 'p'/'P'로 하드코딩하지 않고 Color에 있는 값으로 활용함 
- '객체가 가진 정보(멤버 변수)를 스스로 잘 활용하게(메서드) 하도록 신경쓰기'에 대해서 학습하고 숙지해야 함

2021-02-18 10:38 UTC, bong6981 commented on src/main/java/pieces/Pawn.java
> +    }
위에 주신 코멘트와 함게 수정했습니다~!

2021-02-19 09:46 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +        board.print();
넵 프린트 뿐 아니라 앞으로 로직 짜실 때 값을 반환하지 않는 void메서드를 자주 작성하실 텐데 그때 꼭 void가 필요한지? 구조를 다르게 해서 return 을 하게하면 어떨지? 많이 고민해보세요!

2021-02-19 09:53 UTC, LarryJung approved these changes
수정사항 확인했습니다~ 수고하셨구요! 코멘트를 조금 드리긴 했는데 다음 단계 하셔도 좋을것 같습니다!^^

2021-02-19 09:53 UTC, LarryJung commented on src/main/java/chess/Board.java
> +            throw new InvalidParameterException("pawn의 색을 확인해 주세요");
어떤 색깔이 넘어왔는지 메세지 안에 포함시켜줘도 좋습니다. ㅎㅎ

2021-02-19 09:53 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +import java.security.InvalidParameterException;
InvalidParameterException <- 가져다 쓰고 싶게 생긴 익셉션 이름이긴 한데요, 

독스 들어가보시면 자바 시큐리티 모듈 내 암호화 관련 로직에 자기네들이 쓰려고 만든 일종의 커스텀 익셉션입니다..ㅎㅎ

java.lang 에 들어있는 IllegalArgumentException을 사용하는것이 더 일반적입니다~

2021-02-19 11:21 UTC, merged

2021-02-19 11:24 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +        board.print();
네 void 메서드 작성할 때마다 고민해보겠습니다!

2021-02-19 11:25 UTC, bong6981 commented on src/main/java/chess/Board.java
> +            throw new InvalidParameterException("pawn의 색을 확인해 주세요");
다음 미션에서 해당 부분 수정하겠습니다~!

2021-02-19 11:26 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +import java.security.InvalidParameterException;
오 둘 중에 하나를 고민했는데 학습이 부족했던 결과입니다. 더 학습하고 수정하겠습니다~!