[Roach] 미션 4: 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #111
Opened 2021-02-18 09:10 UTC by tmdgusya

미션 4 는 조금의 학습 용도로 작성된것도 있습니다.
PieceList 같은 경우도 Board 에서 List 에서 말을 찾거나 하는 과정들이 포함되어 있기에, 이런 책임도 보드가 하는것은 아닌것 같다고 생각하여 
PieceList 로 분할하였습니다. 그래서 Board 에서는 PieceList 의 메소드들을 이용해서 간단하게 원하는 말들을 찾을 수 있도록 하였습니다.

StringUtils 의 append 같은 경우도 static method 로 이용할 수 있도록 요구사항에 적혀있어 필드또한 static 하게 하였고,
이를 print() 할때 `getBoardStatusToString` 이 작동되어서 중복이 되는 경우가 있어 init() 으로 초기화 할 수 있도록 하였습니다.

뭔가 나눌때 분리하다보니, 아직 미숙한 점을 많이 느끼는 것 같습니다.
1. init() 과 같은 초기화 메소드 없이는 불가능한가? => 이점은 static 이 아니면 가능할 것 같기도 한데 아직은 잘 모르겠습니다.
2. PieceList 를 나눴을때 이점은 ? Board 안에서 List 에서 특정 조건으로 찾는 로직들이 Board 보다는 PieceList 에서 관리하는게 맞다고 생각했고, 조건탐색 로직등의 코드를 덜어낼 수 있었음 => 근데 Board 에 있었을때가 나은가? PieceList 로 나눠졌을때가 더 나은가? 라고 했을때는 편의성 ? 유지보수 ? 이정도 말고는 이점을 생각해 내긴 힘들었습니다. 다만 저 이점 두개로도 나눌만 하다고는 생각을 하긴 하였는데.. 아직 옳은 것인지는 잘 모르겠습니다.

2021-02-19 01:11 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/PieceList.java
> +        return Collections.unmodifiableList(pieceList);
unmodifiableList 로 list 를 넘겨주는 이유는 외부에서 add remove 등의 메소드로 접근하는 일이 없도록 하기 위해서 아래와 같이 선언했습니다. 객체를 통해서만 list 에 접근할 수 있도록 했습니다.

2021-02-19 08:02 UTC, SANGCO requested changes
Roachs님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      private static final int initialSpaceInterval = 4;
이런 정보들은 지역변수로 만들어서 사용하는건 어떨까요?

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
`PieceList`라는 클래스를 만드셨네요.
우선 클래스 이름에 `List`가 붙는거 보다 `Pieces`가 어떨까 하는 생각이 들구요.

제가 보기에는 지금 Board 클래스가 너무 좀 지저분하다? 장황하다?
`Board` 클래스를 같이 수정해 봅시다.

여기 코드를 보면 흰색 피스, 검은색 피스로 나눠서 관리를 하시겠다는 의도인거 같은데
단순히 흰색, 검은색으로만 나누기 보다는 
흰색, 검은색, 흰색 폰, 검은색 폰으로 나누는게 어떨까 하는 생각이 드네요.
그러면 `Piece` 클래스에 `getStringPiecesList(int startIndex, int endIndex)` 같은 메서드가 필요가 없어지겠죠?
밑에서도 피드백으로 드리겠지만 이부분이 굉장히 지저분해 보였거든요.

그리고 이왕에 `PieceList`를 만드셨다면 만드신 클래스를 적극 활용하는게 좋을거 같습니다.
이와 관련된 피드백은 밑에다 남길게요.

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
이렇게 숫자를 넘겨서 String을 받아 오는거 보다는 위에서 언급한거 처럼
차라리 `PieceList`를 4개 만들고 
```java
public String getWhitePawnsResult() {
    return whitePieceList.getString()
}
```
뭐 이런식으로 반환하는 메서드 4개를 만드는게 더 깔끔할거 같은데 어떻게 생각하시나요~

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
> print() 할때 getBoardStatusToString 이 작동되어서 중복이 되는 경우가 있어 init() 으로 초기화 할 수 있도록 하였습니다.

`StringUtils` 클래스에 `StringBuilder`가 있군요.
유틸성 클래스에서 클래스 변수를 가지게 하지말고
`getBoardStatusToString()`에서 `StringBuilder`를 지역변수로 가진다면
`print()` 메서드도 없앨 수 있을거 같은데요?
간단히 문자열을 합치는 거지만 `StringBuilder`를 사용하고 싶으시면
파라미터로 `StringBuilder`를 넘길 수도 있겠죠?

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
기왕에 만든거 'PieceList'를 적극 활용해 봅시다!
`PieceList` 그냥 `Pieces` 라고 할게요. 

`Pieces`에  정적 팩토리 메서드들을 만들어 보는건 어떨까요?
그래서 `Board` 클래스에서 `Pieces` 클래스에게 요청을 하는거죠.
'리스트에 검은색 폰 8개 넣어서 반환해줘' 뭐 이런식으로

제 설명이 좀 이해가 안되실 수도 있을거 같은데 댓글로 우리 소통합시다.
이해 안되시는거 있으시면 댓글 남겨주세요~

정적 팩토리 메서드는 이펙티브 자바 [아이템 1. 생성자 대신 정적 팩터리 메서드를 고려하라.] 참고 하셔도 좋을거 같네요.
이것도 도움이 되실거 같아서 링크 남깁니다. [일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/util/PieceList.java
> +        return Collections.unmodifiableList(pieceList);
> 객체를 통해서만 list 에 접근할 수 있도록 했습니다.

객체를 통해서만 list를 수정할 수 있게 의도 하셨다는 거죠?

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/util/StringUtils.java
> +    private static StringBuilder sb = new StringBuilder();
위에서 언급했던 부분입니다.
유틸 클래스에 있을 필요가 있을까요?

2021-02-19 08:02 UTC, SANGCO commented on src/main/java/net/honux/chess/util/StringUtils.java
> +    }
이 메서드도 리팩토링 과정에서 쓸모가 없어지지 않을까 싶은데요.

2021-02-19 08:02 UTC, SANGCO commented on src/test/java/net/honux/chess/core/BoardTest.java
> +                () -> assertThat(board.findBlackPawn(Board.BOARD_SIZE*2).get()).isEqualTo(blackPawn)
`Board.BOARD_SIZE * 2 + 1`
중간에 공백을 다 두셔야 합니다.

2021-02-19 08:02 UTC, SANGCO commented on src/test/java/net/honux/chess/core/BoardTest.java
>          );
"pppppppp", "PPPPPPPP", "RNBQKBNR", "rnbqkbnr"
요런거 테스트 클래스 내부에서 상수로 빼서 사용하면 더 좋지 않을까요?

2021-02-19 08:16 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      private static final int initialSpaceInterval = 4;
그게 나을 것 같네요. 굳이 static 변수로서 있을 이유가 없는 것 같습니다.
단순히 메소드 시에만 생성되고 사라지는 지역변수로서 있으면 메모리상으로도 훨씬 좋을 것 같네요.

2021-02-20 11:08 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
색깔 별로 분리하려했는데 Pawn 도 따로 분리하는 것이 깔끔할것 같군요 감사합니다!

2021-02-20 11:09 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
그것도 좋은 방법일거 같고 , 하나 떠오르는건 아래와 같이 해서 list 를 받아서 해도될것 같네요!
```java
private String getStringPiecesResult(Pieces pieces) {
        StringBuilder sb = new StringBuilder();
        for(Piece p : pieces.getPieceList()){
            sb.append(p.getRepresentation());
        }
        return sb.toString();
    }
```

2021-02-20 11:11 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
아 상코 말대로 Pieces 에 getString() 으로 해서 하니 더깔끔해지네요.
```java
public String getString() {
        StringBuilder sb = new StringBuilder();
        for(Piece p : this.pieceList){
            sb.append(p.getRepresentation());
        }
        return sb.toString();
    }

private String getStringPiecesResult(Pieces pieces) {
        return pieces.getString();
    }
```

2021-02-20 11:14 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
오 좋은 방법인것 같네요. 정적 메소드를 이용할때 지역변수의 이용방법을 숙지해둬야겠네요.

2021-02-20 11:21 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
아래와 같이 진행하였습니다. 저 링크글은 진짜 좋은글이네요! :)

이렇게 하니 Pices 를 만든 진짜 목적 그대로 이용되고 있는 것 같네요. 메인 로직에서의 분리와 List 단위의 반복작업이 분리된것 같네요!
해당 부분은 조금 더 공부해봐야할듯 합니다!

```java
private void addPiecesToBoardSize() {
        blackPieces = Pieces.createBlackPiecesExceptPawns();
        blackPawns = Pieces.createBlackPawns();
        whitePawns = Pieces.createWhitePawns();
        whitePieces = Pieces.createWhitePiecesExceptPawns();
    }
```

2021-02-20 11:22 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/PieceList.java
> +        return Collections.unmodifiableList(pieceList);
네 객체를 통해서만 접근이 가능해야 나중에 검증로직같은 것을 거칠수 있을것이고,
Collection을 클래스로 랩핑한 이유가 합당하다고 생각되었습니다.

2021-02-20 11:23 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/StringUtils.java
> +    }
네 리뷰과정을 반영하다보니 사라지게 되었네요.

2021-02-20 11:26 UTC, tmdgusya commented on src/test/java/net/honux/chess/core/BoardTest.java
> +                () -> assertThat(board.findBlackPawn(Board.BOARD_SIZE*2).get()).isEqualTo(blackPawn)
네 가독성을 위해서 떨어뜨리는게 좋겠군요.
세심한 부분 리뷰 감사합니다 👍

2021-02-20 11:28 UTC, tmdgusya commented on src/test/java/net/honux/chess/core/BoardTest.java
>          );
## 리뷰 과정 중 checkBoardPrintMessage() 만 유지

- 원래 각 Pieces 의 Result 도 보는 Test 가 이루어졌으나, checkBoardPrintMessage() 를 통해서 한번에 테스트가 가능하다는 것을 알게되었습니다. 그래서 해당 부분 테스트를 하나로 통일하였고, 코드가 변경되면서 아직까지는 상수로 빼진 않아도 될듯합니다.

2021-02-20 11:28 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/StringUtils.java
> +    private static StringBuilder sb = new StringBuilder();
StringBuilder 는 필요없을 것 같으나, NEWLINE 은 Util 클래스에 있어도 된다고 생각합니다.

2021-02-20 11:47 UTC, tmdgusya commented
@SANGCO 리뷰 반영 내용을 커밋에 담아서 반영하였습니다.

1급 컬렉션 관련 내용은 상당히 흥미있었습니다. 
앞으로 많이 애용해야겠다는 생각이 들었습니다. 유지보수와 중복코드 모두 챙길수 있는 이점이 있다고 생각되었습니다. 
👍

2021-02-20 11:48 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/PieceList.java
> +        return Collections.unmodifiableList(pieceList);
비즈니스 로직을 Pieces 로 옮기다보니 getPieceList() 라는 메소드도 없어지게 되었습니다. 
기존에는 iterator 를 사용하기 위해 사용했는데, 정적 팩토리 메소드로 Pieces 에서 Pieces 를 만들어주게되면서 필요없어지게 되어서 삭제하였습니다

2021-02-20 14:57 UTC, SANGCO requested changes
몇 가지 추가로 리뷰 남깁니다~

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
> +    }
이 private 메서드를 사용하는 메서드 밑으로 이동시켜 주세요~

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
> +    }
whitePawns, blackPawns에 넣을 때는 어떻게 하나요?

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/util/Pieces.java
> +package net.honux.chess.util;
Pieces가 유틸성 클래스 일까요?

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
이거는 피드백은 아니고 제 개인적인 스타일인데 
한줄로 세우는게 더 보기 깔끔하지 않나요?ㅋ

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
> +        addPiecesToBoardSize();
```java
whitePieces = createWhitePiecesExceptPawns();
blackPieces = createBlackPiecesExceptPawns();
whitePawns = createWhitePawns();
blackPawns = createBlackPawns();
```

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
없어도 되겠죠?

2021-02-20 14:57 UTC, SANGCO commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
이 구조면 add()만 계속 호출하면 한도 끝도 없이 List가 길어 질수도 있겠네요.

2021-02-20 14:57 UTC, SANGCO commented on src/test/java/net/honux/chess/core/BoardTest.java
> +                "RNBQKBNR" + StringUtils.NEWLINE +
요런거는 StringUtils static import 하면 깔끔하게 쓸 수 있습니다!

2021-02-20 15:06 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
아 위의 답글을 보니 없어도 되겠군요. 괜한 코드 중복.. 지적해주셔서 감사합니다.

2021-02-20 15:08 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +package net.honux.chess.util;
List 라 생각해서 유틸성 클래스라 생각했는데 혹시 어떤 패키지라고 생각되시나요?

2021-02-20 15:09 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
그 부분은 representation 으로 구분지어야 할듯하네요.

2021-02-20 15:10 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
지금 한번해봤는데 한줄로 세우는 게 깔끔해 보이긴하네요.
딱 접기 누르니까 뭔가 그럴 듯 하네요 :)

2021-02-20 15:11 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
흐음 그렇다면 close 같은 함수를 호출하는게 좋을까요? 아니면 그냥 add 에서 this 를 호출하지 못하도록 할까요?
설계 목적상 계속 호출하려고 한것도 있어서.. 이부분은 어떻게 처리해야할지 감이 안오네요

2021-02-20 15:15 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
```java
 private Pieces getListByColor(Piece piece) {
        if (piece.isBlack()) {
            if(piece.getRepresentation() == BLACK_PAWN_REPRESENTATION) {
                return blackPawns;
            }
            return blackPieces;
        }
        if (piece.isWhite() && piece.getRepresentation() == WHITE_PAWN_REPRESENTATION) {
                return whitePawns;
        }
        return whitePieces;
    }
```

2021-02-20 15:17 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
```java
        if (piece.isBlack() && piece.getRepresentation() == BLACK_PAWN_REPRESENTATION) {
            return blackPawns;
        }
        if (piece.isWhite() && piece.getRepresentation() == WHITE_PAWN_REPRESENTATION) {
            return whitePawns;
        }
        return piece.isBlack() ? blackPieces : whitePieces;
```

2021-02-20 15:17 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
두가지 중 아래 코드는 간결하나 else 가 사용된다는 단점이 있는것 같은데 SANGCO 는 어떤 방식이 좋다고 생각하시나요?

2021-02-20 15:24 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
저는 개인적으로 위의 코드가 괜찮다고 생각되는데 한번 견해를 들어보고 싶습니다 :)

2021-02-20 15:32 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
```java
 public Pieces add(Piece piece) {
        pieceList.add(piece);
        if(!checkPiecesSize()) {
            throw new IndexOutOfBoundsException("더 이상 Piece 를 추가할 수 없습니다.");
        }
        return this;
    }
```

2021-02-20 15:32 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
위와 같이 바꾸어 보았는데 어떨까요?

2021-02-20 15:50 UTC, SANGCO commented on src/main/java/net/honux/chess/util/Pieces.java
> +package net.honux.chess.util;
core 패캐지에 board 클래스 옆이 더 어울릴거 같네요~

2021-02-20 15:56 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
> +    }
저는 if문을 제거 하기 위해 메서드 분리를 했을거 같아요.
add()라는 하나에 메서드로 모든 종류의 piece를 추가하려고 하니깐
저런 if문들이 발생한게 아닌가 생각이 드네요.

이번 미션에서는 우선 밑에 거로 해서 진행하시고
향후에 미션을 진행 하시면서 메서드가 점점 복잡해 진다고 느껴지시면
적극적인 메서드 분리를 시도해 봅시다!

2021-02-20 16:01 UTC, SANGCO commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
현재 단계에 미션에서는 하나의 Pieces 클래스가 가지고 있는 List에
8개가 딱 들어가야 한잖아요?
그래서 지금 수정하신거 보면 add() 하고 if문을 체크 하시는데
add() 하기 전에 간단하게 체크하는게 있으면 좋겠다 싶어서 리뷰 나겼답니다.

2021-02-20 16:03 UTC, tmdgusya commented on src/main/java/net/honux/chess/util/Pieces.java
> +    }
감사합니다. 생각해보니 유효성검증이 먼져 진행되어야 하는데 제가 밑에 적은것 같네요.

2021-02-20 16:11 UTC, tmdgusya commented on src/test/java/net/honux/chess/util/StringUtilsTest.java
> +        assertThat(convertString(sb)).isEqualTo("test"+NEWLINE);
다음 머지때 띄어쓰기 해서 올리기

2021-02-20 16:21 UTC, SANGCO requested changes
간단한거 몇가지만 더 수정하고 후딱 다음 미션으로 넘어갑시다~

2021-02-20 16:21 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Pieces.java
> +        return new Pieces().add(createWhiteRook()).add(createWhiteKnight()).add(createWhiteBishop()).add(createWhiteQueen()).add(createWhiteKing()).add(createWhiteBishop()).add(createWhiteKnight()).a
.add(createWhiteRook())
.add(createWhiteRook())
.add(createWhiteRook())
.add(createWhiteRook())

제가 좋아하는 스타일이란건 요건식으로
표현을 애매하게 했군요ㅠㅠ

2021-02-20 16:21 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
마이너스 값 까지 고려해서
현재는 
`if (!validateSize()) {`
이런데 
`if (validateSize()) {`
이렇게 될 수 있도록 조건문을 만들어보면 어떨까요?

2021-02-20 16:21 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Board.java
>      }
add() 메서드가 사용하고 있으니깐 그 밑으로 이동시켜 주세요.

2021-02-20 16:22 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Pieces.java
> +        return new Pieces().add(createWhiteRook()).add(createWhiteKnight()).add(createWhiteBishop()).add(createWhiteQueen()).add(createWhiteKing()).add(createWhiteBishop()).add(createWhiteKnight()).a
원래 하시던데로 하셔도 될거 같아요.
근데 지금 처럼 길게 하는건 아닌거 같아요ㅋ

2021-02-21 01:42 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
>      }
네넵 자주 사용하는거라 근처에 둬야 가독성이 좋겠군요

2021-02-21 01:45 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
네넵 ! 연산자를 쓰지 않고 기본 연산자를 쓰는게 좋겠군요
```java
 private boolean validateSize() {
        return this.size() >= 8;
    }
```

2021-02-21 02:20 UTC, SANGCO approved these changes
저는 미션4에서 더 이상 피드백 드릴게 없군요.
고생 많으셨습니다~

2021-02-21 02:36 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
8은 들어가면 안되지 않나요?

음 메서드 명을 좀 변경해야 할거 같네요.
지금 메서드 명으로는 원래 하신거 처럼
`if (!validateSize()) {`
이게 더 어울리는거 같네요.

2021-02-21 02:42 UTC, tmdgusya commented
> 저는 미션4에서 더 이상 피드백 드릴게 없군요.
> 고생 많으셨습니다~

감사해요 좋은 피드백이였습니다.
덕분에 세심한 부분들에 대해서 공부할 수 있게 됬어요! 👍

2021-02-21 03:49 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
네넵 유효하지 않은 사이즈일때가 좋은 표현방식인것 같네요 감사합니다~!

2021-02-21 03:49 UTC, SANGCO commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
```java
    private Pieces add(Piece piece) {
        if (isValid()) {
            pieceList.add(piece); 
        }
        return this;
    }
```

익셉션은 isValid 메서드에서 던지는 걸로 하면 어떨까요?
그리고 현재 add() 메서드가 validateSize()를 사용하고 있는데
validateSize() 메서드가 add() 메서드 위에 있네요.

https://stackoverflow.com/a/32131711

이거 링크 한번 참고해주세요.

2021-02-21 03:58 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Pieces.java
> +    }
```java
private void validateSize() {
        if(this.size() >= 8) {
            throw new IndexOutOfBoundsException("더 이상 Piece 를 추가할 수 없습니다.");
        }
    }


    private Pieces add(Piece piece) { 
        validateSize();
        pieceList.add(piece);
        return this;
    }
```

이 방식이 더 나아보인다고 생각하는데 어떻게 생각하시나요?

2021-02-22 08:04 UTC, honux77 commented
상로코치 모두 수고 많으셨어요! 리뷰 내용이 적절한 수준으로 잘 반영되고 있군요. Good! 🥇

2021-02-22 08:04 UTC, merged