[Wan] 미션 3 : 체스판 초기화
codesquad-members-2021/java-chess pull request #116
Opened 2021-02-18 12:24 UTC by MyungWanPark

안녕하세요 백엔드 반의 Wan 입니다! 
제가 구현한 '미션3: 체스판 초기화' 의 특이사항에 대해 잠깐 소개해 드리겠습니다~!

1. main/java/chess/ChessMain.java
- 메인 메소드에서 스캐너로 명령을 입력 받습니다. 
- 메인 메소드 안에 무한 반복문을 돌려서 명령대로 실행하는 것을 구현하였습니다 

2. main/java/chess/Board.java
- step2 까지는 흑색과 백색 폰으로 나누지 않았지만 initialize 메소드에서 각각의 폰을 구분해서 PawnList에 저장해야 하므로 모든 메소드를 흑과 백으로 나눠서 구현하였습니다.
- getWhitePawnsResult()에서는 StringBuilder로 현재 들어간 흰색폰의 갯수만큼 흰색폰의 이니셜을 합쳐서 return으로 보냈습니다. 
- getDotOnBoard() 이 부분은 사실 sb.append("........")을 하려고 했으나 참고코드를 보고 메소드로 표현하는게 더 멋져보여서 
메소드로 구현했습니다.

3. main/java/pieces/Pawn.java
- 체스판에 표기할 폰의 이니셜을 흰색은 소문자 p 검정색은 대문자 P로 나타내기 위해 상수를 사용하였습니다.

4. test/java/chess/BoardTest.java
- initialize()은 Board 클래스에서 폰을 초기에 8개를 생성하고 이것이 폰 배열에 넣어지는 지 테스트하기 위한 메소드입니다.
- getWhitePawnsResult()는 흰색 폰을 체스판에 다 배치하였을때 표기되는 이니셜이 pppppppp이 맞는지 테스트 합니다.
- printBoard()는 일단 폰으로 초기화가 된 후에 화면에 그 모습이 출력이 잘 되었는지 확인하는 테스트 메소드 입니다.

이번에 구현하면서 궁금한 점이 1가지 생겼습니다~! 
첫번째는, test/java/chess/BoardTest.java 에서 printBoard() 메소드는 출력 테스트를 편하게 하기위해 테스트코드로 작성하였습니다. 하지만 테스트 메소드임에도 불구하고 assertThat.isEqualTo를 사용하지 않았는데 그래도 관습상 괜찮을까요?

부족한 점이 많은 코드입니다ㅜㅜ 따끔한 조언 부탁드릴께요~! 
바쁘신 와중에 긴글 읽어주시고 코드리뷰해주셔서 감사드립니다!

2021-02-19 03:49 UTC, honux77 requested changes
크게 수정할 것 없이 잘 했어요. 코멘트 보시고 조금 개선해 주세요.

2021-02-19 03:49 UTC, honux77 commented on src/main/java/chess/Board.java
> +            whitePawnAdd(whitePawn);
생성자를 보고 있으면 하얀 폰이 검정색을 갖도록 생성가능할 것 같은데 이게 맞을까요?

2021-02-19 03:49 UTC, honux77 commented on src/main/java/chess/Board.java
> +    String getBlackPawnsResult() {
이 메소드 이름 요구사항에 있는 거 아니죠? 저는 이 이름이 맘에 들지 않는데 너무 많은 분들이 같은 이름을 써서...
Result가 추상적이로 코드를 보지 않으면 뭔지 잘 모르겠어요. 그냥 getBlackPawnRepresentations() 어때요?

2021-02-19 03:49 UTC, honux77 commented on src/main/java/chess/Board.java
> +    void printBoard(){
위에 공백 한 줄

2021-02-19 03:49 UTC, honux77 commented on src/main/java/chess/Board.java
> +        sb.append(getDotOnBoard());
'\n' 중복이 많이 발생하는군요. 아마 그게 다음 미션에 있을 거에요. 일단 패스~

2021-02-19 03:49 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +    public Pawn(final String color, final char representation) {
color만 받도록 수정

2021-02-19 03:49 UTC, honux77 commented on src/test/java/chess/BoardTest.java
>      @DisplayName("보드를 생성한 후 폰 테스트 한다.")
뭘 테스트하는지 구체적으로 쓰지 않으면 의미가 없어요.

2021-02-19 03:49 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 초기화 합니다")
여기도 마찬가지

2021-02-19 03:49 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 출력합니다")
assert가 없으면 사실 테스트로 의미는 없는데요. 그래도 내가 눈으로 확인하기 위해서 그럴 수 있겠죠.

2021-02-19 03:49 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 출력합니다")
눈으로 확인하는 것도 역시 테스트로서의 가치는 없겠네요.

2021-02-19 05:13 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +            whitePawnAdd(whitePawn);
앗, 그 점은 생각치도 못했네요!  조언해주셔서 감사합니다. 생성자를 구현하는 쪽에서 파라미터에 final을 붙이면 되는 줄만 알았는데, 처음 입력할때 black에 대한 값을 입력할 수도 있겠네요!! 한번 고민해보고 수정하겠습니다!

2021-02-19 05:16 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    String getBlackPawnsResult() {
네, 요구사항에는 없구 루카스 예시에 이렇게 이름이 지어져있어서 그냥 수용해버렸네요! 앞으로 명확하게 메소드 이름을 지을 수 있도록 노력하겠습니다! 조언 감사해요!!

2021-02-19 05:16 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    void printBoard(){
앗, 수정하겠습니다! 꼼꼼히 봐주셔서 감사합니다

2021-02-19 05:19 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +        sb.append(getDotOnBoard());
앗, '\n'의 중복에 대한 해결책을 떠올리지 못해서 더 고민하지 않고 넘어가버렸네요 ㅠㅠ 다음부터 중복에 대해 좀 더 고민한 흔적을 남기겠습니다! 감사합니다.

2021-02-19 05:25 UTC, MyungWanPark commented on src/main/java/pieces/Pawn.java
> +    public Pawn(final String color, final char representation) {
혹시 생성자에는 2가지 보다 1가지만 받는게 좋아서 그렇게 조언해주신건가요?? 저는 Pawn의 상태가 2가지 이므로 생성자에서 2가지로 초기화 했거든요~! 이 부분은 어떤 키워드로 찾아보면 좋을까요??

2021-02-19 05:28 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
>      @DisplayName("보드를 생성한 후 폰 테스트 한다.")
앗, DisplayName의 목적을 생각하지 않고 작성했던 것 같습니다. 구체적으로 무엇을 테스트하는지 명확하게 작성하겠습니다. 조언 감사합니다.

2021-02-19 05:35 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 초기화 합니다")
넵, 여기도 테스트하는 목적을 생각해서 구체적으로 작성하겠습니다!

2021-02-19 05:38 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 출력합니다")
네, 그러면 눈으로 확인하기 위해 출력하는 메소드는 테스트 메소드로 작성하지 않교 다른 추천해주시는 방법이 있을까요??

2021-02-19 07:46 UTC, MyungWanPark commented
소중한 리뷰 정말 감사합니다!
개선한 코드 올렸습니다~!

2021-02-20 12:09 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 출력합니다")
테스트가 잘 되는 코드가 좋은 코드다라는 말도 있어요. 어떻게 하면 좋을까요? 
근데 가치는 없지만 짜는게 안 되는 건 아니니까요. 확인 용도로 쓸 수는 있을 것 같아요.

2021-02-20 12:10 UTC, honux77 commented on src/main/java/chess/Board.java
> +    void whitePawnAdd(Pawn whitePawn) {
앗 그리고 지금 보니 접근 한정작 없는 메소드들이 많이 있네요. private을 붙여 주세요.

2021-02-20 12:10 UTC, honux77 commented on src/main/java/chess/Board.java
> +    void printBoard(){
private을 놓쳤는데 ㅋㅋ 꼼꼼하지 않네요.

2021-02-20 12:12 UTC, honux77 commented on src/main/java/chess/Board.java
> +        System.out.println(sb.toString());
이 부분을 String으로 리턴하는 메소드와 출력하는 메소드로 나누면 String 리턴하는 메소드를 테스트할수 있겠죠?

2021-02-20 12:12 UTC, honux77 requested changes
몇 가지 놓친 부분이 있었네요.
private 한정자 붙이기랑 String 리턴 메소드 만들기 등 다시 한번 수정해 주세요1

2021-02-20 12:14 UTC, honux77 commented on src/main/java/chess/ChessMain.java
> +        Scanner scanner = new Scanner(System.in);
scanner close()는 언제??

2021-02-22 06:32 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    void printBoard(){
앗, 수정하겠습니다!

2021-02-22 06:34 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("보드판을 출력합니다")
조언해주셨던대로 printBoard()를 StringBuilder을 String으로 합쳐서  return하는 메소드와 이를 출력하는 메소드로 분리해서 테스트를 실시할 수 있었습니다! 감사합니다~!

2021-02-22 06:35 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    void whitePawnAdd(Pawn whitePawn) {
private을 붙이면 test클래스에서 접근할 수 없어서 에러가 나는데 그럴경우, 메소드를 private 으로 접근하는 public 메소드로 하나 더 만드는게 좋을까요 :?

2021-02-22 06:36 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +        System.out.println(sb.toString());
오오!! 이부분을 어떻게 테스트 하나 고민하고 있었는데 조언 감사합니다! 바로 수정하겠습니다

2021-02-22 06:37 UTC, MyungWanPark commented on src/main/java/chess/ChessMain.java
> +        Scanner scanner = new Scanner(System.in);
앗! 그러네요! Try-with-resource 문으로 감싸서 수정했습니다!!

2021-02-22 06:39 UTC, MyungWanPark commented
조언해주셔서 감사합니다. 수정하였습니다! 
한가지 궁금한 점이 Board.java 에 있는 메소드들에 private을 붙이게 되면 test폴더 내에 있는 클래스에서 접근이 불가능한데 private메소드로 만들고 이에 접근하는 public 메소드를 만드는 식으로 바꾸는게 좋을까요?

2021-02-22 07:39 UTC, honux77 commented
private 메소드는 테스트를 할 수 없고  public 메소드를 통해서 간접적으로 테스트를 하는게 정상입니다. private 메소드를 테스트하기 위해서 억제로 테스트를 위한 public 메소드를 만든다면 그것도 어딘가 잘못된 것이 아닌지 고민해 봐야 할 것 같습니다. 수고하셨어요!

2021-02-22 07:39 UTC, merged