[Starve] Mission4 - 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #120
Opened 2021-02-19 10:41 UTC by Jiwon-JJW

안녕하세요! 미션 3를 완료 하여, 세번째 PR 요청 드립니다.

### 변경 사항
**Piece**
* Pawn 클래스 에서 Piece로 이름을 변경하였습니다.
* 체스말의 종류에 따라 생성할 수 있는 팩토리 메서드를 생성했습니다.
* 체스말의 색상에 따라 분류되어있던 getRepresentation() 메서드를 하나로 통합하였습니다.

**PieceTest**
* 팩토리 메서드가 정상적으로 작동 하는지 확인하는 메서드를 생성하였습니다.

**Type**
* 본래 Color에서 관리하던 representation 변수를 enum Type으로 옮겨 개별적으로 관리하도록 만들었습니다.
Piece 클래스 내에 생성하면 코드가 복잡해지는 것 같아, 개별적으로 다룰 수 있도록 밖으로 뺐습니다.

**Board**
* 등록된 체스말의 총 개수를 계산하는 totalPiecesCount() 메서드를 생성하였습니다.
동시에, 색상별로 체스말의 개수를 계산하는 메서드는 필요가 없을 것 같아 삭제했습니다.
* 색상별로 체스말을 등록하는 initializeWhitePieces와 initializeBlackPieces 메서드를 생성하였습니다.
색상별 Piece List 내에 체스말을 추가해주는 add 메서드도 그렇고, 체스 말을 생성해주는 create 메서드 자체가 색상별로 분류되어 있어 이러한 방식을 사용했습니다.

**BoardTest**
* 이전의 메서드 삭제 후 체스판의 초기화를 확인해주는 테스트 메서드를 생성하였습니다.

**StringUtils**
* OS별로 개행문자가 다를 수 있어, 이를 처리할 수 있는 클래스를 생성하였습니다.
* Board 내에있는 PiecesList가 보드 사이즈를 넘어갈 수 있는 상황을 대비하여, 보드사이즈를 넘어갈 경우 개행 문자를 추가적으로 중간에 넣어줄 수 있도록 처리 작업을 진행했습니다.
이는 이후 미션 작업 시, 체스판을 관리하는 객체를 생성하여 수정에 들어갈 예정입니다!

여기까지 읽어주셔서 감사합니다!

2021-02-19 13:03 UTC, sonypark requested changes
안녕하세요 Starve, 리뷰어 소니 입니다.😊
요구사항에 맞게 구현 잘 하셨습니다👍
개선할 부분 몇가지에 대해 코멘트 남겼으니 확인 부탁드립니다~

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/pieces/Color.java
>      public String getColorName() {
colorName이라는 필드가 꼭 필요한 걸까요?
Color enum안에 있는 WHITE, BLACK 상수만으로도 충분할 것 같아요.

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/pieces/Piece.java
> +    }
위에 언급한 것과 마찬가지로 Color를 enum으로 사용했다면 문자열로 비교할 필요가 있을까라는 생각이 드네요.
어떻게 변경할 수 있을까요?

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/pieces/Piece.java
> +
불필요한 주석은 삭제해주세요~
구분선을 위한 주석은 필요하지 않습니다.
메서드를 잘 분리하고 연관있는 메서드끼리 묶어 놓는게 가독성 향상에 도움이 됩니다.

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/pieces/Piece.java
> +    }
생성을 함과 동시에 컬러와 타입을 강제했으니, 의도하지 않은 체스말이 생길 일은 없겠네요 👍

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/pieces/Type.java
> +    }
👍

2021-02-19 13:03 UTC, sonypark commented on src/main/java/utils/StringUtils.java
> +
`NEWLINE`은  StringUtils에서만 사용하는 상수인데 접근제어자를 public으로 하는게 맞을까요?

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/Board.java
1. 메서드명만 보고 어떤 역할을 하는지는 한번에 와닿지 않네요. 체스말을 표현하는 로직인데요, 일단 메서드명이 명확하지 않은것 같아요 result가 의미하는게 무엇일까요?
2. getWhitePiecesResult, getWhitePiecesResult로 너무 잘게 나누기보다는 메서드의 인자로 컬러를 넣어서 해당 컬러의 피스들을 보여주는게 더 나을 것 같습니다. 즉, getPiecesResult 하나만 사용해도 될 것 같아요. (메서드명을 적절하게 변경해보세요)

2021-02-19 13:03 UTC, sonypark commented on src/main/java/chess/Board.java
> +        return boardRank.toString();
1. 변수명을 대문자로 적는것은 상수에만 해당합니다. 지역변수는 소문자를 사용해주세요.

2. showBoard 라는 네이밍이 적절할까요? 실제로 보여주는 역할은 Main 클래스의 System.out.println()에서 하고 있네요.

3. Board는 체스판을 리턴하고 그 결과를 출력을 담당하는 클래스에서 해주도록 해보세요.

2021-02-19 13:03 UTC, sonypark commented on src/main/java/utils/StringUtils.java
> +        }
이 부분이 왜 필요한지 잘 모르겠네요. `addNewLine()`의 역할과는 상관없어 보입니다.

2021-02-19 13:03 UTC, sonypark commented on src/test/java/chess/BoardTest.java
> +        assertThat(32).isEqualTo(board.totalPiecesCount());
32는 어떤걸 의미하는 숫자인가요? 상수로 표기해주면 좋겠네요.
이와 같은 매직넘버는 상수로 만드는걸 고려해주세요~
++ 매직넘버에 대해 검색해서 공부해보세요~

2021-02-19 13:03 UTC, sonypark commented on src/test/java/chess/pieces/PieceTest.java
> +    }
assertAll을 사용하는 부분은 저번에 말씀을 드렸는데, 여기는 적용이 안 되어있네요.🤔

2021-02-20 11:50 UTC, Jiwon-JJW commented on src/main/java/utils/StringUtils.java
> +        }
체스말들을 한 List에 관리 하다보니, 체스 판 사이즈를 넘어가는데도 한 줄로 출력이 되어 넣은 것인데, 말씀해 주신대로 역할과 맞지않는 것 같아, getNewLine 메서드로 NEWLINE을 얻을 수 있도록 수정하였습니다!!

2021-02-20 12:09 UTC, Jiwon-JJW commented
리뷰 주셨던 것을 토대로 코드를 변경해 보았습니다!
다시 살펴보면서 중복된 코드를 별개의 메서드로 관리하도록 조금 더 수정해보았습니다~! 
공부해봐야 할 사항도 숙지해보도록 하겠습니다!! 감사합니다!!

2021-02-20 14:26 UTC, sonypark commented on src/test/java/chess/BoardTest.java
> +        final int TOTAL_PIECES_COUNT = 32;
`TOTAL_PIECES_COUNT` 는 상수일까요 지역변수 일까요?

2021-02-20 14:29 UTC, sonypark commented on src/main/java/chess/Board.java
> +    private String getPiecesSort(Color color) {
메서드명에 sort라는 이름이 들어가는게 적절한지 모르겠네요.
내부에 정렬하는 로직은 없는것 같아서요

2021-02-20 14:30 UTC, sonypark approved these changes
수고하셨습니다!
코멘트 남긴거 확인하시고 다음 미션에 반영 부탁드려요~💪

2021-02-22 08:08 UTC, honux77 commented on src/test/java/chess/pieces/PieceTest.java
> +    }
ㅋㅋㅋㅋㅋ 제가 어차피 작은 단위에서는 통과못하면 안 되니까 assertThat()만 써도 괜찮다고 그랬습니다 ㅋㅋㅋ 죄송

2021-02-22 08:09 UTC, merged