[Bibi] 미션3 : 체스판 초기화 pull request 입니다.
codesquad-members-2021/java-chess pull request #122
Opened 2021-02-19 15:40 UTC by bibi6666667

안녕하세요, 백엔드반의 Bibi입니다.
미션3 : 체스판 초기화 를 진행한 step3 브랜치 pull 요청 드립니다🙇‍♀️

<학습한 부분>
- `StringBuilder` 의 개념과 사용법 (더 학습 필요)
- 호눅스의 수업 복습 겸 다음 미션 예습 차원에서 enum과 VO에 대해 조금 학습
돌아보니 이번 미션3은 학습보다는 코딩 위주로 진행되었네요.

<진행한 내역>
- 체스판 초기화
- 체스판 출력
- 체스 게임 시작 부분 만들기 (`main()`, `start`, `end`)
- 약간의 리팩토링

지금 제 코드가 최선은 아니라고 생각하지만,
이제 1주만 남은 상황에서 우선 요구사항을 만족한 코드를 얼른 PR하고
피드백을 받으며 코드를 개선하는 게 더 낫다고 생각했습니다.
그러니 여러분의 많은 제안, 조언, 피드백, 충고 부탁드립니다. 제 학습을 도와주세요..😀

세심한 코드리뷰 늘 감사드리고, 앞으로도 잘 부탁드립니다.
늦은 시간에 알림 드려 죄송합니다.🙇‍♀️ 리뷰어 분들도 좋은 주말 되세요!

2021-02-20 03:55 UTC, SANGCO requested changes
Bibi님 구현 잘하셨네요. 고생하셨습니다!
리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/chess/ChessStarter.java
> +    }
Scanner와 같이 AutoCloseable을 구현한 클래스의 경우 
[try-with-resources](https://www.baeldung.com/java-try-with-resources)를 사용해서 쉽게 리소스를 해제할 수 있답니다.
이번 미션에서 try-with-resources 관련되어서 학습하고 적용해보면 좋을거 같아요~

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/chess/ChessStarter.java
> +    }
"start", "end" 이런 부분들은 상수로 만들어 사용하는건 어떨까요?

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/chess/ChessStarter.java
> +    }
너무 과한 메서드 분리가 아닐까요?

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/pieces/Pawn.java
>      }
기본 생성자가 파라미터가 있는 생성자 보다 위로 와야 합니다.

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/pieces/Pawn.java
> +    public final static String BLACK_REPRESENTATION = "P";
static이 붙은 클래스 변수가 인스턴스 변수보다 위로 가야 합니다.

2021-02-20 03:55 UTC, SANGCO commented on src/main/java/chess/Board.java
> +        blackPawns.add(pawn);
흰색 Pawn을 추가하는 메서드에 검은색 Pawn을 넣는 테스트 코드를 만들어 봅시다.

2021-02-20 03:55 UTC, SANGCO commented on src/test/java/chess/BoardTest.java
>  }
![image](https://user-images.githubusercontent.com/26179444/107593824-b59d4380-6c53-11eb-96a2-8ce5bd465118.png)
IntelliJ 설정을 찾아서 적용해 보아요.
[How to make IntelliJ IDEA insert a new line at every end of file?](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)
[파일 끝에 개행을 추가해야 하는 이유](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)

2021-02-21 02:54 UTC, tmdgusya reviewed
비비 제가 그룹 코드리뷰때 상세하게 봐드리지 못한것 같아서
이렇게 리뷰남기러 왔습니다! 주말엔 푹 쉬시고 제 Comment 부분도 한번 생각해보시고 
답글 달아주시면 감사할듯 합니다 👍

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/ChessStarter.java
> +            Scanner sc = new Scanner(System.in);
스캐너가 반복문안에 있어야 할까요?

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
> +            blackPawns.add(blackPawn);
공통적으로 8이라는 숫자가 같은 의미로 사용되는데
해당 8을 상수로빼서 MAX_SIZE 라던가 BOARD_SIZE 등의 상수로 추출해내는 것은 어떨까요?

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
>          List<Pawn> whitePawns = new ArrayList<>(8);
생각해보니 10~11 Line 에서 new ArrayList() 가 이루어지는데 아래에서 재할당할 이유가 있을까요?

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
>              blackPawns.add(blackPawn);
이경우 현재 동일 인스턴스를 add 하는 것으로 보여지는데 어떤 문제가 일어날 수 있을까요.
사실 지금 상태에서는 충분히 문제를 일으키지 않을 것 같은데,
후에 체스에 대한 조작이 일어난다면, 체스 객체자체가 움직이는 것이 아니라 보드가 체스를 움직이는 느낌이 들것 같습니다.
해당 방식에서는 Pawn 이 이동시 blackpawn 하나만 이동해도 같은 객체라 모두 이동하게 될것으로 보이기 때문입니다.

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
> +        for (Pawn aPawn : whitePawns) {
aPawn 이라는 Naming 은 적절하지 않은것 같습니다.. 어떤 의도인지 잘 모르겠네요.
차라리 pawn 으로하는것이 낫지 않았을까요?

2021-02-21 02:54 UTC, tmdgusya commented on src/test/java/chess/BoardTest.java
>      void putWhitePawn() {
putWhitePawn -> addWhitePawn 가 지금 테스트 케이스 제목에 적절하지 않을까라는 생각을 해봅니다.
어디까지나 개인적인 견해입니다.

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
>      private List<Pawn> blackPawns = new ArrayList<>(8);
위에서 언급한것과 마찬가지로 이부분에서도 8이 이용되고 있는데
상수로 추출하는것이 적절해보입니다.

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
> +    void addWhitePawn(Pawn pawn) {
접근제어자가 필요해 보입니다.

2021-02-21 02:54 UTC, tmdgusya commented on src/main/java/chess/Board.java
> +    void addBlackPawn(Pawn pawn) {
접근제어자가 필요해 보입니다.

2021-02-21 12:52 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
> +    }
네! 공유해 주신 링크 통해 공부한 뒤 적용해 보겠습니다!
start, end도 그러고 보니 상수로 선언해 쓰는 게 훨씬 낫겠네요. 개선해 보겠습니다!
코멘트 주셔서 감사합니다!🙇‍♀️

2021-02-21 13:16 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
> +    }
ready()에 종료 명령어가 있는 게 어색해 보여서 분리했는데, 너무 짧아서 과하게 분리한 것 같네요😅 수정하겠습니다!
코멘트 감사합니다😀

2021-02-21 13:54 UTC, bibi6666667 commented on src/main/java/pieces/Pawn.java
> +    public final static String BLACK_REPRESENTATION = "P";
그렇군요! 기본 생성자, 클래스변수 위치 모두 수정하겠습니다.
코멘트 감사합니다🙇‍♀️

2021-02-21 14:22 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +        blackPawns.add(pawn);
아무 이상 없이 통과가 되네요😅 요구사항만 따라가느라 Pawn을 확인하는 코드를 짜지 않았네요. Pawn의 색을 확인하고 추가하도록 수정하고, 테스트도 해보겠습니다!
코멘트 감사합니다🙇‍♀️!

2021-02-21 14:24 UTC, bibi6666667 commented on src/test/java/chess/BoardTest.java
>  }
앗 저번에 공부했던 부분인데 신경쓰지 못했네요.. 죄송합니다😭
개행 추가하고 인텔리제이 설정도 따라서 해 놓겠습니다!
코멘트도 주시고 링크 공유해주셔서 감사합니다😀👍

2021-02-22 07:08 UTC, bibi6666667 commented
> 비비 제가 그룹 코드리뷰때 상세하게 봐드리지 못한것 같아서
> 이렇게 리뷰남기러 왔습니다! 주말엔 푹 쉬시고 제 Comment 부분도 한번 생각해보시고
> 답글 달아주시면 감사할듯 합니다 👍

@tmdgusya 코드리뷰 감사드립니다 로치!😄
코멘트 주신 부분들 수정하고 생각해 봤습니다.
(로치가 남겨 주신 코멘트가 이메일에서는 보이는데 이 PR에는 코멘트 창이 안 보여서..🤔 부득이하게 여기에 대신 정리해서 남깁니다.)

<수정한 부분>
- `Scanner`를 반복문 밖에 선언했습니다.
- `8`이라는 숫자도 `PAWN_NUM`이라는 이름의 상수로 사용했습니다.

<아직 수정하지 않은 부분>
- `Board`클래스의 `addWhitePawn()`, `addBlackPawn()` 의 접근제어자
  - 저는 Board에 임의로 외부에서 폰을 추가할 수 없게끔 일부러 `public`을 빼고, 테스트코드에서는 사용해야 하니까 `private`는 붙이지 않고 default로 두었습니다. 더 나은 방법이 있다면 개선하고 싶은데, 어떤 방법이 좋은지 추천해 주실 수 있나요?🤔
- 메서드명, 변수명 관련 조언
  - 이 부분은 다음 스텝 진행하면서 한 번 바꿔 보겠습니다! 
- 동일 인스턴스를 add하고 있다는 조언
  - 혹시 `whitePawns.add(whitePawn)`, `blackPawns.add(blackPawn)`부분을 말씀하시는 게 맞나요? 제 코드에서 `whitePawns`는 ArrayList, `whitePawn`은 흰색으로 선언된 `Pawn`이라 동일 인스턴스가 더해지는 상태는 아니라고 생각했습니다.
- Board.java 에서 `new ArrayList`를 재할당하고 있다는 조언
  - 제 코드에서는 예전에 수정된 부분인데 왜 PR에서 이렇게 나타날까요?😅 그래도 코멘트 감사합니다!

신경 써서 피드백과 조언 주셔서 감사합니다 로치!
덕분에 제 코드가 많이 개선되었네요😀👍

2021-02-22 11:47 UTC, SANGCO requested changes
추가로 간단한 리뷰 남깁니다~

2021-02-22 11:47 UTC, SANGCO commented on src/main/java/chess/Board.java
> +    boolean addWhitePawn(Pawn pawn) {
접근 제한자를 왜 디폴트로 하셨는지 궁금합니다~

2021-02-22 11:47 UTC, SANGCO commented on src/main/java/chess/Board.java
> +    boolean addBlackPawn(Pawn pawn) {
여기도 접근제한자

2021-02-22 11:47 UTC, SANGCO commented on src/main/java/chess/Board.java
> +        }
```java
Pawn whitePawn = new Pawn();
Pawn blackPawn = new Pawn(Pawn.BLACK, Pawn.BLACK_REPRESENTATION);
```
이 코드가 for문 밖에 있는것과 안에 있는게 어떤 차이가 있을까요?

그리고 위에 만든 addWhitePawn(), addBlackPawn() 메서드가 
여기서 쓰려고 만드신게 아닌가요?

2021-02-22 11:47 UTC, SANGCO commented on src/main/java/chess/Board.java
> +    void initialize() {
여기도 접근제한자가 디폴트이네요.
참고로 private 메서드는 보통 private 메서드를 사용하고 있는 메서드 밑에 위치 시킵니다.

2021-02-22 12:42 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +    boolean addWhitePawn(Pawn pawn) {
안녕하세요 상코! 추가 리뷰 주셔서 감사합니다😀👍

제 의도는 Board에 임의로 외부에서 폰을 추가할 수 없게끔 하는 것이었습니다.
그래서 public을 뺐지만, 테스트코드에서는 해당 메소드를 사용해야 하니 private는 붙이지 않았습니다. 
더 나은 방법이 있다면 개선하고 싶은데, 어떤 접근제어자가 적당할지 잘 몰라서 default로 두었습니다.
 (접근제한자에 대해 공부한 적은 있지만 사용해 본 적은 별로 없어서.. 조언 부탁드립니다😅)

2021-02-22 12:43 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +    void initialize() {
그렇군요! private메서드들의 위치 수정하겠습니다. 감사합니다🙇‍♀️

2021-02-22 12:50 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +        }
for문 안에 있으면 매번 새로운 Pawn객체를 만들고 그 객체를 추가시키는 반면,
for문 밖에 있으면 만든 객체 하나를 가지고 반복해서 추가하는 차이가 있다고 생각합니다.
addWhitePawn(), addBlackPawn()은 그냥 요구사항대로 만든 메소드인데, 듣고 보니 initialize()에서 사용할 수 있네요. 만들어 놓고 왜 사용을 안 한 건지...😅 수정하겠습니다!
추가 리뷰 주셔서 감사합니다🙇‍♀️🙇‍♀️

2021-02-22 13:52 UTC, SANGCO commented on src/main/java/chess/Board.java
> +    boolean addWhitePawn(Pawn pawn) {
접근 제한자를 선택하실 때 우선 public 혹은 private 만들고
private인데 상속 관계에 있는 객체들에서 사용해야 한다고 하면 protected로
private 인데 다른 패키지에서 사용을 해야 한다면 package-private(default)로
이런식으로 접근을 하면 될거 같습니다.

위에 테스트를 위해서 디폴트로 접근 제한자를 변경 하신건 잘하셨구요.
private 메소드를 테스트 하는 방법이 있는데
그거는 아마 뒤에 나오지 싶습니다.
우선은 이렇게 하셔도 괜찮을거 같아요~

2021-02-22 13:56 UTC, SANGCO approved these changes
수정 잘하셨네요. 고생 많으셨습니다~

```java
Pawn whitePawn = new Pawn();
Pawn blackPawn = new Pawn(Pawn.BLACK, Pawn.BLACK_REPRESENTATION);
```

이 부분은 이번 미션과 다음 미션 까지도 이렇게 가도 상관은 없는데
아마 딱 걸리는 미션이 있을 겁니다.
거기서 뭐 수정해도 좋을거 같네요.
다음 미션으로 넘어 가시죠~

2021-02-22 14:01 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +    boolean addWhitePawn(Pawn pawn) {
오.. 그렇군요! 적어 두고 다음 미션 때도 이런 부분들 생각하면서 접근제어자를 사용해 보겠습니다.
상세히 답변 주셔서 감사합니다!🙇‍♀️👍

2021-02-24 01:17 UTC, merged