[아이작] 미션4: 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #123
Opened 2021-02-19 16:29 UTC by isaac56

안녕하세요 코드스쿼드 백엔드 멤버 아이작입니다.
미션4 모든 기물 배치하기 구현하였습니다.

1. Board 클래스 내부에선 체스말을 Piece 클래스의 2차원 배열로 관리하도록 했습니다.
 - 체스는 게임 도중 보드의 크기가 변하지 않기 때문에, 배열로 관리하는게 편하다고 생각했습니다.

2. Piece를 추상클래스로 정의하고, 이동 범위 등 고유 로직을 Override 하려는 목적으로 Pawn, Rook 등의 자식 클래스를 만들었다가 삭제하였습니다.
 - TDD에 따라 현재 단계에서는 필요 없을 것 같아 삭제하였습니다.

코드 리뷰 잘 부탁드립니다

2021-02-20 05:18 UTC, ksundong requested changes
안녕하세요! 아이작! 리뷰어 Dion입니다. 4단계를 진행하느라 고생 많으셨습니다.
배열의 사용은 근거가 있었지만, 그래도 제안을 드려봤습니다.
추상클래스는 확실히 현재시점에선 그리 필요하지 않다는 의견에 동의합니다.
그리고, 필요없는 메서드들도 바로바로 삭제해주세요.

## 리뷰 내용

- 중복 제거에도 신경을 많이 써주세요.(변수, 메서드)
- 코드 커밋전에 리포맷을 꼭 수행해주세요. 코드 일관성을 지켜주세요~
- 특별한 의미를 담은 리터럴을 읽기전용 변수로 추출해주세요.
- 요구사항을 지켜주세요!

고생하셨습니다! 몇 가지 생각해볼 사항들과 요구사항을 지켜주지 않은 부분이 있어 변경요청을 드렸습니다.
코멘트를 보시면서 궁금하신 점이나, 이해가 되지 않는 부분. 그리고 논의하고 싶은 내용은 코멘트 달아주시구, 변경 완료되시면 푸시하시고 다시 리뷰요청해주세요!

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
코드를 읽어보니 piece에 관련된 부분이 중복이 되는 것 같네요.
한 기물을 추가했을 때, 하나만 변경되도록 신경써주세요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
그리고 2차원 배열을 쓰기보다는, 2차원 배열의 요소인 배열을 따로 추출하는 방법도 한 번 생각해보세요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        initializeSpecialPieces(Piece.Color.WHITE, MAX_IDX);
코드 일관성을 위해서 꼭 리포맷을 해주세요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        initializeSpecialPieces(Piece.Color.WHITE, MAX_IDX);
```suggestion
        initializePawns(BLACK, 1);
        initializePawns(WHITE, MAX_IDX - 1);
        
        initializeSpecialPieces(BLACK, 0);
        initializeSpecialPieces(WHITE, MAX_IDX);
```
저는 색단위보다는 하는 행위에 초점을 맞춰봤어요. 그리고 너무 장황하게 코딩하기보다는 직관적으로 읽히게끔 코딩하는 방법도 생각해보세요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        initializeSpecialPieces(Piece.Color.WHITE, MAX_IDX);
또, 1이랑 0은 하드코딩 되어있는데, 중복이 되어있습니다. 한 번 수정해볼까요?

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        add(Piece.getRook(color), row, 7);
저는 `get` 접두어가 붙은 메서드는 Java에서 특별한 의미가 있다고 생각해서, 가급적이면 `create`를 쓰는게 좋을 것 같아요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>          for(int i = 0; i < MAX_SIZE; i++){
i도 특별한 이름을 줘도 좋을 것 같아요. column이라던가?

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        add(Piece.getRook(color), row, 7);
0, 1, 2, 3, 4, 5, 6, 7도 특별한 의미를 담은 수로 만들 수 있을 것 같고, 중복이 되는 부분도 보이실 것 같아요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>          System.out.println(getRepresentation());
print()는 Board가 하지 말고 Main에서 해봅시다.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +    public String getRepresentation(){
👍

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>                      builder.append(pieces[i][j].getRepresentation());
저는 되도록이면 if else 블록에 중괄호를 넣어주는게 좋은 것 같습니다.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +            builder.append(StringUtils.NEWLINE);
이렇게 하지 말고, 좀 더 좋은 방법을 고안해봅시다. 이는 요구사항에도 있는 부분이에요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/pieces/Piece.java
>      public static final char UNKNOWN_REPRESENTATION = '?';
Unknown은 필요한가요? 제 생각엔 크게 의미가 없을 것 같거든요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/utils/StringUtils.java
> +    private StringUtils(){}
private으로 기본 생성자를 감춰주신 이유가 혹시 있나요?

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/utils/StringUtils.java
> +    }
이 코드 사용되고 있나요?

2021-02-20 05:18 UTC, ksundong commented on src/test/java/net/isaac/chess/BoardTest.java
> +                () -> assertThat(board.pieceCount()).isEqualTo(32),
32라는 숫자도 특별한 변수로 추출해봅시다.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
이 상수를 private으로 감춰보고, appendNewLine만 사용하도록 바꿔봅시다.

2021-02-20 05:18 UTC, ksundong commented on src/test/java/net/isaac/chess/BoardTest.java
> +                appendNewLine("rnbqkbnr");
저는 되도록이면 일관적인 패턴으로 작성하는게 좋은 것 같아요.
한 번에 봤을 때, 4줄이 추가된다는 것을 직관적으로 알기 어렵거든요.

2021-02-20 05:18 UTC, ksundong commented on src/test/java/net/isaac/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.getKnight(Piece.Color.BLACK), Piece.Color.BLACK, Character.toUpperCase(Piece.KNIGHT_REPRESENTATION))
코드가 너무 장황하죠?
이 부분은 분리를 통해서 개별 테스트를 수행하거나, 각 테스트에 대한 설명을 달아주는게 어땠을까? 라는 생각입니다.
그리고 WHITE BLACK 왔다갔다 하는 것보다는, 별도의 메서드로 추출해서 WHITE, BLACK을 인자로 넣어주는 방안도 생각해보면 좋을 것 같아요.

2021-02-20 05:18 UTC, ksundong commented on src/test/java/net/isaac/pieces/PieceTest.java
> +                () -> assertThat(black.isBlack()).isEqualTo(true)
isTrue(), isFalse()를 사용해주세요.

2021-02-20 05:18 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>      }
이 코드는 사용되지 않는 것 같네요~

2021-02-21 02:55 UTC, tmdgusya commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
2차원 배열은 메모리에서 어떻게 배치되는지도 한번 공부해보시면 좋을것 같습니다~!

2021-02-22 14:42 UTC, jihye-woo commented on src/main/java/net/isaac/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
아아앗.. private 선언하는걸 깜빡했네요 얼른가서 바꿔놓고 와야겠습니다😅 감사합니당!

2021-02-22 14:42 UTC, jihye-woo commented on src/test/java/net/isaac/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.getKnight(Piece.Color.BLACK), Piece.Color.BLACK, Character.toUpperCase(Piece.KNIGHT_REPRESENTATION))
우와 모든 체스말에 대해서 테스트를 작성해주셨군요! 
저도 디온의 코멘트 참고해서 아이작처럼 모든 팩토리 메소드들에 대해 테스트를 해봐야겠어요👍👍

2021-02-23 06:10 UTC, isaac56 commented on src/main/java/net/isaac/utils/StringUtils.java
> +    private StringUtils(){}
StringUtils는 static method로만 이루어진 static class로 사용하려고 했습니다.
instance 생성을 막으려고 생성자를 private으로 감췄습니다.

2021-02-23 06:13 UTC, isaac56 commented on src/main/java/net/isaac/utils/StringUtils.java
> +    }
만들어놓고 사용하지 않고 있었네요 ㅠㅠ 
Board class 의 getRepresentation 메소드에서 사용하도록 수정했습니다.

2021-02-23 06:39 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
> 2차원 배열은 메모리에서 어떻게 배치되는지도 한번 공부해보시면 좋을것 같습니다~!

자바에서는 C와 다르게 1차 배열까지만 heap 영역에 연속적으로 할당되는군요. 
2차원 이상부터는 malloc으로 동적할당하는 것처럼 1차배열의 시작 주소를 담고 있구요

2021-02-23 06:47 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
> 그리고 2차원 배열을 쓰기보다는, 2차원 배열의 요소인 배열을 따로 추출하는 방법도 한 번 생각해보세요.

2차원 배열의 요소인 1차원 배열을 따로 추출하여 사용해보라는 말씀이신가요?
배열 크기가 고정된 상황에서 2차원 배열을 선언하여 pieces[x][y] 이런식으로 사용하면 (x,y)위치를 참조한다는 의미의 가독성이 좋아진다고 생각했습니다.

위 상황에서 2차원 배열을 썼을 때의 단점이 무엇인지 저는 잘 떠오르지 않네요 ㅠㅠ

2021-02-23 06:57 UTC, isaac56 commented
안녕하세요 Dion!

Slack에서 말씀하시는 것 자주 뵈었는데, 이렇게 리뷰 받게되다니 영광이네요!

제가 이해한 선에서 고칠 수 있는 부분은 고치고, 잘 이해가 가지 않는 부분은 코멘트 달아놨습니다.
꼼꼼한 리뷰 감사드립니다.

2021-02-23 07:51 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
미션5를 이제봤는데, 체스에서는 row를 Rank라는 값으로 관리하네요!
배열의 index가 아닌 Rank 값으로 접근한다면, 
Map<Integer, ArrayList<Piece>> 또는 Map<Integer, int[]> 로 관리하는 것도 괜찮은 것 같습니다.

2021-02-23 09:04 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>      private List<Piece> blackPieces = new ArrayList<>();
되도록이면 제네릭과 배열은 혼용해서 쓰지 않는다는 점을 염두에두고 코딩해주시면 더 좋을 것 같아요!

2021-02-23 09:06 UTC, ksundong commented on src/main/java/net/isaac/utils/StringUtils.java
> +    private StringUtils(){}
넵넵 잘하셨어요~

2021-02-23 09:21 UTC, ksundong approved these changes
수정하느라 고생 많으셨습니다! 다음 단계 바로 진행하셔도 될 것 같아요.
몇 가지 코멘트 남겼는데 다음 단계 하실 때, 한 번 신경써보시면 좋을 것 같습니다.
고생하셨습니다!

2021-02-23 09:21 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
> +        add(Piece.createRook(color), row, MAX_IDX - rookColumn);
각각이 또 메서드가 될 수도 있겠네요~

2021-02-23 09:21 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>              return null;
`null`을 리턴하는건 좀 주의할 필요가 있어요.
`Optional`도 한 번 공부해보세요~

2021-02-23 09:21 UTC, ksundong commented on src/main/java/net/isaac/chess/Board.java
>      }
이게 board에 있는게 맞는지는 조금 고민해봐야 할 것 같아요~

2021-02-23 09:21 UTC, ksundong commented on src/test/java/net/isaac/chess/BoardTest.java
>          board.add(black, 0, 1);
이 부분도 조금 더 고민해봅시다, '0, 0' ,'0, 1'은 알기 힘들어요.

2021-02-23 09:22 UTC, merged

2021-02-23 09:27 UTC, isaac56 commented on src/test/java/net/isaac/chess/BoardTest.java
>          board.add(black, 0, 1);
0,0과 0,1 등은 그냥 테스트하기 위한 위치일 뿐 특별한 의미는 없어서요 ㅎㅎ
저는 테스트를 위한 상수까지 굳이 변수로 할당해야 하나(?)라는 생각이 드네요 😭

전체 코드는 아래와 같습니다. 
그냥 (0,0)과 (0,1)에 등록해보고 제대로 등록되었나 확인하기 위한 코드였어요

```java
    @Test
    @DisplayName("Board의 Pawn 등록 테스트")
    void pawnAddTest() throws Exception {
        Piece white = Piece.createPiece(Piece.Color.WHITE, Piece.Type.PAWN);
        board.add(white, 0, 0);
        Piece black = Piece.createPiece(Piece.Color.BLACK, Piece.Type.PAWN);
        board.add(black, 0, 1);

        assertAll(
                () -> assertThat(board.findPiece(0, 0)).isEqualTo(white),
                () -> assertThat(board.findPiece(0, 1)).isEqualTo(black),
                () -> assertThat(board.findPiece(0, 2)).isEqualTo(null),
                () -> assertThat(board.findPiece(10, 10)).isEqualTo(null)
        );
    }
```

2021-02-23 13:13 UTC, ksundong commented on src/test/java/net/isaac/chess/BoardTest.java
>          board.add(black, 0, 1);
음 뭔가 메일이 왔었던것 같은데 사라졌네요 ㅎㅎ