[Pyro] 미션4 : 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #129
Opened 2021-02-22 01:30 UTC by ghojeong

<img width="328" alt="스크린샷 2021-02-22 오전 9 57 10" src="https://user-images.githubusercontent.com/38595650/108644989-82c93a00-74f4-11eb-95e0-6af33ccf8292.png">

미션에서 원하는 설계와 달라지는 부분들이 생겨서,
왜 다르게 설계를 하게 되었는지 제 의도를 설명 후,
적합하지 않다고 피드백 받으면 미션의 설계대로 다시 수정하려고 합니다.

### 미션과 다른점 1: isWhite, isBlack 메소드가 Piece 에 없음

isWhite 와 isBlack 메소드가, 거의 직접적인 getColor 메소드 처럼 느껴졌습니다.
(체스게임에서 색깔은 무조건 white 혹은 black 이므로)
저는 체스게임 말들의 색깔을 직접 가져와서, 로직의 분기가 일어나게 하기 보다는,
체스게임의 말들이 본인의 객체내에서 자신이 가진 color 에 따라, 다르게 행동하기를 바랐습니다.
그러는 편이 객체 응집도가 더 높다고 생각했기 떄문입니다.
따라서 getColor, isWhite, isBlack 메소드를 모두 삭제했습니다.

### King, Queen, Rook, Bishop, Knight 를 따로 enum 으로 만들지 않는 이유

`boolean isMovable(Position from, Position to)` 메소드를 polymorphism 으로 구현하려고 계획을 세우고 있습니다.
그러기 위해서는  King, Queen, Rook, Bishop, Knight 를 enum valuem 로 남기는게 아니라,
Piece 를 상속하는 개별적인 클래스로서 존재하게 하는게 더 적합하다고 판단했습니다.

### 중복 코드

현재 `public static Piece of` 메소드에서 중복되는 로직이 발생하고 있습니다.
팩토리 메소드를 상위 클래스인 Piece 로 올릴까 하다가, 다음과 같은 이유로 중복 코드를 남겼습니다.
- of static 메소드의 타입을 Piece 가 아닌 구체적인 하위 타입으로 지정하고 싶다. 
    - (of 의 리턴 타입이 King, Queen, Rook, Bishop, Knight 가 되게 하고 싶다.)
-  static 함수는 override 가 불가능하다.

2021-02-22 07:24 UTC, ghojeong commented
참고로, 제 스타일대로 먼저 코딩을 해 본 것이지, 제 방식을 고집할 생각은 없습니다.
만약 과제 의도 및 설계를 따라가는 편이, 의도하신 학습 효과에 더 적합하다고 생각되시면, 언제든지 설계를 변경하라고 요구해주세요 😜 
금방 설계 갈아엎어서, 올리겠습니다.

2021-02-22 13:28 UTC, tmdgusya commented
출력이 되게 깔끔하네요 !

2021-02-22 13:34 UTC, SANGCO requested changes
Pyro님 구현 잘하셨네요. 고생하셨습니다!
간단한 리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

아 그리고 이거는 리뷰하고 별게로 제가 Pyro님께 해드리고 싶은 말이 있어서요.
제가 Pyro님 코드를 보고 딱 든 생각이 있답니다.
오잉 이게 미션4 커밋이 맞나? 이런 생각이 들더군요.
코드를 보면 Pyro님의 고민이 보여서 너무 좋기는 한데
너무 다음 미션에 해야할 고민을 먼저한다? 이런 생각이 들더라구요.

차라리 딱 현재 미션만 보고 심플하게 해당 미션의 요구사항을 충족하는 코드를 만들어서
빠르게 다음 미션 다음 미션으로 넘어가시는게 더 좋지 않을까? 하는 개인적인 의견입니다.

이번 리뷰는 이번 미션에 관련된 부분만 리뷰해 드렸습니다.
나머지 부분은 빨리 다음 미션에 넘어가서 리뷰어들과 또 같이 고민해 봅시다~

2021-02-22 13:34 UTC, SANGCO commented on src/main/java/chess/domain/board/BoardFactory.java
>  package chess.domain.board;
ScannerView 클래스 수정한게 없으셔서 그냥 여기다 리뷰 드려요ㅋ
저는 ScannerView라는 클래스가 굳이 필요한가 하는 생각이 들었는데요.
이런 시도나 고민은 좋다고 생각합니다.
그런데 무조건 클래스로 도출한다고 그게 능사는 아니라는 점을 가볍게 언급하고 싶었네요.

추가로 이번 미션에서 try-with-resources 관련되어서 학습하고 적용해보면 좋을거 같아요~
Scanner와 같이 AutoCloseable을 구현한 클래스의 경우 
[try-with-resources](https://www.baeldung.com/java-try-with-resources)를 사용해서 쉽게 리소스를 해제할 수 있답니다.

2021-02-22 13:34 UTC, SANGCO commented on src/main/java/chess/domain/board/BoardFactory.java
>  package chess.domain.board;
Main클래스에 `new ChessGame().start();` 이런 코드가 있는데
```java
ChessGame chessGame = new ChessGame()
chessGame.start();
```

혹은 ChessGame 클래스의 start() 메소드를 static 하게 바꾸는게 어떨까싶네요.
`new ChessGame().start();` 이런류의 코드는 굉장히 생소해서요ㅋ

2021-02-22 13:34 UTC, SANGCO commented on src/main/java/chess/domain/board/BoardFactory.java
> +        addBlackRoyalRow(8);
요렇게 수정하신건 너무 잘하신거 같아요.
가독성이 훨씬 좋아졌네요~

2021-02-22 13:34 UTC, SANGCO commented on src/main/java/chess/domain/pieces/Color.java
> +    private final Function<Character, Character> representationStrategy;
functional 인터페이스? 좀 과한게 아닌가 싶다가도 그래도 뭐 이런 시도 좋은거 같아요~

2021-02-22 23:50 UTC, ghojeong commented
> 오잉 이게 미션4 커밋이 맞나? 이런 생각이 들더군요.
> 코드를 보면 Pyro님의 고민이 보여서 너무 좋기는 한데
> 너무 다음 미션에 해야할 고민을 먼저한다? 이런 생각이 들더라구요.

헙! 동의합니다.
미션 진행을 너무 미리 앞서나가서 고민하고 있는건 문제 같네요.
(다만 다음 미션 내용을 Lucas 에서 미리 보고와서 진행중인 것은 아닙니다. 게임할 때도 공략없이 헤딩하는 것을 좋아해서요)
다음 PR 부터는 정말로 해당 미션에서 주어진 내용에 집중해서 작성하도록 하겠습니다.

2021-02-22 23:51 UTC, ghojeong commented on src/main/java/chess/domain/board/BoardFactory.java
>  package chess.domain.board;
> 저는 ScannerView라는 클래스가 굳이 필요한가 하는 생각이 들었는데요.

동의합니다. 이렇게 분리시킨것은 과한것 같습니다.
말씀주신대로 try-with-resource 적용해보겠습니다.

2021-02-22 23:51 UTC, ghojeong commented on src/main/java/chess/domain/board/BoardFactory.java
>  package chess.domain.board;
> 혹은 ChessGame 클래스의 start() 메소드를 static 하게 바꾸는게 어떨까싶네요.

이게 더 좋겠네요. 👍

2021-02-23 00:26 UTC, ghojeong commented
@SANGCO 피드백 반영 완료했습니다!

2021-02-23 00:28 UTC, ghojeong commented on src/main/java/chess/domain/pieces/Color.java
> +    private final Function<Character, Character> representationStrategy;
원래는 RepresentationStrategy 인터페이스, UpperStrategy, LowerStrategy 클래스를 일일히 정의하려다가,
Strategy 클래스를 따로 정의하는게 과하게 지나친것 같아서, Function 인터페이스로 짧게 쓰게 되었습니다.

2021-02-23 01:05 UTC, SANGCO approved these changes
다음 미션으로 가시죠.
고생 하셨습니다~

2021-02-23 23:58 UTC, ghojeong commented
@SANGCO 다음 미션을 진행할 수 있도록 머지 부탁드립니다.

2021-02-24 01:15 UTC, merged