[Kyu] 미션 4: 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #130
Opened 2021-02-22 05:34 UTC by kyu-kim-kr

안녕하세요. 먼저 리뷰 진행 해주시는 분에게 감사드립니다. 미션 진행하면서 간략하게 느낀점? 작성해봤습니다.

---

### 1. 개념 이해
루카스에 있는 미션 요구사항과 안내사항을 보면서 처음 부딪친 것은 개념에 대한 이해였습니다. _Value Object_와 _static factory method_가 무엇인지 몰라서 공부하는 데에 시간을 하루 이상 썼습니다

### 2. StringUtils
완성된 보드를 출력하기 위해서 기존 로직에는 개행하는 문자열 _\n_ 을 직접 삽입했었습니다. _StringUtils_라는 클래스를 따로 빼서 메서드에 문자를 삽입하는 식으로 방법을 바꾸었습니다. 루카스에서 안내한 대로 따라오긴 했지만, 어떤 이점이 있을까 생각해봤습니다.

1. _\n_ 를 넣었을 땐 코드가 지저분해보였지만 쪼금? 더 깔끔하게 변했다 (가독성 향상)
2. 정적 메서드는 이름을 가지고 있어서 _StringBuilder_에 무엇이 들어가는 건지 좀 더 한눈에 파악할 수 있다. (가독성 향상)
3. _StringBuilder_에 한 라인씩 깔끔하게 _append_할 수 있다. (가독성 향상)
4. 직접 _\n_을 타입해서 넣는 것은 실수가 생길수도 있지만 정적 메서드를 사용하면서 그 실수를 줄일 수 있다. 왜냐하면 매개변수가 없으면 컴파일이 안되기 때문이다. (실수 발생 감소)

### 3. enum
꽤 많은 상수들이 생기기 시작해서 _enum_으로 처리했습니다. 근데 제 생각에는 지금은 그냥 상수를 나열해도 괜찮을 거 같습니다. 저는 _enum_을 사용하기가 왠지 모르게 꺼려지는 건 클래스 안에 클래스가 생기기 때문입니다. 코드가 별로 안이뻐보여서요.

### 4. main method
메인 메서드의 코드를 재작성했습니다. 이유는 조건문이 지저분해보여서였습니다. while문 안에서 입력을 받으니까 원하는 조건에 대한 처리가 훨씬 쉬워졌습니다.

---

감사합니다.

2021-02-22 08:12 UTC, pbg0205 commented on src/main/java/net/honux/chess/pieces/Piece.java
> +    public boolean isWhite() {
if문 없이 return this.color = Color.WHITE 이런식으로 작성하시면 코드가 깔끔해지실거 같습니다!

2021-02-22 08:20 UTC, pbg0205 commented on src/main/java/net/honux/chess/pieces/Piece.java
>          BISHOP('b'), QUEEN('q'), KING('k');
White, Black enum에서 코드 중복이 있는 부분을 색상(Color)하고 Type(Representation)을 각각 Enum으로 관리해보시는 방법도 고려해보시면 좋을거 같아요!

2021-02-22 08:21 UTC, pbg0205 commented on src/main/java/net/honux/chess/Main.java
> +        while (!(game = sc.nextLine()).equals("end")) {
오! 저도 처음에 이 방법 생각했었는데ㅋㅋㅋ

2021-02-22 08:24 UTC, pbg0205 commented
kyu가 아까 놀러와줘서 저도 놀러왔습니다ㅋㅋㅋ 몇개 안되는데 코드 보면서 떠오르는 것(?)들 한번 적어봤어요! 코코아 같이 시작했을 때에 뵙던 때보다 훨씬 성장하신거 같아 자극받고 갑니다.👍👍 열정맨 kyu 화이팅

2021-02-22 08:25 UTC, pbg0205 commented on src/main/java/net/honux/chess/pieces/Piece.java
> +    }
if문 없이 return this.color = Color.WHITE 이런식으로 작성하시면 코드가 깔끔해지실거 같습니다!

2021-02-22 08:31 UTC, kyu-kim-kr reviewed
아하 그렇군요 boolean 으로 리턴했을때 그냥 조건만 주면 알아서 판단해서 true, false를 반환하는거였군요

2021-02-22 08:33 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Main.java
> +        while (!(game = sc.nextLine()).equals("end")) {
전 요게 좋은거 같더라구요 ㅋㅋㅋ

2021-02-22 08:35 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/pieces/Piece.java
>          BISHOP('b'), QUEEN('q'), KING('k');
이왕 enum을 쓸거라면 쿠퍼말이 맞는거같아요,,제가 작성한건 그냥 상수로 쭉나열한거랑 다를바가 없다는 느낌이드네요. 감사합니다

2021-02-22 08:36 UTC, kyu-kim-kr commented
> kyu가 아까 놀러와줘서 저도 놀러왔습니다ㅋㅋㅋ 몇개 안되는데 코드 보면서 떠오르는 것(?)들 한번 적어봤어요! 코코아 같이 시작했을 때에 뵙던 때보다 훨씬 성장하신거 같아 자극받고 갑니다.👍👍 열정맨 kyu 화이팅 (리뷰할 때 코드 범위 지정(?) 하는 법을 몰라서 우당탕 되어있는데 그 부분은 양해 부탁해요ㅎㅎ)

오 ㅎㅎ 시작했을때보다 많이 성장했어요?? 그 말 정말 기쁘네요

2021-02-22 12:30 UTC, SANGCO requested changes
Kyu님 구현 잘하셨네요. 리뷰 드릴게 별로 없네요ㅋ
간단한 리뷰 남겼으니 확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-02-22 12:30 UTC, SANGCO commented on src/main/java/net/honux/chess/pieces/Piece.java
> +        }
White, Black 이렇게 색깔로 enum을 만드셨군요.
이번 미션을 수행하는데 있어서는 문제 될게 없을거 같습니다~

2021-02-22 12:30 UTC, SANGCO commented on src/main/java/net/honux/chess/Board.java
>      void initialize() {
이 메서드의 접근제한자를 디폴트로 하신 이유가 궁금합니다~

2021-02-22 12:30 UTC, SANGCO commented on src/main/java/net/honux/chess/Main.java
> +                System.out.println(board.showBoard());
"end", "start" 같은 스트링 값들을 상수로 만들어서 사용하는건 어떨까요?

2021-02-22 12:30 UTC, SANGCO commented on src/main/java/net/honux/chess/Main.java
> +        Scanner sc = new Scanner(System.in);
Scanner와 같이 AutoCloseable을 구현한 클래스의 경우 
[try-with-resources](https://www.baeldung.com/java-try-with-resources)를 사용해서 쉽게 리소스를 해제할 수 있답니다.
이번 미션에서 try-with-resources 관련되어서 학습하고 적용해보면 좋을거 같아요~

2021-02-22 20:24 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Board.java
>      void initialize() {
initialize() 말씀하시는 거죠? public 이었는데 지난 미션에서 실수로 지웠던거 같습니다

2021-02-22 20:31 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Main.java
> +                System.out.println(board.showBoard());
제가 잘몰라서,, 그냥 스트링으로 "start" , "end" 로 적어주었을때랑 상수선언했을때와 별다른 차이점을 잘 모르겠습니다.

예를 들어서,` for (int i = 0; i < 8; i++) { 체스말초기화하는 메서드들} ` 있을 때, 숫자 8은 누가봐도 무슨 의미인지 확인하는 데에 시간이 오래걸리기때문에 BOARD_SIZE 라는 상수로 선언해줬었는데요.

이번 경우에는 잘 모르겠습니다. 설명을 덧붙여주시면 고민해보겠습니다!

2021-02-22 20:33 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Main.java
> +        Scanner sc = new Scanner(System.in);
넵 감사합니다. 공부해보고 적용해보겠습니다!

2021-02-22 21:25 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Main.java
> +        Scanner sc = new Scanner(System.in);
공부해서 적용했습니다. `Scanner scanner = new Scanner(System.in)` 같이 예외처리 안해줘도 되는건 try catch 문에서 try만 작성해줘도 되는것이죠? IDE에서는 아무 에러도 안나고 잘 작동해서 질문드립니다.

2021-02-23 01:17 UTC, tmdgusya commented on src/main/java/net/honux/chess/Main.java
> +        while (!(game = sc.nextLine()).equals("end")) {
오 이거 상당히 깔끔해보이네요

2021-02-23 03:08 UTC, jihye-woo commented on src/main/java/net/honux/chess/pieces/Piece.java
> +        }
오오 이런 방식!! 깔끔하고 좋네요! 👍👍

2021-02-23 08:20 UTC, SANGCO commented on src/main/java/net/honux/chess/Main.java
> +                System.out.println(board.showBoard());
제가 생각하는 장점은 
스트링 값을 상수로 만들어 변경 지점을 한군데로 하면
향후에 추가로 재사용이나 메소드 추출, 클래스 변수, enum 등으로 바꾸기 용이한거 같아요.

호눅스는 어떻게 생각하시나요?
제가 좀 과한 리뷰를 드린걸까요?ㅋ 
아니면 또 다른 장점들이 있을까요~

2021-02-23 08:26 UTC, SANGCO commented on src/main/java/net/honux/chess/Main.java
> +        Scanner sc = new Scanner(System.in);
try-with-resources는 단순히 try()문 괄호 안에 넣은  AutoCloseable을 구현한 클래스에 close()를 호출해 주는거고
만약 try()로 감싼 로직에 익셉션을 던지는 부분이 있으면
catch로 잡던지 밖으로 던지던지 해야할거 같군요!

2021-02-23 08:29 UTC, SANGCO approved these changes
고생 많으셨습니다~

2021-02-23 22:09 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Main.java
> +        Scanner sc = new Scanner(System.in);
아하 이해했습니다. 감사합니다! 😊

2021-02-24 03:17 UTC, merged