[Roach] 미션 5: 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #135
Opened 2021-02-22 10:36 UTC by tmdgusya

이번 요구사항은 조금 어려워서 놓친것들이 세세하게 많을 수도 있다고 생각이듭니다.

최대한 요구사항에 준수하기 위해 노력했으며, 메소드 중복 또는 분리를 위해서 리팩토링을 진행하였습니다.
다만 인터페이스를 적용할 부분을 찾아보고 코드가 복잡해질지, 코드가 더 깔끔해 지는지를 계산해보라고 하셨는데
제 생각에는 각 class 내 Field 의 의존성이 높아서 인터페이스로 분리한들 별로 깔끔해지지 않겠다라는 생각이 들었습니다.
지금의 코드들과 별로 다르지 않을꺼라고 판단되었습니다. (제 기준에서는요 ! 리뷰어님들의 의견도 듣고 공부해보고 싶습니다. )
저번에 상코의 리뷰를 듣고 최대한 분리를 해보려고 했는데 잘 분리된것인지는 모르겠네요.

리뷰어님들의 리뷰 부탁드립니다!

2021-02-23 12:14 UTC, wheejuni requested changes
5단계까지 진행하시느라 고생 많으셨습니다. 💯 
진도를 다소 빠르게 나가고 있는 상황이기때문에, 다음 단계로 급히 넘어가기보단 이번 단계에서 그동안 축적되어 있던 리팩토링 포인트를 모두 해결하고 넘어가는게 좋겠군요. 
이번 리뷰 과정은 조금 험난할 수도 있겠습니다. 

아홉개의 코멘트를 통해 개선 의견을 드렸는데 우선 `Piece` 에 구현되어야 할 메소드가 하나 누락되어있는 것 같고, 여기서부터 깨끗한 설계를 하지 못하게 된 것 같습니다. 
메소드의 namespace와 리턴 타입을 아래와 같이 명시해 드리니 구현해보세요. 

```java
public boolean isMatchingColor(Color color);

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/attribute/Color.java
> +    WHITE, BLACK, NOCOLOR;
`NOCOLOR` 라는 접근법 좋은 것 같습니다. 
그런데 `enum`은 한 줄에 하나씩 선언해주세요.

```suggestion
        WHITE,
        BLACK,
        NOCOLOR;

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/attribute/Type.java
> +    BISHOP('b', 3), QUEEN('q', 9), KING('k', 0), NO_PIECE('.', 0);
여기도 같은 의견 드립니다.

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Board.java
> +    private ArrayList<Rank> board;
`ArrayList` 를 변수 타입으로 받은 코드들에 달린 다른 피드백을 참고해보시면 좋겠어요.

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
`Piece` 에게 색깔도 물어보면 더 간결한 코드로 개선할 수 있지 않을까요?

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
`piece.isWhite()` 라는 아름다운 메소드가 있는 것 같은데요, 
이걸 이용해서 더 좋은 코드로 개선할 수 있을 것 같은데, 어떻게 생각하세요?

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Rank.java
> +        return point;
재밌는 개선포인트가 있을 것 같습니다. 
`color` 베이스로 `pieceList` 를 필터한 다음, `Piece` 를 `Type` 으로 바꾼 후, 다시 `Type` 을 `double` 로 바꿔서 합계를 구하면 좋은 스트림 기반 코드 한 편이 나올 것 같네요. 

_학습 키워드_
> `.filter()`
> `.map()`, `.mapToDouble()`
> `.sum()`

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Board.java
> +        Optional<Piece> piece = Optional.empty();
`Optional` 의 잘못된 용법입니다. `Optional.empty()` 는 `return` 문과 함께 사용할때 가장 아름답습니다. 
불필요한 변수로 보이고 적절한 시점에서의 `return` 을 통해 리팩토링할 수 있을 것 같은데 고민해주세요.

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Board.java
> +    }
[이 글](https://www.baeldung.com/java-stream-filter-count) 을 읽고 리팩토링 아이디어를 얻어보세요. 
더 간단하게 줄일 수 있습니다.

2021-02-23 12:14 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Board.java
> +            appendNewLine(sb, "");
이중 `for loop` 는 많은 경우에 code smell에 해당합니다.
개선할 수 없을까요?

2021-02-24 05:25 UTC, tmdgusya commented on src/main/java/net/honux/chess/attribute/Color.java
> +    WHITE, BLACK, NOCOLOR;
감사합니다. 혹시 가독성때문인가요?
아니면 관례같은 것인가요?

2021-02-24 05:31 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
감사해요! :)

아래와 같이 바꿨더니 가독성면이나 간결성에서 훨씬 더 좋은 코드로 변신했네요.
```java
return (int) pieceList.stream().filter(Piece::isBlack).count();
```

2021-02-24 05:53 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    private ArrayList<Rank> board;
네넵 오늘 한번 읽어보고 어떤 부분에 대한 내용들이 나왔는지 정리해보고 적용시켜보도록 할께요!

2021-02-24 06:28 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
이 부분에서 piece.isWhite() 를 어떻게 써야할지 잘 모르겠습니다.
제 생각에는 여기서 representation 에 대한 비교가 일어난다고 일단 생각을 하였는데
혹시 약간의 힌트를 주실 수 있으신가요?

2021-02-24 06:30 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +        Optional<Piece> piece = Optional.empty();
오 이렇게 사용하니 적절하게 리팩토링 된것 같습니다!
이런 세세한 부분은 생각하지 못했네요 감사해요 👍 
```java
 public Optional<Piece> findPiece(String position) {
        try {
            return Optional.ofNullable(board.get(getRank(position)).get(getIndex(position)));
        } catch (IndexOutOfBoundsException e) {
            return Optional.empty();
        }
    }
```

2021-02-24 06:33 UTC, tmdgusya commented on src/main/java/net/honux/chess/attribute/Color.java
> +    WHITE, BLACK, NOCOLOR;
오우 해보니 훨씬더 깔끔해보이기는 하네요 감사해요 👍

2021-02-24 06:44 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +        return point;
와우 람다식을 이렇게 바꿔볼 수 있었어요!
```java
public int getPointsOfType(Color color) {
        return (int) pieceList.stream().filter(piece -> piece.isMatchingColor(color)).mapToDouble(Piece::getPoint).sum();
    }
```

2021-02-24 06:45 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +        return point;
진짜 간결하게 바뀐것 같네요. :)

2021-02-24 07:12 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    }
아래와 같이 단축해보았습니다 !
```java
return (int) board.stream().mapToInt(rank -> rank.countOfPiece(color, type)).sum();
```

2021-02-24 11:05 UTC, wheejuni commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
지금 우리의 요구사항에서 `Color`는 두 종류이죠?

2021-02-24 11:22 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +            appendNewLine(sb, "");
next Position 에 대한 값들을 return 해주는 방식으로 진행하면 될것 같은데 조금 더 고민을 해봐야 할 것 같아요.
이중 루프를 지우는 것이 쉬운일이 아니네요

2021-02-24 12:15 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
이런식으로 바꿔봤는데 어떻게 생각하시나요?
```java
 public int countOfPiece(Color color, Type type) { // Original
        return (int) pieceList.stream().filter(piece -> piece.getRepresentation() == type.getRepresentation(color)).count();
    }

    public int countOfWhiteTypePieces(Color color, Type type) { // New
        return (int) pieceList.stream().filter(piece -> piece.isMatchingColor(color)).filter(piece -> piece.isMatchingRepresentation(color, type)).count();
    }
```

2021-02-24 12:25 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Rank.java
> +    }
아 아래걸 바꿔보니 이렇게 해도되네요
```java
public int countOfWhiteTypePieces(Color color, Type type) {
     return (int) pieceList.stream().filter(piece -> piece.isMatchingRepresentation(color, type)).count();
}
```

```java
public boolean isMatchingRepresentation(Color color, Type type) {
    return this.representation == type.getRepresentation(color);
}
```

해당 Color 별 Type에 대한 Representation 을 가져오고, 현재 Piece 의 Representation 최대한 Piece 에 색깔과 Color 를 물어보는 방향으로 코드를 바꿔보았습니다. 확실히 객체 지향상으로도 기존의 코드에서 비교문을 쓰기보다는 객체 자체에서 piece.isMatchingRepresentation(color, type) 색깔과 Type 에 대한 boolean 을 주는것이 좋은것 같습니다 !

2021-02-24 12:43 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +    private ArrayList<Rank> board;
일단 리뷰들을 돌아다니며 정리한 바로는
1. board 의 경우 재할당이 되어야 할 이유가 없으므로 final 로 선언하는 것이 좋다. => final 로 적용한뒤 생성자에서 해당 구현체를 대입해주자.
2. ArrayList<Rank> board; => List<Rank> board; : 이 부분은 제가 List 로 선언했었는데 .. 또 무언가 하다가 바뀌었는데 인지하지 못했군요. 이런 기본적인걸 놓쳐서 Commit 하다니 앞으로는 조금 더 신중하게 봐야겠다는 생각이 듭니다.

2021-02-25 05:40 UTC, tmdgusya commented on src/main/java/net/honux/chess/core/Board.java
> +            appendNewLine(sb, "");
RANK 라는 Enum 을 도입하고 체스 기물들이 가질수 있는 Position 을 갖도록 하여 처리하였습니다.
이번 리뷰 관련된 내용 다시 commit 올리도록 하겠습니다.

부족한 부분이나 좋지않은 방향으로 개선된 부분 알려주시면 감사하겠습니다 👍

2021-02-25 13:13 UTC, wheejuni approved these changes
수고하셨습니다. 👍

2021-02-25 13:13 UTC, wheejuni commented on src/main/java/net/honux/chess/entity/pieces/Piece.java
> +        return this.color == color;
👍

2021-02-25 13:13 UTC, merged

2021-02-25 13:38 UTC, tmdgusya commented on src/main/java/net/honux/chess/entity/pieces/Piece.java
> +        return this.color == color;
덕분에 2중 루프를 없애는 방향에 대한 생각을 할 수 있었습니다.
그리고 조금 더 아름다운 코드들에 대한 방향성에 대해 생각을 많이 하게된것 같습니다.
덕분에 많이 발전한것 같습니다 감사합니다 👍