[마르코] Mission4 모든 기물 배치하기 PR 요청합니다.
codesquad-members-2021/java-chess pull request #141
Opened 2021-02-23 08:43 UTC by 95degree

안녕하세요 백엔드 마르코 입니다.
미션4 모든 기물배치하기 PR요청입니다. 이번미션을 통해 정적팩토리메소드를 알게되었고 왜 쓰는지에 대해서 고민해봤습니다.
## 질문
지금까지 미션에서의 이점은 가독성(어떤 색의 어떤 기물을 생성하는지 알기 쉽다)이였습니다. 
이외의 공부해본 다른 장점들은 아직 못 느끼고 있습니다. 
저는 이번 미션에서는 가독성말고는 다른 장점이 없는것 같은데 혹시 제가 캐치 못 한 부분이 있습니다. 리뷰부탁드립니다. !!

## 미션4 정리
- StringUtils 클래스를 추가하여 board 출력에 필요한 문자와 개행문자를 합치는 appendNewLine()을 
static 메소드로 추가하여 필요한 클래스에 import static으로 선언했습니다.

- Piece 클래스에 기물을 추가하는 것을 정적팩토리 메소드로 선언하여 한번에 어떤색의 어떤 기물을 생성하는것인지 알아 볼수 있게 했습니다. isPawn(), isWhite() ,isBlack() 을 선언하여 색이 다르거나, 폰이 아닌 기물이 폰 리스트에 들어가는 것을 방지했습니다.

- Board 클래스에 폰 이외의 기물을 넣을 list를 색깔별로 추가했습니다.

2021-02-23 13:11 UTC, LarryJung reviewed
안녕하세요~ 구현 잘 하셨구요, 수고하셨습니다!
테스트도 잘 작성해주셨고, 전체적으로 가독성 있게 잘 봤습니다. (코드는 가독성이 진짜진짜 중요하다고 생각합니다..)

Piece 클래스 내의 각종 데이터들을 어떻게 효율적으로 관리할 수 있을지 코멘트 보시고 고민해 주시면 좋을것 같습니다. 관련된 데이터 묶음과 기능이 보이면 끊임없이 객체로 도출해내는 연습이 필요할 것 같습니다!

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/chess/Board.java
> +    private List<Piece> blackPieces = new ArrayList<>();
혹시 멤버 변수는 2개 이하 라는 요구사항이 있다면.. 어떻게 하실건가요?
현재는 이렇게 가는게 이전미션에서 큰 수정 없이 접근할 수 있어서 괜찮지만, 왠지 중복이 있는것처럼 보이기도 하네요 ㅎㅎ

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/chess/Board.java
> +            whitePieces.add(piece);
else 를 처리할 필요는 없을까요? false를 응답한다던지.. exception을 발생한다던지..

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    public static final char BLACK_KING_REPRESENTATION = 'K';
enum을 활용해보시는것도 좋을것 같습니다~

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    private char representation;
멤버 변수에 final 을 선언하면 어떤 장점이있을까요?

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    }
enum을 활용하면 equals말고 == 로 비교할 수 있습니다.^^

2021-02-23 13:11 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    }
pawn여부를 representation으로 비교하는게 조금 어색하게 느껴지네요,
pawn 에 대한 정보가 representation 이외에 점점 더 많은 데이터가 붙게 되면 그 조건이 모두 isPawn() 안으로 와야할것 같구요 

기물에 대한 정보를 잘 모아둘 수 있는 클래스나 enum 등이 필요할 시점인것 같습니다.

2021-02-23 13:11 UTC, LarryJung commented on src/test/java/pieces/PieceTest.java
> +    void verifyPiece(final Piece piece, final String color, final char representation) {
메서드 인자의 final 은 어떤 의도로 사용하셨나요?

2021-02-23 13:11 UTC, LarryJung commented on src/test/java/pieces/PieceTest.java
> +class PieceTest {
테스트 꼼꼼하게 잘 작성하셨네요~

2021-02-23 13:11 UTC, LarryJung commented on src/test/java/pieces/PieceTest.java
> +        assertThat(Piece.createWhiteBishop().isPawn()).isFalse();
여기는 assertAll 사용 안하셨네요

2021-02-23 13:21 UTC, LarryJung requested changes
request changes 마크용입니다. 제가 자꾸 빼먹어서^^ 😀

2021-02-24 06:08 UTC, 95degree commented on src/main/java/pieces/Piece.java
> +    private char representation;
final을 선언하면 더 이상 값이 변경되지 않는 상수가 되어 
함부로 값을 바꿀 수 없게 되어 안전해집니다. 
여기서 한번 선언된 color와 representation은 바뀌면 안되는 값이니 final로 선언해야 하네요 !!!

2021-02-24 06:18 UTC, 95degree commented on src/main/java/pieces/Piece.java
> +    public static final char BLACK_KING_REPRESENTATION = 'K';
코멘트를 바탕으로 Color와 Type enum을 만들었습니다.
확실히 enum으로 상수를 관리하니 코드도 더 깔끔해보이고 equals가 아니라 ==으로 비교하는 편이 단순히 문자열을 비교하는 것 보다 검정색, 흰색을 비교한다는 확실한 이미지가 드네요 :)

2021-02-24 06:18 UTC, 95degree commented on src/test/java/pieces/PieceTest.java
> +        assertThat(Piece.createWhiteBishop().isPawn()).isFalse();
아 제가 빼먹었네요 다시 수정했습니다. !!

2021-02-24 06:28 UTC, 95degree commented on src/main/java/chess/Board.java
> +    private List<Piece> blackPieces = new ArrayList<>();
체스판 위에는 폰줄과 뒤에 폰 이외의 기물을 위치합니다. 현재는 2차원 배열이 아닌 list로 관리하기 때문에 한 List에 담는 것 보다 폰줄과 폰 이외의 줄로 나누는 편이 코드를 읽는 사람도 머릿속에 잘 그려지고 board를 출력할 때도 index를 사용하지 않고 한꺼번에 폰줄과 폰 이외의 줄을 출력하면 되기 때문에 더 편하다고 생각합니다.

2021-02-24 06:31 UTC, 95degree commented on src/main/java/pieces/Piece.java
> +    }
enum을 추가하여 수정완료했습니다. 😃

2021-02-24 06:37 UTC, 95degree commented on src/main/java/pieces/Piece.java
> +    }
확실히  많은 데이터가 들어오게 되면 더 복잡해지겠네요.
enum으로 관리하니 representaion이 아니라 PAWN이라는 enum으로 비교할 수 있어 전보다 더 좋네요!!!!

2021-02-24 06:38 UTC, 95degree commented on src/test/java/pieces/PieceTest.java
> +    void verifyPiece(final Piece piece, final String color, final char representation) {
테스트 메소드 예시에 final이 선언되어 따라쳤습니다.
다시 생각해보니 굳이 final로 선언되어야 할 이유가 없네요, 수정완료했습니다.

2021-02-24 06:39 UTC, 95degree commented on src/test/java/pieces/PieceTest.java
> +        assertThat(Piece.createWhiteBishop().isPawn()).isFalse();
이번 PR을 통해 정말 많은 것을 배웠습니다!!!!!!
소중한 리뷰 감사합니다 :)  👍 👍 👍 💯

2021-02-24 07:17 UTC, 95degree commented on src/main/java/chess/Board.java
> +            whitePieces.add(piece);
이 부분은 아직 제가 어느 방향으로 수정해야할지 고민이 되는 부분입니다. 

제 생각에는 if 문이 엉뚱한 Piece가 추가되는 것을 막아주는 것 같은데 여기서 else로 false를 응답시키거나 exception을 발생 될 상황은 제가 코드를 잘못 쳤을때 생기는 상황 뿐이지, 플레이어가 플레이하면서 생기는 부분은 아닙니다. 
그래서 저는 그저 제 코드가 올바른지 테스트 하는 역할뿐이라고 생각합니다. 제가 코드를 작성하고 실행했을때 잘못된 부분을 알 수 있으니까요
하지만 그 역할은 이미  테스트 코드에서도 하고있다고 생각합니다. 
현재는 else를 추가했을때의 이점을 잘 모르겠습니다. 혹시 제가 캐치하지 못한 부분이 있으면 코멘트 부탁드립니다.!!!

2021-02-24 15:53 UTC, LarryJung commented on src/main/java/chess/Board.java
> +            whitePieces.add(piece);
네 저도 항상 고민하는 부분이기도 해서 질문으로 남겼던 거구요 ㅎㅎ
말씀대로 플레이 상황에서 예외가 발생할 여지도 없고, false나 Exception을 발생한다고 해도 의미없는 예외처리를 해야할 수도 있겠네요~ (initialize() 안에서 try catch 를 한들...)

나름의 기준대로 작성하는 모습이 좋아 보입니다~!

2021-02-24 15:55 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    }
네 하지만 덩치가 더~ 커지면 enum 을 넘어 추상클래스, 인터페이스 등으로 추상화를 해야 할 수도 있으니 염두하시면 좋을 것 같습니다^^

2021-02-24 15:55 UTC, LarryJung commented on src/test/java/pieces/PieceTest.java
> +    void verifyPiece(final Piece piece, final String color, final char representation) {
네 참고로 메서드 arg에 final 이 들어있는데 null 값을 넣으면 NPE가 뜹니다. (아마 그럴거에요..)

2021-02-24 15:59 UTC, LarryJung approved these changes
수고 많으셨습니다. 수정분 잘 확인했구요! 머지하시고 다음 단계 진행하시지요~

2021-02-24 15:59 UTC, LarryJung commented on src/main/java/pieces/Piece.java
> +    private final char representation;
representation을 멤버 변수로 꼭 두어야 할지?
아니면 getRepresentation() 을 호출할때 그때 계산해서 값을 넘겨줄 지? 

고민해보시고 다음 미션에 반영해주시면 좋을 것 같습니다. ㅎㅎ

2021-02-24 16:00 UTC, merged