[NAS] 미션 5: 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #142
Opened 2021-02-23 08:57 UTC by Malloc72P

안녕하세요!
백엔드 클래스의 NAS예요! 😄 

미션5에 대한 Pull Request를 남기게 되었습니다! 🚢 

작업내용은 아래와 같습니다!

### 1. 기물의 색과 종류에 따른 enum을 적용했습니다.
색은 ColorOfChessPiece, 종류는 NameOfChessPiece라는 enum으로 구현했습니다.
또한 기물의 종류에 따른 P, K등의 식별문자를 NameOfChessPiece enum으로 관리했습니다.
추가로, 기물의 점수도 해당 enum에서 관리하도록 했습니다.
```java
public enum NameOfChessPiece {
    PAWN("P", 1),
    ROOK("R", 5),
/*~~~*/
```
### 2. 기물과 색에 해당하는 기물의 개수를 반환하는 기능을 구현했습니다.
`getNumberOfDesignatedPiece()`메서드를 구현해서, 해당 기능을 구현했습니다.
패러미터로 기물의 이름과 색상을 받아서, 지정된 색상에 해당하는 체스말의 개수를 구해서 반환하게끔 하였습니다.

### 3. 주어진 위치의 기물을 조회하는 기능을 구현했습니다.
해당 기능의 구현을 위해서, `ChessCoordinate`클래스를 만들었습니다.
`ChessCoordinate`클래스는 좌표관리를 담당하는 객체의 클래스입니다.
해당 클래스에는 `parseStringCoordinate(String strCoordinate)`라는 정적 메서드가 있습니다.
`ChessCoordinate`클래스는 `e5`와 같은 문자열 좌표를, 체스보드의 배열상에서의 좌표로 변환하는 서비스를 제공합니다. 이 서비스는 Board클래스에서 이용합니다.
위의 기능을 이용해서 주어진 위치가 배열에서 어디인지 알아내고, 해당 위치의 체스말을 반환하도록 구현하였습니다.

### 4. 임의의 기물을 체스판에 추가하는 기능을 구현했습니다.
체스판의 어디에 추가할지는 문자열로 입력받습니다. 따라서 체스말을 찾는 기능을 구현할때와 마찬가지로, `ChessCoordinate`클래스의 도움을 받아서 어디에 추가해야 하는지를 알아냅니다.
또한, 예전에 `public void add(ChessPiece piece, int rankIdx, int fileIdx)`라는 메서드를 구현했습니다. 이 메서드는 배열상의 좌표를 가지고 체스판에 체스말을 추가하는 메서드입니다. 그래서 이번 기능은 오버로딩을 이용해서, 간단하게 아래와 같이 구현할 수 있었습니다.
```java
public void add(ChessPiece piece, String strCoordinate) {
    ChessCoordinate coordinate = parseStringCoordinate(strCoordinate);
    add(piece, coordinate.rankIndex, coordinate.fileIndex);
}
```

### 5. 점수계산 기능을 구현했습니다
NameOfChessPiece enum에 추가한 point필드를 이용해서 구현했습니다. 

### 6. 점수가 높은 순으로 정렬된 체스말을 컬렉션에 담아 리턴하는 기능을 구현하였습니다
체스말 클래스인 `ChessPiece`클래스에 두개의 `Comparator`를 정의하였습니다. 해당 `Comparator`는 체스말의 점수를 가지고 비교합니다. 이렇게 구현된 `Comparator`는 Board클래스의 `getPiecesOfColor`메서드에서 사용합니다. 컬렉션에 담은 체스말을 오름차순 또는 내림차순으로 정렬하기 위해서입니다.

### 7. 코드를 좀 더 개선했습니다
* if문을 쓸때, 한줄짜리 코드인 경우, 블록안에 넣지 않고 썼었는데, 전부 블록안에 넣어서 쓰도록 수정했습니다. 확실히, 이렇게 짜니까 보기도 더 좋고, 나중에 실수할 확률이 줄어들 것 같습니다.
* 배열을 다루는 for루프에서 0부터 시작하도록 고쳤습니다. 예전엔 실제세계에서 체스판을 다루는거랑 같게 하려고 1부터 시작했었습니다. 대신 내부적으로는 -1을 해주었는데, 이게 오히려 코드를 복잡하게 만드는 것 같아서 0부터 시작하도록 했습니다.

이상으로 글을 마치겠습니다! 😆 
다시 날이 추워지는 것 같은데, 감기 조심하세요! ❄️

2021-02-24 10:44 UTC, wheejuni requested changes
과제 진행하시느라 수고 많으셨습니다 👏👏
몇 가지 변경 의견을 드렸는데요, 확인해주시고 더 좋은 코드를 만들 수 있었으면 좋겠습니다!

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
> +        }
여기서 사용된 `idx` 라는 축약어는 모두 완전한 단어로 바꿔주세요.

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
>      private int numberOfPieces = 0;
이 변수를 없애는 리팩토링을 진행하면 좋을 것 같은데요. 
설계에 조금 변경이 필요할 것 같기는 합니다.

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
> +        float totalPoint = 0;
외부에 변수가 선언되지 않고도, `for loop`나 `stream`을 이용해서 진행해볼 방법은 없을까요?

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
> +        }
다음 원칙에 입각하여 설계를 다시 구상해주세요. 
이 메소드 안에서의 수정뿐만 아니라, 연관되어 있는 다른 클래스들의 수정이 필요할 수도 있습니다. 

**원칙**

- `.get` 하지 않는다. 물어본다. 
- 카운트를 올리지 않는다. _거르고 골라내서 갯수를 센다._

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
> +    }
여기서도 같은 설계 원칙이 적용돼야 할 겁니다.

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
>  import static net.nas.utils.StringUtils.appendNewLine;
스태틱 임포트는 아껴 주세요. 
클래스의 이름을 통해 스태틱 메소드의 의미가 비로소 완성되는 경우가 많습니다. 스태틱 임포트하지 않는 것이 오히려 가독성에 도움이 됩니다. 기계적으로 무조건 워드 카운트를 줄이는 것이 항상 클린 코드로 가는 길은 아닙니다.

2021-02-24 10:44 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
> +            }
`ColorOfChessPiece` 에 스태틱 메소드가 추가된다면, 이 부분을 매우 깔끔히 바꿀 수 있을 듯합니다.

2021-02-24 12:30 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
> +        }
넵! 알겠습니다. 축약어보다는 완전한 단어가 더 좋을 것 같네요!
앞으로는 축약어 사용을 피하는 편이 좋을 것 같다는 생각이 드네요 😄 
해당 내용 수정해서 커밋하겠습니다!

2021-02-24 12:32 UTC, wheejuni commented on src/main/java/net/nas/chess/Board.java
>      private int numberOfPieces = 0;
아... 이 변수란 `numberOfPieces` 를 말합니다.

2021-02-24 12:32 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
>      private int numberOfPieces = 0;
음 혹시 어떤 변수를 말씀하시는건지 알 수 있을까요?
chessCells변수는 체스보드에 배치된 체스말을 표현하는 변수라서 꼭 필요합니다.

numberOfPieces변수도 보드에 배치된 체스말의 개수를 유지하는데 필요한 변수라서
해당 변수도 꼭 필요해요. 혹시 어떤 이유로 없애는 편이 더 나은지 알 수 있을까요?

2021-02-24 12:43 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
> +        float totalPoint = 0;
`외부에 변수를 선언하지 않고도` 라는 말을 잘 이해하지 못하겠어요.
코멘트를 보면 `float totalPoint = 0`을 말씀하신 것 같은데요, 이 변수를 선언하고 사용하는데에 어떤 문제가 있을까요?

2021-02-24 13:12 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
> +        }
getter메서드로 ChessPiece클래스의 멤버변수값을 가져와서 비교연산하기보다, 그냥 ChessPiece객체한테 물어보는 방식으로 짜는게 더 나은 것 같네요!
```java
ChessPiece currentPiece = chessCells[rankIndex][fileIndex];
if (currentPiece.isNotSameColor(color)) {
    continue;
}
if (currentPiece.isBlank()) {
    continue;
}
```
위의 코드는 get하지 않고 물어보는 방식으로 수정한 코드예요!
조건식안에 `color != ~~` 이렇게 써두니까 확실히 이해하기가 어렵더라구요 😆 
분명히 제가 짠 코드인데도 다시보니까 `어? 이게 뭐였더라?`라고 생각하게 되네요 ㅎㅎ
그래도 바꾸고 나니까 아, 이 코드는 ChessPiece한테 아규먼트로 보낸 색이랑, 얘가 가진 색이랑 같은지 물어보는 코드구나! 하고 쉽게 알 수 있어서 좋은 것 같아요! 감사합니다!

아 그리구, `카운트를 올리지 않는다` 이 부분이 잘 이해가 안가요. `numOfPawnInFile`변수를 말씀하신 것 같은데 혹시 맞나요? 이 변수를 이용해서 카운트를 한 이유는, 세로줄에 폰이 연속해서 있으면 0.5점으로 계산해야해서 이렇게 작성했어요. 혹시 이런 방법을 선택하면 어떤 문제가 발생할 수 있을까요? 곰곰히 고민해봤는데 저는 괜찮을 것 같아서요.

2021-02-24 13:14 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
> +    }
넵! 이 부분도 get을 하기보다 ChessPiece한테 물어보는 방식으로 수정했습니다!
이전보다 더 읽기 좋은 코드가 된 것 같아서 너무 좋습니다!
```java
ChessPiece currentPiece = chessCells[rankIndex][fileIndex];
if (currentPiece.isNotSameColor(color)) {
    continue;
}
if (currentPiece.isBlank()) {
    continue;
}
pieceList.add(currentPiece);

```
혹시 더 개선할 만한 부분이 있다면 알려주시면 감사하겠습니다! 😄

2021-02-24 13:17 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
>  import static net.nas.utils.StringUtils.appendNewLine;
아하.. 이게 오히려 가독성을 해칠 수도 있겠네요...
Board클래스에서  `parseStringCoordinate` 스태틱 메서드가 나오면 어라? Board클래스에 이런 스태틱 메서드가 있었나? 라는 생각이 들 수 도 있을 것 같네요...
확실하게 `ChessCoordinate.parseStringCoordinate()`라고 써주는 편이 가독성을 높이는 측면에서 더 좋을 것 같아요!
놓친 부분을 알려주셔서 정말 감사합니다! 😄

2021-02-24 13:20 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
> +            }
리뷰어님 말을 듣고 생각해보니까, 이 기능은 추출하는게 나을 것 같다는 생각이 들었어요!
확실히 표현문자를 가지고 어떤 색상인지 알아내는 기능이니까, ColorOfChessPiece Enum에 이런 기능을 가진 스테틱 메서드를 추가하는편이 좋겠더라구요.
```java
ColorOfChessPiece.getColorByRepresentation(currChar);
add(createChessPiece(nameOfCurrPiece, colorOfCurrPiece), rankIndex, i);
```
그래서 위의 코드처럼 수정할 수 있었어요! 
앞으로 프로그래밍할때 추출할 수 있는 기능은 추출하는 연습을 하겠습니다! 💪

2021-02-24 13:28 UTC, Malloc72P commented on src/main/java/net/nas/chess/Board.java
>      private int numberOfPieces = 0;
`numberOfPieces`변수를 만든 이유는, 체스보드에 배치된 말의 개수를 빠르게 획득하기 위해서입니다. 체스판에 말이 몇개 배치되었는지 알고싶을때마다 2차원 배열을 전부 순회하는건 너무 비효율적이라고 생각했어요.

그런데 어차피 Board클래스의 `chessCells`는 private이고, 여기에 객체를 추가하거나 없애는 연산은 오직 Board클래스에만 있으니까, add 또는 remove할때 numberOfPieces를 업데이트해주면, 나중에 체스말이 몇개있는지 알고 싶을때, 2차원 배열을 전체 순회할 필요 없이 `numberOfPieces`변수값만 한번 읽어서 리턴하면 되니까 더 좋을 것 같아서 작성하게 되었어요.

음.. 확실히 이렇게 하면 프로그램의 복잡도가 증가할 거라고 생각해요. 솔직히 2차원배열이라고 해봤자 8 X 8 크기밖에 안돼서 그냥 전체순회해도 문제는 없을 것 같기는 한데, 저는 그래도 numberOfPieces변수를 유지하는편이 효율성 측면에서 더 낫지 않을까 하는 생각이 드네요.

2021-02-24 13:43 UTC, Malloc72P commented
안녕하세요?
코멘트 해주신 내용 잘 읽었어요! 😄 
리뷰내용을 반영해서 추가로 커밋했어요!

추가로 수정한 내용은 아래와 같습니다.
#### 1. 축약어 idx를 index로 전부 수정했습니다!
#### 2. static import대신, 명확하게 `ChessCoordinate.parseStringCoordinate()`로 수정했습니다!
#### 3. `initRankByString()`메서드에 있는 기능을 추출해서 `ColorOfChessPiece` enum에 메서드를 추가했습니다!
#### 4. `.get`을 쓰기 보다, ChessPiece클래스에 물어봐서 비교연산을 수행할 수 있도록 수정했습니다!
* 이렇게 수정하니까 가독성도 좋아지고, 실수할 일도 줄어들 것 같습니다!
#### 5. Board클래스에서 `numberOfPieces` 멤버변수를 제거했습니다!
* 프로그램의 복잡도를 낮추는데 도움이 될 것 같습니다!

수정한 내용은 이상입니다!
제 코드를 리뷰해주셔서 감사합니다!

2021-02-25 13:18 UTC, wheejuni approved these changes
수고 많으셨습니다 💯

2021-02-25 13:18 UTC, merged