[K] 미션 5: 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #143
Opened 2021-02-23 09:08 UTC by PizzaCola-K

### 1. 기물의 색, 기물의 종류에 따른 enum 구현
- 기존의 Color enum에 NO_COLOR, Type enum에 NO_PIECE를 추가하였습니다.
- 사용하지 않던 Color enum의 String color를 삭제하였습니다.
- Type 의 getRepresentation(Color color) 메소드를 삭제하였습니다.
  - Color와 Type이 연관 관계가 없도록 하기 위해 이를 두 메소드로 나누었습니다.
  - 두개가 연관관계가 있다면, 둘다 알고 있는 객체에게 그 처리를 맡기는 것이 좋을 것 같습니다.
- Type 에 point를 추가하였습니다. 이후 점수 계산에 사용합니다.

### 2. Piece에 대한 색과 기물에 따라 분리된 팩토리 메소드에서 enum 사용
- 빈칸을 생성할 수 있는 createBlank() 팩토리 메소드를 추가하였습니다.

### 3. 팩토리 메소드 리팩토링
- 내부에  createWhite(type), createBlack(type)를 사용하여 코드 중복을 줄였습니다.
  - Color를 사용하는 메소드가 줄어든 것은 사실인데... 이게 진짜 줄어든 것이 맞는지 궁금합니다.
 
### 4. 체스판의 모든 칸을 Piece로 초기화
- 빈칸도 추가적으로 관리하는것이 좋은 이유는 Piece가 위치를 가지게되면 이후 체스말을 이동할 때 언제나 Piece 갯수만큼 탐색해야하므로 비효율적입니다.
- 그래서 컬렉션의 index와 체스판의 위치를 연관시키는 것이 좋습니다.
- 보드 자료구조를 Piece[] 로 선택하였습니다.
- ArrayList<ArrayList<Piece>>로 실제 구현해보았지만, 이중으로 접근하는 것이 좋지 않았습니다.
- ArrayList<Rank>는 ArrayList<ArrayList<Piece>>와 사실상 다를 것이 없다고 생각하였습니다.
- 그리고 체스판은 8 * 8로 고정이므로, ArrayList에서 Size가 자동으로 늘어나는 기능이 필요하지도 않습니다.
- Rank(row)를 붙여서 1차원 배열로 구성하였습니다. 점수 계산의 경우 File을 기준으로 구현하는 것이 효율적이나, showBoard()는 Rank를 기준으로 붙이는 것이 더 효율적이고, 게임 명령어 입력마다 showBoard()를 할 것이기 때문에 빈도가 높은 showBoard()를 기준으로 하였습니다.

### 5. 기물과 색에 해당하는 기물의 개수를 반환
- Board.countPieceByColorAndType() 메소드는 Board의 squares 배열을 탐색하여 조건에 맞는 기물의 개수를 반환합니다.

### 6. 주어진 위치의 기물을 조회
- Board.findPiece(String position)은 position 위치에 있는 기물을 반환합니다.

### 7. 임의의 기물을 체스판 위에 추가
- Board.move(String position, Piece piece)는 position 위치에 piece를 설정합니다.
- 현재 움직이는 기능은 없고, 단순히 설정만 합니다.
- String position은 Board 내부의 객체인 PositionParser를 이용하여 squares에 접근할 수 있는 index로 변환할 수 있습니다.
- 현재 에러 검증 로직은 없습니다.

### 8. 체스 프로그램 점수 계산하기
- Board.calculatePoint(Color color)는 검은색 또는 흰색의 남은 말들의 점수 합을 계산합니다.
- File을 탐색하며, 점수를 계산합니다.

### 9. 기물의 점수가 높은 순으로 정렬
- PieceSortTest에 Piece를 점수를 기준으로 정렬하였습니다.
- Type을 점수 순으로 나열하여, Type을 이용하여 바로 정렬할 수 있도록 하였습니다.
- Stream으로 변환하여 정렬도 하고, List의 sort 메소드를 이용하여 정렬하였습니다.

### 인터페이스 사용
아직까지 Piece의 경우, Type과 Color에 따라 동작하는 것이 달라지는 경우가 없습니다. 이후 Piece의 이동을 실제로 구현한다면, 사용해도 괜찮을 것 같습니다.
Board의 경우 객체로 나누어 기능을 분리한다면 모를까, 인터페이스가 필요하진 않을것 같습니다.

리뷰 잘부탁드립니다!

2021-02-24 07:44 UTC, SANGCO requested changes
K님 구현 잘하셨네요. 고생하셨습니다!
우선 8번, 9번 요구사항을 제외하고 간단한 리뷰 남겼습니다.

K님과 얘기 나눠보고 싶은 부분이 있습니다.ㅋ
우선 전체적으로 구현 너무 잘해주셨고 
Piece를 배열로 관리하시는 부분도 좋다고 생각합니다!

제가 얘기 나누고 싶은건
- 요구사항 4번에 힌트로 언급된 체스판 row를 Rank라는 클래스로 추상화
- 요구사항 7번에서 제안하는 체스판의 하나하나의 공간 즉 좌표를 추상화

이 부분에 대해 K님은 어떻게 생각하시는지 궁금합니다.
혹시 미션 과제 구현시 이 부분을 고민을 해보셨는지요?

2021-02-24 07:44 UTC, SANGCO commented on src/main/java/pieces/Piece.java
> +    }
이 부분은 클래스 제일 밑으로 위치 시켜야 합니다!

2021-02-24 07:44 UTC, SANGCO commented on src/main/java/chess/Board.java
> +        }
저는 개인적으로 이 기능이 클래스로 도출 할 만한 기능인지 의문이 드는군요!

요구사항 7. 임의의 기물을 체스판 위에 추가
여기에 위치 값을 클래스 추출하는걸 제안하고 있는데
혹시 그것 때문에 따로 클래스로 빼셨나 싶기는 하네요.

참고로 요구사항 7번에서 제안하는 클래스 분리는 체스판 위에 하나하나의 공간
그 공간을 추상화 해보는걸 제안하고 있습니다.

2021-02-24 07:44 UTC, SANGCO commented on src/main/java/chess/Board.java
>      }
이거는 리뷰는 아니고 개인적인 의견인데 초기화 로직이 클래스 위쪽에 위치하는게 깔끔하지 않을까요?

initialize() 메서드가 사용하는 순서데로 initializeRank1, initializeRank2 ... 
이 순서로 메서드를 배치하는게 깔끔하지 않을까요?

이거는 그냥 개인적인 스타일입니다ㅋ

2021-02-24 07:44 UTC, SANGCO commented on src/test/java/pieces/PieceSortTest.java
> +    private void addPiecesInCollection(Collection<Piece> pieceCollection) {
전체적으로 Collection 인터페이스를 사용하는 곳이 많은데 
왜 Collection 인터페이스로 하셨는지 궁금합니다~

2021-02-24 09:45 UTC, PizzaCola-K commented on src/main/java/chess/Board.java
> +        }
> 요구사항 7. 임의의 기물을 체스판 위에 추가
> 여기에 위치 값을 클래스 추출하는걸 제안하고 있는데
> 혹시 그것 때문에 따로 클래스로 빼셨나 싶기는 하네요.

생각하신 것이 맞습니다.

Board 관점에서 Board.findPiece("a4")나 Board.move("d2")와 같이 외부에서 Board에 접근할 때는 추상화된 String position으로 접근하고, 내부적으로는 이를 실제 index로 계산해서 사용한다고 생각했습니다.

그리고 위치값을 *처리*하는 클래스를 추가해보라 되어 있어 위치값을 index로 계산하는 메소드가 아닌 객체로 구현하였습니다. 

그러고서 Board의 내부에선 1차원 배열인 square의 접근을 (0,0) (0,1)... (7,7) 까지의 행렬로 접근하는 것을 구현하였습니다. 그런데 리뷰어분께서 이야기 하신 것처럼 여전히 "a1", "b4" 와 같이 읽기 쉬운 형태가 아니라 이해하지 않으면 보기 힘든 코드로 접근합니다. 조금 고민을 해봤지만, Board 내부에서 일어나는 일인데 더욱 고민할 필요 있나 싶어서 여기까지만 하였습니다.

미션 6에서 Board의 기능을 분리하게 되면서 Board와 다른 객체 사이의 메시지 교환이 생겼습니다. 그러면서 생각한 방법이 있는데, 외부에서 받은 String을
```java
enum Rank {
    EIGHT(0),
    SEVEN(1),
    ...
    ONE(7)
}
enum File {
    A(0),
    B(1),
    ...
    H(7)
}
```
로 나누고, Board의 public 메소드로 위치를 받을때는 이 두개를 매개변수로 받고 내부적으로는 두개를 이용하여 index를 계산하는 것입니다.

이러면 Board 외부에서 Board에 메시지를 보낼 때 for (Enum e : Enum.values()) 같이 foreach문도 사용할 수 있고, 내부적으로도 저 두개를 이용하여 실제 index를 계산하는 메소드를 이용하여 보기 쉬운 코드를 만들 수 있을 것 같습니다.

2021-02-24 09:45 UTC, PizzaCola-K commented on src/main/java/chess/Board.java
>      }
이건 아마 자동완성 기능 사용하다보니 역순으로 배치한 것 같기도 하고... 원래 윗줄부터 초기화하다가 숫자 증가하는 순으로 메소드 배치하는게 좋겠다 싶어서 배치하고서 실제 메소드를 재배치를 안한 것 같습니다.

그리고 initialize가 위에 있지 않은건 어쩌다보니 initalize가 initializeRank1, 2 와 같이 사용되서 덩어리가 큰 것은 아래에 두는게 좋지 않나 라는 생각이었습니다.

2021-02-24 09:45 UTC, PizzaCola-K commented on src/test/java/pieces/PieceSortTest.java
> +    private void addPiecesInCollection(Collection<Piece> pieceCollection) {
특별한 이유는 아닙니다. 요구사항에서 Collection을 강조한 것 같아 최대한 Collection을 사용하였습니다.

> 9. 기물의 점수가 높은 순으로 정렬
> 검은색과 흰색 기물을 구분해서 점수가 높은 순서로 정렬한다.
> 높은 순서로 정렬하는데 성공했다면 낮은 순서로도 정렬해본다.
> 각 색에 해당하는 모든 기물을 자바 collection에 저장한다.
> collection의 정렬 기능을 활용해 점수가 높은 순서에서 낮은 순으로 정렬한다.

그러면서 추가로 공부를 하기 위해 Stream의 기능도 이용해보고 Collection의 Sort도 찾아보고 하였습니다. 그러고 보니, Collections.sort()는 List만 받아서 Collections.sort()를 사용하는 컬렉션은 List로 바꿨습니다.

2021-02-24 09:45 UTC, PizzaCola-K commented on src/main/java/pieces/Piece.java
> +    }
네 알겠습니다. 팩토리 메소드가 많아 덩어리가 크다고 생각해서 작은 메소드들을 위에 두는 것이 좋겠다 생각했었습니다.

2021-02-24 09:59 UTC, PizzaCola-K commented
> 요구사항 4번에 힌트로 언급된 체스판 row를 Rank라는 클래스로 추상화

다른 분들이 리뷰를 받은 것을 보니 2차원 배열을 사용하지 말라고 하셨는데, ArrayList<ArrayList<Piece>>를 ArrayList<Rank>로 구현하는 것은 Rank에 기인한 기능으로 나누는 것 말고는 사실상 구조가 같다고 생각했습니다. 그래서 1차원 배열로 구현하였습니다.

그리고 리뷰를 받고 조금 생각해 봤는데, 반드시 Rank 단위로 해야 하는 일은 showBoard() 말고는 없습니다. File 단위로 하면 유리한 것에 caculcatePoint()가 있고, initialize는 Rank단위나 File단위나 해줘야 하는 것은 같습니다.

물론 메소드를 사용하는 빈도수로 따지면 showBoard()가 압도적으로 많을 것이기 때문에 row를 우선하는 배열로 구현하는 것이 좋습니다. 그래서 제가 구현한 배열도 row를 우선으로 합니다.

2021-02-24 12:17 UTC, PizzaCola-K commented
리뷰해주신 내용을 기반으로 수정했습니다.

- Piece 의 메소드 순서를 이야기해주신 대로 바꾸었습니다.
- Board도 역시 initialize 메소드들을 위로 옮겼습니다.
- Board 내부에 있는 square를 접근할 때 이제 File과 Rank enum을 사용합니다.
- String positon을 파싱하는 PositionParser를 빼고, 메소드로 수정하였습니다. 이제 이 메소드들이 File과 Rank를 반환합니다.

체스판의 Rank를 따로 추상화할 필요는 없는 것 같습니다.

리뷰 감사드립니다!

2021-02-26 00:00 UTC, SANGCO approved these changes

2021-02-26 00:00 UTC, SANGCO commented on src/main/java/chess/Board.java
> +    }
다음 미션을 수행하다 보면 이런 부분들이 복잡해 질거라 예상합니다.
이 코스가 단순히 미션에 있는 요구사항을 구현하는게 아니라
객체지향 프로그래밍을 연습하는 과정이랍니다.
힌트에 나와있는 클래스 혹은 다른 부분을 추상화해도 좋습니다.
다음 미션에서는 최대한 클래스를 만들고 로직을 분산 시켜서 전체적인 코드 복잡도를 줄여봅시다.

2021-02-26 00:53 UTC, PizzaCola-K commented on src/main/java/chess/Board.java
> +    }
네 알겠습니다. 리뷰 감사드려요

2021-02-26 01:44 UTC, ghojeong reviewed
미션 6를 고려하지 않고, 미션 5까지의 요구사항 만을 고려했을 때는 나름 깔끔하게 짜신 것 같습니다.

2021-02-26 01:44 UTC, ghojeong commented on src/main/java/chess/Rank.java
> +    SEVEN(1),
File 과 Rank 를 이렇게 따로 정의하신게 인상깊네요. 신기합니다.

2021-02-26 01:44 UTC, ghojeong commented on src/main/java/pieces/Piece.java
> +        return '.';
색깔에 따라서 representation 이 달라지는 로직을 상위에 정의하신것 인상깊습니다.

2021-02-26 01:44 UTC, ghojeong commented on src/test/java/pieces/PieceSortTest.java
> +        softly = new SoftAssertions();
SoftAssertions 는 이번에 처음 알게 되었는데,
일반 Assertions 와 다르게, SoftAssertions 가 좋은 점과, 사용하시게 된 이유를 알 수 있을까요?
한 수 배워갑니다.

2021-02-26 01:44 UTC, ghojeong commented on src/test/java/pieces/PieceTest.java
> +        softly.assertThat(blank.isBlack()).as("빈칸 색상(검은색) 확인").isFalse();
와 SoftAssertion 을 사용하면 테스트 하나하나에 , 설명을 덧붙일 수 있군요. 신기합니다.

2021-02-26 01:44 UTC, ghojeong commented on src/test/java/chess/BoardTest.java
> +        assertThat(board.calculatePoint(Color.WHITE)).isCloseTo(19.5, within(0.01));
isEqualTo 가 아니라, isCloseTo 문법을 사용하셨는데, 설명 좀 부탁드려요!
이것도 저 한번도 사용해보지 않았는데 신기하네요.
원래 double 이나 float 값에는 이렇게 isCloseTo 를 활용하는게 더 좋은가요?

2021-02-26 01:44 UTC, ghojeong commented on src/main/java/chess/Board.java
> +    }
흠... 이 부분은 저도 마찬가지인데 저도 고쳐보려고 노력해야겠군요.

2021-02-27 02:46 UTC, sanhee commented on src/test/java/pieces/PieceTest.java
> +        softly.assertThat(blank.isBlack()).as("빈칸 색상(검은색) 확인").isFalse();
어?! 저도 배워갑니다 너무 감사합니다😍

2021-03-01 07:42 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +        assertThat(board.calculatePoint(Color.WHITE)).isCloseTo(19.5, within(0.01));
ㅎㅎ 맞아요. isEqualTo는 실패할 가능성이 높아서, 유효숫자 범위로 테스트를 하는 경우가 많습니다.

2021-03-01 07:43 UTC, merged