[ coco ] 미션5: 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #144
Opened 2021-02-23 13:00 UTC by ChoiGiSung

안녕하세요. 백엔드반의 coco라고 합니다.
부족한 코드를 봐주셔서 감사드립니다.

저는 위치를 point로 , 점수를 score를 명명했습니다. 

* ##  기물의 색, 기물의 종류에 따른 enum 구현 
이번 미션 후반부까지는 Piece 내부에 상수로 Color를 구현해서 사용했습니다. String 타입으로 사용하니 사용할 때마다 검증메소드를 호출하는 게 좋지 않아 보여 미션후반에 enum으로 변경하였습니다.
 014951c

* ##  체스판의 모든 칸을 Piece로 초기화
이전 미션 마지막에 리스트를 일급컬렉션 형태로 관리해보는 게 어떨까 하는 생각에 만든 OtherWhitePiece클래스를 Rank 클래스로 변경하였습니다. 초기에는 board에서 기물을 넣고 빼는 메소드를 어떻게 할까 하다 자바지기님의 코드를 참고하여 Rank에서 piece 관련 관리하는 쪽으로 변경했습니다. 
a341b3d 5b9102c

* ##  기물과 색에 해당하는 기물의 개수를 반환
컬러와 타입을 받으면 ranks를 돌면서 개수를 받아서 리턴해줍니다.
1d27572

* ##  주어진 위치의 기물을 조회
Board.class 의 getPieceFromPoint() 메소드는 point를 받아서 사용할 수 있는 위치인지 piecePointValid()를 통해 검증을 진행하고
Rank.class의 findPieceFromPoint() 메소드를 사용해 piece를 구합니다. 
여기서 고민한 점은 메소드명입니다. 둘의 차이점은 get과 find밖에 없지만, 의도한 것은 얻고자 할 때는 get을 직접적으로 찾을 때는 find를 사용했습니다. 근데 다른 분들이 보기에는 혼돈이 될 수 있을 꺼 같습니다. 

a6ecabd b17c61c

* ##  임의의 기물을 체스판 위에 추가
간단하게 set을 통해 구현했습니다. 
40bbf72

* ##  체스 프로그램 점수 계산하기
깔끔하게 풀어낼 방법이 생각나지 않아 2중 루프를 돌았습니다. row를 한 번씩 돌면서 column을 하나씩 뽑아서 검사를 진행합니다. 이 부분에서 제가 코드를 더럽게 작성한다고 많이 느꼈습니다.

3c32a7c 947899b

* ##  기물의 점수가 높은 순으로 정렬
지금은 점수가 큰 순으로 정렬하고 있습니다. o1의 순서만 바꿔주면 반대 기능을 합니다.

cb59c8c

인터페이스 같은 경우는 적용해야 할 곳이 제 눈에는 보이지 않아 넣지는 않았습니다.

긴 글 읽어 주셔 감사합니다.

2021-02-24 07:31 UTC, ghojeong reviewed
구현된 내용이 어떤 커밋에서 작성되었는지, 일일히 문서로 작성해주신것 멋진 것 같습니다.
읽으면서 궁금했던 것들을 커멘트로 남겨보았습니다.

2021-02-24 07:31 UTC, ghojeong commented on src/test/java/net/coco/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.createWhitePawn(), Color.WHITE, PieceType.PAWN),
assertAll 로 여러 테스트 한꺼번에 같이 진행하는 모습 보기 좋은 것 같습니다.
verifyPiece 로 중복 코드를 제거하고, 테스트 코드도 꼼꼼하게 잘 짜신것 같습니다.

2021-02-24 07:31 UTC, ghojeong commented on src/test/java/net/coco/chess/BoardTest.java
> +                () -> assertThat(Piece.createWhiteKing()).isEqualTo(getWhitePiecesSortByScore.get(15))
`getWhitePiecesSortByScore.get(15)` 의 값을 확인하려 하신것 같은데,
assertThat 메서드의 파라미터명을 보시면 아시겠지만,
actual 이 앞에 있고, expected 가 뒤에 있습니다.
결과적으로 테스트 결과는 동일하게 진행될테니 크게 상관은 없겠지만,
가독성을 위해서 순서를 바꾸면 어떨지 제안을 해봅니다.
맨처음에 getWhitePiecesSortByScore 가 아니라, Piece.create 를 테스트 하려고 한다고 착각했어서요.

2021-02-24 07:31 UTC, ghojeong commented on src/test/java/net/coco/chess/BoardTest.java
> +        ).isInstanceOf(IllegalArgumentException.class)
예외상황에 대한 테스트 매우 좋습니다 👍

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/pieces/Point.java
> +            throw new IllegalArgumentException("올바른 point가 아닙니다.");
범위를 넘어갈 경우에 대한 예외처리 좋습니다 👍

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/pieces/Point.java
> +        this.column = Character.getNumericValue(point.charAt(1)) - 1;
Character.getNumericValue 는 저도 모르는 메소드였는데 한수 배워갑니다.

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/pieces/Piece.java
> +    }
Color enum 을 Piece 클래스 안으로 넣으신 이유가 있으신가요?
밖으로 분리하는게 더 좋다고 주장하기 보다는, 이런식으로 클래스 안으로 넣게 되는 상황과 이유가 궁금해서 여쭈어봅니다.
enum Color 의 사이즈가 작아서 Piece 에 넣은 것인지,
아니면 Piece 와 Color 가 매우 긴밀한 관계인지라, 객체 응집성을 위해서 하나로 합친 것인지 궁금해서요..

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/pieces/Piece.java
> +    public int hashCode() {
Piece 가 Value Object 라서 equals 와 hashCode 를 정의해주셨군요. 👍 
create 를 할 때마다, 새로은 Piece 인스턴스가 생성되는 것도 메서드 네이밍과 매우 잘 어울리는 것 같습니다.

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/chess/Board.java
> +        Collections.sort(getWhitePieces, (o1, o2) -> (int) (o2.getScore() - o1.getScore()));
equals 와 hashCode 를 자동생성할 때는 어쩔 수 없지만,
직접 작성할 때는 o1 과 o2 같은 네이밍은 좋지 못한것 같아요.
piece1 과 piece2 는 어떨까요?

2021-02-24 07:31 UTC, ghojeong commented on src/main/java/net/coco/chess/Rank.java
> +        return Collections.unmodifiableList(pieces);
와우! unmodifableList 를 사용하셨군요 👍 
사용하신 의도와 목적, 그리고 기대하신 효과를 여쭈어보아도 될까요ㅛ?

2021-02-24 08:42 UTC, ChoiGiSung commented on src/test/java/net/coco/chess/BoardTest.java
> +                () -> assertThat(Piece.createWhiteKing()).isEqualTo(getWhitePiecesSortByScore.get(15))
앗, 감사합니다 파이로! 실제 값이 앞에 기댓값이 뒤에 기억하겠습니다.

2021-02-24 08:45 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Piece.java
> +    }
맞습니다. Color의 사이즈가 작아서 Piece안에 넣은 게 결정적인 이유입니다.
원래는 상수로 계속 사용을 했었는데 매번 검증하는 게 여간 귀찮은 게 아녔습니다.
그래서 미션 후반에 enum으로 변경하여 사용했습니다!

2021-02-24 08:46 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        Collections.sort(getWhitePieces, (o1, o2) -> (int) (o2.getScore() - o1.getScore()));
확실히 하는 게 더 보기 좋네요! 수정했습니다.

2021-02-24 09:04 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Rank.java
> +        return Collections.unmodifiableList(pieces);
List로 바로 반환해 줘도 되지만 외부에서 add,set이나 delete를 막기 위함이 있었습니다.
현재는 그저 리스트에서 대표문자를 뽑아, String으로 만들 때만 사용을 하고 있습니다.

2021-02-25 10:08 UTC, sonypark requested changes
안녕하세요 coco, 리뷰어 소니 입니다.😊
미션5 구현하느라 수고 많으셨습니다.
예외 사항도 꼼꼼히 작성하려고 노력하신게 보이네요👍
리팩토링 관점에서 개선 가능한 부분 코멘트 남겼으니 확인 부탁드립니다:)

2021-02-25 10:08 UTC, sonypark commented on src/test/java/net/coco/chess/BoardTest.java
> +                () -> assertThat(board.getPieceCount(Color.NO_COLOR, PieceType.NO_PIECE)).isEqualTo(32)
테스트가 통과하지 않는데 확인 부탁해요~

2021-02-25 10:08 UTC, sonypark commented on src/test/java/net/coco/chess/BoardTest.java
> +    @DisplayName("주어진 위치의 기물을 조회시 올바르지 않은 point 입력시")
DisplayName을 더 명확하게 적으면 좋겠네요. 의도하신 내용은 Point 입력값이 체스판 범위를 벗어난 경우 예외를 발생하는거겠죠?

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/Piece.java
> +
Enum은 == 비교가 가능합니다.

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/PieceType.java
>      }
if문에 중괄호는 생략하지 말아주세요.
`getWhiteRepresentation`, `getBlackRepresentation`메서드는 이렇게까지 안 나눠도 될 것 같습니다. 메서드의 역할이 너무 적고, `getRepresentation` 메서드 내 조건문만 보고도 쉽게 이해 가능한 부분이라서요. 이건 개인 취향이니 그대로 두셔도 괜찮습니다!

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/PieceType.java
> +    NO_PIECE('.', 0.0);
👍

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/printer/PrintChess.java
이 메서드는 출력을 하는 역할인데, 리턴값이 있을 필요가 있을까요?

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
>              case END:
Main 메서드에 Scanner close 해주는 부분이 없네요. try with resources를 적용해보세요
```java
Scanner sc = new Scanner(System.in);
```

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
>      }
1. Color는 사용되고 있지 않네요
2. Stream으로도 구현가능하네요.
```java
public int getPieceCount(Color color, PieceType pieceType) {
        return ranks.stream()
                .mapToInt(rank -> rank.findPieceCount(pieceType))
                .sum();
    }
```

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/Point.java
> +    private int column;
final로 선언해도 좋겠네요

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/Point.java
> +            throw new IllegalArgumentException("올바른 point가 아닙니다.");
예외 메시지에서 왜 올바른 point가 아닌지에 대해 설명을 해주면 더 좋을 것 같아요.
행과 열의 조건문을 나눴다면 에러 메시지도 나뉠 수 있을 것 같고, 조건문 하나로 합쳐서 예외를 발생시킬 수도 있겠네요.

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/pieces/Piece.java
> +import java.time.Period;
사용하지 않는 import는 삭제해주세요~

커밋 하기 전 optimize imports 해주는걸 권장합니다. (인텔리제이에서 옵션으로 제공합니다.)
![image](https://user-images.githubusercontent.com/34808501/109133326-3bfb6e80-7798-11eb-8f2e-8e668f23b1e6.png)

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/chess/Rank.java
> +    }
파라미터가 column인데 실제 사용되는 곳에서는 row를 받고 있네요
```java
    public Piece getPieceFromPoint(String pointStr) {
        Point point = new Point(pointStr);
        return ranks.get(point.getColumn()).findPieceFromPoint(point.getRow());
    }
```

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
>      }
```suggestion
return ranks.stream()
                .map(getRank -> getRank.findPieceByColumn(color, column))
                .collect(Collectors.toList());
```
스트림을 이용하면 위와 같이 바꿀 수 있습니다 :)
다른곳에도 스트림을 적용할 수 있는 부분이 있는지 찾아본 후 적용해보세요~

2021-02-25 10:08 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +        Collections.sort(getWhitePieces, (piece1, piece2) -> (int) (piece2.getScore() - piece1.getScore()));
List에서도 sort 메서드를 제공합니다.
```java
getWhitePieces.sort((piece1, piece2) -> (int) (piece2.getScore() - piece1.getScore()));
```

2021-02-25 10:10 UTC, sonypark commented on src/test/java/net/coco/chess/BoardTest.java
> +
변수명으로는 적절치 않은 네이밍이네요

2021-02-26 02:54 UTC, ChoiGiSung commented on src/test/java/net/coco/chess/BoardTest.java
> +                () -> assertThat(board.getPieceCount(Color.NO_COLOR, PieceType.NO_PIECE)).isEqualTo(32)
음.. 제 로컬에서는 잘되는데 이상하네요. 일단 다른 piece들까지 추가로 test해 봤습니다. 
0a3ca2b

2021-02-26 02:59 UTC, ChoiGiSung commented on src/test/java/net/coco/chess/BoardTest.java
> +    @DisplayName("주어진 위치의 기물을 조회시 올바르지 않은 point 입력시")
수정했습니다!

2021-02-26 03:02 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Piece.java
> +
상수를 enum으로 변경하면서 상수 사용 부분을 다 수정했다고 생각했는데 이 부분을 변경하지 못했었네요.
수정 완료했습니다!

2021-02-26 03:04 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PieceType.java
>      }
수정했습니다!

2021-02-26 03:07 UTC, ChoiGiSung commented on src/main/java/net/coco/printer/PrintChess.java
이 부분은 출력값을 테스트하기 위해 리턴값을 명시해 줬습니다.

2021-02-26 03:21 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
>              case END:
main문에서 if문을 통해 false가 되면 close()해주고 있습니다.
 ```
   public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Board board = new Board();
        while (true) {
            System.out.println("input > ");
            String input = sc.next();
            if (commandSwitch(board, input)) {
                sc.close();
                return;
            }
        }
    }
```
try with resources는 처음에 생각해 봤지만 depth가 한 단계 늘어난다고 생각해서 꺼렸는데,
다른 분 코드를 보니 메소드로 빼고 scanner를 매개변수로 넘겨주더라고요. 혹시 사용한다면 이렇게 사용할 생각입니다.
```
        try (Scanner scanner = new Scanner(System.in)) {
            play(scanner);
        }
```

2021-02-26 03:26 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
>      }
mapToInt가 있었네요! stream은 정말 기능이 많네요.

2021-02-26 05:07 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Point.java
> +    private int column;
setter가 없긴 하지만 유지 보수를 위해 선언하는 것도 좋아 보이네요!

2021-02-26 05:10 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Point.java
> +            throw new IllegalArgumentException("올바른 point가 아닙니다.");
그렇네요. 다르게 명시하던가 합쳐야겠네요. 지금은 합쳤습니다!

2021-02-26 05:10 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Piece.java
> +import java.time.Period;
수정 완료했습니다!

2021-02-26 05:25 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Rank.java
> +    }
아.. 개념상의 문제가 있었네요. "a8"일때 a가 column, 8이 row인데 반대로 생각했네요.
Point class부터 고쳤습니다. 감사합니다!

2021-02-26 05:34 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
>      }
와! 감사합니다! 적용할 수 있음 다 해보겠습니다!

2021-02-26 05:47 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        Collections.sort(getWhitePieces, (piece1, piece2) -> (int) (piece2.getScore() - piece1.getScore()));
몰랐어요! 감사합니다!

2021-02-26 05:58 UTC, ChoiGiSung commented on src/test/java/net/coco/chess/BoardTest.java
> +
수정했습니다.

2021-02-26 14:57 UTC, sonypark approved these changes
이제 테스트 통과하네요.💯
수고하셨습니다.
다음 단계 진행해주세요~💪

2021-03-01 07:55 UTC, honux77 commented on src/main/java/net/coco/pieces/Point.java
> +        this.column = Character.getNumericValue(point.charAt(1)) - 1;
근데 `point.charAt(1) - '1'` 해도 동일한 결과긴 하겠어요.

2021-03-01 07:56 UTC, honux77 commented on src/main/java/net/coco/pieces/PieceType.java
>      }
제가 며칠전 알고리즘 대회에서 이거 생략했다가 망했습니다 ㅋㅋㅋㅋ.

2021-03-01 07:57 UTC, honux77 commented on src/main/java/net/coco/pieces/Piece.java
> +import java.time.Period;
IntelliJ가 커밋전 체크 기능이 좋네요. 저도 사용해 봐야겠어요.

2021-03-01 07:57 UTC, honux77 commented on src/main/java/net/coco/chess/Board.java
>      }
ㅇㅇ 이런 건 스트림 쓰는게 가독성이 훨씬 좋군요.

2021-03-01 07:58 UTC, merged