[Wan] 미션4 : 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #145
Opened 2021-02-23 13:23 UTC by MyungWanPark

안녕하세요~! 백엔드 반의 Wan 입니다.
'미션4: 모든 기물 배치하기'를 구현해보았습니다.

특이사항에 대해 잠깐 설명해드리겠습니다~!

1. main/java/chess/Board.java
- Arraylist를 폰과 폰 외의 다른 유닛들로 구분하여 넣었습니다.(미션3에 구현했던 폰과 관련된 기능을 반영하기 위하여)
- addWhitePieces() : 폰을 제외한 흰색 유닛들을 체스판 순서대로 팩토리 메소드로 생성하여 넣었습니다.
- bringWhitePiecesRepresentation() : 폰을 제외한 유닛들이 있는 arraylist에 유닛들을 순서대로 꺼내서 그 이니셜을 합쳐 반환하도록 구현하였습니다.

2. main/java/pieces/Piece.java
- 모든 체스판 유닛들의 이니셜을 상수로 지정하였습니다.
- 팩토리 메소드를 사용하여 체스판 유닛들의 객체를 생성한 후 반환하도록 구현하였습니다.
- isWhite() : 유닛의 색상이 흰색인지 확인해보는 메소드입니다.

3. main/java/utils/StringUtils.java
- NEWLINE 이라는 상수를 이용하여 운영체제에 맞춘 개행기능을 넣었습니다.
- appendNewLine() : 반복되는 개행문자를 없애기 위해 '문자열 + 개행' 을 반환하는 메소드를 구현하였습니다.

4. test/java/chess/BoardTest.java
- showPieceNum() : board.pieceCount()가 유닛의 갯수를 잘 세는지 확인하기 위한 테스트 메소드입니다.
- showTotalBoard() : board.bringBoard()가 유닛을 잘 배치했는지 확인하기 위한 테스트 메소드입니다.

5. test/java/pieces/PieceTest.java
- verifyPiece() : piece.getColor()와 piece.getRepresentation()가 역할을 잘 하는지 테스트하기 위한 메소드 입니다. 
- isWhiteAndBlack() :  isWhite()가 흰색 구분을 잘 하는지, isBlack()은 검정색 구분을 잘 하는지 테스트 하기 위한 메소드 입니다.

한가지 궁금한 점이 있습니다~!
test/java/pieces/PieceTest.java 에서 isWhiteAndBlack() 의 메소드의 경우 모든 경우의 수(흰색, 검정색의 폰,룩,나이트,비숍,퀸,킹)를 테스트해야하도록 구현해야 할까요?

바쁘신 와중에 긴 글을 읽어주셔서 감사합니다!
많이 부족한 코드라 따끔한 조언 부탁드리겠습니다!!
좋은 하루 되세요😀😀

2021-02-24 06:10 UTC, Polynomeer commented on src/main/java/chess/Board.java
>      }
안녕하세요! 어제 리뷰 시간에 저의 짧은 생각으로 너무 급하게 말씀드린 것 같아서 노파심에 말씀 드립니다. 지금처럼 메서드가 어차피 private이고 동작이 `blackPawns.add(blackPawn)`이 전부라면 메서드가 굳이 필요없는게 맞겠지만, blackPawns를 외부로부터 보호하고 싶고, 메서드를 통해서만 add하고 싶다면, 메서드를 정의하는 것이 필요한 것 같습니다. (getter/setter의 목적과 같은 것 입니다.) 다만, 그러기 위해서는 접근제한자가 private이 아니어야 할 것 입니다.

그런데 지금은 그냥 private 멤버에 private 메서드가 접근하는 상태라서 둘 중에 하나로 선택하시는게 낫지않을까 하는 생각을 해보았습니다! 1) 메서드의 접근제한자 private을 제거하거나, 2) 그냥 메서드를 제거하거나(내부에서만 add한다면)

2021-02-24 10:54 UTC, MyungWanPark commented on src/main/java/chess/Board.java
>      }
안녕하세요 어거스트! 어제 안그래도 그부분에 대한 이해가 가지 않아서 수정을 못했습니다~! 이렇게 댓글을 남겨주셔서 감사해요!! 저는 blackPawns를 외부로부터 보호하고 싶고, 메서드를 통해서만 add하고 싶어서 메서드의 접근제한자 private을 풀고 public으로 바꿔야 겠네요!!

2021-02-24 14:18 UTC, sonypark requested changes
안녕하세요 Wan, 리뷰어 소니 입니다.😊
미션4 구현하느라 수고 많으셨습니다.
몇가지 개선할 점이 보여서 코멘트 남겼으니 확인 후 반영 부탁드립니다:)

2021-02-24 14:18 UTC, sonypark commented on src/test/java/pieces/PieceTest.java
> +}
assertAll을 사용하는 방법도 고려해보세요~
[참고 링크](https://github.com/codesquad-members-2021/java-chess/pull/23#discussion_r572844078)

2021-02-24 14:18 UTC, sonypark commented on src/test/java/chess/BoardTest.java
> +        assertThat(32).isEqualTo(board.pieceCount());
assertThat을 사용할 때는 assertThat에 actual이 오는 방향으로 적어주세요~
[참고 링크](http://joel-costigliola.github.io/assertj/assertj-core.html)
```java
assertThat(actual).isEqualTo(expected);
```

2021-02-24 14:18 UTC, sonypark commented on src/main/java/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
`NEWLINE`은 StringUtils에서만 사용되니 접근제어자를 private으로 하는건 어떨까요?

2021-02-24 14:18 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +}
```suggestion
public boolean isWhite() {
        return this.color.equals("white");
    }

    public boolean isBlack() {
        return this.color.equals("black");
    }
```
위 코드는 이렇게 단순화 할 수 있을 것 같아요.
그리고 문자열이 아닌 Enum으로 만들면 아래와 같이 더 직관적인 코드로 만들 수 있을 것 같네요.
다음 단계에서 Enum으로 변환하는 내용이 있으니 그 때 진행하셔도 될 것 같습니다

```java
public boolean isWhite() {
        return this.color == Color.WHITE;
    }
```

2021-02-24 14:18 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +    }
다음 미션에서 Enum으로 변환해보세요~

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/ChessMain.java
>                  }
start를 여러번 입력하면 출력결과가 이상해지네요. 왜 그럴까요?
![Uploading image.png…]()

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/ChessMain.java
> +            e.printStackTrace();
이 예외는 언제 발생할까요? 문자가 아닌 입력이 들어오는 경우는 어떤 경우인가요?

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/Board.java
>      public static final int PAWN_NUMBER = 8;
접근제어자를 신경써주세요~

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/Board.java
>      }
`sizeOfPieces`를 바로 사용해도 되지 않을까요?

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/Board.java
>      }
Board에서 출력 로직도 담당하기보다는 Board에서 체스판을 리턴하면 Main에서 출력해주는건 어떨까요?

2021-02-24 14:18 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +    }
메서드명에서 Instance는 빼도 될 것 같네요

2021-02-24 14:18 UTC, sonypark commented on src/main/java/chess/Board.java
> +        }
중복이 많이 보이는데, 중복을 제거할 수 있는 방법도 고민해주세요~

2021-02-25 08:25 UTC, MyungWanPark commented on src/test/java/pieces/PieceTest.java
> +}
링크도 주셔서 감사합니다! asertAll 사용해보겠습니다!!

2021-02-25 08:25 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +        assertThat(32).isEqualTo(board.pieceCount());
앗, 그부분을 실수했네요! 고치겠습니다~!

2021-02-25 08:26 UTC, MyungWanPark commented on src/main/java/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
상수는 무조건 public으로만으로 생각했네요! 사용되는 곳을 고려하여 private으로 고치겠습니다! 감사합니다

2021-02-25 08:26 UTC, MyungWanPark commented on src/main/java/pieces/Piece.java
> +}
훨씬 보기가 편하네요! 조언 감사합니다~!!

2021-02-25 08:26 UTC, MyungWanPark commented on src/main/java/pieces/Piece.java
> +    }
넵넵!!

2021-02-25 08:27 UTC, MyungWanPark commented on src/main/java/chess/Board.java
>      public static final int PAWN_NUMBER = 8;
앗, 접근제어자 신경쓰겠습니다!!

2021-02-25 08:27 UTC, MyungWanPark commented on src/main/java/chess/Board.java
>      }
앗, 그렇네요 중복되는 메소드는 제거하겠습니다~!

2021-02-25 08:28 UTC, MyungWanPark commented on src/main/java/chess/Board.java
>      }
각 클래스의 역할에 대해 생각을 못해봤네요! 조언 감사합니다~!!

2021-02-25 08:29 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +        }
앗, 이부분도 중복이네요!! 지적해주셔서 감사합니다!! 중복을 제거할 수 있도록 고민해본 후 반영하겠습니다~!!

2021-02-25 09:51 UTC, MyungWanPark commented on src/main/java/pieces/Piece.java
> +    }
보다 명확하게 표현하려고 했는데 메소드 명이 길어진것 같네요! instance는 빼겠습니다~!

2021-02-25 10:24 UTC, MyungWanPark commented
수정하였습니다😀😀
조언해주셔서 감사합니다!
덕분에 코드가 훨씬 깔끔해진 것 같습니다~!

2021-02-25 10:31 UTC, MyungWanPark commented on src/main/java/chess/ChessMain.java
> +            e.printStackTrace();
앗, 숫자를 입력해도 문자로 인식을 하네요!! ㅠㅠ 시험을 해보지 않고 예외처리를 한 것 같습니다. 조언 감사드립니다!!

2021-02-25 10:38 UTC, MyungWanPark commented on src/main/java/chess/ChessMain.java
>                  }
앗, 그러네요!! initialize()가 반복될때마다 실행되어서 board.java에 있는 유닛들의 ArrayList가 계속해서 쌓였던것 같습니다! 
수정하겠습니다~! 감사합니다

2021-02-26 13:25 UTC, sonypark commented
> 수정하였습니다😀😀
> 조언해주셔서 감사합니다!
> 덕분에 코드가 훨씬 깔끔해진 것 같습니다~!
> 
> 한 가지 궁금한 점이 있습니다!
> assertAll 같은 경우는 서로 독립적인 메소드(서로 관련이 없는)끼리 묶여있을때 사용하는 것이 좋을까요??

개념적으로 하나로 묶어 테스트 해야하는 경우는 assertAll을 사용하고, 그렇지 않은 경우는 독립된 테스트 메서드로 나눠주는게 좋습니다.
자세한 내용은 [링크](https://stackoverflow.com/questions/40796756/assertall-vs-multiple-assertions-in-junit5)로 대신하겠습니다.

2021-02-26 13:26 UTC, sonypark approved these changes
피드백 반영 확인했습니다.
다음 단계 진행해주세요
미션5도 화이팅!!💪

2021-03-01 08:05 UTC, merged