[노을] 미션 4: 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #150
Opened 2021-02-24 17:15 UTC by sanhee

안녕하세요😃  코드스쿼드 백엔드 과정 `노을`입니다.

이번 미션은 자바 기초 공부를 하느라 늦게 진행 하게 되었습니다.

기초 공부를 하면서 자바의 `상속`과 그리고 요구사항에서 학습하게 된 `정적 팩토리 메서드`를 학습 차원에서 사용 해보고 싶어,

요구사항과는 다르게 `Piece` 클래스를 체스 유닛들의 `조상 클래스`로 만들어 하위 유닛들이 상속을 받는 구조로 설계하였습니다.

#### 혹시 이와 같이 하면 안되는 것이라 하면 요구사항에 맞게 다시 PR 요청을 드리도록 하겠습니다.😂

![클래스 구성](https://i.imgur.com/nyRjWuo.png)

궁금한 점은  정적 팩토리 메서드를 아래와 같이 구현을 했는데 올바르게 활용 했는지 잘 모르겠습니다.

```java
public class PieceFactory {
    public static Piece createBishop(UnitColor unitColor) { //m 정적 팩토리 메서드
        return new Bishop(unitColor);
    }

    public static Piece createKing(UnitColor unitColor) {
        return new King(unitColor);
    } 
    ... 반복
```

마지막으로 요구사항과는 관련없는 이야기이지만 문득  체스 게임이라고 생각하니까 좌표정보에 대한 책임을 Board 클래스에게 줄 것인지, 체스 유닛들이 개별적으로 가지고 있게 할 것 인지 고민을 하게 되었는데, 어떻게 하는게 좋은 방식인지 궁금합니다.

오늘도 바쁜 시간 내어 리뷰해주셔서 감사합니다.😎

2021-02-25 10:36 UTC, LarryJung requested changes
구현 잘 하셨습니다~
공부하셨으면 미리 적용해 보셔도 좋습니다. ㅎㅎ 이미 미션의 중반 이상이기 때문에.. 그럴 수 있다고 생각이 드네요^^

상속을 사용한 부분에서 같은 기능과 같은데이터를 한곳으로 모아놓은 목적 정도로 보이는데요, 그런 이유라면 꼭 상속을 사용할 이유가 없습니다 (상속vs합성 을 찾아보세요)
리뷰 중 isYou() 라는 메서드를 제시해 드렸으니, 이 것을 한번 구현해보시면서 상속구조를 사용했을 때 어떤 이점이 있을 지 생각해주시면 좋을것 같습니다. ^^ 하다가 다르게 바꿔보셔도 좋습니다.


position 의 책임에 관해..
이 것은 어떻게 해도 상관 없습니다! 먼저 가장 쉽게 돌아가는 코드를 짠 후에 리팩토링을 하면서 제 자리를 찾아가도록 하시면 됩니다 ㅎㅎ

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
>      }
이 메서드 조금 개선해보면 좋을 것 같습니다.
일단 pieces 포문인데 아이템 변수 이름이 pawn -> piece가 되어야 할 것 같구요,

포문 블럭을 아래처럼 짜보면 상속구조를 좀 더 이용하게 되실 거에요~
```java
for (Piece piece : this.pieces) {
  if (piece.isYou(color, UnitType.PAWN)) {
    pawnLine.append(piece.getRepresentation());
  }
}
```

boolean classCheck 을 각 객체에게 위임한 꼴이라고 생각하시면 될것 같습니다. :)

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        return boardString.toString();
기회가 되신다면 재귀로 한번 짜보시는것도.. 추천드립니다. ㅎㅎ

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/PieceFactory.java
> +public class PieceFactory {
팩토리 클래스를 공부하셨군요~😀

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/property/UnitColor.java
> +}
파일 끝 개행 넣어주세요^^

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        final int LINE_OF_PIECE = 8;
상수값 뿐 아니라 StringBuilder도 final 을 사용할 수 있겠죠? 생각해보면 특정하게 변수의 재할당이 필요한 몇몇 경우를 제외하고는 final을 붙여줄 수 있는 대상들이 많이 있습니다. ㅎㅎ

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/Bishop.java
> +}
상속은 이렇게 사용하면 됩니다. ㅎㅎ 다만 아쉬운 점이 하나 있는데 최종 코멘트에서 남기도록 하겠습니다.

2021-02-25 10:36 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/property/UnitType.java
> +    }
어느 것이 더 나은지는 판단해주세요~ switch 할때 이렇게도 할 수 있을 것 같네요

```java
public static char getMark(UnitColor color, String unitClassName) {
        final char mark;

        switch (color) {
            case BLACK:
                mark = Character.toUpperCase(UnitType.valueOf(unitClassName.toUpperCase()).unitRepresentation);
                break;
            case WHITE:
                mark = Character.toLowerCase(UnitType.valueOf(unitClassName.toUpperCase()).unitRepresentation);
                break;
            case NONE:
                mark = UnitType.valueOf(unitClassName.toUpperCase()).unitRepresentation;
                break;
            default:
                mark = ' ';
        }
        return mark;
    }
```

- default를 두지 않고 변수 선언 시 기본값을 채워주기
- final 로 두고 특정 케이스에만 값을 할당하고 나머지 경우도 default로 메꾸기

2021-02-25 11:40 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
>      }
반영해서 PUSH 완료하였습니다.😍
이전보다 훨씬 간결해져서 너무 좋네요 ㅎㅎ
아직 자바 초심자라서 추상적인 내용보다  이러한 레퍼런스가 좀 더 학습에 있어 이해도가 높고 오래 기억에 남는 것 같습니다. 감사합니다.

2021-02-25 11:41 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
>      }
코드는 아래와 같이 작성하였습니다.

```java
    public boolean isYou(UnitColor unitColor, UnitType unitType) {
        boolean classCheck = this.getClass().getSimpleName().equalsIgnoreCase(unitType.name());
        return isColor(unitColor) && classCheck;
    }
```

2021-02-25 13:13 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        return boardString.toString();
말씀하신 사항 반영해서 PUSH를 했습니다.
하지만, 제가 재귀함수를 많이 안해봐서 올바르게 했는지 잘 모르겠습니다.
한번 검토해주시면 감사하겠습니다.

```java
public StringBuilder showBoard(int index, int count) {
        final StringBuilder boardString = new StringBuilder();
        final int LINE_OF_PIECE = 8;

        if (index == 63) {
            return boardString.append(findPiece(index).getRepresentation()).append(StringUtils.NEWLINE);
        }

        if (count == LINE_OF_PIECE) {
            count = 0;
            return boardString.append(findPiece(index).getRepresentation()).append(StringUtils.NEWLINE).append(showBoard(index + 1, count + 1));
        }
        return boardString.append(findPiece(index).getRepresentation()).append(showBoard(index + 1, count + 1));
    }
```

와 같이 구현하였고

```java
System.out.println(board.showBoard(0, 1).toString());
```

와 같이 호출이 가능합니다.
showBoard() argument 중 count가 1인 이유는 체스 라인 8개를 직관적으로 카운트하기 위함이었습니다.

2021-02-25 13:14 UTC, sanhee commented on src/main/java/net/sanhee/pieces/PieceFactory.java
> +public class PieceFactory {
학습하고 미션에 바로 적용해서 올바르게 활용 했는지 잘 모르겠습니다.

2021-02-25 13:17 UTC, sanhee commented on src/main/java/net/sanhee/pieces/property/UnitColor.java
> +}
`파일 끝 개행`에  대해 처음 알게 되었는데, 키워드 알려주셔서 감사합니다.
말씀하신 사항 반영하여  PUSH 하였습니다!

2021-02-25 13:24 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        final int LINE_OF_PIECE = 8;
말씀하신 사항 반영하여 PUSH를 하긴 했는데,
`질문사항`🖐이 있습니다!

`StringBuilder`, `List` 등 final을 하면 내부 변수를 변경할 수 있는데 해야 하는 이유에 대해서?? 
예시 또는 키워드를 알려주시면 감사하겠습니다.

제가 검색했던 키워드는 : 
- `자바 fianl stringbuilder list` 
- `자바 final`
- `자바 fianl을 붙일 수 있는 대상` 

등 이었는데 원하는 결과를 찾지 못했습니다.

2021-02-25 13:30 UTC, sanhee commented on src/main/java/net/sanhee/pieces/property/UnitType.java
> +    }
enum을 학습할 때,  switch문에서 default를 사용하지 않아도 된다는 내용을 보아서
특별한 생각없이 작성한 것 같습니다.
리뷰어님이 말씀하신 것처럼 특정 케이스에서만 값을 할당하고, final로 상수 지정해두는 것이 좀더 안전할 것 같습니다.

* PUSH 완료했습니다!

2021-02-25 14:03 UTC, sanhee commented on src/main/java/net/sanhee/pieces/Bishop.java
> +}
상속관계일떄 조상클래스에 isYou() 메서드를 추가하니까 모든 자식 클래스에서 동일하게 사용할 수 있어 코드 중복이 줄어드는 것을 확인할 수 있었습니다. 
상속을 했던 것은 체스 객체들이 많은 정보를 공통으로 사용하고 move나 point같은 일부 요소만 다를거라고 생각했기 때문에 상속을 사용했었습니다.

2021-02-25 14:09 UTC, sanhee commented
말씀하신 사항 반영하여 PUSH 완료 했습니다.

😀질문사항1. https://github.com/codesquad-members-2021/java-chess/pull/150#discussion_r582828975 
😎질문사항2. 포함관계를 사용했을 때, 간단한 예시를 알고싶습니다.
  - 자바의 정석 교재에서는 is a , has a 과 같이 어떤 관계일 때 상속 또는 포함관계를 사용하라고 돼있어, 완벽히 이해하지 못했습니다.
  - Pawn, Rook 같은 체스 객체 클래스들을 각자 만들어두고 Piece 안에 넣는건가요??..너무 기초적인 질문이라서 죄송합니다.

2021-02-25 16:58 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        return boardString.toString();
PUSH를 잘못해서 `미션5` 내용이 미션4로 왔습니다...
showBoard()는 아래와 같이 재구현했습니다. 
https://github.com/codesquad-members-2021/java-chess/pull/150/commits/e27e2ec5522fe151abe3bf703068f04a9b0e5ffe

2021-02-26 09:26 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        final int LINE_OF_PIECE = 8;
오늘 그룹원에게 같은 질문을 해봤는데, 
참조하고 있는 객체에 대한 주소를 변경하지 못하게 하는 것으로,
객체지향 프로그래밍에서 캡슐화를 이루기 위해 최대한 제한을 두는 거라는 의견이 모였는데,
틀린 의견이 있을까요??

2021-02-26 12:49 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
>      }
한번만 더 개선해볼 수 있을까요?ㅎㅎ
힌트를 드리자면.. 

1. Piece를 추상클래스로 선언
2. isYou 메서드를 각 자식 클래스에서 구현

요 조건으로요!

리플랙션을 이용해서 클래스 이름을 직접 꺼내는 것은 위험한 코딩방식 중 하나에요,
왜냐하면 클래스이름이 변경되면 로직도 수정을 해야하기 때문인데요,
위 방식으로 개선을 해 보시겠어용?

2021-02-26 12:55 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        return boardString.toString();
넵 확인했습니다. 잘 짜셨구요! 포문은 **전부** 재귀로 변경할 수 있다는 것만 알려드리고 싶었어요.

재귀는 포문의 단점을 보완하는 방식이지만 주의점도 있으니 사용할때 주의할 점도 있답니다. (재귀vs공재귀 개념이 있습니다. 아직 깊게 안들어가셔도 되어용)
체스 미션에서 요구되는 개념은 아니었지만 도전과제로 코멘트 드렸습니다. ^^

2021-02-26 12:55 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/PieceFactory.java
> +public class PieceFactory {
잘 사용하셨습니다. 눈으로 보기 좋았으면 어느정도는 성공입니다. ㅎㅎㅎ

2021-02-26 13:09 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        final int LINE_OF_PIECE = 8;
final 이 하는 역할은 메모리 주소의 재할당 (쉽게 말해서 변수의 재할당) 을 못하게 하는 것입니다.

개인적인 선호 때문인것도 있는데용~ 저는 변수가 재할당이 필요할까? 생각하셔서 그럴일이 없을것 같다. 앞으로도 없어야 안전할 것 같다 라고 생각하면 final 을 보통 붙입니다. 왜냐면 값의 변경 가능성을 최대한 닫아두는 것이 좀 더 안전한 코드라고 생각하기 때문입니다.

2021-02-26 13:18 UTC, LarryJung commented
> 말씀하신 사항 반영하여 PUSH 완료 했습니다.
> 
> 🤠질문사항1 [#150 (comment)](https://github.com/codesquad-members-2021/java-chess/pull/150#discussion_r582821060)
> 😀질문사항2 [#150 (comment)](https://github.com/codesquad-members-2021/java-chess/pull/150#discussion_r582828975)
> 😎질문사항3. 체스 코드에서 포함관계를 사용했을 때, 간단한 예시를 알고싶습니다.
> 
> * 자바의 정석 교재에서는 is a , has a 과 같이 어떤 관계일 때 상속 또는 포함관계를 사용하라고 돼있어, 완벽히 이해하지 못했습니다.
> * Pawn, Rook 같은 체스 객체 클래스들을 각자 만들어두고 Piece 안에 넣는건가요??..너무 기초적인 질문이라서 죄송합니다.

답글이 많이 늦어서 죄송합니다~ㅠ 
수정사항은 확인했구요 ㅎㅎ 조금 더 코멘트를 드렸습니다.

is a, has a 관계를 생각해서 상속을 해야할지 어떻게 해야할 지 판단하실 수도 있는데요, 
어느 자바교재에서는 상속을 아예 자제하라는 말도 있습니다. 즉 상속은 모두 합성으로 대체할 수도 있다는 것인데요 ㅎㅎ

현재 코드에서 상속을 해서 얻는 이점이 적다는 것을 보여드리면.. 
제가 아래처럼 Piece가 UnitType 을 받는거로 로직을 수정하면, isYou 메서드 구현부도 간결해지고 굳이 상속을 했어야 할 이유는 없어 보이죠?
```java
public class Piece {

    private final UnitType unitType;
    private final UnitColor color;
    private final char representation;

    public Piece(UnitColor color, UnitType unitType) {
        this.unitType = unitType;
        this.color = color;
        //m 생성자 매게변수를 줄이기 위해, 호출한 클래스의 이름을 활용하였습니다.
        this.representation = UnitType.getMark(this.color, this.getClass().getSimpleName());
    }

    public UnitColor getColor() {
        return color;
    }

    public char getRepresentation() {
        return representation;
    }

    public boolean isColor(UnitColor color) {
        return this.getColor().equals(color);
    }

    public boolean isBlack() {
        return this.getColor() == UnitColor.BLACK;
    }

    public boolean isWhite() {
        return this.getColor() == UnitColor.WHITE;
    }

    public boolean isYou(UnitColor unitColor, UnitType unitType) {
        return isColor(unitColor) && this.unitType == unitType ;
    }
}
```

이렇게 되면 굳이 표현하자면
Piece를 상속하는 자식객체를 만들지 않고, UnitType 이란 멤버 변수를 합성해서 문제를 해결한 꼴이 되는 거에요~

2021-02-26 22:27 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
>      }
맞습니다.😂
기존에 `NO_PIECE`라는 클래스 이름이 있었는데, 클래스 명명규칙에 맞지 않는 것 같아 `None`으로 재정의 하였다가
당시에는 문제를 모르고 나중에  테스트 할 때 오류가 났는데, 클래스 이름을 바꾼걸 깜박해서 오류 파악을 제대로 못하고 "왜 오류가나지?" 라고 생각하고, 계속 다른곳만 삽질 했었습니다...👻

리뷰어님 리뷰 반영하여 Pieces 클래스를 추상 클래스로 선언하였고, 아래와 같이 각 클래스마다 추상 메서드를 구현해주었습니다. 기존의 파일 이름을 사용하는 방식보다 훨씬 이해하기 쉬운 코드가 된 것 같아 기분이 좋습니다.😀😍

  ```java  
  @Override
    public boolean isYou(UnitColor unitColor, UnitType unitType) {
        return UnitType.BISHOP == unitType && super.isColor(unitColor);
    }
 ```

* PUSH 완료했습니다!

2021-02-26 23:05 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        return boardString.toString();
재귀는 스택에 메모리가 계속 쌓여서 메모리가 부족하기 쉬워, 
이러한 문제를 해결하기 위해 각 연산 단계마다 즉시 계산하는 `공재귀`를 사용할 수 있다는 것을 알게되었습니다.

그래서 아래같이 StringBuilder 를 정적변수로 선언 해서 해볼까 했는데..

###  `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space` 
을 확인할 수 있었습니다 ㅋㅋ...

🔔 혹시 공재귀에 대한 자바 예제 샘플은 어떻게 학습할 수 있을까요??
구글에 검색을 해보면 코틀린에 대한 포스트만 많은 것 같아, 전체적으로 이해하기 어려운 부분이 있어 질문을 드리게 되었습니다.

```java
 static final StringBuilder boardString = new StringBuilder();

    public StringBuilder showBoard(int index, int count) {
        final int LINE_OF_PIECE = 8;

        if (index == 63) {
            return boardString.append(findPiece(index).getRepresentation()).append(StringUtils.NEWLINE);
        }

        if (count == LINE_OF_PIECE) {
            count = 0;
            return boardString.append(findPiece(index).getRepresentation()).append(StringUtils.NEWLINE).append(showBoard(index + 1, count + 1));
        }
        return boardString.append(findPiece(index).getRepresentation()).append(showBoard(index + 1, count + 1));
    }
```

2021-02-26 23:08 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        final int LINE_OF_PIECE = 8;
이번을 계기로 final 개념을 정리 할 수 있었습니다.
답변 감사합니다!!

2021-02-27 00:33 UTC, sanhee commented
... 생략
> Piece를 상속하는 자식객체를 만들지 않고, UnitType 이란 멤버 변수를 합성해서 문제를 해결한 꼴이 되는 거에요~

생각해보니 아직 단계에서는 다수의 체스 유닛 클래스가 필요하지 않은 것 같아 불필요한 클래스를 제거하고,
Piece 내부에 타입과 컬러 변수를 합성해서 구현해보았습니다.

https://github.com/codesquad-members-2021/java-chess/pull/150/commits/636c54cd5d33f12be8da9f623ece29ad16fd7069

포함관계가 어떻게 이루어지는 것인지 잘 몰랐었는데, 설명해주셔서 많은 이해를 할 수 있었습니다.

혹시 제가 잘못한 점이 있다면 지적해주시면 감사하겠습니다!

2021-02-27 00:39 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
>      }
현재는 아래와 같이 리팩토링을 진행하였습니다.

```java
    public boolean isBishop(UnitColor unitColor){
        return (isType(UnitType.BISHOP) && isColor(unitColor));
    }

```

2021-03-03 12:09 UTC, sanhee commented
@honux77 
호눅스님! 혹시 merge 해주실 수 있나요??
리뷰어님이 바쁘신거 같아서요!!
다음 PR을 하게된다면.. 그때 마저 반영하겠습니다!

2021-03-03 12:36 UTC, merged