[Sky] 미션5 : 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #151
Opened 2021-02-25 00:30 UTC by aksmf1442

안녕하세요! 미션 5의 요구사항을 따라가다보니 미션4에 설계했던 코드랑 많이 달라져서 이상한 부분이 많더라도 리뷰 잘 부탁드립니다! 

## 미션 5 주요 변경사항

* 미션5의 다섯 번째 요구사항까지는 List 자료구조를 통해서 initialize한 기물들을 관리하고 있었는데 여섯 번째 요구사항에서 주어진 위치의 기물을 조회할 수 있도록 메소드를 구현하라고 나와있어서 이건 Map 자료구조를 사용해서 Map<Position, Piece>와 같이 관리하는게 더 편하겠다 싶어서 주어진 위치의 기물을 조회하는 기능은 map을 따로 만들어서 조회할 수 있도록 만들었습니다.

* 위에서 말한 것처럼 map을 만들긴 했었지만 위치를 조회하는 용도로만 사용하고 다른 곳에서는 사용하지 않고 있었는데 조원들과의 그룹리뷰 시간에 토론을 하면서 Map 자료구조를 사용할 거면 list 자료구조를 굳이 사용할 필요가 없다는 것을 깨닫고, list를 전부 없애고 map을 통해서 모든 것을 할 수 있도록 리팩토링 했습니다.

* 체스 프로그램 점수 계산하는 요구사항에서는 같은 색의 pawn이 같은 file에 두 개 이상 있으면 그 file에 있는 pawn의 점수가 0.5점이 되는 부분이 까다로웠는데, 이 부분은 Piece 클래스의 getPoint()에 pawn이 있는 file의 리스트를 넘겨줘서 그 file리스트에 pawn이 두 개 이상있으면 0.5점을 반환하고 아니면 1점을 반환할 수 있도록 했습니다.

2021-02-25 13:44 UTC, wheejuni requested changes
5단계까지 진행하시느라 수고 많으셨습니다. 💯 
몇 가지 개선 의견 남겨드렸는데 참고해주세요. 감사합니다~

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/chess/Board.java
> +    private Map<Position, Piece> piecePositions = new LinkedHashMap<>();
`LinkedHashMap` 을 선택하신 이유가 궁금하네요.

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/chess/Board.java
> +        final int FILE_SIZE = 8;
이 변수는 끌올해서 클래스 상단부에 선언돼야 할 것 같아요. 
상수 성격의 변수가 지역변수로 선언되어 있는 것은 아무리 봐도 조금은 이상한데요. 어떻게 생각하시나요?

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/chess/Board.java
> +            }
`stream` 으로 개선할 수 있을 것 같은데 어떨까요? 

```suggestion
        placePositions.values().stream().filter(p -> p.equals(piece)).count()

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/chess/Board.java
> +            if (color == piece.getColor()) {
`.get()` 해서 꺼낸 후 비교하는 방법보다는 `Piece` 에게 색깔을 직접 물어보는 방법이 훨씬 안전하고 깔끔할 것 같아요.
아래와 같은 메소드가 `Piece` 에 구현되어 있으면 될 텐데요, 어떤가요?

```java
public boolean isMatchingColor(Color color);

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/pieces/Piece.java
> +    public double getPoint(List<Piece> fileList) {
이 메소드는 여기에 위치하면 안될 것 같다는 생각이 듭니다. 
`Piece` 가 자신 여러개를 갖고 있는 `fileList` 를 파라메터로 받아서 직접 점수까지 계산하는 로직은 좀 어색합니다. 
`Piece` 는 자기 자신만의 점수를 관리하도록 하고 계산은 다른 곳에서 이뤄지는게 더 좋아 보이네요.

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/pieces/Piece.java
> +
갑자기 생각난 건데, `Piece` 가 `Position` 도 직접 들고 있는 구현은 어떨까요?
만약 그렇다면 `Board` 가 굳이 `LinkedHashMap` 의 형태로 관리할 필요도 없을 것 같은데요?

2021-02-25 13:44 UTC, wheejuni commented on src/main/java/net/sky/pieces/Piece.java
> +        return count > 1 ? defaultPoint / 2 : defaultPoint;
삼항연산자의 활용 자체는 나쁘지 않은데 개인적인 생각으론 삼항연산자 내부에 연산이 들어가면 그때부턴 가독성이 좀 떨어집니다. 
차라리 아래와 같이 풀어쓰는 것이 가독성 측면에서 더 나을수도 있겠습니다.

```suggestion
        if (count > 1) {
            return defaultPoint / 2;
        }
        return defaultPoint;

2021-02-26 02:16 UTC, aksmf1442 commented on src/main/java/net/sky/chess/Board.java
> +        final int FILE_SIZE = 8;
제가 아직 부족한 점이 많아 모르는것도 많아서 길게 질문 드립니다! 
1. 상수 성격의 변수가 메소드 한 곳에서만 쓰여도 무조건 클래스 상단부에 선언하는게 더 좋은 방법인가요?  
2. 그리고 사실 이 FILE_SIZE와 같은 값인 START_RANK라는 변수가 클래스 상단부에 있는데 제가 전달하고 싶은 의미와 변수명이 품은 의미가 달라서 새로 변수를 초기화 했는데, 이 경우엔 그냥 값은 같으니까 START_RANK라는 변수를 사용하는게 좋을까요 아니면 값이 같더라도 전달하고 싶은 의미의 변수를 새로 만드는게 좋을까요?
답변해주시면 감사하겠습니다!👍

2021-02-26 02:26 UTC, aksmf1442 commented on src/main/java/net/sky/chess/Board.java
> +    private Map<Position, Piece> piecePositions = new LinkedHashMap<>();
순서대로 화면에 출력하고 싶어서 LinkedHashMap을 사용했습니다! 그런데 생각해보니까 출력할 때도 LinkedHashMap을 사용하지 않고 순서대로 출력할 수 있는 방법이 있네요. 다시 HashMap으로 변경해서 사용해 봐야겠네요.

2021-02-26 02:36 UTC, aksmf1442 commented on src/main/java/net/sky/chess/Board.java
> +            }
훨씬 직관적인 것 같아서 좋은 것 같아요. 변경 해볼게요!

2021-02-26 03:32 UTC, aksmf1442 commented on src/main/java/net/sky/pieces/Piece.java
> +
그 구현도 해볼까 생각했었는데 위치를 찾고 변경하는게 Map이 더 편할 것 같아서 Map을 사용해봤습니다!

2021-02-26 03:32 UTC, aksmf1442 commented on src/main/java/net/sky/pieces/Piece.java
> +        return count > 1 ? defaultPoint / 2 : defaultPoint;
변경했습니다!

2021-02-26 03:33 UTC, aksmf1442 commented on src/main/java/net/sky/pieces/Piece.java
> +    public double getPoint(List<Piece> fileList) {
생각해보니까 자기 자신을 여러 개를 파라미터로 받는 부분은 어색한 것 같네요. 변경했습니다!

2021-02-26 03:34 UTC, aksmf1442 commented on src/main/java/net/sky/chess/Board.java
> +            if (color == piece.getColor()) {
변경했습니다!

2021-02-26 03:59 UTC, wheejuni commented on src/main/java/net/sky/chess/Board.java
> +        final int FILE_SIZE = 8;
이 메소드 한 곳에서만 사용된다면 상수로 보지 않아도 되고, 이 경우에 네이밍 컨벤션은 일반 변수와 같이 카멜 케이스(`fileSize`) 로 해 주세요. 

값이 같아도 사용처와 의미가 다르다면 다른 변수로 선언해주세요.

2021-02-26 04:00 UTC, wheejuni commented on src/main/java/net/sky/pieces/Piece.java
> +
`Map` 중에서도 `LinkedHashMap` 을 선택한 이유는요?

2021-02-26 04:41 UTC, aksmf1442 commented on src/main/java/net/sky/chess/Board.java
> +        final int FILE_SIZE = 8;
답변 감사합니다!

2021-02-26 05:01 UTC, aksmf1442 commented
사실 체스판 자체가 8x8이라 list나 배열로 관리하는게 맞는 것 같아서 처음에는 list로 관리를 하고 있었는데요..🥲  위치를 찾고 변경하는데 map을 사용하려니까 기존의 list와 새로 사용하려는 map 둘 다 쓰면 자원낭비?라는 느낌이 들었습니다. 그래서 체스의 핵심은 기물들의 위치이동이라고 생각을 해서 편하게 위치이동을 하기 위해서 list를 지우고 map만 남겨뒀는데요. 이 방법은 별로 좋지 않은 방법일까요?

2021-02-27 02:35 UTC, wheejuni commented
@aksmf1442 단순히 `List` 를 `Map` 으로 변경한 일에 대해 좋은 방법, 좋지 않은 방법임을 판단하기는 어렵네요.
여기에 의존되어있는 다른 로직들이 어떻게 작성되어있는지가 훨씬 더 중요한데요, 대체로 무난하게 구현된 듯 합니다.

2021-02-27 02:35 UTC, merged