[Bibi] '미션4 - 모든 기물 배치하기' PR입니다.
codesquad-members-2021/java-chess pull request #153
Opened 2021-02-25 07:25 UTC by bibi6666667

안녕하세요, 백엔드반의 Bibi입니다😀
'미션 4 - 모든 기물 배치하기' 에 대한 Pull Request 드립니다.

<새로 학습한 부분>
- 개행문자와 `System.getProperty("line.separator")`
- 값 객체

<활용했지만 학습이 더 필요한 부분>
- 팩토리 메서드
- import static

<궁금했던 부분>
- Piece클래스에 모든 기물의 색, 이름, 기호를 정의하다 보니 규모가 커진 것 같은데, 이 정도 규모이면 분리가 필요한 정도인지 그렇지 않은지 고민했습니다🤔
- 값 객체에 대해 공부하고 Piece클래스에 적용하긴 했는데, 값 객체라고 할 수 있는지 의문입니다.

제 나름대로는 리팩토링을 해 보았는데, 이게 괜찮은 코드인지 자신이 없네요.
모두의 많은 조언과 피드백 부탁드립니다🙇‍♀️ 감사합니다!

2021-02-25 10:43 UTC, sonypark requested changes
안녕하세요 Bibi, 리뷰어 소니 입니다.😊
미션4 구현하느라 수고하셨어요~👍
미션5 넘어가기 전에 개선이 필요한 부분에 대해 코멘트 남겼으니 확인 후 반영 부탁드립니다:)

2021-02-25 10:43 UTC, sonypark commented on src/main/java/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
`NEWLINE`은 StringUtils 내부에서만 사용되니 private 접근제어자를 사용하는게 나을것 같네요

2021-02-25 10:43 UTC, sonypark commented on src/main/java/chess/ChessStarter.java
>      }
콘솔에 start를 입력하면 바로 종료 되네요. 바로 종료되는걸 의도하신 건가요?

++ 지역변수 네이밍 규칙은 소문자를 사용합니다. 자바 상수의 경우에 대문자를 사용하는데요, 자바 상수 선언 방식에 대해 공부해보세요~
```java
 final String START = "start";
 final String END = "end";
```

2021-02-25 10:43 UTC, sonypark commented on src/main/java/chess/ChessStarter.java
>                      System.exit(0);
System.exit(0);이 꼭 필요할까요?

2021-02-25 10:43 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +    public final static char BLACK_KING_SYMBOL = 'K';
1. 접근제어자에도 순서 컨벤션이 있습니다.
[java-constant-variable-naming-convention](https://stackoverflow.com/questions/12519475/java-constant-variable-naming-convention) 참고해서 수정해보세요~

2. 말씀하신대로 Piece 클래스에 선언된 변수와 메서드가 많아서 크기가 비대해졌네요. 이 부분은 미션5에서 Enum으로 전환하면서 어느정도 해결이 될거에요 :)

2021-02-25 10:43 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +    }
String 비교는 `==` 으로는 안 될 것 같은데, 왜 그럴까요? 어떻게 수정해야 할까요?

2021-02-25 10:43 UTC, sonypark commented on src/main/java/pieces/Piece.java
> +    }
getter, setter 같은 메서드는 일반적으로 클래스 하단에 배치합니다:) (참고해주세요)

2021-02-25 10:43 UTC, sonypark commented on src/main/java/chess/Board.java
> +            blackOthers.add(piece);
1. 추상 클래스가 아닌 일반 클래스에서 default 접근제어자를 사용하는 경우는 많지 않습니다. 클래스 내부에서만 사용되면 private, 외부에서도 사용되면 public 접근제어자를 사용해주세요~
2. 리턴값이 boolean이어야 할 필요는 없을 것 같아요.
3. 조건문도 개선할 점이 보이는데, 이 부분은 Enum으로 전환하면서 자연스럽게 해결될 것 같습니다.

2021-02-25 10:43 UTC, sonypark commented on src/main/java/chess/Board.java
> +        return sb.toString();
`showBoard` 메서드에서는 출력만 담당하면 될 것 같은데, 반환값을 리턴하는 이유가 있나요?
체스판을 반환하고 싶다면 Board에서는 체스판을 리턴하고, Main에서 출력하는 로직으로 변경하는게 좋을 것 같네요

2021-02-25 10:43 UTC, sonypark commented on src/main/java/chess/Board.java
>      }
이건 메서드 보다는 변수로 처리하는게 더 좋을 것 같습니다.

2021-02-25 14:40 UTC, bibi6666667 commented on src/main/java/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
네! 수정하겠습니다😀

2021-02-25 14:49 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
>      }
게임 시작시 체스판을 출력하라고만 되어 있어서 출력만 했는데, 듣고 보니 좀 그렇네요.
체스판 출력 후 `ready()`를 호출하도록 수정하겠습니다!

자바 상수명은 모두 대문자에 Snake Case를 쓴다, 지역변수는 소문자에 Camel Case를 쓴다 이 정도만 알고 있는데, 위와 같이 지역변수인 상수의 경우는 어떻게 지어야 하나요?🤔
우선은 상수니까 대문자로 쓰긴 했는데, 이런 경우 상수이기 전에 지역변수이므로 `start` `end`이런 식으로 사용하면 되는 건가요?

2021-02-25 14:53 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
>                      System.exit(0);
없어도 잘 종료되긴 하지만, 여기서 프로그램이 종료된다는 걸 명시적으로 나타내고 싶어서 사용했습니다. 사용하면 안 좋은 메소드인가요?😮

2021-02-25 14:55 UTC, bibi6666667 commented on src/main/java/pieces/Piece.java
> +    public final static char BLACK_KING_SYMBOL = 'K';
네! 링크 참고해서 제어자 선언 순서를 수정했습니다. 링크 공유 감사합니다🙇‍♀️

2021-02-25 14:58 UTC, bibi6666667 commented on src/main/java/pieces/Piece.java
> +    }
`==`는 두 대상의 주솟값을 비교하는 연산자이고 기본타입 비교에 주로 사용하며,
`equals()`는 두 대상의 값 자체를 비교하는 메서드입니다. String은 기본타입이 아니기 때문에 `equals()`를 사용해야 합니다. 이런 실수를 하다니 부끄럽네요😭 수정하겠습니다!
코멘트 감사합니다🙇‍♀️

2021-02-25 14:59 UTC, bibi6666667 commented on src/main/java/pieces/Piece.java
> +    }
그렇군요😮 getter메서드들 위치 모두 수정하겠습니다!
코멘트 감사합니다🙇‍♀️

2021-02-25 15:01 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +            blackOthers.add(piece);
접근제어자 public으로 수정하고, 리턴값 없이 해당 메서드 사용하도록 수정하겠습니다!
코멘트 감사합니다🙇‍♀️

2021-02-25 15:02 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +        return sb.toString();
출력문 삭제 후 ChessStarter에서 리턴값을 받아 출력하도록 수정했습니다!
코멘트 감사합니다🙇‍♀️

2021-02-25 15:05 UTC, bibi6666667 commented on src/main/java/chess/Board.java
>      }
확실히 그렇네요ㅠ 수정했습니다!
코멘트 감사합니다😀

2021-02-26 14:30 UTC, sonypark commented on src/main/java/chess/ChessStarter.java
>      }
[Code Conventions for the Java Programming Language : 9 - Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html#367)에 따르면 static final이 붙은 클래스 상수는 대문자 언더스코어를 사용한 네이밍 규칙(`uppercase with words separated by underscores ("_")`)을 따른다고 나와있습니다. 자바에서 final이 붙으면 재할당이 불가능하기 때문에 개념상 상수이긴 하지만, 일반적으로 자바 상수라고 하면 static final 붙은 클래스 상수를 말하는 경우가 많습니다. 저도 클래스 상수의 의미에서 자바 상수로 선언할 것을 말씀드렸습니다. static이 붙지 않은 인스턴스 상수나, 위 코드처럼 메서드 내부의 지역 변수로 사용되는 경우는 카멜 케이스를 사용하는 경우가 많은것 같습니다. (물론 속한 팀의 컨벤션에 따라 다를 수 있습니다.)

현재 코드에서 START,END는 클래스 상수로 선언하는게 더 나아보입니다. 그 이유는 "start", "end"라는 문자열이 메서드가 실행될 때마다 메모리에 할당되었다가 끝날때 해제될 필요가 없고, 객체를 생성할 때마다 매번 초기화가 필요하지 않기 때문입니다. 한번 static 으로 초기화 한뒤 메서드나 객체의 호출 횟수에 상관없이 재사용 하면 되기 때문입니다.

정리하자면, 
- 자바에서 final을 붙여 만든 변수(상수)는 클래스 상수에 한해 `대문자 언더스코어`를 사용한 네이밍을 하고, 나머지는 `카멜 케이스`를 사용한다.
- 위 코드의 경우는 클래스 상수로 선언하는게 낫다.


관련 내용은 링크를 첨부할테니 참고해서 공부하며 고민해주세요😊
- [Naming convention: Final fields (not static)](https://softwareengineering.stackexchange.com/questions/252243/naming-convention-final-fields-not-static)
- [Use of final local variables in java - Stack Overflow](https://stackoverflow.com/questions/18225572/use-of-final-local-variables-in-java)
- [What is a constant and how to define constants in Java?](https://www.tutorialspoint.com/what-is-a-constant-and-how-to-define-constants-in-java)
- [why are java constants declared static?
](https://stackoverflow.com/questions/8093230/why-are-java-constants-declared-static/8093375)
- [왜 자바에서 final 멤버 변수는 관례적으로 static을 붙일까?
](https://djkeh.github.io/articles/Why-should-final-member-variables-be-conventionally-static-in-Java-kor/)

2021-02-26 14:45 UTC, sonypark commented on src/main/java/chess/ChessStarter.java
>                      System.exit(0);
`System.exit(0);`는 메인 메서드를 종료하는 것과 동일한 기능을 합니다. 이 코드가 없어도 메인 메서드가 정상적으로 종료될 것이기 때문에 굳이 필요없는 코드라고 생각합니다. 'System.exit(0)'를 사용해서 프로그램을 종료해야 하는 경우는 크게 두 가지가 있을 것 같네요.

1. 특정 예외가 발생했을 때 따로 처리하지 않고 바로 프로그램 종료
2. 메인 메서드가 아닌 곳에서 프로그램을 종료하고 싶을때
> The typical use-case for System.exit is when there is an abnormal condition and we need to exit the program immediately.

Also, if we have to terminate the program from a place other than the main method, System.exit is one way of achieving it.

아래 링크 글도 한 번 읽어보세요~

- [A Guide to System.exit()](https://www.baeldung.com/java-system-exit)

2021-02-26 14:48 UTC, sonypark approved these changes
비비 피드백 반영하느라 고생하셨습니다!
좋은 질문이 많네요. 덕분에 저도 공부가 되었습니다.😊
제가 틀린 부분이 있을 수 있으니 비비도 같이 공부해서 토론해보면 좋을 것 같아요!
코멘트 남긴거 읽어보시고 답변 부탁드립니다👍
미션4는 Approve 할게요~ 다음 단계 진행해주세요!💪

2021-02-27 04:41 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
>      }
와 자세한 설명과 링크 첨부 감사합니다!🙇‍♀️🙇‍♀️ 공부해 보고, 클래스 상수로 만든 뒤 상수 컨벤션으로 변경하겠습니다!

2021-02-27 04:57 UTC, bibi6666667 commented on src/main/java/chess/ChessStarter.java
>                      System.exit(0);
아 특별히 사용하는 경우가 있었군요! 남용하지 말고 해당 경우에만 사용하도록 하겠습니다. 링크와 코멘트 감사합니다🙇‍♀️👍

2021-03-01 08:17 UTC, merged