[Pyro] 미션5 : 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #155
Opened 2021-02-25 11:18 UTC by ghojeong

내일이 java-chess 교육과정의 마지막 날인지라,
클린코드 고려치 않고 막장으로 돌아가게 재빠르게 구현했습니다.
따라서 indentation depth 가 2를 넘어가는 곳이 존재합니다.

#### 1. 기물의 색, 기물의 종류에 따른 enum 구현

색은 Color enum 으로 구현했지만, 기물의 종류는 별도의 싱글톤 클래스로 구현했습니다.

#### 2. Piece에 대한 색과 기물에 따라 분리된 팩토리 메소드에서 enum 사용

ofWhite 와 ofBlack 메서드로 구현했습니다.

#### 3. 팩토리 메소드 리팩토링

별도로 리팩토링은 하지 않았습니다.

#### 4. 체스판의 모든 칸을 Piece로 초기화

지난 미션 4에서 BoardFactory 클래스를 통해 구현했습니다.

#### 5. 기물과 색에 해당하는 기물의 개수를 반환

board.count(); 함수로 구현했습니다. 클린하지 않습니다.

#### 6. 주어진 위치의 기물을 조회

board.getPiece(); 함수로 지난 미션 4에서 이미 구현했습니다.

#### 7. 임의의 기물을 체스판 위에 추가

board.put(); 함수로 구현했습니다.

#### 8. 체스 프로그램 점수 계산하기

board.getScore(); 함수를 통해 구현했습니다. 철저하게 함수형으로 구현해보려고 했는데, 잘 안되서 클린하지 않은 코드로 일단 빨리 작성했습니다.

#### 9. 기물의 점수가 높은 순으로 정렬

Piece 클래스에 implements Comparable 을 함으로써 구현했습니다.

2021-02-25 14:16 UTC, tmdgusya commented on src/main/java/chess/domain/pieces/Piece.java
> +                : -1;
여기 이렇게 한줄로 쓰신 이유가 뭔가요? 되게 독특해서 궁금하네요

2021-02-25 23:35 UTC, ghojeong commented on src/main/java/chess/domain/pieces/Piece.java
> +                : -1;
오! 급하게 막 구현하다보니 저런 코드가 나왔네요.
저런것도 사실 2중 조건문으로 생각되기 때문에, 클린하지 않습니다.
Piece 간의 점수 격차 또한 표현해주지 못하기 때문에
`return (int) 2 * (getScore() - piece.getScore());` 로 고치겠습니다.

2021-02-26 01:54 UTC, pbg0205 commented on src/main/java/chess/domain/pieces/Piece.java
> +                : -1;
```java
@Override
public int compareTo(Piece piece) {
       return Double compareTo(getScore(), piece.getScore();
}
```
오름차순 정렬하시거면 이렇게 구현해보시는 것도 괜찮을거 같습니다!

2021-02-26 11:21 UTC, ghojeong commented on src/main/java/chess/domain/pieces/Piece.java
> +                : -1;
오, Double.compareTo 함수는 생각도 못해봤는데 감사합니다!

2021-02-26 11:35 UTC, wheejuni requested changes
전반적으로 구현이 굉장히 깔끔히 잘 되었습니다. 👍 💯 
아주 훌륭한 코드인데 간단한 개선 사항 몇가지 제한해 코멘트 드립니다. 
반영 부탁드릴게요~

2021-02-26 11:35 UTC, wheejuni commented on src/main/java/chess/domain/board/Board.java
> +    }
좋은 구현이네요 👍

2021-02-26 11:35 UTC, wheejuni commented on src/main/java/chess/domain/board/Board.java
> +        double scoreOfPawns = pawns.stream()
요 사이에 개행 한 줄 넣어주세요. 가독성이 조금...

2021-02-26 11:35 UTC, wheejuni commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> !(piece instanceof Pawn))
`instanceof` 의 사용은 대개 안티 패턴이라 사용을 극히 제한할 것을 요구하는 경우가 많은데요. 
꼭 사용해야 하나요? `Piece` 에 `Pawn` 여부를 알려주는 `public boolean` 메소드가 있다면 `instanceof`는 걷어낼 수 있을 것 같은데요.
`instanceof` 제거하는 리팩토링 진행해 주세요.

2021-02-26 11:35 UTC, wheejuni commented on src/main/java/chess/domain/pieces/Piece.java
> +    public abstract double getScore();
👍 👍 👍 
아까 말씀드린 `Pawn` 여부 나타내는 추상 메소드도 추가해 주세요.

2021-02-26 11:43 UTC, ghojeong commented
한참 리뷰중이신데, 실수로 리뷰를 re-request 했습니다.
리뷰 주신 내용들 수정해서 다시 요청하겠습니다.

2021-02-26 11:44 UTC, ghojeong commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> !(piece instanceof Pawn))
헉 그렇군요! 제가 자바 경력이 짧은지라, warning 이 뜨지 않으면 사용할 수 있는 문법이라고 착각할 때가 종종있습니다.
instanceOf 를 사용하지 않도록 리팩토링하겠습니다.

2021-02-26 11:55 UTC, ghojeong commented on src/main/java/chess/domain/pieces/Piece.java
> +    public abstract double getScore();
instanceOf 를 제거하기 위해 Pawn 여부를 나타내는 추상 메소드를 Piece 에 추가할까 하다가,
Board 이외에는 Pawn 을 체크하는 로직을 사용할것 같지 않아서,
응집력을 높이기 위해 Board 안에 isPawn 메소드를 정의했습니다.

isPawn 을 추상 메소드를 하위 클래스들에게 전부 구현하도록 하는 것은, 군더더기 처럼 생각이 되어서요.

2021-02-26 12:00 UTC, ghojeong commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> !(piece instanceof Pawn))
찾아보니 리스코프 치환 법칙을 위반하는 안티 패턴 코드가, instanceof 를 사용하려 할때 자주 등장한다고 나오는군요.
알려주셔서 감사합니다.

2021-02-27 02:39 UTC, wheejuni commented on src/main/java/chess/domain/pieces/Piece.java
> +    public abstract double getScore();
@ghojeong 전혀 군더더기가 아니고, 권장되는 방법입니다.

2021-02-27 02:42 UTC, wheejuni approved these changes

2021-02-27 02:42 UTC, wheejuni commented on src/main/java/chess/domain/board/Board.java
> +    }
`Board.isPawn()` 이라는 메소드는 이름만으로 조금 어색하게 느껴지진 않으시나요? 
보드는 보드일뿐인데 폰임을 알려주는 메소드라니... 물론 `private` 노출도라서 상관 없다고 생각하실 수도 있겠지만요. 
이런 사유에서 `Piece` 에 `.isPawn()` 추상 메소드가 추가돼야함을 말씀드린 것인데 제 뜻이 온전하게 전달되지 않은 것 같아 많이 아쉽네요.

2021-02-27 02:42 UTC, merged

2021-02-27 11:45 UTC, ghojeong commented on src/main/java/chess/domain/board/Board.java
> +    }
@wheejuni  헉, 제 생각이 짧았군요. instanceOf 만 없애면 된다고 생각했는데,
Board.isPawn 이라는 메소드 명을 보니, private 메소드라 하더라도 확실히 이상하다고 느꼈습니다.
이상한 고집부려서 죄송합니다.
해당 부분 수정하여 PR 올리겠습니다.