[Jung] 미션5: 보드에 위치 부여 및 점수 계산 PR입니다.
codesquad-members-2021/java-chess pull request #158
Opened 2021-02-26 03:56 UTC by rla36

안녕하세요? Jung입니다!
커밋 개수에서 드러나듯이,,, 미션5 하면서 고민이 정말 많았습니다.. 

###   주요 변화
- Color, Type 이넘 Piece클래스 안으로 이동
- Rank 클래스 생성
- Position 클래스 생성

### 고민한 것들
**Rank클래스**
- 기존에 Board에서 Piece를 직접 담당했었는데, 이것을 Rank클래스로 대부분 넘겨버렸습니다. Rank가 Piece를 담당하고, Board는 Rank를 담당하도록 역할 분배했습니다.
- 이렇게 역할 분배를 한 결과, Board에서 Piece를 직접 접근하기 위해선 for문을 2개 중첩해 사용해야 하는 문제가 발생했습니다. 가독성이 떨어져 어떻게 고칠지 고민했는데 별 성과는 없었습니다.. 조언부탁드립니다!

**Board클래스**
- Board의 calculatePoints메서드에서 pawn이 같은 file에 있으면 개다 0.5점씩 차감을 합니다. Board에서는 Rank를 다루고, Rank에서는 Piece를 다루기에 Board에서 직접 file에 접근할 수 있는 방법이 없어 코드가 복잡해졌습니다. 더 나은 해결책이 있을 것 같은데 고민할 시간이 필요할 것 같습니다..

**Position 클래스**
- Position 인스턴스는 같은 rank, file이라면 같은 위치로 생각해도 되므로 VO에 해당된다고 생각해 equals, hashCode를 오버라이딩했습니다.
- Position에서 생성자를 private으로 설정하고 Position.at("a4") 와 같이 at메서드를 통해 인스턴스를 받도록 했습니다. 이렇게 하면 인스턴스의 무분별한 생성을 막고, 메모리 과부하를 방지할 수 있다는 이야기를 들었습니다. [출처](https://stackoverflow.com/questions/12901734/what-is-the-advantage-of-singleton-design-pattern) 
- Board의 첫번쨰 고민과 관련해서, Board에서 file을 직접 접근할 수 없으므로, 차라리 Position안에 file이넘, rank이넘을 만들면 어떨까 생각했습니다. 그렇지만 게임플레이어가 위치를 String으로 입력할 것이기에 Position의 생성자 매개변수로 String을 받는 이점이 분명하다고 생각했습니다. (아니면 at메서드로 String을 입력받아 분해해 이넘으로 만든 후에 생성자의 매개변수에 이넘 넣어 return new Position(이넘, 이넘)하는 방법도 있을 것 같습니다.. 휴..)

Board에서 Rank클래스를 분리하는 데서 대부분의 고민이 생긴것 같은데, Board가 비대해지더라도 Rank의 역할을 Board로 통합시키는 것이 어떨지 다시 한번 생각해봐야할 것 같습니다.

리뷰해주셔서 감사합니다!

2021-02-26 15:56 UTC, sonypark requested changes
안녕하세요 Jung, 리뷰어 소니 입니다.😊
구현한 코드 잘 보았습니다.
특히 테스트 코드를 꼼꼼히 짜려고 노력하신 것 같아 좋았어요!
간단한 코멘트 남겼으니 확인 부탁드립니다~

2021-02-26 15:56 UTC, sonypark commented on src/test/java/net/jung/chess/pieces/PieceTest.java
> +    @DisplayName("createBlack로 만들어진 Piece는 Color.NO_COLOR, Type.NO_PIECE이다. ")
DisplayName 오타! -> checkCreateBlank로 변경
처음에 보고 'Black이 왜 NO Color이지?' 했네요🤔

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Position.java
> +        }
예외 처리 👍
2와 같은 매직 넘버는 피해주세요~

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Position.java
> +    private int rankIndex;
final을 붙여도 좋겠네요

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Piece.java
> +    }
getter 메서드는 하단에 배치해주세요. (Overriding 한 메서드 위)

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Board.java
>      }
```java
    public int boardPieceSize() {
        return rankList.stream()
                .mapToInt(Rank::rankPieceSize)
                .sum();
    }
```
(참고) 스트림을 이용하면 이렇게 구현할 수도 있습니다.

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Board.java
>      }
화면에 표현해주기 위한 로직은 이곳에서 하는게 아니라 Main 또는 출력을 담당하는 클래스에서 해주는게 좋을 것 같아요.
Board는 체스판만 리턴하고 출력은 외부에서 해주는 방식

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Rank.java
> +    }
여기도 마찬가지로, rank 는 pieces만 리턴하고 출력을 위한 로직은 외부에서 하는 방식을 생각해보세요

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Rank.java
> +    private ArrayList<Piece> pieceList = new ArrayList<>();
List와 같은 자료형의 이름은 변수명에 넣지 않는걸 권장합니다.
pieceList보단 pieces가 낫겠네요

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Board.java
> +        }
```suggestion
        points = colorPieceList.stream()
                .mapToDouble(Piece::getDefaultPoint)
                .sum();
```
여기도 stream으로 바꾸거나 enhanced for loop를 사용할 수 있겠네요

2021-02-26 15:56 UTC, sonypark commented on src/main/java/net/jung/chess/Board.java
> +        Collections.sort(colorPieceList, Collections.reverseOrder());
```suggestion
        colorPieceList.sort(Collections.reverseOrder());
```
List에도 sort라는 내장 함수가 있습니다.

2021-02-26 15:58 UTC, sonypark commented on src/main/java/net/jung/chess/Position.java
> +    public static Position at(String location) throws IllegalArgumentException {
at 보다는 정적 팩토리 메서드에서 주로 사용하는 네이밍을 사용하시면 더 좋을 것 같네요.
어떤 네이밍을 주로 사용하는지 찾아보세요~

2021-02-28 11:15 UTC, rla36 commented on src/test/java/net/jung/chess/pieces/PieceTest.java
> +    @DisplayName("createBlack로 만들어진 Piece는 Color.NO_COLOR, Type.NO_PIECE이다. ")
앗 실수.. 꼼꼼하게 봐주셔서 감사합니다!! 수정하겠습니다 ㅎㅎ

2021-02-28 11:18 UTC, rla36 commented on src/main/java/net/jung/chess/Position.java
> +        }
네 2를 Postion클래스에 private static final int NUM_OF_DIGITS = 2 를 추가해 2를 대체하도록 수정했습니다.!

2021-02-28 11:19 UTC, rla36 commented on src/main/java/net/jung/chess/Position.java
> +    private int rankIndex;
한번생성되면 바뀔일이없으니까 그렇겠네요! 변수, 메서드 속성 정하는게 아직도 많이 부족합니다 ㅎ.. 감사합니다!!

2021-02-28 11:26 UTC, rla36 commented on src/main/java/net/jung/chess/Piece.java
> +    }
메서드 위치에도 컨벤션이 있었군요..! 수정했습니다! 컨벤션을 공부해보겠습니다

2021-02-28 11:27 UTC, rla36 commented on src/main/java/net/jung/chess/Board.java
>      }
감사합니다 부끄럽지만 제가 아직 스트림 공부를 못해서..ㅜ 일단 말씀해주신대로 수정하고 공부해보겠습니다 !!!

2021-02-28 11:32 UTC, rla36 commented on src/main/java/net/jung/chess/Rank.java
> +    private ArrayList<Piece> pieceList = new ArrayList<>();
앗 다른 곳에서는 List로 했는데 왜 저기만 ArrayList가 들어갔을까요.. 다형성 때문에 List로 쓰는 경우가 많다고 알고 있습니다! 말씀하신 사항 수정했습니다~ (Board의 rankList도 ranks로 수정했습니다!)

2021-02-28 11:35 UTC, rla36 commented on src/main/java/net/jung/chess/Board.java
> +        }
여기서도 마찬가지로 일단 수정한 후에 스트림을 제대로 공부하겠습니다!

2021-02-28 11:53 UTC, rla36 commented on src/main/java/net/jung/chess/Position.java
> +    public static Position at(String location) throws IllegalArgumentException {
factory method naming convention검색하니 create를 많이 쓴다고 해 createPosition으로 수정하도록 하겠습니다!
Position.at("a6")식으로 하면 의미가 직관적으로 와닿는다고 생각했는데 컨벤션이 중요하단 것을 몰랐습니다ㅜ 알려주셔서 감사합니다

2021-02-28 12:02 UTC, rla36 commented on src/main/java/net/jung/chess/Board.java
>      }
넵 조금더 고민해보겠습니다...!

2021-03-01 04:55 UTC, sonypark approved these changes
수정 사항 확인했습니다.
고생 많으셨습니다!

2021-03-01 11:21 UTC, honux77 commented on src/main/java/net/jung/chess/Position.java
> +    public static Position at(String location) throws IllegalArgumentException {
https://stackoverflow.com/questions/3368830/how-to-name-factory-like-methods 요 링크도 참고하세요.
제 생각에는 of 괜찮을 것 같은데 어때요?

2021-03-01 11:21 UTC, merged