[August] 미션 5: 보드에 위치 부여 및 점수 계산
codesquad-members-2021/java-chess pull request #159
Opened 2021-02-26 07:11 UTC by Polynomeer

## 미션 5: 보드에 위치 부여 및 점수 계산

안녕하세요? 항상 친절한 리뷰 감사합니다. 이번 PR은 미션5에 관한 내용입니다.

2021-02-27 02:31 UTC, wheejuni requested changes
5단계까지 진행하시느라 수고 많으셨습니다. 👍 💯 
개선할 점이 좀 있는데요, 코멘트 하나하나 읽어보시고 반영해 주셨으면 좋겠습니다.
체스 과제 진행기한이 얼마 남지 않았는데 마무리가 잘 되었으면 좋겠습니다!

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Board.java
> +            point += piece.getPoint(pieces);
`.stream()` 기반으로 개선해주세요.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Board.java
> +        List<Piece> pieces = findPiecesByColor(color);
아래 합계 계산하는 로직과 한 스트림으로 묶이면 좋겠네요.

```java
findPiecesByColor(color).stream().map....

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Board.java
> +        }
`.toString()` 에 사이드 이펙트 발생 우려가 있는 복잡한 로직은 넣지 말아주세요. 
그리고 `.toString()` 이 생성하는 문자열은 특정 로직에서 사용될 문자열이 아닌, 객체에 대한 범용적인 상태 표현이어야 합니다. 
콘솔에 보드의 상태를 나타내는 목적으로 사용할 로직은 별도의 메소드를 설계해서 빼 주시고 `.toString()` 에는 가급적 IDE가 자동 생성해주는 정도의 로직을 넣어 주면 좋겠습니다.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Board.java
> +        for (Rank rank : board) {
여기도 `this.board` 의 원소를 `List<Piece>` 로 바꾼 다음 `.collect()` 하는 로직으로 재설계하면 좋겠네요.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +class Rank {
접근 제어자는요?

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +    void add(Piece piece) {
여기도요?

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +    List<Piece> getPieces() {
여기도 없네요? ㅠㅠ

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +    int countPieces(Color color, Type type) {
헐~ 여기도 ㅠㅠㅠ

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +    static Rank initializeWhitePieces(int rankIndex) {
여기도요.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/chess/Rank.java
> +    }
이 로직도 `.toString()` 용도로는 조금 과한 듯 싶기도 합니다. 
IDE의 자동생성 정도로 간소화해주세요.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/piece/Piece.java
> +    public void addPiecesByColor(Color color, List<Piece> piecesByColor) {
`color` 하나만 파라메터로 받고, 이 메소드에선 `boolean` 값을 내려준 다음에, 
리스트에 넣는 책임은 리스트를 가진 쪽에서 직접 수행해도 될 텐데요. 너무 과합니다.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/piece/Piece.java
> +    }
이 메소드 두 개를 `public` 으로 오픈하면 훨씬 더 유연한 설계가 가능할 것으로 보입니다.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/piece/Piece.java
> +    }
`match` 보다 `get` 이 오픈수준이 더 높은 것은 좀 어색합니다. `match` 가 더 우선 사용돼야 합니다.

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/piece/Piece.java
> +    }
이 두 메소드는 아래 메소드로 합칠 수 있지 않나요?

```java
public boolean isMatchingColor(Color color);

2021-02-27 02:31 UTC, wheejuni commented on src/main/java/piece/Piece.java
> +    public double getPoint(List<Piece> pieces) {
이 메소드는 여기에 있으면 안될 것 같습니다. 
`Piece` 가 `List<Piece>` 를 받아서 점수를 계산하는 로직은 어색한데요. 
이 클래스엔 자기 자신의 점수를 리턴하는 정도의 로직을 배치하고, 실 점수 계산은 다른 클래스에서 이뤄져야 할 것 같네요.

2021-02-28 05:52 UTC, Polynomeer commented on src/main/java/chess/Board.java
> +        }
`.toString()`의 목적에만 신경을 쓰고 사이드 이펙트를 고려하지 못 했습니다. `PrintUtils::showBoard()`로 이동했습니다.

2021-02-28 05:53 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +class Rank {
패키지 내부에서만 접근하므로 디폴트로 두었습니다. 하지만 `PrintUtils::showBoard()`에서 사용하게 되어서 public으로 변경하였습니다.

2021-02-28 05:57 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +    void add(Piece piece) {
음.. 저는 우선은 private으로 최소한의 접근 제한자를 두고싶습니다. 하지만 테스트할 필요가 있으며 클래스 외부에서 사용하는 경우에는 public과 package-private(default) 두 가지 중에 선택을 해야했습니다. 저는 그래도 패키지 내부에서만 사용한다면 default로 선언하는게 맞다고 생각했는데, 그게 문제가 되나요? 혹시 default는 실무에서 잘 사용하지 않는건가요? 궁금합니다!

2021-02-28 05:59 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +class Rank {
저는 우선은 private으로 최소한의 접근 제한자를 두려고 했습니다. (최소한의 접근 제어자로 시작하는것이 좋다는 호눅스의 팁을 빌려서) 하지만 테스트할 필요가 있으며 클래스 외부에서 사용하는 경우에는 public과 package-private(default) 두 가지 중에 선택을 해야했습니다. 저는 그래도 패키지 내부에서만 사용한다면 default로 선언하는게 맞다고 생각했는데, 그게 문제가 되나요? 혹시 default는 실무에서 잘 사용하지 않는건가요? 궁금합니다!

2021-02-28 06:00 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +    int countPieces(Color color, Type type) {
Board에서 사용하므로 public으로 변경했습니다! 이런 경우에는 좀 헷갈리네요.

2021-02-28 06:01 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +    static Rank initializeWhitePieces(int rankIndex) {
public으로 변경했습니다.

2021-02-28 06:29 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +    }
toString의 사용을 모두 StringUtils의 정적 메서드로 변경했습니다.

2021-02-28 06:42 UTC, Polynomeer commented on src/main/java/piece/Piece.java
> +    public void addPiecesByColor(Color color, List<Piece> piecesByColor) {
네! Rank에서 `findPiecesByColor()`가 사용중이었는데, 거기에서 이 기능을 담당하도록 했습니다. 여기에서 사용하는 `Piece::matchColor()`은 public으로 접근제한을 열게 되었습니다.

2021-02-28 06:44 UTC, Polynomeer commented on src/main/java/piece/Piece.java
> +    }
우선 matchColor()는 위의 코멘트에서 오픈하게 되었습니다. matchType()도 오픈하면 좀 더 심플한 설계가 될 것 같은데, 이 부분은 좀 더 고민해보겠습니다.

2021-02-28 06:45 UTC, Polynomeer commented on src/main/java/piece/Piece.java
> +    }
verification이나 validation 메서드가 당연히 외부에서 사용되는 의미가 강하니까 그렇겠군요. 무슨 말인지 이해했습니다.

2021-02-28 07:00 UTC, Polynomeer commented on src/main/java/piece/Piece.java
> +    }
네, `isRightColor(Color expectedColor)`이라는 메서드로 한번 합쳐보았습니다.

2021-02-28 07:26 UTC, Polynomeer commented on src/main/java/piece/Piece.java
> +    public double getPoint(List<Piece> pieces) {
Board클래스에 `getPoint()`메서드를 추가하여 이 로직을 담당하도록 하였습니다. 여기에서는 단순히 필트 type의 point를 반환하는 메서드로 변경했습니다.

2021-02-28 07:30 UTC, Polynomeer commented on src/main/java/chess/Rank.java
> +    List<Piece> getPieces() {
몇 개는 정말로 접근 제어자를 빠뜨린 부분이 있어서 주의해야 겠다는 생각이 들었습니다 ㅠㅠ

2021-02-28 07:47 UTC, Polynomeer commented on src/main/java/chess/Board.java
> +            point += piece.getPoint(pieces);
pieces 리스트의 stream을 얻어서 합계를 구하는 방식으로 변경해보았습니다.

2021-02-28 07:48 UTC, Polynomeer commented on src/main/java/chess/Board.java
> +        List<Piece> pieces = findPiecesByColor(color);
묶으려고 했다가 `getPoint()`를 Board에 포함하게 되면서 그냥 변수로 두게 되었습니다!

2021-02-28 08:03 UTC, Polynomeer commented on src/main/java/chess/Board.java
> +        for (Rank rank : board) {
stream을 사용한 코드로 변경했습니다.

2021-02-28 08:04 UTC, Polynomeer commented
리뷰에 대한 변경사항을 모두 반영하였습니다! 확인 부탁드립니다.

2021-03-01 05:00 UTC, wheejuni approved these changes

2021-03-01 05:00 UTC, merged