[Tree]미션4 : 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #162
Opened 2021-02-26 15:44 UTC by choitree

안녕하세요 저번 PR에서 중복적으로 지적해주신 부분을 주의해서 코드 수정해보았습니다.
정말 기본적인 내용이지만 제가 주의하지 않았던 내용들에 대해서 여러 차례 정확하게 적었는지 살펴보았습니다. 
또한, 메소드명과 변수명도 최대한 주석처리 없이 이해할 수 있도록 수정해봤습니다. 
이전 미션에 잔재인 코드는 모두 삭제하였고, 테스트가 필요한 메소드별로 테스트 코드를 작성했습니다.
enum을 사용해서 Piece를 관리하고 싶어서, enum class로 관리하였고 
조원의 코드 리뷰를 받고 조금 더 고심한 끝에 enum을 전면 수정하였습니다.

주석을 최대한 줄이라는 리뷰를 받아, 주석을 모두 삭제하였으나 메소드명에 대한 고민이 있는 부분에 한 줄 남겨두었습니다. 
초기화된 기물을 배치하는 단계에서 List를 받아, Pawn과 Pawn이 아닌 기물을 나눠서 메소드를 작성하였는데 
Pawn이 아닌 기물에 대해서 메소드 명명이 어려워 변경 전 메소드명을 함께 적시하였습니다.

저번 PR에서 Dion이 어마어마하게 고생해주셨고, 또한 오늘 이미 조원들이 리뷰어의 노고를 십시일반으로 덜어준 점이 큰 상태입니다. 
리뷰 받은 내용을 기준으로 오늘 전면 수정한 후 rebase하고 재차 검토해서 PR 요청합니다.
누가 리뷰해주실지는 모르지만, 미리 너무너무 죄송하고 감사합니다ㅠ_ㅠ

(커밋 메시지가 알맞지 않아서 브랜치를 다시 만들어서 커밋메시지를 다시 적어봤습니다.)

2021-02-27 06:56 UTC, sonypark requested changes
안녕하세요 Tree, 리뷰어 소니 입니다.😊
구조 변경이 필요한 부분이 꽤 보입니다.
대부분 미션5에서 요구사항으로 주어질 부분인데요, 미리 고민해보시는 게 좋을 것 같아요.
코멘트 남긴 부분 중 적용 가능하신 부분에 대해 반영 부탁드릴게요~

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
StringUtils 내부에서만 쓰이니 접근제어자는 private이 좋겠네요

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/tree/pieces/Pieces.java
> +    }
Pieces라는 enum이 color와 representation을 문자열 형태로 갖고 있네요.
그러다 보니 enum 내 상수가 늘어나게 되고, 코드의 응집도가 떨어지는데요.
Color와 Representation에 대한 enum을 각각 생성해서 Piece 클래스에서 사용하면 어떨까요?
이 부분은 미션5의 요구사항이니, 한 번 고민해보시고 어렵다면 미션5에서 진행하셔도 됩니다.

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +    public static final int TOTAL_PIECES_SIZE = 32;
TOTAL_PIECES_SIZE 만 public인 이유가 있을까요?

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +    private List<Piece> blackPieceList = new ArrayList<>();
- 변수명에 자료형 이름(List, Set, Map)은 사용하지 않는 걸 권장합니다.
   - whitePieces, blackPieces가 낫겠네요.
- 현재는 행/열의 구분 없이 하나의 리스트에 체스말을 담고 있는 구조인데요, 체스말의 이동 기능을 구현하려면 지금과 같은 구조로는 어려울 것 같아요. 이부분은 미션5에서 변경하시게 될 거에요. 어떻게 바꾸는게 좋을지 미리 고민해보시는 것도 좋습니다.

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +    }
showBoard 메서드는 이름만 보면 출력을 담당할 것 같은데, 실제 구현은 그렇지 않네요.
그리고 체스판을 출력하는 로직이 Board 클래스의 역할인지도 생각해보시길 바랍니다.
Board 클래스는 체스판을 리턴하고, Main 클래스나 출력 로직을 담당하는 클래스에서 체스판을 전달받아 출력해주는게 더 자연스러울 것 같습니다.

2021-02-27 06:56 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +        return sb.toString();
- for문을 enhanced for loop로 개선해보세요. 가독성이 훨씬 더 좋습니다.
- 현재 로직에서는 두 메서드를 하나로 합치는 것도 가능하겠네요.

2021-02-27 06:56 UTC, sonypark commented on .idea/modules/test.iml
> +</module>
이 파일은 .gitignore로 제외시켜야 할 파일 같네요.

2021-02-27 07:06 UTC, sonypark commented
> 그런데, 파일에 마지막 1줄을 비워두더라도, github에서는 그 개행이 안보이는 것이 맞나요?
> 인텔리제이에서는 보이는데 github에서는 보이지 않네요

음 이 부분은 저도 잘 모르겠는데요.  `no newline at end of file` 라는 표시가 없으면 정상적으로 반영이 된 게 아닐까 생각합니다.
![image](https://user-images.githubusercontent.com/34808501/109378414-a2f26200-7915-11eb-8e64-cabfd1d433e0.png)

2021-02-27 07:09 UTC, choitree commented on src/main/java/net/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
조원끼리 리뷰할 때, private으로 변경하라고 해서 바꿨었는데, 
BoardTest 내에서 appendNewLine 메소드 내에서 해당 변수를 사용해서
public으로 다시 바꿨었습니다.
혹시 이런 경우, 새로 변수를 만들어서 appendNewLine에서 따로 사용하고
StringUtils 클래스 내 변수는 private으로 두는게 좋을까요?~

2021-02-27 07:10 UTC, choitree commented on src/main/java/net/tree/pieces/Pieces.java
> +    }
지금 미션5 진행중인데 안그래도 전면 수정이 되는 부분이더라구요!!
해당 내용은 미션5를 통해서 간결하게 만들어보도록 하겠습니다☺️

2021-02-27 07:12 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +    public static final int TOTAL_PIECES_SIZE = 32;
TOTAL_PIECES_SIZE도 BoardTest에서 사용되는 변수라서
public으로 했습니다!
사실 Board 클래스에서는 현재 사용되지 않는 변수인데
그럼 test클래스 내에 변수 선언을 하고 private으로 선언할까요?

2021-02-27 07:14 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +    private List<Piece> blackPieceList = new ArrayList<>();
네네!! 찾아보니 나중에 자료구조를 변경할 경우를 위해서
변수명에 복수를 주로 사용한다는 사실을 알게되었습니다

현재 기능에서는 print 하는 부분만 사용되어서 우선 2개의 리스트로 사용했고, 다음 미션은 2차 배열로 만들어볼까 생각중입니다~
변수명은 변경하도록 하겠습니다!!

2021-02-27 07:16 UTC, choitree commented on .idea/modules/test.iml
> +</module>
gitignore 파일을 gitignore.io 사이트에서 만들었는데, 그러면
현재 있는 파일 내용을 전체 지우고 저에게 맞는 내용을 붙여넣으면 되는걸까요?~

2021-03-01 03:52 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +    }
appendBoard에서 showBoard로 변경했었는데, 
조금 더 고민해보고 보드 자체를 초기화해서 피스가 자기 자리에 위치하기 위한 작업이라서 
createInitializedBoard() 로 변경했습니다~~

2021-03-01 03:58 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +    }
원래 출력하는 메소드를 printBoard() 로 만들고, 그 안에서는 위에 sout내에서 showBoard() 메소드만 호출해서
printBoard() 를 Main에서 호출하는 방식으로 사용했는데, 단순히 구현된 메소드를 sout으로 호출하는 것은 불필요할 수 있을 거 같아서
(이전 리뷰에서 안내받은 내용) print 메소드 자체를 삭제하였습니다.
그리고 Main메소드에서 그냥 System.out.println(showBoard())로 바로 사용했습니다.

sony말씀은 그러면 별도로 출력 기능만 있는 클래스를 만들어서, 
콘솔에 출력이 필요할 때는 그 클래스 내 메소드를 호출해서 사용하는 방식으로 사용하는 것이 좋다는 말씀인가요?~~ 
제가 말씀해주신 내용을 정확하게 이해하지 못해서 여쭤봅니당😶

2021-03-01 04:23 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +        return sb.toString();
enhanced for loop로 변경했습니다!

2021-03-01 04:26 UTC, choitree commented on src/main/java/net/tree/chess/Board.java
> +        return sb.toString();
저도 두 메소드를 하나로 합치려고 했는데, 보드에 피스를 초기화 하는 순서가
appendNewLine("RNBQKBNR") +
appendNewLine("PPPPPPPP") +
blankRank + blankRank + blankRank + blankRank +
appendNewLine("pppppppp") +
appendNewLine("rnbqkbnr"));
위에와 같아서, 호출되는 순서가 달라서 두 메소드로 분리했습니다~~
5단계에서는 한가지 메소드 내에서 호출할 수 있는 방법으로 변경해보도록 하겠습니다!

2021-03-01 04:34 UTC, choitree reviewed
우선 말씀해주신 부분에서 메소드명이나 변수명은 변경하였습니다.
미션5를 구현중인데, 확실히 리팩토링되는 부분이 엄청 많은거같아요
소니의 'Color와 Representation에 대한 enum을 각각 생성해서 Piece 클래스에서 사용하면 어떨까요? ' 이 제안도
미션5에서는 반영되는 부분이더라구요!! 현재 미션에서 변경하려고 했는데, 리팩토링이 되어가고 있는 부분이 지금처럼 남겨두어야
더 잘 보일거같아서, 현재 미션에서는 반영하지 않았습니다.

private 접근제어자로 작성하라고 알려주신 부분은 제가 다른 클래스에서도 변수 호출하는 부분이 있어서 
변경하지 않았는데, 해당 변수는 private으로 두고 새로운 변수를 생성해서 활용하는 것이 좋은 방법인지 모르겠어서 
코멘트로 여쭤보았습니다~~ 확인 부탁드립니다☺️

2021-03-01 04:57 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +    public static final int TOTAL_PIECES_SIZE = 32;
네 테스트코드에서 사용하기 위해 public으로 선언하는건 좋은 방법은 아니라고 생각합니다.
테스트코드는 말 그대로 테스트를 위한 코드이기 때문에, 테스트 코드에서 필요한 변수는 테스트 코드 내에 선언하는게 좋을 것 같네요.

2021-03-01 05:03 UTC, sonypark commented on .idea/modules/test.iml
> +</module>
gitignore.io. 사이트를 이용하신 것은 좋습니다.
gitignore 파일에 추가 되기 전 커밋된 파일들은 아마 추적이 불가능할텐데요.
그 때는 git rm --cached 옵션을 사용해서 더이상 추적하지 않도록 할 수 있습니다.
자세한 내용은 [링크](https://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/)를 참고해주세요

2021-03-01 05:06 UTC, sonypark commented on src/main/java/net/tree/chess/Board.java
> +    }
Stringbuilder를 사용해서 문자열로 파싱하는 부분은 모두 출력 로직이라고 생각합니다.
Board에서는 Pieces 리스트만 반환해주고, 출력 로직은 Main 클래스나 OutputView와 같은 출력을 담당하는 클래스에서 해주는 건 어떨까라는 의미에서 말씀드렸습니다. 아마 미션5에서 구조 변경이 많이 생기실텐데 그 때 고민해보셔도 될 것 같습니다.

2021-03-01 05:07 UTC, sonypark approved these changes
반영해주신 부분 확인했습니다~
추가 코멘트 남긴 부분은 다음 단계하면서 반여해주세요:)

2021-03-01 11:22 UTC, honux77 commented on src/main/java/net/utils/StringUtils.java
> +    public static final String NEWLINE = System.getProperty("line.separator");
테스트 메소드에서 사용하기 때문에 public으로 바꾸는 건 좀 이상한 느낌? test에서만 로컬 변수로 선언해서 쓰면 어떨까요?

2021-03-01 11:24 UTC, merged