[K] 미션 2 체스판 생성
codesquad-members-2021/java-chess pull request #24
Opened 2021-02-09 02:27 UTC by PizzaCola-K

- Pawn() 생성자를 추가했습니다.
  - 인자가 없을 경우 기본으로 흰색 Pawn을 생성합니다.
- 코드 중복을 줄이기 위해서 `public static` 변수로 `BLACK_COLOR`, `WHITE_COLOR` 추가했습니다.
  - 다른 색을 추가할 수 없도록 enum 타입으로 선언하였고, 다른 곳에서 쓸일이 없을 것이므로 private로 선언하였습니다.
  - 그래서 테스트 코드 로직을 조금 수정하였습니다.
- BoardTest를 추가하였습니다.
  - `addPawnToBoard(Board board, Pawn pawn, int size)` 메소드로 코드 중복을 줄였습니다.
    - Pawn pawn: Board에 넣을 Pawn 객체
    - Board board: Pawn을 넣을 Board
    - int size: 넣고 난 후, Board가 가지는 Pawn의 갯수
- Board 객체를 추가하였습니다. `add(Pawn), size(), findPawn(int)` 메소드를 가집니다.
  - add(Pawn) : Board에 Pawn을 추가합니다.
  - size() : Board가 가지고 있는 Pawn의 갯수를 반환합니다.
  - findPawn(int index) : Board가 가지고 있는 index 번째 (0, 1, 2,...) Pawn을 반환합니다.

2021-02-09 13:07 UTC, sonypark reviewed
안녕하세요 K, 리뷰어 소니 입니다.😊
기능 단위로 나누어 커밋을 잘 작성해주신 부분이 인상적이었습니다.👍
커밋 메시지도 잘 작성해주셔서 고민하신 부분을 이해하는데 도움이 되었습니다.
간단한 코멘트 남겼으니 확인 부탁드릴게요!

++
아래 기능 요구사항은 아직 반영 안 된 것 같은데 체크해주세요~
4.추가 테스트
- 체스 판에 Pawn 이외의 객체가 추가되지 않도록 한다.
- 말의 리스트에 new Integer("7")과 같이 Pawn 이외의 객체를 추가해 컴파일 에러가 발생하는지 확인한다.
- 즉, Pawn 이외의 다른 객체를 추가하면 컴파일 에러가 발생하도록 구현해야 한다

2021-02-09 13:07 UTC, sonypark commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
상수의 접근제어자를 public으로 하신 이유가 있을까요??

2021-02-09 13:07 UTC, sonypark commented on src/main/java/pieces/Pawn.java
> +        return color.toString();
Color를 `toString()` 으로 변환해서 반환하는 이유가 무엇인가요?

2021-02-09 13:07 UTC, sonypark commented on src/test/java/pieces/PawnTest.java
>      }
Color의 검증 로직을 테스트 코드에 작성하는 것보다, Color 안으로 넣어보는건 어떨까요? Enum 안에도 메서드를 만들 수 있습니다.
Enum에 대해 공부할 때 참고하시면 좋을 링크 공유드립니다.
[Java Enum 활용기](https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html)

2021-02-09 13:07 UTC, sonypark commented on src/test/java/pieces/PawnTest.java
>          verifyPawn(black);
이미 만들어 놓으신 Enum을 활용하여, 문자열 `white`가 아니라 `Color.WHITE` 로 넣는건 어떤가요?

2021-02-10 01:04 UTC, PizzaCola-K commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
```java
import static org.junit.Assert.*;

import org.junit.Test;

import pieces.Pawn;

public class BoardTest {
    @Test
    public void create() throws Exception {
        Board board = new Board();
        
        Pawn white = new Pawn(Pawn.WHITE_COLOR);
        board.add(white);
        assertEquals(1, board.size());
        assertEquals(white, board.findPawn(0));
        
        Pawn black = new Pawn(Pawn.BLACK_COLOR);
        board.add(black); 
        assertEquals(2, board.size());
        assertEquals(black, board.findPawn(1));
    }
}
```

미션2의 `BoardTest`를 보면 `Pawn`을 생성할 때 `Pawn.WHITE_COLOR`, `Pawn.BLACK_COLOR`를 인자로 받아서 생성합니다. 

일단, 이를 단순히 `String`으로 했다면 이 값을 "Red"나 "Blue"로 하여도 생성이 될 것이라서 `Color` Enum을 만들어서 이를 생성할 때의 인자로 받도록 하였습니다.

그래서 제가 만든 `Pawn`의 생성자는 `Pawn(), Pawn(Color color)` 이렇게 두가지였습니다.

여기서 제가 선택할 수 있는 것은
- `Color` enum을 외부에 공개하는 것
- `Pawn`을 생성할 때 사용할 변수를 공개하는 것

위에 두가지 중 하나입니다. 그래서 제가 선택한 것은
- `Color` enum이 아마도 외부에서 쓰이지 않을 것이라 생각을 하고,
- 작성되어 있는 `BoardTest`의 요구사항을 맞추기 위해서 

`Color` enum을 `Pawn` 내부로 숨겨 `private`로 만들고, `Pawn`을 생성하기 위한 전용 변수 `BLACK_COLOR`, `WHITE_COLOR` 를 만들어 `public static final`로 하여 공개하였습니다.

이 변수들을 `public`으로 하지 않으면 다른 패키지에서 Pawn을 생성할 때 사실상 `Pawn()` 생성자만 사용할 수 있기 때문에 `public`으로 하였습니다.

하지만 미션3을 진행 하다보니 `Color` enum이 `Pawn` 뿐만 아니라 `Board`에서도 쓰는 것이 좋을 것 같아 이후에는 `Color` enum을 `Pawn`의 외부로 옮겼습니다.

2021-02-10 01:22 UTC, PizzaCola-K commented on src/main/java/pieces/Pawn.java
> +        return color.toString();
미션 1의 테스트 코드에서 `getColor()`의 반환값이 `String` 이었습니다. 이를 최대한 유지하기 위해서 `Color` enum 내부의 값인 "black"이나 "white"를 반환하도록 하였습니다.

2021-02-10 01:47 UTC, PizzaCola-K commented on src/test/java/pieces/PawnTest.java
>      }
좋은 자료 감사합니다! 이 코드를 작성할 때는 `Pawn`의 `Color` Enum의 역할을 단순히 `Pawn` 객체를 생성하는 용도로 제한하였습니다. 좀 더 유연하게 생각해보겠습니다.

2021-02-10 01:52 UTC, PizzaCola-K commented on src/test/java/pieces/PawnTest.java
>          verifyPawn(black);
`Color` enum을 외부에서 사용하지 않을 것으로 생각하여 이것을 `Pawn` 객체의 내부에 `private`로 선언하였습니다. 그래서 외부에서 `Color` enum를 사용할 수 없었습니다.

그런데 미션 3를 진행하면서 보니 `Board`에서 `Color` enum을 사용해야 할 것 같아 외부로 옮겼습니다. 하지만 아직 테스트 코드는 `Color` enum으로 접근하지 않습니다.

2021-02-10 03:14 UTC, PizzaCola-K commented
> ++
> 아래 기능 요구사항은 아직 반영 안 된 것 같은데 체크해주세요~
> **4.추가 테스트**
> 
> * 체스 판에 Pawn 이외의 객체가 추가되지 않도록 한다.
> * 말의 리스트에 new Integer("7")과 같이 Pawn 이외의 객체를 추가해 컴파일 에러가 발생하는지 확인한다.
> * 즉, Pawn 이외의 다른 객체를 추가하면 컴파일 에러가 발생하도록 구현해야 한다

체스판에 객체를 추가하는 메소드가 Board.add(Pawn pieces) 라서, Pawn 객체 말고 다른 객체를 추가할 때는 컴파일 에러가 발생합니다. 테스트 코드에 넣으면 전체 컴파일이 되지 않아서 따로 테스트 케이스를 작성하지 않았습니다.

2021-02-10 03:25 UTC, PizzaCola-K commented on src/test/java/pieces/PawnTest.java
>          verifyPawn(black);
그리고 이부분은 미션 1의 기존 테스트 로직 (`String`으로 `Pawn`을 생성하고, 그 색의 `String`을 확인)을 유지하려고 하다보니 이런식으로 작성하게 되었습니다. 이런 경우가 되면 테스트 코드를 수정하는 것이 좋을까요?

2021-02-10 11:53 UTC, sonypark requested changes
K가 남겨준 코멘트를 보면서 어떤 생각을 갖고 코드를 작성했는지 알 수 있어 좋았습니다.
왜 이런 구조를 선택했고 이렇게 코드를 작성했는지 고민하고 정리하는 습관은 아주 좋은 부분인 것 같습니다.👍👍
추가로 코멘트 남겼으니 확인 부탁드립니다.

2021-02-10 11:53 UTC, sonypark commented on src/main/java/pieces/Pawn.java
> +        return color.toString();
미션 1의 테스트 코드는 Enum을 사용하지 않기 때문에 String으로 값 비교를 하고 있습니다. K는 Enum을 사용하셨으니 Enum으로 비교하시면 될 것 같습니다.

```java
assertThat(pawn.getColor()).isEqualTo(Color.WHITE);
```

2021-02-10 11:53 UTC, sonypark commented on src/test/java/pieces/PawnTest.java
>          verifyPawn(black);
네 미션에 있는 예제 코드는 참고용일 뿐이지 구조를 그대로 따라야하는 것은 아닙니다. 더 좋은 구조가 있다면 그렇게 짜는 것이 좋습니다. K가 Enum을 쓴 이유는 Enum의 장점을 이용하려고 하신거라고 생각되는데요. 그럼 기존의 방식보다 더 나은 방식으로 변경하는 것이 바람직하다고 생각합니다. 예제 코드에 너무 얽매이지 않으셨으면 좋겠어요!😊 

그런 의미에서 이번 기회에 Enum을 사용할 때의 장점을 한 번 정리해두시면 좋을 것 같네요!
컬러를 "white", "black"이라는 문자열이 아니라 Enum으로 관리하면 어떤 장점이 있을까요?

2021-02-10 11:53 UTC, sonypark commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
Enum의 장점 중 하나는 재사용성에 있습니다. 상수를 열거형 자료형으로 만들어 놓음으로써 여러곳에서 가져다 사용할 수 있어 편리한데요. Color라는 Enum이 Pawn 클래스에서만 사용되지 않고 다른 클래스에서도 사용될 것을 고려하여 외부로 뺀 후 사용하는 것을 고려해보세요. 그렇게 되면 Pawn 내부의 상수는 더 이상 필요없을 수도 있겠죠? 바로 Enum에 정의된 상수 값을 사용해도 되니까요! 어떤 구조로 변경하면 좋을지 생각해보시면 좋을 것 같습니다😊

2021-02-10 13:09 UTC, PizzaCola-K commented on src/test/java/pieces/PawnTest.java
>          verifyPawn(black);
만약 String을 생성자로 받았다면, 객체 내의 상수를 이용하더라도, 외부에서 "Blue"나 "Red", 심지어 "asdf"와 같은 String을 이용하더라도 객체를 생성할 수 있었을 것입니다. 그런 의미에서 Enum으로 관리하면 그 종류를 제한할 수 있어서 장점이 있습니다.

[Java의 날짜와 시간 API](https://d2.naver.com/helloworld/645609)
또한 Java 초기의 Date, Calendar API에서도 드러났던 문제이지만, 공통으로 사용하는 상수를 int와 같은 너무 범용적인 타입의 변수로 지정했을 때, 
```
calendar.add(Calendar.SECOND, 2); 
```
에서 Calendar.SECOND 대신 Calendar.JUNE과 같은 값을 넣어도 문제점을 찾기 어렵습니다. 이러한 것도 enum을 활용하면 메서드를 잘못 사용하는 경우를 줄이는 등의 이점이 있을 것입니다.

2021-02-10 13:19 UTC, PizzaCola-K commented
요청사항 확인하고 수정하여 정리하였습니다.
Enum에 대해서도 좀 더 정리해볼 수 있어서 좋았습니다.

좋은 리뷰 감사드립니다!

2021-02-11 03:44 UTC, sonypark approved these changes
잘 반영해주셨네요. 수고하셨습니다!👍

2021-02-13 02:25 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
저는 조금 다르게 생각했는데요. Color 는 다른 클래스에서도 사용되는구나.  별도로 분리할까? 어떤 클래스에서 사용되지?
피스들에서만 사용되는군. 필요한 시점에 피스라는 클래스로 바꿔야겠다. 그러면 color는 Piece에서만 사용되겠구나.
뭐 이런식으로 생각했던 것 같아요.

2021-02-13 02:27 UTC, honux77 commented
💯 수고 많으셨어요!

2021-02-13 02:27 UTC, merged

2021-02-15 09:10 UTC, sonypark commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
네 저도 호눅스와 생각한 흐름은 같았습니다! 다만 Color를 특정 클래스 내부에 두기보다는 piece라는 패키지를 만들어 해당 패키지 안에 만드는 게 어떨까? 라고 생각했습니다. piece 패키지 안에 다양한 piece 클래스들이 있고 piece클래스들이 패키지내의 Color를 사용하는 방식으로! 😄

2021-02-15 11:47 UTC, PizzaCola-K commented on src/main/java/pieces/Pawn.java
> +    public static final Color BLACK_COLOR = Color.BLACK;
[Thread.State](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html)

Thread의 State Enum을 보고서 Pawn의 내부에서만 사용한다면, Color Enum도 내부에 넣는 것이 좋겠다 라고 생각을 했었습니다. 이전에 봤던 것이 생각의 폭을 좁히는 것 같습니다.