[시온] 미션 2: 체스판 생성 제출합니다.
codesquad-members-2021/java-chess pull request #26
Opened 2021-02-09 02:49 UTC by ehdrhelr

안녕하십니까.

코드스쿼드 2021 마스터즈 백엔드 과정 Shion 입니다.

- Pawn 기본생성자에서 다른 생성자를 호출해서 color에 "white"값을 할당해주었습니다. 기본생성자에서 바로 값을 할당해주는 것과 비교해서 어떤 것이 더 나은 방법인지는 더 공부해봐야 할 것 같습니다.
- BoardTest 클래스에서 전역변수를 3개 사용했는데(Board board, int index, int size) 보기에 썩 좋지 않은 것 같아서 더 나은 방법을 모색해봐야 할 것 같습니다.
- BoardTest에서 학습 차원에서 여러 애노테이션을 사용해보았습니다. 조금 과하다고 생각하실 수도 있을 것 같지만 너그럽게 봐주시면 감사하겠습니다!

코드 리뷰 부탁드립니다.

감사합니다!

2021-02-09 14:05 UTC, wheejuni requested changes
안녕하세요, 리뷰어 브라이언입니다. 첫 리뷰를 통해 만나뵙게 되어 반갑습니다. 💯 
간단한 수정 사항 몇 가지를 제안드렸습니다. 살펴보시고, 의문나는 점은 언제든지 댓글로 재질문 부탁드려요. 감사합니다!

2021-02-09 14:05 UTC, wheejuni commented on src/main/java/chess/pieces/Pawn.java
> +    public static final String WHITE = "white";
👍

2021-02-09 14:05 UTC, wheejuni commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals(++size, board.size()),                  // board에 pawn이 추가되었으므로 size를 먼저 1 증가시킨 후에 연산한다.
명시적으로 `1` 이라고 조건을 주면 될 것 같은데요,
`size` 가 분리돼야 할 이유가 있었나요?

2021-02-09 14:05 UTC, wheejuni commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals(pawn, board.findPawn(index++))          // index는 0부터 시작하므로 먼저 연산한 후에 1 증가시킨다.
여기서도 `board.findPawn(1)` 로 하는게 더 직관적일 것 같습니다.
`index` 가 늘어날 이유가 있나요? 앞으로 그런 변경이 예상된다 하더라도, 지금 이 코드의 반면을 보면,
그런 변경을 예상해 미리 대응할 이유는 없어 보입니다. `index` 와 `size` 가 분리되기까지의 고민하셨던 부분들을 알고싶네요.

2021-02-10 04:05 UTC, ehdrhelr commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals(++size, board.size()),                  // board에 pawn이 추가되었으므로 size를 먼저 1 증가시킨 후에 연산한다.
테스트가 @ValueSource 애노테이션에 지정된 배열의 크기만큼 반복되기 때문에 명시적으로 1을 지정하면 2번째 테스트부터는 올바른 테스트 결과를 가져올 수 없어서 size변수를 선언하여 관리하였습니다!

배열의 크기를 바꾸었을 때 대응하고자 변수로 관리하였는데, 브라이언의 리뷰를 보고 곰곰이 생각해보니 board에 흰색pawn과 검은색pawn, 각각 1개씩 두개만 넣는다고 가정해서 size를 변수로 관리하지 않고 명시적으로 1 또는 2로 조건을 주는게 오히려 가독성이 더 좋을 것 같다는 생각이 들었습니다 ㅎㅎㅎ

2021-02-10 04:13 UTC, ehdrhelr commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals(pawn, board.findPawn(index++))          // index는 0부터 시작하므로 먼저 연산한 후에 1 증가시킨다.
오늘 호눅스 수업에서도 브라이언이 리뷰해주신 부분에 대한 질문을 했었는데, 예상되는 변경사항에 미리 대응해서 코드를 작성하기 보다는 현재 문제를 해결할 수 있는 코드를 작성하는게 우선인 것 같습니다...!

하드코딩을 하지 않으려는 생각에 index와 size로 관리했는데, 코딩을 하다 중복이 발생하면 그때 해도 늦지 않은 것 같네요 :)

2021-02-10 12:52 UTC, wheejuni approved these changes
👍

2021-02-10 12:53 UTC, merged