Mission1
codesquad-members-2021/java-chess pull request #39
Opened 2021-02-09 08:37 UTC by rla36

미션 1 입니다!
git 사용이 익숙치 않아서 커밋이 지저분한데
미션2부터는 깔끔하게 해보겠습니다

2021-02-09 22:58 UTC, kyu-kim-kr reviewed
안녕하세요 Jung! 저희는 한번도 같이 팀해본적이 없네요. 같이 2021 마스터즈 코스에서 공부하고 있는 Kyu라고합니다!

2021-02-09 22:58 UTC, kyu-kim-kr commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
안녕하세요.
혹시 Pawn 클래스에서 선언하신 변수들을 사용하지 않고
이 메소드에서 다시 변수를 선언하셔서 사용하신 이유가 있으신가요?

2021-02-09 22:58 UTC, kyu-kim-kr commented on src/Test/java/Chess/PawnTest.java
> +    }
밑에 만드신 메소드 `verifyPawn()`을 사용하시면 코드의 중복을 줄일 수 있을거 같아요 😊

2021-02-10 01:28 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
안녕하세요?!! 큐님 처음 뵙네요ㅎㅎ
3.리팩토링에 "white", "black" 문자에 대한 중복을 제거하기 위해 create() 메소드에 local variable을 추가한다. 
->이 요구사항 만족하려고 지역변수로 선언한 것인데 제가 잘못 이해한 건지 한번 생각해봐야할 것 같아요! 
create()에 선언된 white, black는 테스트용으로 Pawn생성자의 매개변수로 집어넣을 스트링이고 이것이
pawn의 getColor로 호출된 W, B와 일치하는지 확인하는 것이 테스트 목적이라 따로 선언한 것 같아요!

2021-02-10 01:31 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +    }
넵넵 verifyPawn() 만들기 이전, 이후 버전을 따로 커밋해서 변경사항을 반영하려했는데 잘 안됐나봐요.. 다시 시도해보겠습니다 감사합니다 큐!

2021-02-10 02:36 UTC, kyu-kim-kr commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
아 미션1에 다시 들어가서 확인해보니까 jung 말이 맞는거 같아요ㅎㅎ
미션2에 들어가니까 미션진행하면서 create()에 만든 변수를 옮겨라고 적혀있네요!

2021-02-10 05:20 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
네네 저도 지금보니까 
미션2 동시에 진행하면서 pawn 클래스에  final string W, B  선언한 걸 
미션1 커밋에 포함시켰네요 어휴 
말씀해주셔서 감사해요!

2021-02-10 05:36 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +import static org.junit.Assert.assertEquals;
5번째 라인의 "import static org.assertj.core.api.Assertions.*;"를 임포트했는데도 assertThat()메서드 사용시 오류가 발생해서 6번째 라인에서 "import static org.junit.Assert.assertEquals;" 를 추가적으로 임포트했습니다. 
assertThat 사용할때 Assertions.assertThat()와 같이 앞에 클래스명 추가해주면 오류가 사라지는데, 그럼 5번째라인에서 스태틱 임포트한 의미가 무엇인지 모르겠어서 일단 6번째 라인을 추가했습니다.
무슨 문제인지 해결되면 코멘트 추가하겠습니다! (조언해주시면 감사하겠습니다.)

2021-02-10 11:52 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
ㅎㅎ 좋은 상호 피드백이군요.

2021-02-10 11:53 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +    }
이 부분 커밋 해주세요~

2021-02-10 12:13 UTC, ksundong requested changes
안녕하세요! **Jung**!! 저는 디온이고, 리뷰로 만나뵙게되어 반갑습니다! 첫 PR 축하드려요~🥳
아쉽지만 이 PR은 변경할 부분이 많아서 처음부터 다시 작업하시는 것이 좋을 것 같다는 의견을 조심스레 드려봅니다.(코드상의 문제는 아닙니다. 파일을 되돌리고, 커밋을 다시 작성하시는 것이 학습단계에서 어려우실 것 같아서 그렇습니다.)

## 변경 의견

- `build.gradle`은 필수적인 파일입니다. 이 파일이 없으면, 제대로 동작하지 않습니다. 현재단계에서 빌드 툴에 대해서 학습하시긴 벅찰 것 같아서, 그냥 되돌려 두시는 것을 추천드립니다.
- 전반적으로 커밋 메시지가 좀 더 자세하면 좋겠다는 의견 역시 드립니다.
- PR을 작성하실 때, 이 코드를 작성하시면서 들었던 의문점, 중점적으로 리뷰받고 싶은 내용 등을 작성해주시면 좋습니다. (조금 더 상세하면 좋겠다는 의견 드립니다.)

코멘트 참고하셔서 해당부분도 반영부탁드립니다.

작업하느라 고생 많으셨고, 어려움이 많이 따르셨을 것 같습니다. 😭
궁금하신점 Comment 남겨주시고, 해당 부분 변경이 어려우시면 슬랙의 `Dion`에게 DM 주시거나 동료들과 함께 해결해주세요.

고생하셨습니다!

2021-02-10 12:13 UTC, ksundong commented on build.gradle
> -}
이건 지우시면 안될 것 같은데요~

2021-02-10 12:13 UTC, ksundong commented on .idea/misc.xml
> -</project>
이 파일을 지워주신 이유는 무엇일까요?

2021-02-10 12:13 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;      //-> 임포트했더니 테스트 에러나던 것 단번에 해결?!
띠용? 왠지 인텔리제이 내장 JUnit이 들어간 느낌인데...
뭔가 잘못된 것 같습니다.

2021-02-10 12:13 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +    public void create() {
DisplayName이 테스트의 내용을 제대로 전달하고 있지 않습니다. 흰색 폰과 검은색 폰 모두 생성해주고 있네요.
마찬가지로 `create()`라는 메서드 명은 테스트 내용을 제대로 전달하고 있지 않네요.

2021-02-10 12:13 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +        String b = "black";
되도록이면 명확한 네이밍을 해주세요. w보다는 white가 b 보다는 black이 나을 것 같습니다.

2021-02-10 12:13 UTC, ksundong commented on src/main/java/Chess/Pawn.java
> +    public static final String B = "black";
접근제어자에 대해서 학습해보시고, 이 코드가 무슨 문제가 있을지 고민해보세요.
또, `W`, `B` 같은 변수명은 좋지 않다고 생각합니다.

2021-02-10 12:13 UTC, ksundong commented on src/main/java/Chess/Pawn.java
> +    public static final String B = "black";
그리고, color가 `""` 과 같은 문자열이 들어와서 문제가 발생할 수 있을 것 같은데 이를 어떻게 해결할 수 있을까요?
`enum`에 대해서 학습해보시기 바랍니다!

2021-02-10 12:13 UTC, ksundong commented on src/main/java/Chess/Pawn.java
> +    public Pawn(){     this("white");}
포맷팅에 신경써주세요!
또, 기본 생성자를 정의할 때, 기본값으로 "white"를 직접 입력해주셨는데, 작성하신 상수 `W`를 사용하시면 되겠죠?

2021-02-10 15:29 UTC, rla36 commented on build.gradle
> -}
안녕하세요 디온님? 자세한 코멘트 감사드려요ㅜ 
제가 미션을 완료한 후에 커밋을 단 한번 하면 된다고 착각하고 있었어서 커밋이 몇개 없고 자세하지도 않습니다.. 저도 뒤늦게 깨닫고 아쉬움이 많았는데 디온님 말씀대로 이번에 한 PR은 밀어버리고 신규 브랜치 생성해서 최대한 세세하게/자세하게 커밋한 후 미션1 PR 다시해보려고 합니다..

2021-02-10 15:30 UTC, rla36 commented on build.gradle
> -}
build.gradle 에 코멘트 주신 것에 대해선, 제가 git add filename 해서 스테이지에 올린 적이 없는 파일인데 갑자기 PR에 나타나서 잘못 추가된 것으로 알고 삭제했어욬ㅋㅋ쿠ㅜ 아래 .idea/misc.xml 파일도 마찬가지입니다.

2021-02-10 15:35 UTC, rla36 commented on build.gradle
> -}
코멘트 남겨주신 부분 모두 반영해서 코드 수정 후 커밋하고 다시 PR하겠습니다 이 PR은 새로운 미션1 PR 보낸 후에 Close pull request 해주시면 감사하겠습니다!

2021-02-10 16:23 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;      //-> 임포트했더니 테스트 에러나던 것 단번에 해결?!
import org.junit.Test;    임포트 전에는 테스트코드 run하자 terminated, failed to start라고 뜨던 것이 import org.junit.Test;  임포트하고 나서 테스트코드 전부 pass됩니다. 
무엇이 문제인지 모르겠지만 일단 테스트코드 구동되니까 일단 지금은 임포트하고 추후에 공부하겠습니다 ..ㅎㅎ 아는 것이 많지 않아 어디를 건드려야 해결될 문제인지 감이 잡히지 않네요ㅜㅜ org.junit.Test 임포트하지 않고도 테스트 구동되는 방법 아시면 알려주시면 감사하겠습니다ㅜㅜ

2021-02-10 16:36 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;      //-> 임포트했더니 테스트 에러나던 것 단번에 해결?!
build.gradle 지우셔서 발생하는 문제입니다.
그냥 돌아가면 되는게 아니라 현재 단계에서 익혀야 할 부분이기 때문에 코멘트를 남겼어요.

일단 각 IDE에는 JUnit이 내장되어있습니다. 하지만 그 버전은 JUnit4 버전이고, 구버전입니다.

사용상에 문제는 없지만, 현재 교육과정의 목표는 JUnit5의 학습입니다. 따라서 우리는 JUnit5를 어떻게 추가해주는지도 알아야합니다.

build.gradle 파일의 변경사항을 보시면,JUnit5관련 의존성이 보이실겁니다. (의존성은 이 프로젝트가 해당 프로젝트를 필요로 한다는 의미입니다.)
이 부분을 제거해주셨기 때문에, 코드는 동작하지 않을겁니다.

'왜 안될까?'를 생각해보세요. 다른사람은 되는데 나는 안되는거면 자신의 환경이 다른사람과 동일한지도 체크해보세요. 대다수는 이 환경 설정이 잘못되었기 때문에 발생합니다.

급하게 진행하지 마시고, 차례차례 이해하면서 천천히 Jung의 페이스대로 진행해주세요. 학습과 이해를 도와드릴게요.😊

2021-02-10 16:41 UTC, ksundong commented on build.gradle
> -}
네 천천히 Jung 속도대로 작업해주세요.
너무 급하실 필요는 없습니다. 현재 단계를 잘 해내시면 앞으로도 문제 없으실 거에요.
그리고 지금 다 못 끝내시더라도 리뷰 계속해드릴테니까 학습할 수 있는 내용은 다 학습하시고 넘어갑시다!

2021-02-10 18:46 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;      //-> 임포트했더니 테스트 에러나던 것 단번에 해결?!
넵 감사합니다! 그런데 build.gradle을 삭제한 것은 mission1과 상관없다고 착각해서...^^ 리뷰어분께 안보이도록 mission2 진행하던 것들과 함께 삭제한 것이고요 업스트림 동기화와 상관있는진 모르겠는데 여기서 삭제했는데도 제 인텔리제이에선 build.gradle 파일 그대로 남아있습니다! 그래서 build.gradle 파일이 없어서는 아닐 것 같습니다ㅜㅜ
말씀해주신 환경설정 때문에 삽질 정말정말 많이 하고 있습니다ㅜ 코딩보다 더 많이 하고 있습니다.. 다른분들 코드 참고하면서 무엇이 문제일까 좀 더 탐구해보겠습니다!

2021-02-11 02:10 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;      //-> 임포트했더니 테스트 에러나던 것 단번에 해결?!
아마 다른 분들도 같은 문제 겪으셨는데, 해결하셨던 것 같아요.
때로는 동기들에게 도움을 받아보는 것도 좋을 것 같네요. 힘내세요!

2021-02-11 06:14 UTC, ksundong commented
#58 PR이 오픈되어 이 PR을 Close 합니다.
다음에는 직접 Close 해주세요~

2021-02-11 06:14 UTC, closed without merging