[Kyu] 미션 2: 체스판 생성 완료
codesquad-members-2021/java-chess pull request #46
Opened 2021-02-09 19:22 UTC by kyu-kim-kr

안녕하세요.

설명이 필요할 거 같은 부분은 각 커밋에 작성했습니다.

감사합니다.

2021-02-10 14:03 UTC, sonypark reviewed
안녕하세요 Kyu, 리뷰어 소니 입니다.😊
요구사항대로 깔끔하게 잘 작성하셨네요.
현재는 크게 문제는 안 되지만 생각해보면 좋을 부분에 대해 피드백 남겼으니 확인 부탁드립니다~

2021-02-10 14:03 UTC, sonypark commented on src/test/java/net/honux/chess/pieces/PawnTest.java
> +    }
`verifyPawn` 메서드에는 assertJ 라이브러리를 사용하셨고 `create_기본생성자()`메서드에서는 junit의 assert문을 사용하셨는데 특별한 이유가 있을까요?
편한 것을 사용하시되 통일성있게 작성해주시면 좋을 것 같습니다.

2021-02-10 14:03 UTC, sonypark commented on src/test/java/net/honux/chess/pieces/PawnTest.java
> +    }
추가적으로 하나의 테스트에서 여러개의 assert문을 사용할 경우 발생할 수 있는 문제점도 함께 알고 사용하시면 좋을 것 같아요.
자세한 내용은 [링크](https://github.com/codesquad-members-2021/java-chess/pull/23#discussion_r572844078) 참고 부탁드릴게요:)

2021-02-10 14:03 UTC, sonypark commented on src/main/java/net/honux/chess/Board.java
> +
컬렉션을 선언할 때 위와 같이 ArrayList로 선언하는 것과 List로 선언하는 것은 어떤 차이가 있을까요?
당장은 모르셔도 되지만, 중요한 부분이니 공부해보시면 좋을 것 같아요!

참고 링크
- [java - Polymorphism: Why use "List list = new ArrayList" instead of "ArrayList list = new ArrayList"? - Stack Overflow](https://stackoverflow.com/questions/9852831/polymorphism-why-use-list-list-new-arraylist-instead-of-arraylist-list-n)
- [ArrayList or List declaration in Java - Stack Overflow](https://stackoverflow.com/questions/12321177/arraylist-or-list-declaration-in-java)

2021-02-11 23:07 UTC, kyupid commented on src/test/java/net/honux/chess/pieces/PawnTest.java
> +    }
> verifyPawn 메서드에는 assertJ 라이브러리를 사용하셨고 create_기본생성자()메서드에서는 junit의 assert문을 사용하셨는데 특별한 이유가 있을까요?

특별한 이유는 없고 루카스의 예제 코드를 그대로 가져왔던 거 같습니다. 

AssertJ 가 뭔지 JUnit 이 뭔지 몰라서 서치를 좀 해봤는데요.

AssertJ는 JUnit 의 Assertion 을 보완하기 위해 (가독성을 높이기위해?) 나온 라이브러리 라고 생각했습니다.
그래서 AssertJ 라이브러리를 가져왔다면, assert문을 쓸때 JUnit 보다는 AssertJ 걸 써야겠다고 생각했습니다.

이따가 AssertJ 를 사용해서 통일성있게 코드를 수정하겠습니다.

2021-02-11 23:07 UTC, kyu-kim-kr commented on src/main/java/net/honux/chess/Board.java
> +
언급하신 링크들 잘 읽었습니다.

무슨 말인지는 알겠으나, 아직 상속 관계에 대한 이해가 부족해서 정확하게 이해하진 못했습니다.

상속에 대해서 다시 한번 학습해야 할 것 같습니다.

감사합니다!

2021-02-12 08:09 UTC, sonypark approved these changes
수고하셨습니다. 
다음 미션 진행해주세요~!💪

2021-02-12 09:02 UTC, jihye-woo commented on src/main/java/net/honux/chess/Board.java
> +
@sonypark 인지를 못하고 지나갔던 부분인데 덕분에 알게되었습니다!😮
그리고 공유해주신 링크 참고하면서 [ArrayList와 LinkedList를 어떤 상황에 써야하는지도](https://stackoverflow.com/questions/322715/when-to-use-linkedlist-over-arraylist-in-java/24607151#24607151) 한 번 더 짚고 넘어갈 수 있었습니다

감사합니다!🙇‍♀️

2021-02-14 05:16 UTC, honux77 commented
@kyu-kim-kr 충돌이 발생하면 머지할 수 없어요. 충돌해결해 주세요.

2021-02-14 05:16 UTC, honux77 requested changes
충돌해결 요망

2021-02-14 06:25 UTC, kyu-kim-kr commented
### 충돌에 대한 해결 시도1

step1 에서 생성된 브랜치 step2 입니다.
이전 PR에서 step1 은 마지막 수정 후 merged 되었고,
step2 에선 변경된 step1이 적용되지 않았다고 생각했습니다.
그래서 변경이력을 적용하기 위해 수동으로 변경된 코드만 동기화시키고 push 했으나 여전히 충돌이 일어났습니다.

### 시도 2

[여기](https://planbs.tistory.com/entry/Git-Pull-request%EC%97%90%EC%84%9C-%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94-%EC%B6%A9%EB%8F%8C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0) 를 참고해서 upstrem/kyu-kim-kr 의 변경사항을 step2 브랜치로 가져오기 위해서
git checkout step2
git pull upstream kyu-kim-kr
명령어를 통해 변경사항을 가져왔으나 여전히 충돌이 일어났습니다.

아직 해결중입니다.

2021-02-14 19:52 UTC, kyu-kim-kr commented
#### 원인
step2가 충돌이 일어났다. 뭐가 원인인지 전혀 알 수가 없다. PawnTest에서 충돌이 난다고해서 충돌이 난 이유를 생각해봤다. 충돌난 이유는 step1이 merged 되고 upstream/kyu-kim-kr 가 업데이트 되었는데 로컬에는 upstream의 변경사항이 적용되지 않아서이라고 생각했다.
#### 충돌 발생 그림으로 이해하기
>_**그림1**_
>![](https://images.velog.io/images/kyukim/post/b6ab92e5-417d-4325-9666-0d077356c893/2021-02-15_07-37-30.jpg)

1. local에서 step1은 C3지점에서 PR을 날렸다.
2. PR을 날리고 step2를 추가해서 다른 기능을 C6까지 구현했다.
3. 그런데 PR을 날린 step1에서 리뷰어가 기능을 수정/추가를 요구했다.
4. C7, C8 기능을 수정/추가 했다.
5. 리뷰어가 approved 해서 최종적으로 step1이 upstream으로 merged 되었다.
6. **이 시점 혹은 그 이전에 step2 또한 PR을 날렸었는데 conflict 발생한다.**

#### 추측
추측하기전에 local의 step1은 더 이상 필요없으므로 삭제한다. 

1. merged 되었을 때 upstream의 main 브랜치는 C8을 가리키고 있을 것 같다. 따라서, o/main도 C8을 가리키고 있다.
2. local의 main을 upstream과 동기화하기 위해서 `git pull` 명령어로 변경사항을 가져온다.
3. 그러므로, local의 main 또한 C8을 가리키게 된다. 그림으로 나타내면 아래 그림 2와 같을 것이라고 예상한다.

>**_그림 2_**
>![](https://images.velog.io/images/kyukim/post/975e78d3-67de-47e8-8e91-552fd38a9cff/2021-02-15_07-59-13.jpg)

#### 문제 해결하기
>**_그림 3_**
>![](https://images.velog.io/images/kyukim/post/d7fba59c-d8e7-43ed-9165-36221e571b74/%EC%A0%9C%EB%AA%A9%20%EC%97%86%EB%8A%94%20%EA%B7%B8%EB%A6%BC%20(16).png)

기본적으로 Pull Request는 내가 작업한 **하나의** 브랜치를 베이스 저장소의 **하나의** 브랜치로 pull (fetch & merge) 하는 것이다. 따라서, upstream의 줄기는 여러 갈래로 나뉘어지는게 아니 한줄기가 되어야 할 것이다. 그림들에서 그냥 upstream이라고 했지만 upstream/kyu-kim-kr 부분을 생략했던 것이다.

그래서 위에있는 그림 2에서 push하면 하나의 줄기가 아니라 C3부터 갈라져 나오는 여러 갈래의 줄기가 될것이다. 그래서 conflict 나는 것이다.

이 문제를 해결하려면 rebase를 통해 local의 커밋을 아래 그림 4와 같이 정리해주면 문제가 해결될 것이라고 본다.

>**_그림 4_**
>![](https://images.velog.io/images/kyukim/post/8fcdfccb-752c-4d54-822c-97bd3b614a26/2021-02-15_08-19-50.jpg)

---

위와 같이 생각하고 실제 터미널에서 이것저것 시도해봤는데 여전히 conflict 나서 그러는데,
혹시 upstream에 step1까지 merged 된거 가져와서 미션 2 다시해도 될까요?

2021-02-15 06:57 UTC, honux77 commented
@kyu-kim-kr 충돌 해결하기!

2021-02-15 07:02 UTC, closed without merging

2021-02-15 09:21 UTC, sonypark commented
@kyu-kim-kr upstream에 merge를 하면 **merge 커밋**이 하나 생기는데요. 로컬 step2 브랜치에서 upstream의 merge 커밋을 pull 받아와야 충돌이 해결 될 것 같네요. 로컬 step2 브랜치에서 upstream을 pull 받은 후 push 하면 해결 될 것 같습니다. upstream을 pull 받을때도 아마 충돌이 날 것 같아요.([여기](https://github.com/codesquad-members-2021/java-chess/pull/46#issuecomment-778734810)서 변경된 부분을 직접 수정하신 부분에서 충돌이 발생할텐데 이거 해결하고 push 하시면 됩니다.) - upstream에 이미 반영된 부분을 수정했으니 충돌이 나는 건 자연스러운거에요~~