[yeon] 미션2: 체스판 생성
codesquad-members-2021/java-chess pull request #51
Opened 2021-02-10 08:18 UTC by kimnayeon0108

안녕하세요! yeon입니다. 미션 2단계 체스판 생성 구현하고 리뷰 요청합니다 😊
아래에 각 클래스별 필드와 메서드를 설명드리겠습니다.

 1. 체스판에 해당하는 **Board 클래스**
- pawns : Pawn 타입의 객체만 담을 수 있는 ArrayList를 만들었습니다.
- add() : 인자로 받은 pawn을 ArrayList에 담는 기능을 합니다.
- size() : ArrayList의 크기를 반환합니다.
- findPawn() : 인자로 받은 숫자의 위치에 해당하는 Pawn 객체를 반환합니다.

2. **BoardTest 클래스**
- Pawn 타입의 전역변수 white, black 를 추가했습니다.
- 체스판에 해당하는 전역변수 board 를 추가했습니다.
- check() : 예상되는 크기(size), 해당 Pawn 타입 객체의 반환이 예측되는 index값 그리고 Pawn타입의 객체를 인자로 넣어서
객체를 board에 추가한 뒤, board 메소드의 반환값과 같은지 비교하는 메소드입니다.
- create() : check()메서드를 넣어서 테스트합니다.

3. **Pawn 클래스**
- 기본생성자 추가: 기본생성자로 생성된 객체는 white 색을 갖도록 합니다.
- WHITE, BLACK: white, black 의 string 값을 갖는 상수를 추가했습니다.

4. **PawnTest 클래스**
- create_기본생성자() 메서드 추가: 기본생성자로 객체 생성시 객체의 color가 white인지 확인해주는 코드를 작성했습니다.

여기까지 미션2를 구현했습니다.
귀한 시간 내서 코드리뷰 해주셔서 감사합니다!

2021-02-10 12:20 UTC, wheejuni commented
안녕하세요 @kimnayeon0108 . 
코드 컨플릭트가 발생했네요. 왜 이런 현상이 발생했을까요? 그리고 어떻게 해소할 수 있을까요? 
_이 PR을 닫지 않고_ 컨플릭트를 해결하는 방법에 대해 고민해 주시고, 컨플릭트를 해결해 주세요. 
리뷰는 그 다음에 진행할게요.

2021-02-10 14:48 UTC, kimnayeon0108 commented
upstream의 제 브랜치를 pull 해서 인텔리제이에서 파일(코드) 수정후 커밋을 진행하니 컨플릭트를 해결한듯 합니다!

2021-02-10 14:49 UTC, wheejuni commented
@kimnayeon0108 잘하셨어요! 혼자 해결하시다니 대박

2021-02-10 14:52 UTC, kimnayeon0108 commented
@wheejuni 뿌듯하군요! 사실 아직도 merge, rebase 등의 개념이 완벽히 잡히진 않았지만 이런 과정을 통해 점점 알게되는거 같습니다 ㅎㅎ 
덕분에 또 배웠습니다!

2021-02-10 14:55 UTC, kimnayeon0108 commented
PR 하기 전에 upstream의 제 브랜치를 rebase 해주었는데 왜 충돌이 발생했는지 잘 모르겠습니다...

2021-02-10 15:07 UTC, wheejuni commented
@kimnayeon0108 PR하기전에 브랜치를 rebase한 것은 상황과 무관할 것 같고, 작업하신 브랜치가 언제 분기되었느냐가 중요할 것 같아요.
제가 보기엔 rebase하기 전에 step2 브랜치를 만드시고 작업하셨을 것 같거든요.
그래서 conflict가 발생했고... upstream에는 이미 rebase가 돼 있으니까, 이걸 당겨서 merge한 걸로 컨플릭트가 해결된 거고요.
어렵죠? ㅋㅋㅋ 이해가 잘 안되어도 괜찮습니다. 일단 컨플릭트를 해결한 것만으로도 의미가 있어요. 밤늦게 수고 많으셨어요.

2021-02-10 15:19 UTC, kimnayeon0108 commented
@wheejuni 이해가 잘 안되긴 하지만 더 고민해보겠습니다ㅠㅠ 감사합니다~!🙌

2021-02-10 15:21 UTC, wheejuni commented
@kimnayeon0108 네, 왜 그럴까요?

2021-02-10 15:22 UTC, kimnayeon0108 commented
@wheejuni 왜 그런지는 잘 떠오르지 않네요 ㅠㅠ 늦은시간까지 도와주셔서 감사합니다!!!

2021-02-11 04:03 UTC, kimnayeon0108 commented
@wheejuni 업스트림을 리베이스를 하지않고,
새로운 브랜치를 생성하면 PR을 머지한것이 로컬의 새로운 브랜치에 반영되지 않아서 충돌이 일어난다고 생각합니다.

앞으로 리뷰를 받기 전에 새로운 미션을 수행하느라 브랜치를 생성하고, 리뷰을 받은 후에 리베이스를 할텐데 그럼 이때마다 충돌이 불가피한것이 맞나요...? PR전에 충돌을 해결면 되는것 맞나요??

2021-02-11 05:28 UTC, wheejuni commented
@kimnayeon0108 PR 전, 최신화된 업스트림이 작업한 브랜치에 반영되면 되지 않을까요? 그러면 컨플릭트가 발생하지 않을 것 같아요. 보통 "선 머지 후 PR" 이라고들 많이 하는데요, 업스트림 -> 작업 브랜치 방향의 머지를 한번 해주면 컨플릭이 나지 않을 것 같은데... 이해가 되시나요?

2021-02-11 05:34 UTC, wheejuni requested changes
컨플릭트때문에 밤 늦게까지 고생하시고 수고 많으셨습니다. 
간단한 개선 의견 드렸는데, 확인해주세요!

2021-02-11 05:34 UTC, wheejuni commented on src/main/java/chess/Board.java
> +    private ArrayList<Pawn> pawns = new ArrayList<>();
타입을 `List`로 해 주세요. 
앞으로 코드를 작성하실 때, 구체적인 구현 클래스보단 인터페이스에 의존하는 방향의 코드를 작성하고자 노력해보면 좋겠어요. 

https://medium.com/better-programming/code-against-interfaces-not-implementations-37b30e7ab992 

아직 어려운 글일 수 있는데 읽어보시는 것도 추천해요. 

지금 단계에서 이해하기 쉽지 않은 개념이겠지만, 학습 초반부에 잘못된 습관이 들 수 있어 리뷰합니다. 

```suggestion
    private List<Pawn> pawns = new ArrayList<>();

2021-02-11 05:34 UTC, wheejuni commented on src/main/java/chess/pieces/Pawn.java
> +    public static final String BLACK = "black";
👍👏🙌🏿

2021-02-11 05:34 UTC, wheejuni commented on src/test/java/chess/BoardTest.java
> +    Pawn white, black;
한 줄에 하나의 변수만 선언하는 것을 원칙으로 해 주세요. 

```suggestion
    private Pawn white;
    private Pawn black;
```

2021-02-11 10:27 UTC, kimnayeon0108 commented
> @kimnayeon0108 PR 전, 최신화된 업스트림이 작업한 브랜치에 반영되면 되지 않을까요? 그러면 컨플릭트가 발생하지 않을 것 같아요. 보통 "선 머지 후 PR" 이라고들 많이 하는데요, 업스트림 -> 작업 브랜치 방향의 머지를 한번 해주면 컨플릭이 나지 않을 것 같은데... 이해가 되시나요?

아 이해했습니다! 감사합니다😀

2021-02-11 11:57 UTC, kimnayeon0108 commented on src/main/java/chess/Board.java
> +    private ArrayList<Pawn> pawns = new ArrayList<>();
감사합니다! 보내주신 링크도 읽어보았는데 지금은 명확히 이해가 되진 않지만 나중에 한번 더 읽어보겠습니다~

2021-02-11 11:58 UTC, kimnayeon0108 commented on src/test/java/chess/BoardTest.java
> +    Pawn white, black;
네에! 앞으로 한줄에 하나의 변수만 선언하도록 하겠습니다

2021-02-11 12:09 UTC, wheejuni approved these changes
👍

2021-02-11 12:09 UTC, merged