[Bat] Mission2- 체스판 생성 완료
codesquad-members-2021/java-chess pull request #52
Opened 2021-02-10 08:39 UTC by kjk402

안녕하세요. 웹백엔드과정 Bat입니다.

하기와 같이 미션2 구현하여 pull request 드립니다.

• mission2 summary
--------------------------------------
- Pawn 생성 시 ArrayList에 담을 수 있도록하였습니다.
- Pawn을 Board에 생성 시 Board의 Size와 Board의 특정 index(idx)를 활용하여 테스트를 하였습니다.
- WHITE, BLACK 순으로 생성, TEST 내용을 @DisplayName에 담았습니다.
-첫번째 Test에서 코드의 중복이 있어 verifiBoard 메서드를 생성하여 중복을 제거하였습니다. 
-@BeforeEach 을 붙여서 테스트 실행 전에 Board를 한번만 선언합니다.
--------------------------------------
• 지난 미션에서의 개선점
mission1에서 필요없는 파일까지 올렸으나 이번에는 git add '파일명' 을 사용하여 개선하였습니다.

• mission2을 완료 후 인지한 점.
다시 확인 해보니 commit 수가 적고 commit 메시지가 많이 간결한 것 같습니다. 
더욱 자주, 자세히 commit하겠습니다.

감사합니다.

2021-02-10 15:21 UTC, SANGCO reviewed
bat님 안녕하세요, 리뷰어 상코입니다.
작성하신 코드에 대해서 코멘트를 남겼습니다. 
확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-02-10 15:21 UTC, SANGCO commented on src/main/java/net/kjk402/chess/pieces/Pawn.java
> +    }
두 개의 생성자가 접근 제한자가 다르네요?
어떤 의도의 코드인지 궁금합니다~

2021-02-10 15:21 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +    public void create(){
일관성 있게 여기도 public 접근 제한자를 제거 하는게 어떨까요?
(JUnit5에서는 테스트 클래스나 메서드에 public을 붙이지 않아도 됩니다.)

2021-02-10 15:21 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        verifyBoard(Pawn.BLACK,2,1);
콤마(,) 뒤에는 공백을 삽입해야 합니다.
IntelliJ에 Reformat code 옵션을 찾아서 설정 해보는건 어떨까요.

2021-02-10 15:21 UTC, SANGCO commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
> +    public void create_기본생성자() throws Exception {
여기도 접근 제한자 관련 위와 동일한 피드백 입니다.

2021-02-10 15:21 UTC, SANGCO commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
>      public void create(){
여기도 접근 제한자 관련 위와 동일한 피드백 입니다.

2021-02-10 15:21 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +}
IntelliJ 설정을 찾아서 적용해 보아요.
[How to make IntelliJ IDEA insert a new line at every end of file?](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)
[파일 끝에 개행을 추가해야 하는 이유](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)

2021-02-10 16:02 UTC, SANGCO reviewed
추가로 리뷰 남깁니다~

2021-02-10 16:02 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        assertEquals(pawn, board.findPwan(idx));
assertAll()에 대해서 학습하고 적용해 보는건 어떨까요~
[JUnit 5 소개](https://javacan.tistory.com/entry/JUnit-5-Intro) (링크에 assertAll() 부분 참고해 주세요.)

2021-02-10 16:02 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +    @DisplayName("흰색폰 넣은 다음 검은색폰을 넣는다.")
Bat님 다른 개발자가 이 @DisplayName만 보고 이 테스트가 어떤 테스트인지 딱 알 수 있을까요?
좀더 구체적으로 어떤 테스트인지 설명하면 더 좋을거 같은데 어떻게 생각하시나요~

2021-02-10 16:02 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +    public void create(){
@DisplayName이 있더라도 메서드 이름을 딱보면 이 메서드가 무슨 일을 하는 메서드구나 하고 알 수 있으면 좋지 않을까요?
이 테스트 메서드의 기능이 create 일까요?

2021-02-10 16:02 UTC, SANGCO commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
>      public void create(){
여기도 메서드 명이 create() 이네요~

2021-02-14 09:16 UTC, kjk402 commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        verifyBoard(Pawn.BLACK,2,1);
해당 옵션 윈도우 기준 Ctrl + Alt +L 으로 동작되는 것 확인하였습니다. 
감사합니다.

2021-02-14 09:21 UTC, kjk402 commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
>      public void create(){
상기 접근제한자 관련 피드백들 확인 후 public 제거 완료하였습니다.
JUnit5의 @Test 에서는 클래스나 메서드에는 public을 따로 선언해주지 않아도 된다는 점 확인하였습니다. 
감사합니다.

2021-02-14 09:25 UTC, kjk402 commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
>      public void create(){
@DisplayName 과 메서드명을 조금 더 자세하고 구체적으로 명시하도록 하겠습니다.
특히 메서드명 선언시에는 중복까지 잘 확인하도록 하겠습니다.

감사합니다.

2021-02-14 09:32 UTC, kjk402 commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +}
올려주신 링크 참고하여 Intellij에서 설정해줬습니다.

2021-02-14 09:40 UTC, kjk402 commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        assertEquals(pawn, board.findPwan(idx));
assertAll(
                () -> assertEquals(expectedSize, board.size()),
                () -> assertEquals(pawn, board.findPwan(idx))
        );

2021-02-14 09:46 UTC, kjk402 commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        assertEquals(pawn, board.findPwan(idx));
assertAll  상기와 같이 적용하였습니다.
assertAll을 사용 이전에는 첫번째 테스트에서 오류가 난다면 다음테스트는 진행되지 않았습니다.
제 코드에서는 size확인을 먼저한 후 index를 확인하는 순서인데 size가 맞지 않다면 findPwan은 동작하지 않았는데, assertAll을 적용하고 나서는 일단 전부 테스트 후 틀린 부분만 Comprison Failure 을 통해 보여주는 것을 확인하였습니다.

감사합니다.

2021-02-14 23:46 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +        verifyBoard(Pawn.BLACK,2,1);
네 맞습니다. 단축키도 있답니다.
저 설정은 커밋하기 전에 자동으로 코드를 정렬해 준답니다.

2021-02-15 01:46 UTC, SANGCO requested changes
수정 잘하셨네요~
간단한 리뷰 추가로 남깁니다~

2021-02-15 01:46 UTC, SANGCO commented on src/test/test/net/kjk402/chess/chess/BoardTest.java
> +    void verifyBoard(String color, int expectedSize, int idx) {
BoardTest 클래스 안에서만 사용하는 메서드는 private 접근 제한자가 좋겠죠?

2021-02-15 01:46 UTC, SANGCO commented on src/test/test/net/kjk402/chess/pieces/PawnTest.java
> +    void verifyPawn(final String color) {
접근 제한자 동일한 피드백입니다.

2021-02-15 01:46 UTC, SANGCO commented on src/main/java/net/kjk402/chess/pieces/Pawn.java
> +    }
생성자 접근 제한자는 수정이 안된거 같네요.
질문 있으시면 댓글 남겨주세요~

2021-02-15 05:07 UTC, kjk402 commented
>간단한 리뷰 추가로 남깁니다~
 ㄴ 해당 리뷰 참고하여 수정하였습니다. 감사합니다.

2021-02-15 06:04 UTC, SANGCO approved these changes
고생 하셨습니다~
다음 미션도 화이팅 화이팅

2021-02-15 06:06 UTC, merged

2021-02-15 06:06 UTC, honux77 commented
👍

2021-02-15 06:10 UTC, kjk402 commented
SANGCO 그리고 호눅스 감사드립니다.