[Jung] 미션1 재도전 후 PR 보냅니다
codesquad-members-2021/java-chess pull request #58
Opened 2021-02-11 05:16 UTC by rla36

미션 1 엎고 다시 했습니다. 
이전에는 미션을 모두 완료한 후에 커밋을 단 한번 한 반면, 두번째 시도에선 새로운 기능 구현시마다 커밋하려고 노력했습니다.
이전에 만들었던 파일을 없애는 과정에서 지저분한 커밋이 많이 생겼는데, 감안해서 봐주시면 감사하겠습니다ㅜ

2021-02-11 06:44 UTC, ksundong commented
되도록이면 새로 시작하실 때는 새로운 브랜치를 삭제할 내용이 있는 브랜치 위치에서 따는 것이 아니라 원래 브랜치에서 따주세요!
![image](https://user-images.githubusercontent.com/38597469/107608634-e1ceb980-6c7f-11eb-95a9-964b78550f59.png)

요 이미지 상에서 Jung이 기존에 하신 작업은 `feature/1` 이라고 가정한다면, `feature/2` 브랜치를 새로 만들어서 작업해주시는게 더 낫습니다!

2021-02-11 07:02 UTC, ksundong requested changes
Jung! PR 잘 봤습니다. 고생 많이 하셨어요.👍
커밋메시지 작성은 충분합니다. 깔끔하고 의미가 잘 전달되게끔 단계별로 잘 작성해주셨네요.
PR에는 궁금했던 점, 해결하고 싶은 점, 고민거리들 같은 질문 거리들을 준비해주시면 더 좋습니다. (없으시면 안하셔도 됩니다.)

## 리뷰

- `gitignore`에 대해서 한 번 알아보세요.(필수 x)
- `gradle`이 어떤 것인지, 의존성이 무엇인지, 어떤 의존성이 우리 프로젝트에 필요할지 고민해보세요.(필수x)
- **접근 제어자**에 대해서 공부해보시고 수정해주세요.(필수)
- JUnit4가 아니라 JUnit5를 사용할 수 있도록 해봅시다.(필수)

구현사항은 만족해주셨지만, 다른 분들하고 같은 환경에서 학습하실 수 있도록 JUnit5 사용을 유도하고 있어서 부탁좀 드릴게요! 혼자 프로젝트 하실 때에는 JUnit4를 쓰셔도 문제는 없는데, 최근에는 JUnit5를 사용하는 추세로 넘어가고 있어서 JUnit5를 학습하시는게 더 좋을 것 같아요.
거기에 접근 제어자(access modifier)도 조금만 신경 써주시면 좋을 것 같습니다!

고생하셨습니다!! 파이팅!! 💪

2021-02-11 07:02 UTC, ksundong commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="corretto-1.8" project-jdk-type="JavaSDK" />
이런 파일은 `.gitignore`에 등록해주시는 편이 좋습니다!
한 번 학습해보세요!

2021-02-11 07:02 UTC, ksundong commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.6.2'
```suggestion
    implementation 'ch.qos.logback:logback-classic:1.2.3'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testImplementation 'org.assertj:assertj-core:3.11.1'
```

로 변경해보세요.
중복된게 너무 많습니다.

2021-02-11 07:02 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;
이 부분 정말 해결 안되시면 트러블 슈팅하는거 Zoom으로 도와드릴게요!

2021-02-11 07:02 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +    public void createPawnsByColor(){
읽기 좋네요. 좋습니다! 💯

2021-02-11 07:02 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +    }
외부에서는 `verifyPawn`을 사용할 일이 있을까요?
제 생각에는 내부에서만 쓰일 메서드이기 때문에 `private`을 사용하는게 더 좋을 것 같은데요!

2021-02-11 07:02 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +    }
중복 제거는 잘 하셨어요! 👍

2021-02-11 07:02 UTC, ksundong commented on src/main/java/Chess/Color.java
> +}
`enum` 의 사용 좋습니다. 👍

2021-02-11 07:02 UTC, ksundong commented on src/main/java/Chess/Pawn.java
> +    Color color;
**접근제어자**에 대해서 한 번 공부해주세요.
어떤 부분이 문제가 될 수 있는지, 왜 `default(package-private)` 접근제어자를 사용하면 안되는지에 대해서도 관심가져보시면 좋을 것 같아요.

2021-02-11 07:02 UTC, ksundong commented on src/main/java/Chess/Pawn.java
> +    }
위와 동일합니다! **접근제어자** 에 대해서 신경써주세요!

2021-02-11 07:02 UTC, ksundong commented on src/main/java/Chess/Color.java
> +}
앗... 커밋 하실 때 잘못 커밋하셨나봐요.

2021-02-12 07:43 UTC, rla36 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="corretto-1.8" project-jdk-type="JavaSDK" />
gitignore 공부해보겠습니다 감사해요! 

위 깃 브랜치 생성 관련해서 이미지 파일 첨부해주신것 도움 많이 됐어요! 
main으로 switch(checkout)한 후에 새로운 브랜치 생성해야 하는 모르고 기존에 작성하던 브랜치에서 switch해버렸네요 ㅋㅋ ㅜㅜ 갈아엎은 파일들이 커밋 목록에 남아있는게 영 보기 싫었는데 다 삭제해버린 커밋부터 rebase로 메인에 갖다붙일수있을지 공부해봐야겠습니다. 감사합니다!

2021-02-12 07:43 UTC, rla36 commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.6.2'
넵

2021-02-12 07:44 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;
아 화면 공유로 알려주시면 정말정말 감사하겠습니다 제 능력 밖이에요 이거는 ㅋㅋㅋ ㅜㅜ

2021-02-12 07:47 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +    }
접근제어자 공부를 더 해야할것같습니다! 메서드나 변수 선언할때 클래스, 패키지, 상속클래스의 내부/외부에서 쓰일 일이 있을지 생각해보고 접근제어자를 결정해야하는데 일단 public으로 선언하면 편하니까 그렇게 한 것 같네요 항상 메서드/변수의 쓰임 위치를 고민해봐야할 것같아요  지적 감사합니다!

2021-02-12 07:49 UTC, rla36 commented on src/main/java/Chess/Color.java
> +}
네네 파일 변경부분은 빠지고 생성한 것만으로 잘못 커밋됐네용.. 이후 커밋에서 수정됐습니다!

2021-02-12 09:01 UTC, ksundong commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="corretto-1.8" project-jdk-type="JavaSDK" />
rebase는 안되구, cherry pick을 하셔야합니다.
이 부분도 공부를 해보셔야 할 거에요!

2021-02-12 09:01 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;
가능하신 시간 알려주시면 줌으로 도와드리겠습니다~

2021-02-12 10:09 UTC, ksundong commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.6.2'
@rla36
제가 조금 수정한 부분이 있는데, 이미 logback관련 코드가 있어서 추가했습니다.

2021-02-12 10:33 UTC, ksundong commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;
![image](https://user-images.githubusercontent.com/38597469/107757642-2b470380-6d69-11eb-998d-ba335bca20dc.png)
이렇게 한 번 바꾸고 해보시겠어요? jupiter로 바꿔주시고 해보세용!

2021-02-13 14:24 UTC, rla36 commented on src/Test/java/Chess/PawnTest.java
> +import org.junit.Test;
말씀하신 것 둘 다 intellij IDEA로 설정했는데도 Test가 안돌아가네요..
![image](https://user-images.githubusercontent.com/74045466/107844416-79fea700-6e16-11eb-9873-5481d4c68eb7.png)

import org.junit.Test를 주석처리 한후 Test가 Terminate된 모습
![image](https://user-images.githubusercontent.com/74045466/107844463-eed1e100-6e16-11eb-96a4-0f279d6b26d7.png)

주석처리 해제하고 Test잘 돌아가는 모습
![image](https://user-images.githubusercontent.com/74045466/107844483-07da9200-6e17-11eb-88ab-0422bd161a59.png)

2021-02-13 16:11 UTC, rla36 commented on src/main/java/Chess/Pawn.java
> +    Color color;
Color 접근 제어자 private으로 수정했습니다! default로 두면 같은 패키지 내의 다른 클래스에서 변경되는 문제가 있을 것 같습니다.

2021-02-13 16:21 UTC, closed without merging