[노을] 미션 2: 체스판 생성
codesquad-members-2021/java-chess pull request #60
Opened 2021-02-12 07:30 UTC by sanhee

안녕하십니까!
2021 코드스쿼드 백엔드 과정에 참여중인 `노을` 입니다.

미션2(체스판 생성)를 구현하게 되어, 코드 리뷰를 부탁드리게 되었습니다.

귀한 시간 내주셔서 감사합니다.

새해 복 많이 받으세요!

<br>

### 참고사항
- 컴파일 에러를 내는  테스트케이스는 주석처리를 하였습니다 (총 2개)

  >1. 체스 판에 Pawn 이외의 객체가 추가되지 않도록 한다.
  >2. Pawn클래스 생성시 약속되지 않은 문자일 경우, white를 지정한다.

- 영작을 잘못해서 커밋 메시지를 한글로 작성하였습니다.
- 일관된 커밋 메시지를 작성하지 못하였습니다.

2021-02-12 09:34 UTC, jihye-woo commented on src/main/java/net/sanhee/chess/Pawn.java
enum을 사용하시는 경우라면, color 값의 유효성을 검증하는 코드를 UnitColor enum으로 보내는건 어떨까요?
예를 들면 아래 코드처럼요!
```java
public static UnitColor getUnitColor(String color) {
        switch (color.toLowerCase()) {
            case "white":
                return UnitColor.WHITE;
            case "black":
                return UnitColor.BLACK;
            default:
                throw new IllegalArgumentException("error message");
        }
    }
```
enum에 대해 아직 잘 모르긴 하지만..!😂 Color와 관련된 책임을 UnitColor enum이 맡게되면 좋을 것 같다는 생각에서 조심스럽게 의견을 내봅니다..🙋‍♀️

2021-02-12 09:49 UTC, wheejuni requested changes
안녕하세요, 리뷰어 브라이언입니다. 2단계를 진행하시느라 고생 많으셨습니다. 💯 
우선 커밋 메세지를 우리말로 작성하는 것은 전혀 문제되지 않습니다. 저도 현업에서 코드를 작성하고 커밋할 때, 우리말로 커밋메시지를 작성하는 것을 선호합니다. 

커밋 메세지에 대해서 너무 고민하지 마시구요, 간단한 리뷰사항 두 가지 남겼습니다. 확인해주세요~

2021-02-12 09:49 UTC, wheejuni commented on src/test/java/BoardTest.java
> +    */
사용하지 않는 코드는 그때그때 지우는 것을 기본 원칙으로 해 주세요.
나중에 필요해지면 그때 가서 이 코드가 살아있던 시점으로 시간여행을 하면 됩니다. git으로 관리되고 있어서요.

2021-02-12 09:49 UTC, wheejuni commented on src/test/java/BoardTest.java
> +    static public Board board = new Board();
`static` 을 선택한 이유를 알고 싶어요.

2021-02-12 16:25 UTC, sanhee commented on src/test/java/BoardTest.java
> +    */
리뷰 감사합니다 👍 

브라이언이 말씀하신 사항, 반영하여 GitHub에 push를 하려고 하는데 아래와 같이
reject가 일어났습니다.

![](https://i.imgur.com/WFdHsQg.png)

## 타임라인
- 0번째는 첫번째 push를 하기전에 작업한 내역입니다.

0. step1 브랜치를 사용하지 않는 것 같아 git branch -d step1 을 통해 제거 하였습니다.
1. git pull 후 push 를 다시 했지만 여전히 reject 였습니다.
2. 검색 후 git pull --rebase 를 알게돼, 다시 push 해보았지만 역시 reject 였습니다.
3. 마지막 시도로는, git pull –allow-unrelated-histories 옵션을 추가 한 뒤, push를 진행했더니 reject 없이 진행되었습니다.
- [참고링크_깃(git) pull 명령 후 non-fast-forward 문제 해결방법](https://devlog.jwgo.kr/2018/03/09/resolving-git-pull-problem/)

다만 최종적으로, pull request 에 왔더니, commit이 엄청나게 쌓여있는 것을 확인할 수 있었습니다..
아직 Git에 대해 많은 공부를 하지 않아 정확하게는 모르겠지만 pull을 많이 진행했던 탓인것으로 추정되는데 맞을까요??

2021-02-12 16:32 UTC, sanhee commented on src/test/java/BoardTest.java
> +    static public Board board = new Board();
Board 객체를 static으로 선언한 이유는
모든 Pawn 객체가 공유하는 변수라고 생각해서 지정하였습니다.

```java
@Test
    @DisplayName("흰색 Pawn을 체스 판, 첫번째 칸에 추가")
    public void create() throws Exception {
        spawnPawn(UnitColor.WHITE, 1);
    }

    @Test
    @DisplayName("흑색 Pawn을 체스 판, 두번째 칸에 추가")
    public void create2() throws Exception {
        spawnPawn(UnitColor.BLACK, 2);
    }

```


와 같이 연속적으로  Pawn을 놓는다고 생각했기 때문에 Board 정보가 공유되어야 각 객체간 위치정보가 꼬이지 않을거라고 생각했습니다.

2021-02-13 00:06 UTC, wheejuni commented on src/test/java/BoardTest.java
> +    static public Board board = new Board();
`@Test` 애노테이션이 붙은 메소드는 완전히 독립적인 환경에서 각각 실행된다고 생각하는 것이 맞습니다.
(지금 단계에서 학습하실 내용은 아니지만, 실제로 독립적인 환경에서 각각 실행되고, 심지어 순차실행도 보장되지 않습니다.)
따라서 각 `@Test` 메소드간에 정보가 공유된다는 설계는 조금 나쁜 것 같고요. 
@BeforeEach 나 @AfterEach 같은 생명주기 훅을 사용해서 그때그때 변수를 초기화하는 방법이 더 좋은 설계라고 생각합니다.

2021-02-13 00:34 UTC, wheejuni commented on src/test/java/BoardTest.java
> +    */
pull을 많이 진행했던 것이 문제가 아니라 `-allow-unrelated-histories` 옵션을 추가한 바람에 양쪽 브랜치의 공통 커밋이 필터되지 못해 같은 내용을 담은 커밋이 다른 커밋 hash로 한번씩 다 새로 올라간 것입니다. 

제가 정확한 로컬 커밋 상황을 알 수 없어 정확한 트러블슈팅을 해드리기는 어렵겠네요. 향후 비슷한 문제가 다시 발생한다면 알려주세요. 

@honux77 혹시 의심가는 원인이 있으신가요?

2021-02-13 02:44 UTC, honux77 commented on src/test/java/BoardTest.java
> +    */
메시지 그대로 내 커밋이 원격 커밋보다 뒤에 있는 것이 직접적인 원인입니다.  (근본 원인은 저도 잘 모르겠어요 ㅎㅎ)
무작적 2번을 하는게 아니라 저장소 전체 상태를 그래프로 보고 어떤 커밋들이 빠져있는지 확인한 후 다양한 방법을 사용해서 그 커밋들을 가져와야 합니다. 

가장 의심가는 원인은 브랜치를 생성할 때 무관한 곳에서 시작되어서 pull로 못 가져온게 아닐까? 싶군요.

2021-02-14 04:34 UTC, merged

2021-02-14 05:31 UTC, sanhee commented on src/test/java/BoardTest.java
> +    */
보잘 것 없는 질문에 두 분이나 답변해주셔서 너무 감사합니다!! 😆

제가 아직 Git의 커밋을 잘 다루지 못하고, 커밋 그래프를 보지 못해서 현재로서 문제파악은 못하지만, 오늘 학습하면서 말씀하신 사항들 체크하고 다음 PR때 반영해보도록 하겠습니다. 😁

시간 내주셔서 감사합니다!!
남은 연말 잘 보내세요!

2021-02-14 05:38 UTC, sanhee commented on src/test/java/BoardTest.java
> +    static public Board board = new Board();
테스트 케이스 마다, 
Boar 객체가 새롭게 생성 돼서, 임시방편으로 문제 해결을 위해 static으로 선언을 했던건대
@Test는 개별적인 환경에서 돌아가서 그랬던거군요!
거기에 순차 실행이 보장되지 않는다는 것도 너무 충격이네요..

오늘 @BeforEach와 @AfterEach 애노테이션 학습한 후 다음 PR때 리뷰 반영해서 적용하도록 하겠습니다!

개선사항 말씀해주셔서 감사합니다.👍