[Bongf] 미션 2 : 체스판 생성
codesquad-members-2021/java-chess pull request #61
Opened 2021-02-13 08:12 UTC by bong6981

안녕하세요! 코드스쿼드 백엔드 Bongf입니다. 
- 지난 피드백을 받고 merge되어 피드백 반영한 내용도 함께 작성했습니다 
- 코드를 작성한 다음 다른 분들이 받은 피드백을 참고하여 코드를 수정했습니다 (커밋 메시지 Fix로 시작되는 부분입니다) 
- Pawn에 다른 객체가 추가되지 않도록 한다 부분은 new Integer("7")로 수행하여 컴파일 에러가 발생하는지 확인하였고 이에 대한 코드는 삭제하였습니다. 
- 가장 어려웠던 부분은 test끼리는 독립적이어야한다는 부분이었습니다. 
    -  학습한 바로는 하나의 테스트당 하나의 로지컬한 컨셉만 테스트하게하라 였는데
    -  board에 pawn을 생성하고 board의 size를 확인하는 부분과 인덱스로 pawn을 찾는 부분이 한 번에 수행되어야 했기 때문에 다른 분들이 받은 피드백을 보고 assertAll로 바꾸었으나 이것이 어쨌든 다른 기능을 확인하는 부분인데 분리해줘야 하지 않을까 고민했습니다 
    - 또, 이전까지는 ParameterizedTest로 돌렸을 때는 white, black 같이 각각의 test 결과가 나왔는데, 이를 없애니 이를 확인할 수 없어 고민했습니다. 
- 워낙 많이 부족하고 아예 개념을 잘못이해하서 삽질하는 고민이 아닌가 하는 생각이 들었지만 나름 긴 시간 동안 고민했는데 답을 찾지 못해 해당 사항을 남겨둡니다.   
코드 리뷰 감사하다는 말씁 드립니다!

2021-02-14 03:12 UTC, LarryJung reviewed
수고하셨습니다. 요구사항대로 작 작성해주셨지만, 보면서 질문들을 몇가지 남겨드렸네요.^^ 확인 부탁드리고 답글로 소통하시지요!

2021-02-14 03:12 UTC, LarryJung commented on src/main/java/chess/Board.java
> +    private List<Pawn> board = new ArrayList<>();
pawn list 멤버 변수 이름으로 board 는 맞지 않는 것 같습니다. 이미 Board 클래스의 인스턴스에도 board라는 이름을 쓸 것인데 (테스트코드를 보면..) 

```suggestion
    private List<Pawn> pawns = new ArrayList<>();
```
로 수정해주세요. ㅎㅎ

2021-02-14 03:12 UTC, LarryJung commented on src/main/java/chess/Board.java
> +    }
접근제어자를 default로 두신 이유가 있으신지요?

2021-02-14 03:12 UTC, LarryJung commented on src/main/java/pieces/Pawn.java
> +    private final Color color;
final 키워드를 붙이면 어떤 장점이 있을까요? (단점도 있을까요?)

2021-02-14 03:12 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +    }
요 테스트코드는 다른 이유가 아니라면 private으로 선언하는게 나을 것 같네요!

2021-02-14 03:12 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +    void addPawnOnTheBoardAndVerify(Pawn pawn, int i) {
메서드 네이밍은 아마 평생.. 고민이 되실건데 그냥 저라면(저도 아직도 이름정할 때 고민이 많네요..) 
`addPawnVerify` 정도로 하고 넘어가지 않을까 싶기도 하네요 ㅎㅎ

메서드, 변수, 클래스, 인터페이스 등 각종 네이밍 컨벤션은 어떻게 되고 어떻게 지으면 적절할 지 많이 고민해보시고 찾아보시면 도움 많이 되실 거에요

2021-02-14 03:12 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +                () -> assertThat(board.findPawn(i - 1)).isEqualTo(pawn)
제 생각엔 테스트코드에 '로직'이 들어간 느낌인데요! 
`findPawn(i - 1)` 이 1을 넣으면 0번째것을 꺼내는 것을 보니..  빼기 1 해주는 '로직'은 findPawn 메서드 안으로 들어가야 더 적절할 것으로 보입니다.

2021-02-14 03:12 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +    void createPawnOnTheBoard() throws Exception {
throws Exception은 어떻게 붙게 되었을까요?

2021-02-14 03:12 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +    void addPawnOnTheBoardAndVerify(Pawn pawn, int i) {
그리고.. 로지컬한 묶음이라는 것은 생각하기 나름일 수도 있습니다. 

pawn 을 추가하는 기능을 테스트한다.
-> 넣었을 때 사이즈가 늘어난다 & 넣은 것을 정확히 찾아낼 수 있다.

요렇게 생각을 하셨다면 특별히 분리할 필요는 없어 보이네요 ㅎㅎ

2021-02-15 07:11 UTC, honux77 requested changes
리뷰어 코멘트 보고 개선해 주세요~

2021-02-15 07:44 UTC, bong6981 commented on src/main/java/chess/Board.java
> +    private List<Pawn> board = new ArrayList<>();
네! 제가 해당 미션의 내용을 잘못이해하여 멤버 변수 명을 잘못 지은 것 같습니다.  말씀 주신 사항으로 수정했습니다!

2021-02-15 07:44 UTC, bong6981 commented on src/main/java/chess/Board.java
> +    }
우선 접근제어자는 최대한 좁게 설정하고 필요시 확장하라고 학습하여 학습내용을 적용해보았습니다! 아직 Board의 메서드들이 다른 패키지에서는 쓰이지 않아 default로 두었습니다!

2021-02-15 07:46 UTC, bong6981 commented on src/main/java/pieces/Pawn.java
> +    private final Color color;
final 키워드를 붙이면 상속 및 재정의를 막을 수 있다 (변경을 막을 수 있다)라고 학습했습니다. 여기서는 상수 정의에 사용했기 때문에 생성시에 색을 할당했다면 재할당이 불가능한 것으로 이해하고 적용했습니다. 장점은 다른 곳에서 색을 바꾸려고 할 때 막을 수 있다는 점이고 단점은 혹 코드를 작성하다가 색을 바꿔야 하는 기능들을 구현할 수 없다는 단점을.. 생각해 보았습니다!

2021-02-15 07:47 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +    }
네!  해당 Boardtest 클래스 안에서만 사용되어 private으로 바꿨습니다! 놓치고 있었네요.

2021-02-15 07:48 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +    void addPawnOnTheBoardAndVerify(Pawn pawn, int i) {
말씀주신 네이밍 이름이 더 적합한 것 같아 해당 이름으로 변경했습니다. 네이밍 컨벤션에 대해 공부해보겠습니다! 로지컬한 묶음에 대한 고민이 많았는데 이렇게 생각하면 되는 군요! 감사합니다

2021-02-15 07:52 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +                () -> assertThat(board.findPawn(i - 1)).isEqualTo(pawn)
이 피드백을 받고 test 코드에 로직을 넣으면 그 또한 버그를 만들어 낼 수 있기 때문에 지양해야 한다는 사실을 알았습니다.  

다만 미션에서 findPawn 메서드 자체가 미션의 'Pawn을 추가할 때마다 목록을 얻어와 추가한 Pawn을 정상적으로 가지는 것을 확인한다.' 부분에서  해당 인덱스를 넣고 리스트에 pawn이 잘 들어가 있는지 확인해야 한다고 이해했습니다. 해서 새로 커밋한 바와 같이 아예 number(폰의 갯수), index(list에서 pawn이 들어가야 할 자리)로 두 개의 매개변수를 받아 넘겨주는 것으로 수정했는데 어떠실지 문의드립니다.

2021-02-15 07:57 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +    void createPawnOnTheBoard() throws Exception {
생각없이 예제 코드를 따라하다 보니 해당 부분이 들어간 것 같습니다. ㅠㅠ
-Exception은 모든 예외의 최고조상이다.
-보통 메서드에 예외를 선언할 때에는 메서드 내에서 발생할 수 있는 (일반적으로 필수처리예외만 적는다) 예외를 명시해준다. 
-메서드를 사용하려는 사람들은 이 메서드의 선언된 예외를 보고 어떤 예외가 발생할지 예측할 수 있다. 
라고 다시 학습했습니다. 
다만, 지금 이 코드에서 제가 생각할 수 있는 필수처리 예외를 찾기 어려워 삭제했습니다!

2021-02-15 07:59 UTC, bong6981 commented on src/test/java/chess/BoardTest.java
> +    void createPawnOnTheBoard() throws Exception {
학습 속도가 느리고 아직 기초도 많이 부족한 편이라 주신 피드백을 보고 학습하고 적용하는 것까지 시간이 오래 걸렸습니다. 자세한 피드백 주셔서 감사합니다!

2021-02-15 08:19 UTC, bong6981 commented
안녕하세요. 학습 속도가 느리고 아직 기초도 많이 부족한 편이라 주신 피드백을 보고 학습하고 적용하는 것까지 시간이 오래 걸렸습니다. 자세한 피드백 주셔서 감사합니다!

말씀 주신 피드백 반영했습니다. 
 - 미션 내용 자체를 잘못 이해해  잘못  네이밍한 변수명 board를 pawns로 수정
 - BoardTest 내에서만 쓰이는 메서드에 대해 private으로 선언 
 - 추천주신 메서드명(addPawnVerify)으로 수정, 네이밍 컨벤션 더 학습 필요 
 - 이해 없이 작성한 코드 throws Exception을 삭제. 
     - 현재에는 처리할 예외를 발견하지 못해 해당 부분 삭제 
 - test에 로직이 들어가는 것을 지양해야 한다는 것을 배웠으며, 이에 따라 test안의 로직 삭제 
     - 다만 findPawn() 자체가 해당 리스트에 pawn이 잘 들어갔는지 확인하는 기능이라 해당 인덱스로 찾아야 한다고 생각하여 인덱스에 해당하는 부분을 매개변수로 넣어줌 
 
그 외 질문주신 내용 
- Board클래스의 접근제어자를 default로 설정한 이유
    -  학습과정에서 최소한으로 접근 제어자를 설정해두고 필요시 확장한다고 배워, 다른 패키지에서 아직 사용된 일이 없어 디폴트 패키지로 설정 
- final 키워드를 붙인 장점 
   -  한 번 값이 할당되면 다른 곳에서 변경할 수 없도록 방지 
   -  단점은 혹시 색상을 바꿔야할 기능이 필요하다면 이 기능을 위해 다른 멤버 변수를 선언하는 등 다른 방법으로 접근해야 함 (검색으로 찾지 못해 위와 같이 최대한 생각해보려고 노력해보았습니다) 
으로 정리했습니다.

2021-02-15 16:04 UTC, honux77 commented
최소한의 접근 제어자 = private 입니다 ㅎㅎ. 특별한 이유 없으면 클래스는 public, 멤버는 private을 염두에 두세요.

2021-02-15 16:05 UTC, honux77 approved these changes

2021-02-15 16:05 UTC, merged

2021-02-16 09:09 UTC, LarryJung commented on src/test/java/chess/BoardTest.java
> +    void createPawnOnTheBoard() throws Exception {
넵 ㅎㅎ 자바에서는 CheckedException, UnCheckedException 두 부류가 있는데 차이점에 대해서 학습해 보시는 것을 권해드려요~