[MJ]미션2: 체스판 생성
codesquad-members-2021/java-chess pull request #64
Opened 2021-02-14 01:15 UTC by MJbae

안녕하세요 MJ입니다.
미션 요구사항에 따라 구현해보았습니다.

2021-02-14 05:23 UTC, honux77 commented
PR 본문에 했던 작업 내용을 요약하면 더 좋을 것 같아요.

2021-02-14 05:23 UTC, honux77 commented on src/main/java/mj/chess/Pawn.java
> +    private final Color color;
final도 나쁘지 않군요.

2021-02-14 05:25 UTC, honux77 commented
커밋 메시지를 가능하면 구체적으로 적어주세요. 제목만으로 무엇을 했는지 잘 알 수가 없네요.
그리고 커밋에는 Why?를 적어주시는 것이 좋습니다.

2021-02-14 05:27 UTC, honux77 commented on src/main/java/mj/chess/pieces/Pawn.java
> +    public Pawn(String color) {
enum을 사용했으면 생성자도 enum으로 하는 게 좋을 것 같아요.

2021-02-14 05:30 UTC, honux77 requested changes
enum을 사용하면 type safe가 생기는데요. 해당 부분 공부하고  String으로 처리한 부분을 enum으로 바꾸면 좋겠네요.

2021-02-14 05:30 UTC, honux77 commented on src/main/java/mj/chess/pieces/Pawn.java
> +    public String getColor() {
여기도 enum으로 리턴

2021-02-14 05:30 UTC, honux77 commented on src/test/java/mj/chess/BoardTest.java
> +        check_validity_of_pawn(new Pawn(WHITE.name()), 1, 0);
가능하면 스네이크 케이스보다는 카멜 케이스가 자바에 잘 어울립니다.

2021-02-14 05:30 UTC, honux77 commented on src/test/java/mj/chess/BoardTest.java
> +public class BoardTest {
junit5에서 테스트 메소드는 접근제어자 없이 사용하는 게 일반적입니다.

2021-02-15 00:58 UTC, MJbae commented on src/main/java/mj/chess/pieces/Pawn.java
> +    public String getColor() {
enum을 어설프게 공부한거 같아요. 제대로 공부해서 수정해보겠습니다! 리뷰 감사합니다.

2021-02-15 01:01 UTC, MJbae commented on src/test/java/mj/chess/BoardTest.java
> +public class BoardTest {
그렇군요! 적용하겠습니다. 리뷰 감사합니다.

2021-02-15 14:14 UTC, MJbae commented
@honux77 코멘트 남겨주신 부분을 반영해서 리팩토링했습니다~

2021-02-15 15:10 UTC, honux77 commented on build.gradle
> +    implementation 'junit:junit:4.12'
junit4 의존성이 들어갔는데 제거해 주세요.

2021-02-15 15:10 UTC, honux77 commented on build.gradle
> +    implementation 'junit:junit:4.12'
커밋하기 전에 변경사항을 한 번 더 확인해 주는 것도 잊지 마세요.

2021-02-15 15:11 UTC, honux77 commented on src/main/java/mj/chess/Board.java
>      private ArrayList<Pawn> pawns = new ArrayList<>();
앗 이것도 놓쳤는데 `List<Pawn> pawns` 로 선언하는게 일반적입니다.

2021-02-15 15:12 UTC, honux77 commented on src/main/java/mj/chess/pieces/Pawn.java
> +    private final ColorOfPiece color;
Color를 ColorPiece로 바꿨는데 왜 그랬는지는 잘 모르겠네요.

2021-02-15 15:14 UTC, honux77 commented on src/test/java/mj/chess/BoardTest.java
> +    void verifyAddition(Pawn pawn, int size){
테스트 내부에서 사용하는 메소드는 private이 좋을 듯

2021-02-15 15:14 UTC, honux77 approved these changes
enum을 그냥 기존처럼 Color로 선언하는게 더 자연스러워 보입니다.
몇가지 코멘트는 다음 PR에 함께 반영해 주세요.

2021-02-15 15:14 UTC, merged

2021-02-15 16:12 UTC, MJbae commented on src/test/java/mj/chess/BoardTest.java
> +    void verifyAddition(Pawn pawn, int size){
다른 그룹원 리뷰에서 봤던 내용인데도 까먹고 적용을 못했네요... 코멘트 감사합니다.