Mission 1
codesquad-members-2021/java-chess pull request #66
Opened 2021-02-14 13:36 UTC by MyungWanPark

미션1의 Pawn class와 PawnTest class를 만들었습니다!

2021-02-14 14:39 UTC, ksundong requested changes
안녕하세요! Wan 리뷰로 처음 만나뵙게되어 반갑습니다. 리뷰어 디온입니다.
몇가지 리뷰와, 코멘트를 남겨드렸습니다. 해당 부분에 대한 질문이 생기시면 질문 남겨주세요.
그리고, 변경이 완료되시면 리뷰어로 저를 재등록 해주시면됩니다.(꼭 안하셔도 됩니다.)

## 리뷰

- PR 제목에 닉네임을 붙여주세요.
- PR 내용을 조금만 더 상세히 작성해주세요. 의문점이나 궁금한점, 미션을 진행하면서 학습한 내용을 간단하게 정리해주셔도 좋습니다. (이는 학습에 도움이 되기 위함이고, 실무에서는 다른 형식으로 PR을 작성합니다.)
- 접근 제어자에 대해서 반드시 학습해주시고, 코드에 반영해주세요.(필수)
- JUnit5에서는 테스트 메서드에 `public` 접근 제어자는 붙이지 않는것이 일반적입니다. 지켜주세요!
- 한 번 우리가 의도한 값만 들어올 수 있을지 생각해주세요.(Pawn 생성자)
- 메서드 명은 명확하게 지어주는 습관을 들여주세요.
- 중복이 되지 않는다면, 일단은 테스트 코드에서 메서드를 추출할 필요는 없습니다.

고생많으셨습니다! 조금만 다듬어주시면 바로 다음단계 진행하셔도 될 것 같습니다!

2021-02-14 14:39 UTC, ksundong commented on src/main/java/Pawn.java
> +    String color;
**접근 제어자**에 대해서 학습해주세요!
이 클래스는 잠재적으로 같은 패키지의 다른 클래스가 존재할 경우 속성이 변경될 여지가 있습니다.
가급적이면 속성은 감추고 이를 접근할 수 있는 메서드를 만들어주는 편이 좋습니다.

2021-02-14 14:39 UTC, ksundong commented on src/main/java/Pawn.java
> +    }
color가 우리가 의도한 값만 들어올 것이라고 예상할 수 있을까요?
가급적이면 우리가 의도한 값만 들어올 수 있도록 해주는 편이 안전합니다.
`enum`에 대해서도 한 번 공부해보세요!

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +    }
JUnit5에서는 테스트 클래스, 테스트 메서드(`@Test`가 붙은 메서드)에는 `public`을 붙여주지 않는 것이 일반적입니다.

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +    }
메서드 명에도 신경써주세요. `create()`라는 테스트 메서드명은 이 테스트가 무엇을 하는지 명확하지 않아보입니다.

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +    }
이 메서드는 굳이 추출해주신 이유가 있나요? 중복이 되지 않는다면, 굳이 추출할 필요는 없습니다.

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +    }
TDD 방법을 잘 따르셨네요. 👍

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +        assertThat(pawn2.getColor()).isEqualTo("black");
혹시 이후에 black에 대한 테스트를 왜 제거하셨는지 여쭤봐도 될까요?

2021-02-14 14:39 UTC, ksundong commented on src/test/java/PawnTest.java
> +}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
해당 리뷰를 참고해주세요!
인텔리제이도 웹스톰과 동일한 옵션을 주시면 됩니다!

2021-02-15 07:15 UTC, MyungWanPark commented on src/main/java/Pawn.java
> +    String color;
이점을 생각 못했던 것 같습니다! 앞으로 접근 제어자에 대해 신경쓰겠습니다~!

2021-02-15 07:16 UTC, MyungWanPark commented on src/main/java/Pawn.java
> +    }
사용자가 다른 값을 입력할 수 있다는 점을 생각하지 못했습니다. enum에 대해 공부해 보겠습니다!

2021-02-15 07:16 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +    }
네 감사합니다!!

2021-02-15 07:17 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +    }
앗 루카스에 있는 그대로 해야되는 줄 알아서 미쳐 신경을 못썻던것 같습니다! 지적해주셔서 감사합니다!

2021-02-15 07:18 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +    }
중복이 되지 않는다면 추출하지 않겠습니다~! 감사합니다!!

2021-02-15 07:18 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +        assertThat(pawn2.getColor()).isEqualTo("black");
앗, 하나의 경우만 확인하면 되는 줄 알고 착각했습니다. Black에 대한 테스트를 추가하겠습니다~!

2021-02-15 07:19 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +}
해당 리뷰 참고해보겟습니다. 링크까지 남겨주셔서 감사드립니다~!

2021-02-15 08:58 UTC, MyungWanPark commented
Wan 입니다! (이렇게 닉네임으로 제목pr 날리면 될까요? )
꼼꼼하게 리뷰해주신 덕분에 생각하지 못했던 부분들을 고려할 수 있어서 감사드립니다!
Enum에 대해 학습하던도중 모르는 부분이 생겨서 여쭤보고 싶은 부분이 있습니다

Test폴더 내에서 Enum 클래스를 만들었을때, Main 폴더안의 클래스에서는 Enum 클래스에 접근이 불가능했는데 그 이유가 궁금합니다....
이와 반대로 Main폴더 내에서 Enum클래스를 만들었을때는, Test 폴더에서 접근이 가능했기 때문입니다.(createPawn메소드에서 접근가능했더든요...)

추가로 reviewer 등록하는 방법에 대해 찾아보고 있는데 방법을 찾게 되면 바로 등록하겠습니다!!

2021-02-15 11:18 UTC, ksundong commented on src/test/java/PawnTest.java
> +    }
이 부분은 좀 더 생각해볼만한게 중복이 아니더라도 가독성을 위해 추출하는 경우도 있습니다.
현재는 그럴 필요는 없다는 의미에요!

2021-02-15 11:19 UTC, ksundong commented on src/test/java/PawnTest.java
> +        assertThat(pawn2.getColor()).isEqualTo("black");
하나의 경우만 확인해도 됩니다. 다만, 우리는 요구사항에서 white와 black 두 가지 색상으로 생성이 가능해야한다는 조건이 있었기 때문에 테스트를 해주시는게 좋습니다.

2021-02-15 11:23 UTC, ksundong approved these changes
고생하셨습니다. 다음단계 진행해주세요!

질문에 대한 답변은 이렇습니다.
우리가 실제로 배포하는 코드에는 굳이 테스트 코드가 배포될 필요가 없습니다.
따라서, 테스트 영역에서 작성한 코드는 배포되는 코드에 영향을 미치면 안됩니다.
그래서 테스트 영역에 생성해주었던 enum이 실제 배포하는 영역에서 불러와지지 않았던 것입니다.
답변이 되셨나요?

몇 가지 코멘트 남긴 부분은 다음단계에서 수정해주세요. 고생하셨습니다~

2021-02-15 11:23 UTC, ksundong commented on src/main/java/Colors.java
> +    WHITE,BLACK;
👍

2021-02-15 11:23 UTC, ksundong commented on src/main/java/Colors.java
> +    WHITE,BLACK;
보통 enum과 같은 클래스들은 복수형으로 네이밍을 하지 않습니다.
`Color`가 낫겠네요!

2021-02-15 11:23 UTC, ksundong commented on src/test/java/PawnTest.java
> +    @DisplayName("흰색 폰이 생성되어야 한다")
흰색폰이 생성되어야 한다는 이름과 테스트 메서드의 내용이 다르죠?
이런 부분은 주의해주셔야합니다.

2021-02-15 15:16 UTC, honux77 commented
👍

2021-02-15 15:16 UTC, merged

2021-02-16 00:52 UTC, MyungWanPark commented on src/test/java/PawnTest.java
> +    @DisplayName("흰색 폰이 생성되어야 한다")
앗 제가 꼼꼼하게 보지 못했네요! 주의하겠습니다!!

2021-02-16 00:52 UTC, MyungWanPark commented on src/main/java/Colors.java
> +    WHITE,BLACK;
그렇군요!! enum 클래스들은 복수형으로 네이밍하지 않겠습니다 감사합니다!

2021-02-16 00:53 UTC, MyungWanPark commented
질문에 대해 답변해주셔서 감사드립니다~! '테스트 코드는 배포될 필요가 없기때문에 테스트 코드에 있는 내용이 배포되는 파일에 영향을 미치게 되면 안된다' 라는 내용 새롭게 알게 되었습니다. 다음단계 진행하겠습니다~! 리뷰해주셔서 감사합니다!