[Jung] Mission2 PR입니다
codesquad-members-2021/java-chess pull request #76
Opened 2021-02-15 08:35 UTC by rla36

*  테스트메서드 작성할 때 고민되었던 부분이
1) 여러개의 메서드를 한 테스트 안에서 검증하면 테스트가 실패했을 때 어떤 메서드 때문에 실패했는지 모른다는 점, 그리고 2) 한 테스트 메서드 안에서 하나의 assertThat만 실패해도 다른 assertThat이 돌아가지 않는다는 점이었습니다.

앞의 문제들을 해결하기 위해서 assertAll을 사용해봤습니다.
1) 의 이유로 만들었던 메서드별로 테스트 메서드를 따로 만들어 size() findPawn()를 따로따로 검증할까 생각해봤지만, 
add size findPawn을 한번에 묶어서 테스트하면 중복제거로 코드를 절약(?)할 수 있는데 메서드를 하나씩 검증하려면 추가하는 메서드가 늘어남에 따라 테스트메서드도 기하급수적으로 늘어나는게 아닌가 하는 생각이 들었습니다.
테스트메서드 작성할 때 메서드별로 따로 테스트메서드를 만드는게 좋을까요?

*  @BeforeEach는 테스트메서드가 하나뿐이라 사실 필요없는 부분이지만, 학습차원에서 한번 써보고 싶어서 써봤습니다..ㅎㅎ

*  ArrayList인 pawnList에 pawn을 add()하는 메서드에서 개수제한 예외를 넣고 싶었으나, pawnList가 흑백합쳐 16개의 폰을 받을지, 흑/백 따로 8개씩 받을지 미션2 진행 단계에선 모르겠어서 일단 예외를 만들지 않았습니다.

2021-02-15 08:36 UTC, rla36 commented on src/Test/java/chess/BoardTest.java
> +        assertAll("흰색 폰을 보드에 올린 후 size, findPawn메서드 검증한다.",
테스트메서드 안에 assertAll을 한번만 사용하는 것이 좋다는 이야기를 들었는데,  
size()를 흰색 폰 더한 후, 검은색 폰 더한 후 총 두번 검증하고싶어 두개로 나누었습니다.
더 바람직한 쓰임 알려주시면 감사하겠습니다

2021-02-15 15:07 UTC, SANGCO requested changes
Jung님 안녕하세요, 리뷰어 상코입니다.
작성하신 코드에 대해서 코멘트를 남겼습니다. 
확인해 보시고 질문 있으시면 댓글 부탁드립니다~

2021-02-15 15:07 UTC, SANGCO commented on src/Test/java/chess/BoardTest.java
> +package chess;
src/Test/java 라고 대문자로 되어있는 패키지 src/test/java로 수정해 주세요~

2021-02-15 15:07 UTC, SANGCO commented on src/Test/java/chess/BoardTest.java
> +    Pawn blackPawn;
접근 제한자 대해서 생각해 봅시다~

2021-02-15 15:07 UTC, SANGCO commented on src/Test/java/chess/BoardTest.java
> +                () -> assertThat(board.findPawn(1)).isEqualTo(blackPawn));
```java
assertAll(
    () -> {
        board.add(whitePawn);
        assertAll("흰색 폰을 보드에 올린 후 size, findPawn메서드 검증한다.",
            () -> assertThat(board.size()).isEqualTo(1),
            () -> assertThat(board.findPawn(0)).isEqualTo(whitePawn));
    },
    () -> {
        board.add(blackPawn);
        assertAll("검은색 폰을 보드에 올린 후 size, findPawn메서드 검증한다.",
            () -> assertThat(board.size()).isEqualTo(2),
            () -> assertThat(board.findPawn(1)).isEqualTo(blackPawn));
    }
);
```
이런식으로도 할 수 있겠죠?
람다 표현식에 대해서 간단하게 어떤건가 하고 찾아봐도 좋을거 같네요~

2021-02-15 15:07 UTC, SANGCO commented on src/main/java/pieces/Pawn.java
> +    }
기본 생성자가 매개 변수가 있는 생성자 보다 위로 오는게 좋겠죠?

2021-02-15 15:07 UTC, SANGCO commented on src/main/java/pieces/Pawn.java
> +package pieces;
패키지를 전체적으로 한번 정리를 해야할거 같습니다.
net.jung.chess 이런식으로 만들어서 그 하위에 폴더와 파일들을 만들어 봅시다.
메인 클래스도 본인이 만든 패키지로 옮기면 net.honux.chess는 이제 필요 없으니 지우는게 좋겠죠?

2021-02-16 01:46 UTC, rla36 commented on src/Test/java/chess/BoardTest.java
> +    Pawn blackPawn;
네! 테스트 안에서만 쓰이는 것들이기 때문에 private으로 수정했습니다 지적 감사합니다!

2021-02-16 02:05 UTC, rla36 commented on src/Test/java/chess/BoardTest.java
> +                () -> assertThat(board.findPawn(1)).isEqualTo(blackPawn));
넵 람다식을 잘 몰라 검색한 걸로 따라했는데 제대로 공부해봐야할 것 같습니다..
일단 말씀해주신대로 수정했고 공부해보겠습니다!

2021-02-16 02:08 UTC, rla36 commented on src/main/java/pieces/Pawn.java
> +    }
넵 기본생성자가 생성자 중 가장 위로 올라오도록 하는게 컨벤션(?)인데 만든순서대로 추가하느라 생각을 못했어요. 말씀해주셔서 감사합니다~

2021-02-16 02:42 UTC, rla36 commented on src/main/java/pieces/Pawn.java
> +package pieces;
넵 말씀하신대로 수정했습니다!

2021-02-16 07:33 UTC, SANGCO approved these changes
피드백 드린게 잘 반영이 되었군요.
고생하셨습니다~

2021-02-17 05:10 UTC, merged