[마르코] Mission2 PR 요청드립니다.
codesquad-members-2021/java-chess pull request #78
Opened 2021-02-15 08:59 UTC by 95degree

안녕하세요 마르코입니다. Mission2 PR 요청드립니다.

아래는 제가 Mission2 구현을 대략 요약한 스케줄입니다.

1. 매개변수 없는 Pawn클래스 생성을 위해 생성자 오버로딩을 사용하였습니다.
2. "white","black"문자열을 Pawn클래스의 static final 상수로 만들었습니다.
3. 위에서 만든 상수를 바탕으로 PawnTest를 리팩토링 하였습니다.
4. BoardTest클래스에 먼저 create 메소드를 만들었습니다.
5. Board 클래스에 BoardTest를 위해 필요한 메소드들을 구현했습니다.
6. 패키지 정리 및 분리를 하였습니다.
7. BoardTest의 반복되는 부분을 줄이기 위해 verifyAddPawn 메소드를 추가하여 리팩토링 하였습니다.
8. verifyAddPawn 메소드 내에 assertEquals가 여러개 존재 하여 한번에 테스트 체크를 하기 위해 assertAll을 사용하여 리팩토링 하였습니다.

2021-02-15 15:19 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +}
다른 분 PR에도 있던데 파일 끝에는 linefeed가 있어야 해요. 인텔리J 자동설정 가능하니 다른 PR 읽어보거나 검색해 보세요.

2021-02-15 15:21 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +                ()->assertEquals(pawn, board.find(index++)),
index는 test의 지역변수로 만드는게 타당해 보입니다.

2021-02-15 15:21 UTC, ksundong commented on src/main/java/pieces/Pawn.java
> +}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344

2021-02-15 15:21 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    private int index =0;
불필요한 멤버변수 index를 제거해 주세요.

2021-02-15 15:23 UTC, honux77 requested changes
코멘트 확인해 보시고 수정해 주세요.

2021-02-16 02:08 UTC, 95degree commented on src/main/java/pieces/Pawn.java
> +}
코멘트 감사합니다 :)
수정완료했습니다.
정해진 텍스트 규격 약속(?)을 지켜야 하기 때문에 파일 끝에는 개행을 해 줘야 하네요!!

2021-02-16 02:31 UTC, 95degree commented on src/test/java/chess/BoardTest.java
> +    private int index =0;
먼저 코멘트 감사합니다. 😊
달아주신 코멘트를 바탕으로 수정해보고 공부해봤습니다.

멤버변수 index를 제거하고 지역변수로 만들고 람다식에 index++을 넣을려고하니 final 또는 Effectively final 변수만 사용이 가능하다고 나와 왜그런지 다시  생각해보니 
람다식은 함수형으로 순수함수를 사용해야야 하는데 index++은 , 같은 인풋을 넣었을때 다른 아웃풋이 나오게 되니 가변적이니 사용이 불가한 것 같습니다.

추가로 멤버변수가 많으면 안되는 이유도 공부를 해봤습니다.
클래스의 멤버변수가 많으면 그 만큼 클래스가 해야 할 일이 많다->응집도가 떨어진다.
결국 좋은 객체 설계라고 할 수 없다.

이렇게 정리해봤는데 혹시 잘못 알고 있는것이 있으면 코멘트 주시면 감사하겠습니다.

2021-02-16 09:54 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals(pawn, board.find(index)),
다음에는 assertThat으로 사용해 주세요.

2021-02-16 09:54 UTC, honux77 approved these changes
수고하셨어요. 요구사항 반영해서 잘 수정했네요.
다음에는 assertThat을 사용해 주세요.

2021-02-16 09:55 UTC, merged