[ coco ] 미션3 : 체스판 초기화
codesquad-members-2021/java-chess pull request #79
Opened 2021-02-15 09:22 UTC by ChoiGiSung

안녕하세요. 백엔드반의 coco라고 합니다.  

* ###  pieces/Pawn
이번 미션에서는 Pawn class 안에 있던 color 상수들을 enum으로 빼서 작성했습니다.   
또 구분문자인 representation을 새로운 필드로 갖게 되었습니다.

* ### pieces/PawnEnum
상수를 대신해 enum을 도입했으며 내부에 구분문자를 가지게 있게 했습니다. 이 때문에  pawn 생성 시 enum 만 파라미터로 넘겨주면 안에서 구분문자를 꺼내서 사용하게 되었습니다.

* ###  pieces/PawnTest
이전에 사용하던 상수들을 enum으로 전부 변경하였습니다.

* ###  chess/Board
원래는 보드 하나당 pawns 하나를 가지고 있었지만 whitePawns, blackPawns 리스트 2개로 분리했습니다.  
그로인해 각각의 size나 find하는 메소드들이 생겨나 많은 메소드가 내부에 있습니다.  

1. #### initialize 메소드
    초기화 함수로 pawns 리스트들을 clear 해주고 8번 반복해서 pawn들을 넣어줍니다.

2. #### getPawnsResult 메소드
    pawns들에서 들어있는 pawn들을 알기 위해 사용합니다. 알고자 하는 색상을 매개변수로 받아서 분기점을 통해 getPawnsToString 을 호출해 String을 return 해줍니다.

3.  #### getPawnsToString 메소드
    pawns들 안에 들어있는 pawn들을 String형태로 반환해 줍니다.

* ###  chess/BoardTest

한 개였던 pawns를 2개의 리스트(white, black)로 분리해서 많은 메소드들이 생성되었습니다.  

1. #### verifyPawnToPawns 메소드
    색상을 주어서 해당 색상의 pawn을 넣고 잘 들어갔는지 index를 통해 검사합니다. 내부적으로는 입력받은 enum을 통해 분기점을 만들어 verifyWhitePawnsIndex, verifyBlackPawnsIndex 메소드를 각각 호출해줍니다.  

2. #### verifyPaswsSize 메소드
    색상을 주어서 해당 pawns의 size가 증가하고 있는지 검증합니다. 매개변수로 받은 enum을 통해 분기점을 만들어 verifyWhitePaswsSize, verifyBlackPaswsSize 메소드를 각각 호출합니다.  

3. #### initialize 메소드와 print 메소드
     해당 메소드를 검증합니다.  

pawns 리스트가 색상대로 2개로 분리되어서 메소드가 2배로 증가하였습니다.

2021-02-15 13:29 UTC, tmdgusya commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    PawnEnum(String representation) {
개인적으로 String 보다는 char 를 이용했으면 어땠을까 라는 생각이 듭니다.

2021-02-15 13:29 UTC, tmdgusya commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    public String representation;
지금 상태에서 아래와 같은 코드를 외부에서 입력하면 어떻게 될까요

```java
PawnEnum. WHITE_COLOR.representation = 'c';
```

2021-02-15 13:29 UTC, tmdgusya commented on src/main/java/net/coco/chess/Board.java
> +    private String blank() {
해당 부분을 private final static blank = "********\n"; 로 했을때와 지금과 같이 method 를 이용했을때
어떤 차이가 있을까요? 어느 방법이 조금 더 지금상황에 좋은 방법일까요?

2021-02-15 16:39 UTC, sonypark requested changes
안녕하세요 coco, 리뷰어 소니 입니다.😊
요구사항에 맞게 기능이 잘 동작하네요.
다만 몇가지 아쉬운 점이 있어 코멘트 남겼으니 확인 후 수정 부탁드릴게요!

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +                .append(blank());
체스말의 위치가 바뀐것 같네요. 체스판에서 검은말과 흰말의 위치를 확인해주세요~

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +        StringBuilder boardPrint = new StringBuilder();
체스판을 출력하는 로직은 Board에서 수행해야할 기능일까요?

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +    }
의도하지 않은 color의 piece가 들어올 경우 검증 로직이 필요할 것 같네요

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +        for (int i = 0; i < 8; i++) {
매직넘버를 줄일 수 있는 방법은 무엇일까요?

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +                .collect(Collectors.joining());
👍

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +    private String blank() {
메서드로 빼기에는 역할이 너무 없는 것 같네요😅

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
> +        Board board = new Board();
Scanner 같은 객체는 생성한 뒤 close를 해줄 것을 권장합니다. 그 이유는 무엇일까요?

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
> +            case "end":
start, end와 같은 문자열은 상수를 활용해주세요~

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    ,BLACK_COLOR("P");
PawnEnum을 만드신 이유는 무엇인가요?
만약 다른 Piece추가 된다면 Piece마다 Enum이 생기는걸까요?
PawnEnum의 역할이 무엇이고 왜 필요한지, 그렇지 않다면 어떻게 해야할지 고민해보시길 바랍니다.
네이밍에 자료형이 들어가는게 맞을지도 생각해보세요~

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +        return blackPawns.size();
이 메서드는 필요한 기능인가요?

2021-02-15 16:39 UTC, sonypark commented on src/test/java/net/coco/pieces/pawnTest.java
>      }
👍

2021-02-15 16:39 UTC, sonypark commented on src/test/java/net/coco/chess/BoardTest.java
> +    }
Pawn 스펠링~🔤

2021-02-15 16:39 UTC, sonypark commented on src/main/java/net/coco/chess/Board.java
> +        }
이 부분은 addWhitePawn, addBlackPawn과 중복되네요. 만들어 놓은 메서드를 활용해보세요

2021-02-16 01:56 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    PawnEnum(String representation) {
의견 감사합니다 로치! 문자 하나만 저장하기에 char로 다시 변경했습니다. 평소 char보다는 String을 자주 사용해 이런 부분은 생각지 못했네요.

2021-02-16 01:58 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    public String representation;
외부에서 변경할 거라는 생각을 하지 못했네요. final을 붙여서 해결해 봤습니다.
이런 부분 하나하나가 후에 예기치 못한 장애를 만들 수 있겠다는 생각을 하는 좋은 기회였습니다.
감사합니다!

2021-02-16 02:07 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +    private String blank() {
그렇네요. 상수를 사용하면 메소드 3줄에서 1줄로 코드랑도 줄어들어 좋은 거 같습니다.
매번 함수로 빼지 말고 역할을 다시 한 번 생각해 봐야겠네요

2021-02-16 02:08 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +                .append(blank());
하하.. 변경 완료했습니다..

2021-02-16 02:25 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        StringBuilder boardPrint = new StringBuilder();
Board를 print 하는 기능은 새로운 class를 만들어 그 안에 할당했습니다.
이 때문에 print 메소드의 내부구조가 pawns의 내용물들을 문자열로 받아서 print해 주는 형식으로 바뀌게 되었습니다.

2021-02-16 02:35 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +    }
여러 예외처리를 안 하고 있었네요. 앞으로 더 신경 쓰도록 하겠습니다. 감사합니다!

2021-02-16 02:42 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        for (int i = 0; i < 8; i++) {
상수로 변경해 봤습니다! 상수로 변경을 해서 개발자의 의도를 쉽게 파악할 수 있고 만약에 경우 값들도 쉽게 변경할 수 있어 졌습니다.

2021-02-16 03:07 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
> +        Board board = new Board();
close() 명령을 수행하였습니다. 명령을 선언해 주지 않으면 gc가 수거해 가지 않아 메모리 누수가 발생하는 것을 알았습니다. gc는 메모리 리소스만 관리하지 시스템 메모리 리소스는 개발자가 닫아야 하는군요. gc에 대해 좀 더 공부하겠습니다!

2021-02-16 03:13 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
> +            case "end":
상수로 변경했습니다. 변하지 않는 값이기에 상수로 선언하는 게 맞는 거 같습니다!

2021-02-16 03:32 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    ,BLACK_COLOR("P");
맞는 말씀이십니다. PawnEnum으로 만들어 사용하면 확장성도 떨어지고 다른 Piece들이 늘어나면 다른 enum들이 늘어날 수 있습니다. 저 또한 이런 생각을 가지고 있었으나 이번 미션은 이렇게 해보고 다음 미션에서 만나는 요구사항에 따라 새롭게 고치는 것도 경험해 보고 싶었습니다. 
근데 지금 와서 생각해보니 representation에 대한 대처가 힘들 것 같다는 생각이 듭니다. representation에 관해서는 새로운 방법을 모색하거나 다른 분들의 코드를 참고해야 할 것 같습니다. 감사합니다.

2021-02-16 05:34 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        return blackPawns.size();
저의 현재 구조는 white와 black, Pawns들의 size를 return 해주고 있습니다.
질문을 보고 다른 분들의 코드를 살펴보았습니다. 다른 분들은 두 리스트의 size를 합하여 return 하더군요.
코드의 목적은 pawn이 잘 들어가고 있는지 size를 검사 하는 거기 때문에 굳이 색상별로 나눌 필요가 없다는 것을 알게 되었습니다.

그래서 저 또한 get Size() 메소드로 합쳐 진행해 보겠습니다.

2021-02-16 05:49 UTC, ChoiGiSung commented on src/test/java/net/coco/chess/BoardTest.java
> +    }
수정했습니다!

2021-02-16 05:50 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/Board.java
> +        }
수정했습니다! 이미 있는 함수를 사용하니 코드의 목적이 더 잘 보이는 것 같습니다!

2021-02-16 12:24 UTC, sonypark commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    public String representation;
Enum의 필드 접근제어자를 public으로 두는게 좋은 선택인지 생각해보세요~
생성자와 필드의 위치도 확인 부탁드립니다.

2021-02-16 12:42 UTC, sonypark requested changes
수정이 필요한 곳에 코멘트 남겼으니 반영 부탁드릴게요~

2021-02-16 12:42 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
> +                System.out.println(PrintChess.printBoard(blackPawns, whitePawns));
PrintChess 클래스의 `printBoard()` 메서드를 보면 출력을 담당할 것 같은데 출력은 `commandSwitch()`에서 해주고 있네요.

2021-02-16 12:42 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
> +        }
명령어를 잘못 입력했을 때 프로그램을 종료시키는 것이 자연스러운 흐름일까요?

2021-02-16 13:53 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    public String representation;
음.. 현재는 필드에 직접 접근하는 모습인데 접근제어자를 변경하고 getter 메소드를 추가하는 것으로 변경했습니다.
이러면 final도 굳이 붙일 필요가 없을 거 같아 final은 삭제 조치했습니다.

2021-02-16 14:04 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
> +                System.out.println(PrintChess.printBoard(blackPawns, whitePawns));
printBoard()의 형태를 결과물만 return하는 모습으로 설계를 했었는데, 
printBoard() 메소드에서 출력까지 하는 것으로 변경했습니다!

2021-02-16 14:04 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
> +        }
사용자로서는 다시 입력 받는 게 좋을 거 같아 변경했습니다!

2021-02-16 16:18 UTC, sonypark requested changes
수정해주신 부분 확인했습니다!
코멘트 남긴 부분 확인해주세요~
특히 Enum 사용 관련한 부분에 대해 수정이 필요해보입니다.🤔

2021-02-16 16:18 UTC, sonypark commented on src/main/java/net/coco/chess/StartGame.java
> +                PrintChess.printBoard(blackPawns, whitePawns);
`printBoard()'라는 메서드 이름에 맞게 인자로 board를 넘기는건 어떨까요?

2021-02-16 16:18 UTC, sonypark commented on src/main/java/net/coco/pieces/PawnEnum.java
> +
Enum의 필드는 한 줄에 하나씩 구분하여 명시하도록 해주세요~
```java
PawnEnum {
    WHITE('p'), 
    BLACK('P');
```

2021-02-16 16:18 UTC, sonypark commented on src/main/java/net/coco/pieces/Pawn.java
>      }
color의 타입이 PawnEnum인게 맞을까요? color와 representation은 하나의 Enum으로 묶는게 적절한지도 고민이 필요해 보입니다. Enum을 사용하기 어렵다면 일단 자바 상수를 이용해서 구현하는 걸 추천드립니다. Enum을 잘 모르는 상태에서 오용하게 되면 오히려 코드의 복잡도를 높일 수 있습니다. 먼저 자바 상수로 구현한 후 추후 미션에서 Enum으로 변경하는 것도 좋은 방법입니다.

2021-02-16 16:18 UTC, sonypark commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    WHITE('p'), BLACK('P');
```suggestion
public enum PawnEnum {
    WHITE('p'), 
    BLACK('P');
```
Enum의 필드는 한 줄에 하나씩 입력해주세요~

2021-02-17 03:07 UTC, ChoiGiSung commented on src/main/java/net/coco/chess/StartGame.java
> +                PrintChess.printBoard(blackPawns, whitePawns);
printBoard() 하기 전에 파라미터를 준비하는 과정이 있어서 코드량이 길어졌는데, 그냥 보드를 넘기면 됐었네요.
왜 이런 생각을 못했을까요. 감사합니다!

2021-02-17 03:27 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/Pawn.java
>      }
조언 감사드립니다. 저의 의도는 현재는 pawn만 있으니 미래를 생각하지 않고 pawn에만 딱 들어맞게 설계를 했습니다. PawnEnum을 생각해보면 확장성은 없고 pawn의 특징들만 가지고 있습니다. color라든지 'p'와 'P'로 정의된 representation 라던지.. 
둘을 묶은 이유는 파라미터를 간단히 넘겨주고 싶은 마음도 있었습니다. 
하지만 이런 생각 때문에 코드의 복잡도 생각은 하지 못했네요. Pawn의 생성자는 겉으로는 enum만 파라미터로 넘겨주는데, 내부에서는 enum 내부에 있는 representation까지 사용하니 외부에서 봤을 때 정확한 동작을 예측하기 힘들 거 같다는 생각도 듭니다.
아직 다음 미션을 보지는 않았지만 미션4를 확인하고 다른 enum으로  representation 을 빼든지 아니면 기물마다 구분문자를 상수로 가지고 있게 하던지 설계를 다시 진행하겠습니다. 감사합니다.

2021-02-17 03:27 UTC, ChoiGiSung commented on src/main/java/net/coco/pieces/PawnEnum.java
> +    WHITE('p'), BLACK('P');
수정 완료했습니다!

2021-02-17 14:36 UTC, sonypark approved these changes
확인했습니다.
다음 단계 진행해주세요~💪

2021-02-18 09:15 UTC, honux77 commented
수고하셨어요!

2021-02-18 09:15 UTC, merged