Add Pawn class and test file
codesquad-members-2021/java-chess pull request #8
Opened 2021-02-08 08:13 UTC by kimnayeon0108

Pawn 클래스와 test 메소드를 구현한 PawnTest 클래스를 생성했습니다.

2021-02-08 12:57 UTC, wheejuni requested changes
안녕하세요, 리뷰어 브라이언입니다. 
이렇게 첫번째 리뷰로 만나뵙게 되어 반갑습니다. 💯 👍 

개선 의견을 아래와 같이 남겨 드렸으니 한번 확인해 주세요!

2021-02-08 12:57 UTC, wheejuni commented on src/test/java/PawnTest.java
> +    }
테스트 클래스 안에서 `private` 으로 책임분리를 너무 작게 하실 필요는 없습니다.
그리고 지금은 단순한 생성자 호출만 있기 때문에, `verify` 라는 메소드 이름과 이 메소드가 수행하고 있는 역할이 조금 다른 것 같기도 합니다.

2021-02-08 12:57 UTC, wheejuni commented on src/test/java/PawnTest.java
> +        Pawn blackPawn = verifyPawn("black");
여기서 아래와 같이 바로 생성자를 호출하셔도 되겠네요.

```suggestion
        Pawn whitePawn = new Pawn("white");
        Pawn blackPawn = new Pawn("black");
````

2021-02-08 12:57 UTC, wheejuni commented on src/test/java/PawnTest.java
> +        assertThat(blackPawn.getColor()).isEqualTo("black");
👍

2021-02-09 01:42 UTC, kimnayeon0108 commented on src/test/java/PawnTest.java
> +    }
리뷰 감사합니다!  verifyPawn 메소드를 수정해보겠습니다~🙇‍♀️

2021-02-09 01:43 UTC, kimnayeon0108 commented on src/test/java/PawnTest.java
> +        Pawn blackPawn = verifyPawn("black");
요구사항에서 veritfyPawn 메소드로 코드 중복을 제거하라는 것을 잘 이해하지 못하고 코드를 작성한 것 같습니다. 해당 메소드를 수정해보겠습니다!

2021-02-09 01:45 UTC, kimnayeon0108 commented on src/test/java/PawnTest.java
> +        assertThat(blackPawn.getColor()).isEqualTo("black");
첫 코드리뷰 요청과 테스트파일 작성도 처음이라 미숙한 부분이 많습니다😰 앞으로 잘부탁드립니다! 리뷰 감사합니다🙇‍♀️

2021-02-09 02:16 UTC, kimnayeon0108 reviewed
verifyPawn 메소드 수정해서 PawnTest 작성해보았습니다!

2021-02-09 02:18 UTC, kimnayeon0108 commented
> verifyPawn 메소드 수정해서 PawnTest 작성해보았습니다!

새로운 커밋 리뷰 요청을 이렇게 하는게 맞는 건지 잘 모르겠습니다ㅠㅠ 틀린부분 있으면 피드백 주시면 감사하겠습니다!

2021-02-09 14:08 UTC, wheejuni approved these changes
잘 하셨어요. 💯 
수정사항 반영 후 재리뷰 요청은, 오른쪽 위 'reviewers' 코너에 보면 리뷰어 이름 옆에 동그랗게 감겨져 있는 화살표 모양의 아이콘이 있을 겁니다. 그걸 눌러주시면 돼요. 저에게도 알림이 옵니다. 그러면 제가 빠르게 봐드릴 수 있겠죠. 

![image](https://user-images.githubusercontent.com/24876532/107375241-dbc7c400-6b2b-11eb-9887-c9b892968143.png)


이번 단계는 여기까지 하고 다음 단계로 넘어가는게 좋을 것 같네요. ㅎㅎ 수고 많으셨어요.

2021-02-09 14:12 UTC, merged

2021-02-10 06:44 UTC, kimnayeon0108 commented
> 잘 하셨어요. 💯
> 수정사항 반영 후 재리뷰 요청은, 오른쪽 위 'reviewers' 코너에 보면 리뷰어 이름 옆에 동그랗게 감겨져 있는 화살표 모양의 아이콘이 있을 겁니다. 그걸 눌러주시면 돼요. 저에게도 알림이 옵니다. 그러면 제가 빠르게 봐드릴 수 있겠죠.
> 
> ![image](https://user-images.githubusercontent.com/24876532/107375241-dbc7c400-6b2b-11eb-9887-c9b892968143.png)
> 
> 이번 단계는 여기까지 하고 다음 단계로 넘어가는게 좋을 것 같네요. ㅎㅎ 수고 많으셨어요.

감사합니다!!🙇‍♀️