[이노]미션3: 체스판 초기화
codesquad-members-2021/java-chess pull request #80
Opened 2021-02-15 10:19 UTC by eNoLJ

Pawn class에 representation 속성이 추가 됨에 따라 pawn 생성 시 어떻게 상수를 관리 할 지 고민했습니다.
처음엔 Representation라는 enum을 추가로 만들어 관리하려 생각했다가 piece라는 enum을 만들어 color와 representation 두개의 매개변수를 가지도록 만들었습니다. 
그리고 추후 폰 외의 다른 말들의 representation를 추가할 때 또한 간단하게 추가가 가능해지도록 의도했습니다.

그렇게 Pawn의 생성자를 호출 할 때 color와 representation 값을 넘겨주지 않고 Piece enum 하나만 넘기면 되도록 만들었습니다. 하지만 이게 좋은건지 판단이 잘 안됩니다. 인자 하나만 넘겨 간단해 보이지만 한편으로는 직관적이지 못해보이기도 합니다. 인자를 color와 representation 두개로 넘긴다면 직관적으로 폰은 color와 representation 두개의 속성을 가지고있구나 라고 생각할 수 있지만 piece enum을 넘기게 되면서 그 부분이 모호해졌기 때문입니다.
이 부분에 대해서 피드백을 남겨주시면 감사하겠습니다!!

그 외엔 Board의 변수도 흰색과 검은색 따로 관리를 해줄 필요성이 생겨서 Map을 만들어 관리하도록 했습니다. 이유는 흰색과 검은색 List를 각각 만들면 그에 맞는 메소드 또한 두개씩 만들어야하는 문제가 생기기 때문에 Map 하나로 key로는 흰색과 검은색을 지정하고 value는 List를 추가하여 메소드가 중복되는 문제를 해결했습니다.

매번 리뷰로 새로운 부분을 알게되어 재미를 느끼고 있습니다. 이번에도 잘 부탁드립니다!! 감사합니다.

2021-02-15 13:06 UTC, tmdgusya commented on src/main/java/chess/Board.java
> +    private final HashMap<String, LinkedList<Pawn>> pawns;
필드에 HashMap 같은 구현체보다는 Map 타입으로 쓰는것이 조금 더 좋은 방안입니다 :)

한번 이부분에 대해서도 공부해보셔도 좋을것 같아요!

2021-02-15 13:58 UTC, eNoLJ commented on src/main/java/chess/Board.java
> +    private final HashMap<String, LinkedList<Pawn>> pawns;
> 필드에 HashMap 같은 구현체보다는 Map 타입으로 쓰는것이 조금 더 좋은 방안입니다 :)
> 
> 한번 이부분에 대해서도 공부해보셔도 좋을것 같아요!

최종적으로 수정된 파일보시면 HashMap이 아닌 Map으로 구현했습니다!! 미션2에서 리뷰받았던 부분인데 미션2의 리뷰 전에 미션3를 작성해서 미션2 리뷰 받은 후 미션3까지 수정하다보니 커밋내용에는 수정 전의 내용이 기록에 남았나보네요!!
암튼 리뷰 감사드립니다!! 앞으로도 환영이에요!!!

2021-02-15 18:05 UTC, SANGCO requested changes
아노님 안녕하세요, 리뷰어 상코입니다.
구현 잘하셨네요~
이번 미션에서는 특별히 수정할 부분은 없어 보이네요.

> Pawn의 생성자를 호출 할 때 color와 representation 값을 넘겨주지 않고 Piece enum 하나만 넘기면 되도록 만들었습니다. 하지만 이게 좋은건지 판단이 잘 안됩니다. 인자 하나만 넘겨 간단해 보이지만 한편으로는 직관적이지 못해보이기도 합니다. 인자를 color와 representation 두개로 넘긴다면 직관적으로 폰은 color와 representation 두개의 속성을 가지고있구나 라고 생각할 수 있지만 piece enum을 넘기게 되면서 그 부분이 모호해졌기 때문입니다.

생성자나 메서드로 넘기는 데이터들이 연관이 있다면 
test(LocalDate start, LocalDate end) -> test(DateRange dateRange)
이런식으로 클래스를 만들어 넘기는게 더 가독성도 좋고 이해하기 좋겠죠?

```java
public Pawn(Piece piece) {
    this.color = piece.color;
    this.representation = piece.pawn;
}
```

이 경우에는 Piece enum에 대해 고민을 해보면 좋을거 같아요.
Piece라는 클래스 명은  color와 representation을 아우르는 적절한 이름인가?
color, representation은 하나의 enum에 있는게 맞는걸까?

앞으로 미션이 복잡해 지면서 이런 종류의 고민을 많이 하시게 될테니
이번 미션에서는 일단 넘어가도 괜찮겠다고 생각합니다.
일단 밑에 남겨드린 간단한 피드백을 처리하고 
호눅스한테 머지 받고 다음 미션으로 넘어갑시다~

2021-02-15 18:05 UTC, SANGCO commented on src/main/java/chess/Game.java
> +    public static void main(String[] args) {
패키지를 전체적으로 한번 정리를 해야할거 같습니다.
net.eno.chess 이런식으로 만들어서 그 하위에 폴더와 파일들을 만들어 봅시다.
현재는 main() 메소드가 두개가 있는데
net.honux.chess 패키지와 그 안에 있는 main() 메소드는 이제 필요 없으니 지우는게 좋겠죠?

2021-02-15 18:05 UTC, SANGCO commented on src/main/java/chess/Board.java
> +        this.pawns.put(Piece.BLACK.color, new LinkedList<>());
LinkedList를 쓰셨네요? 
어떤 고민을 했고 왜 LinkedList를 선택 했는지 궁금합니다!

2021-02-16 02:26 UTC, eNoLJ commented on src/main/java/chess/Game.java
> +    public static void main(String[] args) {
말씀대로 패키지 정리 후 push 했습니다!!
감사합니다.

2021-02-16 02:30 UTC, eNoLJ commented on src/main/java/chess/Board.java
> +        this.pawns.put(Piece.BLACK.color, new LinkedList<>());
아 이부분 언급해주셔서 눈치 챘습니다. 솔직히 LinkedList를 평소에 많이 쓰는 습관을 갖다보니 생각해보지도 않고 사용했습니다. ArrayList로 변경 후 푸시했습니다. 그리고 왜 이런 습관을 갖게 되었지 생각해보는 계기가 되었습니다. 생각해보니 ArrayList와 LinkedList의 차이를 잘 몰라서 어떤게 더 적절한지 판단을 하지 못했던 것 같습니다. 그래서 해당 내용을 찾아보니 내부적으로 순차적인 추가/삭제 중간에 추가/삭제에 있어서 속도 차이가 있고 ArrayList는 내부적으로 기본 크기가 넘어가면 새로 크기를 할당하기에 그 부분에 있어서는 비효율적이라는걸 알게 되었습니다. 이 외에도 앞으로 list, map, set 등 자료구조를 사용할 때 각각의 특성을 고려하여 작성하는 습관을 들이겠습니다!!

소중한 리뷰 감사드려요 덕분에 많이 배우고 있습니다^^

2021-02-16 02:37 UTC, eNoLJ commented
enum 부분은 리뷰어분의 의견을 듣고 싶은 마음에 color와 representation을 하나의 enum에 넣어서 올렸습니다. 이 부분에 있어서 소중한 의견 감사드립니다!! 솔직히 저도 하면서 너무 직관적이지 않게 느껴져서 고민이 많았지만 또 한편으로는 나누면 너무 거추장스러워 보이지 않을까 생각이 들었습니다. 다음 미션에서는 한번 나눠보겠습니다. 그리고 앞으로 미션을 하면서 의식적으로 지금 한 방법처럼 한번에 처리를하면 어떻게 될지 생각을 해보면서 진행해보도록 하겠습니다. 감사합니다!!

2021-02-16 08:11 UTC, SANGCO approved these changes
고생하셨습니다~

2021-02-17 05:14 UTC, honux77 commented on src/main/java/chess/Board.java
> +        this.pawns.put(Piece.BLACK.color, new LinkedList<>());
대부분 ArrayList가 잘 맞는 경우가 많아요.

2021-02-17 05:16 UTC, honux77 commented
enum은 하나의 타입입니다. 주로 불연속값이면서 값의 범위가 명확히 제한되어 있고, 소수이면서 type safe해야할 필요가 있으면 사용하는데, 제가 보기에는 아직까지는 color와 representation 모두 enum을 사용할 이유는 없어 보입니다.
다만 사용한다면 둘 다 별도의 타입이니까 따로 만드는게 맞고, 이번 프로젝트에 한해서는 함께 사용해도 무방합니다.

2021-02-17 05:16 UTC, merged

2021-02-17 05:57 UTC, eNoLJ commented
지금까진 color와 representation 모두 enum을 사용하는게 약간 배보다 배꼽이 큰 모양새일 수 있군요. 아직 전 enum에 대해 어떤 타이밍에 어떻게 써야하는지 명확한 판별이 어려운 것 같습니다. 지금은 연습차원으로 써보고 앞으로 조금씩 감을 잡아가 보도록 하겠습니다. 리뷰 감사드립니다!!