[노을] 미션3 : 체스판 초기화
codesquad-members-2021/java-chess pull request #83
Opened 2021-02-16 01:43 UTC by sanhee

안녕하십니까, 백엔드반 `노을` 입니다!! 👦
오늘도 리뷰 해주셔서 감사합니다 :)

미션3을 진행 하면서, 궁금한 점과 고민한 점을 정리하겠습니다.

<br>

#### 1. 커밋을 최대한 자세하게 작성해보았는데, 잘 작성했는지 모르겠습니다. 

#### 2. 흰색/흑색 Pawn의 생성, 개수확인 등 작은 단위의 테스트들을 만들어보고 싶었으나 `@Test` 마다 환경이 초기화 되는 것 같아, `@Test` 메소드 한 개에 검사하고자 하는 메소드를 한꺼번에 넣었습니다. 

   >- 미션2 리뷰: https://github.com/codesquad-members-2021/java-chess/pull/60#discussion_r575582823 
   >- 미션3 커밋링크:  26a0906fcdc74e5adb3a0ba181a330f70c792f22

#### 3. Pawn 열의 결과를 생성하는 `getWhitePawnsResult()`, `getBlackPawnsResult()` 메소드의 리팩토링을 어떻게 해야 할지 감이 오질 않습니다.  

   >- 좋은 방법이 떠오르지 않아, 단순히 메소드를 분리 해두긴 했는데 조언해주시면 감사하겠습니다.
   >- 커밋링크: d72224de95d629152bb30017e0b372592c6ba18a

#### 4. 체스를 출력하기 위해 2차원 리스트(`List<String[]> boardList`) 를 사용하였는데, 올바른 방식인지 궁금합니다.

 >- 커밋링크1: c142e1176304cec90d774790b341a891e4621f6f
 >- 커밋링크2: c191f00120b6d6617406e148812a3e79cab9c054

#### 5. initialize() 메소드에서 중복되는 리스트 삽입과정을, 반복문으로 리팩토링 하다보니 가독성이 더 떨어진 것 같습니다.

 >- 커밋링크: a898985b37104a9f0f07e69d00458951efd6b98b

2021-02-16 10:20 UTC, LarryJung reviewed
3단계부터 요구사항이 확 복잡해져서 고민을 많이하신 게 느껴집니다!
잘 하셨지만 더 간결하게 짤 수 있는 방법에 대해서 좀 더 학습해 보실 것을 권해드립니다.

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        StringBuilder PawnLine = new StringBuilder();
변수 이름은 camelCase로 써주세요~

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +    }
요 로직 뿐 아니라 전반적으로 for i 문이 많은 것은 객체를 별로 활용하지 못하고 있다는 사인이 될 수 있습니다. 왜냐하면 포문 안에 `int i`가 등장한 이유는 `i`를 가지고 리스트의 인덱스로 접근하겠다는 의도가 있기 때문인데요~ 보통 이렇게 되면 데이터를 꺼내오는 식의 사고를 주로 하게 되어 객체 중심적으로 짜기 어렵게 될 수도 있습니다. (제 생각입니다.ㅋㅋ)

for문을 사용할때 for each 문 또는 스트림을 활용해보세요

저라면 가지고 있는 pawns를 이용하여 충분히 간결하게 짤 수 있을 것 같네요
```java
public String appendPawnRep(UnitColor color) {
  StringBuilder pawnLine = new StringBuilder();
  for (pawn : pawns) {
    // 색상이 같으면 append
    if (pawn.isColor(color)) pawnLine.append(pawn.getRepresentation());
  }
  return pawnLine.toString();
}
```

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +    }
클래스 내부에서만 쓰이는 메서드이므로 private으로 선언해주세요

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +    private final List<String[]> boardList = new ArrayList<>();
멤버 변수를 3개 이하로 줄여보세요. (충분히 가능합니다!)

보드를 출력하는데 필요한 최소한의 정보는
```java
private final List<Pawn> pawns = new ArrayList<Pawn>();
private final String defaultUnitRep = "........";
```

이정도만 있어도 충분할 것 같습니다. 위치에 대한 정보가 필요하다면 Pawn 안으로 넣을 수도 있고,
위치,Pawn 을 감싼 새로운 클래스가 필요할 수도 있을 것 같구요~

특히나 whitePawn, blackPawn 은 arrayPawnInit 의 로컬변수로 선언이 되어도 될것으로 보이네요!

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +        }
그런데..  boardList가 꼭 initialize할때 초기화 되어야 할까요? 
initialize할때는 기물(현재는 pawn)만 잘 셋팅을 하고, Print 할때 그때그때 로직을 돌려도 될것 같은데요~

지금처럼 폰 셋팅할때 한번에 프린트될 내용까지 초기화를 하면, 게임 도중 폰 색깔이 바뀔 때 정합성 문제가 생길 수 있고
프린트 로직은 다른 기능으로 분리하기도 어렵습니다.

요지는 boardList 또한 꼭 가지고 있어야 할 멤버변수인지 고민해보시고 ㅎㅎ
Board가 어떤 데이터가 아닌 꼭 필요한 객체는 무엇인지? (추상적이네요..) 그리고 그 객체로 뭘 할 수 있을지? 를 고민해주시면 좋을 것 같습니다

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/Pawn.java
> +    public static final char WHITE_REPRESENTATION = 'p';
enum 을 좀 활용해보자면..
```java
private static final Map<UnitColor, char> colorMap;

...

public UnitColor getColor() {
  return this.colorMap.get(this.color);
}
```

이렇게 할 수도 있겠네요~

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/Pawn.java
> +    private final char shape;
Board와 유사하게 말씀드리면.. 
1. shape가 미리 선언이 되는 것과
2. getShape() 할때 그때 로직을 돌리기

두 가지 방식으로 짤 수 있을 것 같고 위에 map 예제 드린 것과 한번 비교해보세요!

2021-02-16 10:20 UTC, LarryJung commented on src/test/java/BoardTest.java
> +    int totalPawnCnt;
특별한 목적이 없다면 private으로 선언해주세요.

2021-02-16 10:20 UTC, LarryJung commented on src/test/java/BoardTest.java
> +    int totalPawnCnt;
그리고 initialize() 테스트에서 하셨던 것처럼 Board를 꼭 테스트 클래스의 멤버 변수로 필요는 없을 것 같습니다~ createPawn 테스트 안에서 직접 로컬변수로 선언해서 테스트환경을 더 좁게 가둬두는것도 좋습니다.ㅎㅎ

2021-02-16 10:20 UTC, LarryJung commented on src/main/java/net/sanhee/chess/ChessGame.java
> +}
👍

2021-02-17 05:39 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        StringBuilder PawnLine = new StringBuilder();
와!!!! 빠르고 세심한 리뷰 너무 감동 받았습니다 👍
리뷰 반영해서 수정했습니다!

2021-02-17 05:45 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +    }
감사합니다, 수정했습니다!

2021-02-17 05:49 UTC, sanhee commented on src/main/java/net/sanhee/chess/ChessGame.java
> +}
감사합니다😁 
현재 바로 고칠 수 있는 간단한 수정사항부터 우선적으로 진행 하고 있습니다.👀

2021-02-17 06:03 UTC, sanhee commented on src/test/java/BoardTest.java
> +    int totalPawnCnt;
테스트코드에서 클래스와 메소드에 접근제어자를 쓰지 않는 것을 
변수에도 해당하는것으로 착각했었습니다...
수정하였습니다. 감사합니다😊

2021-02-17 06:53 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +    }
와...✨ 저는 이런 생각을 도저히 하지 못했었는데..
새로운 사실과 제 무지함(?)에..정말 충격 받았습니다. 
팁 감사합니다.  stream으로도 한번 도전 해보겠습니다.

2021-02-17 07:58 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +    private final List<String[]> boardList = new ArrayList<>();
리뷰 감사합니다 ㅎㅎ
우선 whitePawn, blackPawn을 initialize() 메소드의 지역변수로 만들고 push 하였습니다.
boardList는 좀 더 생각 한 후 개선하겠습니다!

2021-02-17 08:24 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +        }
그러고보니 기존 상태는 프린트를 하면 초기 상태의 체스 보드판만을 출력해서 게임 진행이 불가능했겠네요.. 
initialize 에 넣었던 boardList가 게임 도중에 문제가 생길거란걸 미처 생각 못했습니다.😥 

추가적으로, boardList 또한 꼭 필요한 멤버가 아닌 것 같아서, print() 메소드의 로컬변수로 변경했습니다.

섬세한 리뷰 감사합니다!🤠

2021-02-17 08:29 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +    private final List<String[]> boardList = new ArrayList<>();
boardList를 print() 내부로 이동시켰습니다!

2021-02-17 08:59 UTC, sanhee commented on src/main/java/net/sanhee/pieces/Pawn.java
> +    private final char shape;
map 예제를 하기전에 먼저 할 수 있는 코드를 짜보았습니다!

```java
public char getShape(){
        switch (this.color) {
            case BLACK:
                return BLACK_REPRESENTATION;
            case WHITE:
            default:
                return WHITE_REPRESENTATION;
        }
    }
```

2021-02-17 10:17 UTC, sanhee commented on src/main/java/net/sanhee/pieces/Pawn.java
> +    public static final char WHITE_REPRESENTATION = 'p';
```java
    private static final Map<UnitColor, Character> colorMap = new HashMap<UnitColor, Character>() {{
        put(UnitColor.BLACK, 'P');
        put(UnitColor.WHITE, 'p');
    }};

   public char getShape() {
        return colorMap.get(this.color);
    }
```

와 같이 구현을 했는데, 지금 단계에서는 final로 선언해둔게 좀 더 직관적인 것 같아서 커밋을 하지 않았는데 제가 잘못 구현한걸까요??

2021-02-17 11:12 UTC, sanhee commented
리뷰해주신 사항 반영하면서 `Resolve Conversation` 버튼을 눌렀는데,
제가 임의로 눌러도 되는게 맞을까요??

2021-02-17 11:19 UTC, LarryJung commented on src/main/java/net/sanhee/pieces/Pawn.java
> +    public static final char WHITE_REPRESENTATION = 'p';
아~ 아니요 ㅎㅎ 정답은 없으니 나중에 더 수정이 필요하다 싶으면 계속 고치시면 되겠습니다!

2021-02-17 11:32 UTC, LarryJung requested changes

2021-02-17 11:32 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +    }
이전보다 이렇게 하는게 더 보기가 좋은것 같네요 저는 .^^

2021-02-17 11:32 UTC, LarryJung commented on src/main/java/net/sanhee/chess/Board.java
> +
이 부분도 조금 리팩토링을 해보자면

```java
public void initialize() {
        arrayPawnInit(UnitColor.WHITE);
        arrayPawnInit(UnitColor.BLACK);
    }

private void arrayPawnInit(UnitColor color) {
    for (int i = 0; i < Pawn.MAX_SPAWN_NUMBER; i++) {
        pawns.add(new Pawn(color));
    }
}
```

이렇게 할 수 있지 않을까요? 변수는 적을수록 좋다는 말도 있으니(다 그런건 아닙니다만..) 기억해주세요!

2021-02-17 11:39 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +    }
저도 그렇게 생각합니다!! 훨씬 간결해지고 이해하기 쉬운 코드가 된 것 같습니다. ㅎㅎ

2021-02-17 11:48 UTC, sanhee commented on src/main/java/net/sanhee/chess/Board.java
> +
이 부분도 전혀 생각치 못했는데, 코드를 짤 때 조금 더 신경써서 짜야겠습니다😂
꼭 필요없는 변수를 사용해서 낭비하고 있었네요.
리뷰해주신 내용 반영해서 push 했습니다!!

정말 섬세한 리뷰 너무 감사드립니다..감동입니다 😀

2021-02-17 15:08 UTC, LarryJung approved these changes
네 확인했습니다! 수고하셨습니다.^^ 다음단계 준비하시죠~

2021-02-17 15:46 UTC, sanhee commented
죄송합니다...실수로 close 눌렀네요..

다음부터는 주의하겠습니다.

2021-02-18 09:17 UTC, merged