[cooper] 미션3 : 체스판 초기화
codesquad-members-2021/java-chess pull request #85
Opened 2021-02-16 05:44 UTC by pbg0205

안녕하세요.

코드스쿼드 2021 마스터즈 백엔드 과정 Cooper 입니다.
미션3 : 체스판 초기화 리뷰 부탁드립니다. 

### 미션3 변경사항
-  Pawn 클래스 멤버 변수 representaion을 추가하였습니다.
Pawn의 represetation 추가 방법에 대해 고민하였습니다. color와 representation을 매개인자로 받는 생성자를 선언하는 방법도 고민해보았지만 Color enum에 내부 변수를 별도로 선언해 representation을 초기화하면 별도의 예외 처리가 필요하지 않을 것 같다고 판단했습니다. representation enum을 선언하는 방법도 고려해보았습니다만 폰 하나만 존재하는 상황에서 색상에 따라서 representation을 할당할 수 있기 때문에 representation enum은 잠시 보류해두었고 우선적으로 내부 변수로 할하는 방법으로 구현 진행하였습니다.

- Board 클래스의 리스트를 HashMap으로 관리하도록 변경하였습니다.
 흰색과 검정색 폰을 관리하기 위해 whitePawnList와 blackPawnList를 별도로 관리하였습니다. 하지만 코드를 작성하는 과정에서 같은 기능이지만 다른 List를 사용하기 위한 중복 코드가 계속해서 발생하였습니다.
 각각의 color에 따라서 리스트를 참조할 수 있다면 중복되는 메서드가 줄어들고 리스트를 관리하기에 더욱 용이하다고 판단했습니다. 그래서 Color를 Key값, List<Pawn>를  value로 가지는 HashMap를 선언하여 색상에 따른 폰리스트를 관리할 수 있도록 구현했습니다.

- Board print 메서드를 구현했습니다.
 폰들은 배치되는 각각의 행이 정해져 있어 해당 행일 경우에만 List에 존재하는 폰들을 출력하는 방식으로 구현 진행하였습니다. 그래서 Board 클래스에 폰이 초기화되는 행 번호를 상수로 선언하였고 각각의 폰이 위치하는 행을 추가하였습니다.

- 메인클래스 로직을 추가하였습니다.
 while문에 조건으로 isPlaying이라는 boolean 변수를 이용해 현재 게임 중인 상태를 확인하고 start 명령어를 입력받을 경우 현재 초기화된 상태를 출력하고 end 명령어를 입력받을 경우, isPlaying = false 형태로 변경하여 게임이 종료되도록 구현하였습니다.

2021-02-16 10:12 UTC, imjinbro commented on src/main/java/cooper/chess/Board.java
> +    public String print () {
print 라는 메소드명으로 되어있어서 판을 출력하는 역할까지 할 것으로 보였는데, 코드 상에서는 체스판만 리턴하고 있네요
Board 클래스 역할을 잘 인지하셔서 프린트 하는 역할(System.out.println)까지 맡지 않도록 한 것까지는 좋았으나 메소드명은 체스판을 가져온다는 의미로 지어주시면 좋겠습니다.

2021-02-16 10:18 UTC, imjinbro commented on src/main/java/cooper/chess/Main.java
>      public static void main(String[] args) {
지금은 코드가 몇줄 안되어서 읽기 어려운건 아니지만 조금 더 넘어가면 하나라도 놓치면 읽기가 힘들 수 있을듯해요
커맨드에 대한 처리 메소드를 만드신 것처럼 메소드로 묶어보는건 어떨까요?

잡지의 목차(아래)처럼 코드 작성하신다면 한 눈에 코드가 어떤 기능들을 할지 보여서 더 좋을 것 같아요!
1. XX
2. OO
3. TT

2021-02-16 10:18 UTC, imjinbro commented on src/main/java/cooper/chess/Main.java
> +        Scanner scanner = new Scanner(System.in);
지금은 코드가 몇줄 안되어서 읽기 어려운건 아니지만 조금 더 넘어가면 하나라도 놓치면 읽기가 힘들 수 있을듯해요
커맨드에 대한 처리 메소드를 만드신 것처럼 메소드로 묶어보는건 어떨까요?

잡지의 목차(아래)처럼 코드 작성하신다면 한 눈에 코드가 어떤 기능들을 할지 보여서 더 좋을 것 같아요!

XX
OO
TT

2021-02-16 10:24 UTC, imjinbro commented on src/main/java/cooper/chess/Board.java
> +    private final Map<Color, List<Pawn>> pawnListMap;
데이터 타입이 조금 복잡해지는게 느껴지실까요?
컬러가 소유한 pawn을 다루기가 복잡해지실거예요 
하나의 클래스로 분리해보는 것도 추천드립니다.
관련된 링크 하나 남겨두도록 하겠습니다.
https://jojoldu.tistory.com/412

2021-02-16 10:29 UTC, imjinbro commented on src/main/java/cooper/chess/Board.java
> +    public String print () {
요구사항에 print()를 만들어라고 되어있지만 System.out.println() 이라는 실제 출력하는 역할이 Main 클래스에 있다면 
Board 클래스의 메소드는 출력 역할이 아니므로 코드 읽는 이 또는 협업하는 팀원이 혼동되지않도록 이름을 지어주는 것도 중요합니다~!

2021-02-16 10:29 UTC, imjinbro commented on src/test/java/cooper/chess/piece/PawnTest.java
> +    public void create_defaultConstructor() {
junit5 > @DisplayName 을 사용하여 해당 테스트가 어떤 역할인지 표시하는 것도 해보시길 권해드립니다!

2021-02-16 10:35 UTC, imjinbro requested changes
안녕하세요 리뷰어 콜린입니다.
몇가지 코멘트를 남겨드렸습니다.
메소드를 분리하는 것과 pawnListMap 복잡한 구조를 수정 어떻게 할지 조금 더 고민해보시면 좋을듯 하여 Request changes 드립니다.

2021-02-17 07:21 UTC, pbg0205 commented on src/main/java/cooper/chess/Main.java
> +        Scanner scanner = new Scanner(System.in);
조언 감사합니다!😄 Main class에 체스 게임 내부 로직을 구현하는 것보다 전체적인 게임 로직을 담당하는 클래스에서 별도로 관리하는 것이 나을 것 같아 별도의 ChessGame 클래스를 선언해보았습니다. ChessGame 내부에서 리뷰해주신 내용대로 메서드를 분리시키는 방식으로 진행해보았는데 혹시 부족한 부분 있으면 말씀 부탁드립니다!

2021-02-17 07:21 UTC, pbg0205 commented on src/test/java/cooper/chess/piece/PawnTest.java
> +    public void create_defaultConstructor() {
리뷰해주신대로 각각의 테스트에 @display 어노테이션을 추가해보았습니다!

2021-02-17 07:22 UTC, pbg0205 commented on src/main/java/cooper/chess/Board.java
> +    private final Map<Color, List<Pawn>> pawnListMap;
말씀해주신대로 일급 객체 형태로 구현해보려고 별도로 PawnGroup으로 클래스를 분리해서 작성해보았습니다. 하나 고민이 들었던 부분이 생성자의 매개인자로 Map<Color, List>을 아규먼트로 받아올 때, List 내부에 모든 element들을 추가한 상태도 전달 하는 방법이 불변성을 유지하는 방법인지에 대해 고민했습니다ㅠ Map에 final을 선언해서 Map의 불변성이 유지할 수 있지 않을까 해서 빈 ArrayList를 전달받고 List 안에 element를 추가할 수 있는 방법으로 구현해보았는데 이렇게 구현해도 불변성이 유지가 되는 방법이 맞는지 궁금합니다ㅠ

2021-02-17 07:22 UTC, pbg0205 commented on src/main/java/cooper/chess/Board.java
> +    public String print () {
@imjinbro 아무래도 print라는 내용이 출력을 의미하는 부분인데 요구사항에 맞추려보니 그대로 명명하게 되었습니다ㅠ 메서드명을 getBoardStatus와 각 행을 탐색하는 메서드명도 printEacchRow -> getEachRowStatus 재명명하였는데 getter 느낌이라서 정확한 명명인지는 확신이 잘 안서네요ㅠ 확인 부탁드립니다!

2021-02-17 15:57 UTC, imjinbro commented on src/main/java/cooper/chess/Board.java
> +    public String print () {
print 명명보다는 더 나아보여서 좋네요
정답은 없지만 다른 사람이 코드를 읽었을 때 어떨까 라는 생각도 같이 해보시면서 짜시면 조금이라도 도움 되지 않을까 생각해봅니다!
수고하셨습니다

2021-02-17 15:59 UTC, imjinbro commented on src/main/java/cooper/chess/Main.java
> +        Scanner scanner = new Scanner(System.in);
메소드로 구분해주니 코드 읽기가 한결 편해졌군요
Main, ChessGame을 굳이 구분하지않고, Main을 ChessGame으로 변경하는 것도 좋은 방법이라고 생각합니다.

2021-02-17 16:10 UTC, imjinbro commented on src/main/java/cooper/chess/Board.java
> +    private final Map<Color, List<Pawn>> pawnListMap;
final을 굳이 지정해주지 않더라도 setter 메소드를 외부에 공개하지않는다면 불변성은 유지가 되겠죠?
저 글에서 언급한 불변성도 위의 이야기로 보입니다.
현재는 Public으로 할당된 메소드가 없다보니 타 플레이어가 뭔가 변경할 수가 없겠네요
객체의 상태(멤버필드 할당된 값)는 객체(본인)가 판단하여 변경한다에 대해서 공부해보시면 좋을 것 같네요

그리고 제가 컬렉션을 클래스 랩핑하길 추천드린건 복잡한 콜렉션 타입을 필드로 가지고 있다보니 
코드가 점점 복잡해지는 면이 있어보여서 추천드리긴 했습니다.
이 방법(랩핑 클래스 만들기) 말고도 다른 방법이 또 있을 수 있으니 이제 변경은 하지 않더라도 앞으로 코딩 하실 때 여러 안에 대해서 고려 해보는 습관을 길러보는 것도 추천드립니다!

고생하셨어요 👍🏼

2021-02-17 16:10 UTC, imjinbro approved these changes

2021-02-18 09:36 UTC, honux77 commented
수고하셨어요!

2021-02-18 09:36 UTC, merged