[Bibi] 미션2 - 체스판 생성 PR입니다.
codesquad-members-2021/java-chess pull request #88
Opened 2021-02-16 09:06 UTC by bibi6666667

안녕하세요. 백엔드반 Bibi입니다.😊
미션 2단계 Pull 요청 드립니다.

<작업 내용>
- (기본 생성자)자바 생성자를 공부하며 Pawn클래스에 매개변수 없는 생성자를 만들고, 컴파일 에러를 해결했습니다.
- (상수)자바 상수에 대해 공부하고, Pawn 클래스에 상수를 만들어 중복코드를 제거했습니다.
- (체스판)Board클래스를 만들고 BoardTest를 추가해 제시된 테스트를 완료했습니다. 또, BoardTest에서 Pawn이외 객체 추가시 컴파일 에러가 나는 것을 확인했습니다.
- (패키지 분리)기존 패키지 bibi를 삭제하고 pieces, chess패키지를 만들어 각각 Pawn과 Board를 넣었습니다.
- (중복 제거) 각 클래스의 중복 코드를 제거했습니다. 인스턴스변수를 사용하고, 메소드를 분리하는 방법으로 중복을 제거했습니다. 테스트 클래스의 경우 @BeforeEach 사용법을 배우고 적용해 중복을 제거했습니다.

<학습 내용>
기본 생성자, 상수, 패키지 분리하는 법과 import 복습, JUnit과 AssertJ의 개념 및 기초적인 사용법(assert메소드, 어노테이션)

부족한 점이 많은 코드라고 생각합니다. 어떤 것이든 괜찮으니 많은 조언과 피드백 부탁드리겠습니다! 
매 미션마다 코드리뷰 신경 써 주시는 점 감사드립니다🙇‍♀️🙇‍♀️ 좋은 저녁 되세요!

2021-02-16 10:10 UTC, honux77 requested changes
수고하셨어요. 코드 개선해서 다시 리뷰 요청 해 주세요.

2021-02-16 10:10 UTC, honux77 commented on src/main/java/bibi/Pawn.java
>      }
final 변수인데 생성자를 통해 값을 넣을 수 있다는 게 신기하지 않나요? 왜 그럴까요?

2021-02-16 10:10 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private ArrayList<Pawn> pawns = new ArrayList<>();
List<Pawn> pawns = ... 으로 많이 사용합니다.

2021-02-16 10:10 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +import static org.junit.jupiter.api.Assertions.*;
assertEquall은 제거하고 asssertThat을 사용해 주세요.

2021-02-16 10:10 UTC, honux77 commented on src/main/java/bibi/Pawn.java
>          this.color = color;
지금 Pawn이 두 개인것 같네요. 불필요한 클래스는 제거해 주세요.

2021-02-16 10:10 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +        this.color = WHITE;
this(WHITE);

2021-02-16 10:10 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +        Pawn white = new Pawn(Pawn.WHITE);
만들었던 기본 생성자를 활용해 보는 건 어때요?

2021-02-16 10:10 UTC, honux77 commented on src/test/java/pieces/PawnTest.java
> +    @DisplayName("색이 없는 폰 생성")
이름과 내용이 맞지 않아요.

2021-02-17 05:56 UTC, bibi6666667 commented on src/main/java/bibi/Pawn.java
>      }
final로 선언한 변수는 값을 변경할 수 없는 상수가 된다고 알고 있었습니다.
따라서, 위처럼 생성자에서 값을 할당하는 것은 값을 변경하는 게 아닌 초기화 과정이므로 문제가 없다. 까지 이해하고 있었습니다.
그런데 생각해 보니 'final로 변수를 선언할 때는 선언과 초기화를 동시에 해야 하며, 그렇지 않은 경우 컴파일 에러가 발생한다'고 알고 있었는데 제 코드가 왜 잘 동작하는지 이상해졌습니다🤔
자바의 정석에서 final 관련 내용을 찾아보니 , 인스턴스변수의 경우에는 예외적으로 생성자에서 초기화가 가능하다는 것을 배웠습니다. final인스턴스변수라도 각 인스턴스마다 다른 값을 가질 수 있어야 하기 때문이었네요.
질문을 던져 주시지 않았다면 깊게 공부하지 못했을 텐데, 코멘트 주셔서 감사합니다! 🙇‍♀️🙇‍♀️

2021-02-17 05:58 UTC, bibi6666667 commented on src/main/java/chess/Board.java
> +    private ArrayList<Pawn> pawns = new ArrayList<>();
그렇군요! 해당 부분 수정한 다음, 왜 ArrayList는 List로 업캐스팅(맞나요?)해서 사용하는지 구글링하고 학습했습니다. 
사실 아직도 완전히 이해되진 않아서, 우선 더 공부해 본 뒤에 목요일 수업 sli.do에 질문 남겨 보겠습니다!
코멘트 감사합니다🙇‍♀️🙇‍♀️

2021-02-17 06:00 UTC, bibi6666667 commented on src/test/java/chess/BoardTest.java
> +import static org.junit.jupiter.api.Assertions.*;
BoardTest와 PawnTest에서 `assertEqual()`을 사용했던 부분을 모두 `assertThat().isEqualTo()`로 변경했습니다.
아울러 AssertJ 에서 제공하는 여러 메서드들도 공부하고 정리하겠습니다.
코멘트 감사합니다!🙇‍♀️

2021-02-17 06:01 UTC, bibi6666667 commented on src/main/java/bibi/Pawn.java
>          this.color = color;
앗.. 급한 마음에 제대로 확인하지 못하고 PR드려서 죄송합니다😭 수정하겠습니다!

2021-02-17 06:01 UTC, bibi6666667 commented on src/test/java/pieces/PawnTest.java
> +    @DisplayName("색이 없는 폰 생성")
이 부분도 제대로 확인하지 않고 PR드려서 죄송합니다🙇‍♀️ 수정하겠습니다!

2021-02-17 06:04 UTC, bibi6666667 commented on src/test/java/chess/BoardTest.java
> +        Pawn white = new Pawn(Pawn.WHITE);
수정하겠습니다! 코드 중복만 없애는 게 아닌, 만들어 둔 모듈을 활용해 코드를 간결하게 하는 것도 리팩토링에 중요함을 기억헤 두겠습니다.
코멘트 감사합니다!🙇‍♀️

2021-02-17 06:09 UTC, bibi6666667 commented on src/main/java/pieces/Pawn.java
> +        this.color = WHITE;
this()를 처음 접했어서 구글링과 자바의 정석 통해 공부한 뒤 해당 부분 변경했습니다!
그런데 한 가지 질문이 있는데,
이렇게 `this.color = WHITE` 에서 `this(WHITE)`로 수정한 것은 기능 수정이 아닌 리팩토링에 해당하는 것이 맞나요?
코드 외형만 바뀌었을 뿐 결국 `Pawn(String color)` 생성자를 호출하기 떄문에 리팩토링이다. 라고 이해했는데,
가능하시다면 조언 부탁드립니다.
코멘트 주셔서 감사합니다 호눅스! 🙇‍♀️🙇‍♀️

2021-02-17 06:29 UTC, bibi6666667 commented
@honux77 안녕하세요, 백엔드반 Bibi입니다.
미션2 PR에 피드백 주신 부분에 대해 공부하고, 코드 개선하여 다시 Pull 요청 드립니다.

<추가로 학습한 부분>
- `List 리스트 = ArrayList`로 업캐스팅? 하여 선언하는 이유
- `this()` 에 대해, 그리고 `this`와의 차이점
- AssertJ에서 제공하는 다양한 assert메소드들 및 사용법 (더 학습 필요)
- `final` 인스턴스 변수 관련 심화 학습

<느낀 점>
- 중복 코드만 피한다고 리팩토링이 다가 아니다. 만들어 둔 모듈을 활용해 코드를 간결하게 하자.
- 내 코드를 잘 살핀 다음 PR을 신중하게 해서 잔실수들을 예방하자..😅

저는 자바 관련 서적 진도 나가고 수업 듣는 것도 재밌지만, 이렇게 직접 코딩하고 피드백 받으며 찾아서 공부하니 지식이 와닿는 느낌이라 요즘 재미있게 공부하고 있습니다! 
그리고 깃 공부가 자동으로 되는 것도 참 좋은 학습방식이라고 느낍니다.👍

신경 써서 자세한 피드백과 코멘트 남겨 주시고, 좋은 질문도 던져 주셔서 감사합니다.🙇‍♀️🙇‍♀️
끝으로 즐거운 오후 되세요! 😀

2021-02-18 15:30 UTC, honux77 approved these changes
💯

2021-02-18 15:31 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +        this.color = WHITE;
넵 맞아요.

2021-02-18 15:32 UTC, honux77 commented on src/main/java/bibi/Pawn.java
>      }
JVM이 생성자를 만나야 객체의 인스턴스를 힙에 생성하기 때문에 final 인스턴스 변수는 생성자에서 초기화할 수 있습니다.
static final 변수는 그렇지 않겠죠?

2021-02-18 15:32 UTC, merged

2021-02-19 01:53 UTC, bibi6666667 commented on src/main/java/pieces/Pawn.java
> +        this.color = WHITE;
그렇군요! 감사합니다😀

2021-02-19 01:54 UTC, bibi6666667 commented on src/main/java/bibi/Pawn.java
>      }
아 원리적으로도 그렇군요. JVM에 대해 더 자세히 공부해 보겠습니다. 감사합니다😀🙇‍♀️