[Starve] Mission3 - 체스판 초기화
codesquad-members-2021/java-chess pull request #89
Opened 2021-02-16 09:19 UTC by Jiwon-JJW

안녕하세요! 미션 3를 완료 하여, 세번째 PR 요청 드립니다.

## 변경 사항

**Pawn**
Pawn 클래스 내의 Color Enum을 별도로 관리하기 위한 작업을 진행하여, 특정 메소드의 수정 작업을 진행했습니다.

**PawnTest**
Pawn 클래스의 변경으로 인하여, create 메소드 수정 작업을 진행했습니다.
assertEquals 대신 assertAll을 사용하는 방식으로 verifyPawn을 수정했습니다.

**BoardTest**
체스 말을 확인하는 initialize 테스트를 추가하였습니다.
Board 클래스의 특정 메소드 변경으로 인하여 전체적으로 수정작업을 진행했습니다.

**Board**
ArrayList를 사용한 Pawns를 색상별로 분류하여, 값을 얻는 메소드들을 수정했습니다.
BoardTest클래스에서 initialize테스트를 위해 getPawnsResult 를 생성했습니다. 중복 코드를 방지하기 위함이며, 각 색상별로 값을 리턴하는 메소드도 추가하였습니다.
체스판을 List로 관리하기 위하여 ArrayList를 추가하였습니다. 따라서 체스판 초기화 및 출력을 할 수 있는 메소드 또한 추가하였습니다.

**Color**
미션 2에서 Pawn내에 있던 Enum을 별도로 관리하기 위하여 분리시켰습니다.
color와 representation를 얻기 위한 메소드도 추가하였습니다.

**Main**
입출력을 담당하는 main 메소드를 가지고 있는 클래스를 생성하였습니다.

감사합니다!

2021-02-16 11:31 UTC, ksundong requested changes
안녕하세요! Starve! 리뷰어 디온입니다. 3단계 미션을 수행하시느라 애써주셨습니다.
전체적인 동작은 지켜주셨지만, 아쉬운 부분이 조금 있어서 변경 요청을 드렸습니다.
궁금하시거나, 도움이 필요한 부분은 언제든지 코멘트 남겨주시면 확인하고 답변을 드리겠습니다.
수정을 마치신 다음에, 리뷰어로 지정해주시면 바로 리뷰 해드리겠습니다!

## 리뷰

- 꼭 코드 포매팅을 수행해주세요.
- 꼭 접근 제어자를 신중하게 지정해주세요.
- 책임 단위로 메서드 분리를 해주세요.
- JUnit5, assertJ를 학습까진 아니더라도, 계속해서 사용해주세요.
- 이름 짓기(매직넘버 지양, 메서드가 하는 일에 맞는 이름을 지어주세요)
- 가능하시다면 `print()`도 테스트를 시도해봐주세요. (필수x)

고생많으셨어요~ 조금만 수정해주시면 좀 더 좋은 코드가 될 것 같습니다!

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +    List<Pawn> blackPawn = new ArrayList<>();
접근제어자에 신경써주세요!!

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +    List<String []> board = new ArrayList<>();
이 형태는 뭔가 많이 잘못된 것 같습니다.
차라리 String 배열을 어떤 클래스로 뽑아내는 편이 좋아보여요.
그리고 접근제어자 잊지 말아주세요~

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +    List<Pawn> blackPawn = new ArrayList<>();
그리고, 컬렉션의 경우에는 복수형 이름을 지어주시는게 더 좋아보입니다!

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
>      }
이 곳 역시 접근제어자가 누락되었습니다. 정말 이 메서드가 package-private이 맞나요?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
switch문은 enum과 함께 쓸 때, enum 자체로 사용이 가능합니다. 한 번 개선해보세요~

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        return sb.toString();
64번 라인의 `sb.toString()`은 리턴이 되어야 하는 이유가 있나요?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
매직넘버가 곳곳에 쓰였습니다. 8은 무엇인가요? 1과 6은 무엇인가요?
코드를 읽는 입장에서는 이 코드는 이해하기 매우 어려운 코드입니다.
보다 간단하게 처리할 수도 있을 것 같은데 한 번 리뷰받으시고 나서 개선하신 후에 다시 개선 포인트를 찾아보는 것도 좋아보입니다.

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
그리고 각각 split을 해주는 부분도 뭔가 깔끔하지 않죠?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        for (int i = 0; i < 8; i++) {
여기에도 8이라는 매직넘버가 있네요.

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        return sb.toString();
이 메서드는 너무 많은 일을 하고 있습니다.
`initialize()`가 여기 있어야 할까요? Main에 있는 것이 더 좋지 않을까요?

그리고 같은 패키지가 아니면 실행조차 되지 않으니 Main이 같은 패키지에 묶여버리게 될겁니다.

그래도 결과를 String으로 반환해주시는 것은 좋은 선택입니다.

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +        return sb.toString();
다만 메서드 명을 바꿔주시는 것이 좋아보여요. print를 전혀 수행하지 않는 메서드이기 때문입니다.

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Main.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
`BufferedReader`를 써주셨는데, 왜 쓰셨는지 알 수 있을까요?
그리고 try-with-resources에 대해서 공부를 해보셨으면 좋겠습니다~

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Main.java
> +        String commend = br.readLine();
```suggestion
        String command = br.readLine();
```
오타가있네요

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Main.java
> +        br.close();
스트림을 닫아주신 것은 잘하셨습니다.

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/pieces/Color.java
> +    private final char representation;
`char` 형을 선택하신 이유가 혹시 따로 있나요?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/pieces/Color.java
> +}
https://github.com/codesquad-members-2021/java-chess/pull/9#discussion_r572027344
해당 코멘트 참고해서 설정 적용해주세요~

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/pieces/Pawn.java
> +    { return color.getColorName();
포매팅이 이상하게 잡힌 것 같네요. 확인부탁드려요~
그리고 `getColor()`라는 이름 말고 더 좋은 메서드명을 고민해주시면 좋겠습니다~
현재는 `color`를 줄 것 같지만 `colorName`을 반환하고 있네요.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +    public void create() {
메서드 명도 신경써주세요.
그리고 DisplayName은 좀 더 테스트 코드를 잘 설명하도록 해주시는게 좋아보여요.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +    public void create() {
지금은 Pawn이 생성됨을 테스트하는 것이 아니라, 해당 Pawn이 추가가 되는지를 보는 테스트 처럼 보입니다. 맞나요?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +    }
여기에 정말 하얀색 Pawn만 들어오는것이 보장이 되나요?

2021-02-16 11:31 UTC, ksundong commented on src/main/java/chess/Board.java
> +    }
아래의 `addBlackPawn()` 또한 같은 문제를 안고 있습니다.
어떻게 해결하면 좋을까요?

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
>  public class BoardTest {
JUnit5에서는 클래스와 Test 애너테이션이 붙은 메서드에는 `public` 키워드를 붙이지 않는 것이 일반적입니다.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals("black",board.getBlackPawn(0).getColor())
assertJ를 사용한 코드로 바꿔주세요.
assertJ는 `assertThat()`으로 시작하는 메서드입니다.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals("black",board.getBlackPawn(0).getColor())
`assertAll()` 로 묶어주시려고 한 시도는 좋은 것 같아요.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("폰이 제대로 생성되었는지 확인한다.")
여기도 테스트를 잘 설명하도록 고쳐주시거나 지워주세요~

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/pieces/PawnTest.java
> +    public void createWhite() {
메서드명하고 DisplayName하고 얘기하는게 다르네요. 어떤게 맞는건가요?

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/pieces/PawnTest.java
> +        verifyPawn(Color.WHITE);
이름은 verifyPawn인데, Color를 받는 것이 조금 이질적으로 느껴집니다.
너무 많이 추출이 된 것은 아닌지 생각해봅시다.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/pieces/PawnTest.java
>      }
위의 테스트에서 이미 검증이 되었는데 둘 다 검증하시는 이유는 무엇일까요?
제거해주셔도 괜찮은 것 같습니다.

2021-02-16 11:31 UTC, ksundong commented on src/test/java/chess/pieces/PawnTest.java
> +    public void verifyPawn(Color color) {
테스트 메서드에서 저는 접근제어자를 크게 신경쓰는 편은 아닌데요.
왜 `private`에서 `public`으로 변경하셨는지 궁금하네요!

2021-02-16 15:06 UTC, Jiwon-JJW commented on src/main/java/chess/pieces/Color.java
> +    private final char representation;
한 단어만을 사용하고 있기 때문에 String형보다 더 나을 것 같아 char형을 선택했습니다!

2021-02-16 15:06 UTC, Jiwon-JJW commented on src/test/java/chess/BoardTest.java
> +    public void create() {
Pawn이 추가가 되는지 확인하는 테스트가 맞습니다! DisplayName및 메서드명 수정하도록 하겠습니다!!

2021-02-16 15:06 UTC, Jiwon-JJW commented on src/main/java/chess/Board.java
> +    }
예외 처리를 하여 수정해보도록 하겠습니다!! 감사합니다!

2021-02-16 15:06 UTC, Jiwon-JJW commented on src/test/java/chess/BoardTest.java
> +                () -> assertEquals("black",board.getBlackPawn(0).getColor())
넵! 수정하도록 하겠습니다!

2021-02-16 15:06 UTC, Jiwon-JJW commented on src/test/java/chess/pieces/PawnTest.java
> +    public void createWhite() {
DisplayName 이 맞습니다! 메서드명 수정하겠습니다!

2021-02-16 15:11 UTC, Jiwon-JJW commented on src/test/java/chess/pieces/PawnTest.java
> +    public void verifyPawn(Color color) {
특별한 이유없이 다른 메서드들을 수정하다가 혼동하여 함께 수정된 것 같습니다!! 😅

2021-02-16 15:16 UTC, Jiwon-JJW commented on src/main/java/chess/Main.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
그간 알고리즘에서 보통 사용하였을 때 Scanner 보다 BufferdReader가 효율이 좋은 것을 느껴, BufferdReader를 사용하였습니다!
알려주신 사항에 대해서 공부해보겠습니다! 감사합니다

2021-02-16 15:43 UTC, Jiwon-JJW commented
말씀해주신 사항을 토대로 최대한 수정해보았습니다!  공부해봐야할 사항은 오전에 진행해보도록 하겠습니다!! 감사합니다!

2021-02-16 22:35 UTC, ksundong commented on src/main/java/chess/Main.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
그 효율은 어디에서 나왔을까요?
이런 부분에 대해서도 한 번 생각해보세요.😊
또한 우리의 프로그램에서 그 효율이 중요한 부분이 정말 의미가 있을까요?

2021-02-16 23:20 UTC, ksundong approved these changes
수정하느라 고생하셨어요!
다음단계에서 좀 더 고쳐보는게 좋을 것 같아요.
다음단계 진행해주세요~

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +    private final int BOARDSIZE = 8;
👍

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
로직이 조금 지저분하죠?
이 부분은 일단 메서드는 분리해둔 상태에서 각각 예외처리를 해주는 것이 어땠을까요?

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
또한 addPawns지만 한 개만 추가하고 있네요!

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +                return "존재하지 않는 색상입니다.";
사실 요 default는 존재하는 색상일 가능성이 크죠. 아마 별다른일이 없으면 실행되지 않을 것이기 때문에 empty string을 줘도 될 것 같아요.

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
여기에는 enhanced for loop 적용이 불가능한가요?

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Row.java
> +public class Row {
일급 컬렉션에 대해서도 공부해보세요~

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Row.java
> +    private final int BOARDSIZE = 8;
여기에도 같은 변수가 등장했군요 어쩌면 public한 상수로 빼는게 낫지않을까요?

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Row.java
> +    private List<Character> pices = new ArrayList<>(BOARDSIZE);
ArrayList의 크기를 지정해주면 어떤일이 생길까요?

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Row.java
> +    private List<Character> pices = new ArrayList<>(BOARDSIZE);
왜 Character List를 구성해주셨는지도 궁금하네요

2021-02-16 23:20 UTC, ksundong commented on src/main/java/chess/Board.java
> +    private List<Row> board = new ArrayList<>(BOARDSIZE);
지금 생각해보니 board가 하는 역할이 조금 애매합니다. Board안에 board가 또 있다고 생각할 수도 있고, 출력정보를 저장하는 것은 별로 효율적이지 않다고 생각되네요~

2021-02-16 23:20 UTC, ksundong commented on src/main/java/pieces/Pawn.java
> +    }
접근제어자 신경써주세요~

2021-02-16 23:20 UTC, ksundong commented on src/main/java/pieces/Pawn.java
> +package pieces;
패키지를 여기로 이동하셨는데 저는 좀 잘못된 선택이라고 봅니다. 어디서 미스커뮤니케이션이 발생했을까요?

2021-02-16 23:20 UTC, ksundong commented on src/test/java/chess/BoardTest.java
> +    @DisplayName("폰의 색상에 맞는 문자열을 출력하는지 확인한다.")
초기화가 되었는지 확인하는게 맞지않을까요?
테스트코드의 동작에 초점을 맞추기보단 우리가 테스트하려고 하는 것이 무엇인가에 초점을 맞춰주세요~

2021-02-16 23:20 UTC, ksundong commented on src/test/java/chess/BoardTest.java
>      }
이런식으로 테스트해줄 수 있겠죠? 잘하셨어요.🎉

2021-02-16 23:20 UTC, ksundong commented on src/test/java/chess/BoardTest.java
>  public class BoardTest {
여기는 아직 public이네요😅

2021-02-16 23:20 UTC, ksundong commented on src/test/java/pieces/PawnTest.java
> +    private void verifyPawn(Pawn pawn, String colorName, char representation) {
Color를 인자로 받는게 낫겠죠?

2021-02-17 01:18 UTC, Jiwon-JJW commented on src/main/java/pieces/Pawn.java
> +package pieces;
이렇게 패키지를 하는 편이 보기 더 편하지 않을까 하여 변경했는데, 지금 다시 보니 그 전처럼 패키지를 설정하여 진행 하는게 더 나을 것 같아 다시 수정할 예정입니다! 😅

2021-02-17 01:21 UTC, Jiwon-JJW commented on src/main/java/chess/Board.java
> +        }
한 번도 해본적이 없어, 미처 enhanced for loop를 적용할 생각을 해보지 못한 것 같습니다! 한 번 시도해보겠습니다!!

2021-02-17 02:06 UTC, Jiwon-JJW commented on src/main/java/chess/Row.java
> +    private List<Character> pices = new ArrayList<>(BOARDSIZE);
ArratList의 크기를 지정해 줄 경우, capacity의 값이 지정한 크기로 지정 됩니다. 이 capacity는 데이터가 꽉 찼을 때 또 데이터 입력이 발생되면 지정된 크기의 약 1.5배 정도 큰 배열이 새롭게 생성되어, 가지고 있던 데이터를 복사하여 배열을 반환하게 됩니다. 더 큰 데이터를 저장해야할 때는 크기를 지정해주는 것이 더 좋겠지만, 공부를 해보니 지금 상황에서는 딱히 지정해둬야할 필요성은 없는 것 같아, 수정하는게 더 나을 것 같다는 생각이 드네요!

Character List로 구성한 이유는, 현재 pawn이나 blank에 오는 문자들이 문자열로 지정되지 않아도 되는 것들이기 때문에 Character가 더 낫다고 생각을 하여 그렇게 생성했습니다!

2021-02-17 02:28 UTC, Jiwon-JJW commented on src/main/java/chess/Main.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
기본 입출력 스트림에 버퍼기능을 추가한 스트림을 사용하여 입력받기 때문에, 입력된 데이터가 바로 프로그램 내로 전달되지 않고 문자를 버퍼링하여 전달되어, 프로그램의 접근 속도가 더 빨라져서 효율이 더 좋게 나오는 것으로 확인했는데, 확실히 현재 프로그램에선 불필요하다고 생각되네요! 현재로써는 Scanner가 더 좋은 선택일 것 같습니다!
감사합니다!

2021-02-17 10:50 UTC, ksundong commented on src/main/java/chess/Row.java
> +    private List<Character> pices = new ArrayList<>(BOARDSIZE);
- 아 수정하시라는 의미는 아니었어요. 언어 스펙을 정확히 이해하셨으면 하는 의도였습니다.
- 그렇군요! 알겠습니다~

2021-02-17 10:56 UTC, ksundong approved these changes
고생많으셨어요. 다음 단계 진행해주세요!
코멘트 남긴 내용은 다음 단계에 반영해주셔도 좋을 것 같습니다!

2021-02-17 10:56 UTC, ksundong commented on src/main/java/chess/Board.java
> +    public static final int BOARDSIZE = 8;
보통 public static인 상수는 맨 위에 올려주는 경향이 많습니다~

2021-02-17 10:56 UTC, ksundong commented on src/main/java/chess/Board.java
> +        }
```suggestion
        if (pawn.getColorName().equals(Color.WHITE.getColorName())) {
            whitePawns.add(pawn);
            return;
        } 
        System.out.println("알 수 없는 color의 pawn입니다.");
        System.out.println("add에 실패하였습니다.");
```
early return이라는 방법입니다~

2021-02-17 10:56 UTC, ksundong commented on src/main/java/chess/Main.java
> +        }
굳이 발생할 예외가 없다면 catch 해주지 않아도 될 것 같아요~

2021-02-17 10:57 UTC, merged