미션 1: 체스 구현 시작하기
codesquad-members-2021/java-chess pull request #9
Opened 2021-02-08 08:17 UTC by Dae-Hwa

미션 1 완료했습니다.

2021-02-08 13:02 UTC, wheejuni requested changes
안녕하세요, 리뷰어 브라이언입니다.
첫 리뷰를 통해 만나뵙게 되어 정말 반갑습니다. 👍 💯 

아래 개선 의견 남겨드렸으니 한번 확인해 보시고, 혹여 추가적인 질문 사항이 생기신다면 댓글로 남겨주세요.

2021-02-08 13:02 UTC, wheejuni commented on src/test/java/kr/codesquad/freddie/chess/piece/PawnTest.java
> +    }
잘 구현해 주셨지만, 이렇게까지 분리하지 않아도 된다는게 제 생각이에요.

2021-02-08 13:02 UTC, wheejuni commented on src/test/java/kr/codesquad/freddie/chess/piece/PawnTest.java
> +        checkColor(Pawn.create("black"), Color.BLACK);
```suggestion
        assertThat(Pawn.create("black").getColor()).isEqualTo(Color.BLACK);

2021-02-09 03:38 UTC, Dae-Hwa commented on src/test/java/kr/codesquad/freddie/chess/piece/PawnTest.java
> +}
수정했습니다. 생각도 못하고 있었는데 그 동안 이런 실수를 많이 하고 있었겠네요 ㅠㅠ
참조해주신 문서 따라서 인텔리j 설정도 해놨습니다. 감사합니다!

2021-02-09 03:39 UTC, Dae-Hwa commented on src/test/java/kr/codesquad/freddie/chess/piece/PawnTest.java
> +    }
@wheejuni 
의견 주신대로 반영하여 수정했습니다!

2021-02-09 03:40 UTC, Dae-Hwa commented on src/test/java/kr/codesquad/freddie/chess/piece/PawnTest.java
> +        checkColor(Pawn.create("black"), Color.BLACK);
수정했습니다

2021-02-09 14:12 UTC, wheejuni approved these changes
수고하셨습니다 👍

2021-02-09 14:12 UTC, merged