[Wan] 미션 2: 체스판 생성
codesquad-members-2021/java-chess pull request #91
Opened 2021-02-16 09:43 UTC by MyungWanPark

## 미션2: 체스판 생성
안녕하세요! '미션2 체스판 생성'을 구현하고 테스트 코드를 진행한 박명완입니다~! 구현 내용은 아래와 같습니다.
   
### 구현내용
**main/java/chess/board.java**
- board 객체가 만들어질때 Pawn타입의 Arraylist가 만들어 질 수 있도록 Board()생성자에 Arraylist 생성자를 넣었습니다
- add메소드에 다른 객체가 추가 될 수 없도록 Pawn 타입의 변수를 파라미터로 등록하였습니다.
   
**main/java/pieces/Color.java**
- pawn의 색깔을 지정해주기 위해 enum을 활용하였습니다.
   
**test/java/chess/BoardTest.java**
- createPawnAndTest() 메서드가 최대한 하나의 역할만 수행 할 수 있도록 board를 생성하는 부분을 따로 빼서 createBoard메소드를 만들었고, test전에 실행이 되도록 BeforeEach 어노테이션을 붙였습니다.
- 리뷰어님의 조언을 반영하여 createPawnAndTest()메서드에서 Pawn을 생성할때, enum을 사용하여 다른 이름으로 객체를 생성하지 못하게 하였습니다.
   
부족한 점이 많은 코드에 귀한 시간을 내주셔서 리뷰해주셔서 감사드립니다! 많은 지적 부탁드릴께요!

2021-02-16 10:02 UTC, honux77 requested changes
고생하셨어요. 코멘트 보고 개선한 후 리뷰 요청 해주세요.

2021-02-16 10:02 UTC, honux77 commented on src/main/java/chess/Board.java
> +    public Pawn findPawn(int i) {
i보다는 index같음 명확한 이름이 좋습니다.

2021-02-16 10:02 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +        this.color = Color.WHITE;
this(Color.WHITE);

2021-02-16 10:02 UTC, honux77 commented on src/main/java/pieces/Color.java
> +public enum Color {
여기서 enum을 많이 사용했더라구요. enum을 사용하면 사용하지 않았을 때와 비교해서 구체적으로 어떤 이득이 있었을까요?

2021-02-16 10:02 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +    void createPawnAndTest() throws Exception {
테스트 메소드의 이름이 굳이 테스트일 필요는 없습니다.

2021-02-16 10:02 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +public class BoardTest {
junit5의 테스크 클래스와 메소드는 기본 접근 제어자를 사용하는 것이 일반적입니다.

2021-02-16 10:02 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
assertEqual은 사용하지 말고 assertThat을 사용해 주세요.

2021-02-16 10:02 UTC, honux77 commented on src/test/java/chess/BoardTest.java
> +        assertEquals(black, board.findPawn(1));
코드 중복이 보이는데 제거해주면 더 좋겠죠?

2021-02-16 10:02 UTC, honux77 commented on src/test/java/pieces/PawnTest.java
> +     void createBasicPawn() throws Exception {
Exception 제거

2021-02-16 12:10 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    public Pawn findPawn(int i) {
앗, 파라미터 이름에도 신경을 더욱 쓰겠습니다!

2021-02-16 12:11 UTC, MyungWanPark commented on src/main/java/pieces/Pawn.java
> +        this.color = Color.WHITE;
이렇게 사용이 가능하다는 것을 처음 알게 되었습니다. 공부해보고 적용하겠습니다!

2021-02-16 12:14 UTC, MyungWanPark commented on src/main/java/pieces/Color.java
> +public enum Color {
enum을 사용함으로써 특정 데이터 타입(클래스 명)을 명시할 수 있어 가독성이 증가하며, 상수의 역할과 마찬가지로 지정하지 않은 값을 사용하면 컴파일 에러가 발생함으로써 의도한 값만 넣을 수 있습니다~! 혹시 다른 이득이 더 있다면 더 찾아보겠습니다!

2021-02-16 12:14 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +    void createPawnAndTest() throws Exception {
앗 처음 알게 되었습니다! Test를 빼면, 더 심플하게 네이밍을 할 수 있겠네요! 감사합니다!!

2021-02-16 12:15 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +public class BoardTest {
JUnit5의 테스크 클래스와 메소드는 기본 접근 제어자를 사용하겠습니다!

2021-02-16 12:16 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
두 가지  메소드의 차이점에 대해 공부해보고 assertThat을 사용하겠습니다! 감사합니다

2021-02-16 12:18 UTC, MyungWanPark commented on src/test/java/chess/BoardTest.java
> +        assertEquals(black, board.findPawn(1));
앗, 코드 중복이 있네요! 중복을 어떻게 제거해볼지 고민해보고 제거하겠습니다!

2021-02-16 12:18 UTC, MyungWanPark commented on src/test/java/pieces/PawnTest.java
> +     void createBasicPawn() throws Exception {
앗, 의미가 없는 Exception이 있네요! 제거하겠습니다!

2021-02-16 13:10 UTC, MyungWanPark commented
호눅스가 해주신 조언들을 따라 개선해보았습니다. 귀한 시간 내주셔서 감사합니다! 
혹시 또 부족한 점이 있다면 조언 부탁드릴께요~!

2021-02-16 19:06 UTC, kyu-kim-kr reviewed
안녕하세요 완. 저희 팀원들 pr 돌아가면서 보고 있어요. ㅎㅎ

2021-02-16 19:06 UTC, kyu-kim-kr commented on src/main/java/chess/Board.java
> +    }
생성자로 이렇게 ArrayList 만드신 이유가 뭔지 여쭤봐도 될까요?? 저는 필드에 했는데 어떤 차이점이 있는지 완 의견을 듣고싶습니다

2021-02-16 19:06 UTC, kyu-kim-kr commented on src/main/java/pieces/Pawn.java
> +    }
저도 `this.color = Color.WHITE` 라고 했었는데 완처럼 수정하니 다른 생성자로 넘겨주는 편이 더 깔끔해보인다는 생각이 드네요.

2021-02-17 00:18 UTC, honux77 commented on src/main/java/chess/Board.java
> +    }
어 그렇네요. 이런 간단한 코드는 그냥 직접 초기화를 하는 게 더 간편하죠?

2021-02-17 00:19 UTC, honux77 commented on src/main/java/pieces/Pawn.java
> +    }
큰 상관은 없는데 this 생성자를 쓰면 조금 있어보이기도 하고요 ㅋㅋㅋ

2021-02-17 00:21 UTC, honux77 commented on src/main/java/pieces/Color.java
> +public enum Color {
그런 일반적인 대답이 나올 것 같았습니다.
1) 직접적인 가독성이 증가하였나? -> 제가 보기엔 복잡성 증가로 가독성이 감소했습니다.
2) 상수와 마찬가지로.. -> 그럼 왜 상수를 사용하지 않았나? 
상수를 사용했을 때와 비교해서 이득이 없어 보입니다. 무언가를 사용할 때는 구체적으로 현재 상태에서 왜 사용했는지를 명확하게 생각하고 사용하는 게 좋아요.

2021-02-17 00:22 UTC, honux77 commented on src/test/java/pieces/PawnTest.java
> +        Pawn pawn2 = new Pawn(Color.BLACK);
pawn, pawn2보다는 whitePawn, blackPawn이 약간 더 낫겠죠?

2021-02-17 00:22 UTC, honux77 approved these changes
수고하셨어요!

2021-02-17 00:22 UTC, merged

2021-02-17 06:51 UTC, MyungWanPark commented on src/main/java/pieces/Color.java
> +public enum Color {
아아 복잡성이 증가될 수가 있군요 ㅜㅜ 무언가를 사용할때는 현재 상태에서 구체적으로 이득이 되는 이유를 명확하게 생각해보고 사용하겠습니다~! 조언 감사드립니다~!!

2021-02-17 06:55 UTC, MyungWanPark commented on src/main/java/chess/Board.java
> +    }
@kyu-kim-kr  필드에 아무것도 안남기는게 더 깔끔해 보여서 안남겼는데 오히려 생성자를 추가 구현하게 되어서 복잡성이 증가될 수도 있겠네요! 좋은 지적해주셔서 감사합니다!

@honux77 넵 알겠습니다! 명확하게 이유가 있지 않는 이상 더 간편하게 작성하겠습니다. 감사합니다!

2021-02-17 06:57 UTC, MyungWanPark commented on src/main/java/pieces/Pawn.java
> +    }
@kyu-kim-kr 한가지 주의하실 점이 있습니다~! 찾아보니 이렇게 작성하려면 다른 생성자가 같은 역할 즉, this.color = color; 이 있었기 때문에 가능하단 점 입니다. 다른 생성자를 삭제해보면 컴파일 에러가 나는것을 알 수 있습니다~!

2021-02-17 06:58 UTC, MyungWanPark commented on src/test/java/pieces/PawnTest.java
> +        Pawn pawn2 = new Pawn(Color.BLACK);
앗, 변수의 가독성에 신경을 쓰지 못했네요ㅠㅠ 더욱 신경을 쓰겠습니다! 감사합니다~!!

2021-02-17 06:59 UTC, MyungWanPark commented
아직 코드리뷰를 step2 까지만 받아보았지만, 부족한 점을 많이 일깨워주셔서 정말 감사드립니다!