[아이작]Step3 구현
codesquad-members-2021/java-chess pull request #92
Opened 2021-02-16 10:28 UTC by isaac56

안녕하세요 아이작입니다.
2021 코드스쿼드 체스만들기 미션 Step3 구현하였습니다.
부족한 코드지만 리뷰 잘 부탁드립니다~!

1. Board에서 모든 체스말을 관리할 수 있도록, Piece라는 abstract class를 만들었습니다.
2. Piece는 모든 체스말이 상속받아야 할 class 입니다. 
 - 각 체스말은 color라는 공통 속성을 갖고 있고, 
 - Board에 출력하기 위한 representation 문자나 이동 범위 등 체스말 종류별로 다르게 구현해야하는 것도 있어서 abstract class로 구현했습니다.
3. Board 클래스에서는 Piece의 2차원 배열로 체스말을 관리하도록 했습니다.
4. Board 클래스 내에서 흰색말, 검은말의 목록을 따로 관리하도록 List<Piece> 변수를 각각 생성했습니다.

2021-02-16 13:20 UTC, sonypark requested changes
안녕하세요 아이작, 리뷰어 소니 입니다.😊
3단계 미션 구현하시느라 수고 많으셨습니다.
2차원 배열, 추상 클래스 사용 등 구현을 위해 고민한 흔적들이 보이네요.
그런데 이 부분이 원하는 기능을 구현하기 위해 적절한 선택이었는지는 고민해봐야할 것 같아요.
더 좋은 방법은 없는지, 이렇게 구현했을 때의 문제는 무엇인지 생각해보시면 좋을 것 같습니다.
코멘트 확인하시고 궁금한 점은 질문 남겨주세요~

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/Main.java
> +    }
Scanner는 생성 후 close를 해주는걸 권장합니다. 왜 그럴까요? 이유를 알았다면 어떻게 close 할 수 있을까요? try catch를 사용하셨으니, [try with resources](https://www.baeldung.com/java-try-with-resources)에 대해 공부해보세요~

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/Main.java
> +        String cmd;
네이밍은 되도록 축약하지 않고 써주세요

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/Main.java
> +                if(cmd.equals("start"))
변하지 않는 값은 가독성과 유지보수를 위해 자바 상수를 사용해보세요

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +        return pieces[rowIdx][colIdx];
if 문에는 중괄호를 꼭 기입해주세요

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +
else if 사용을 지양해주세요

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +    }
```suggestion
private boolean isValid(int location){
        return location >= 0 && MAX_SIZE > location;
    }
```
좀 더 간단히 표현 가능할 수도 있겠네요

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +            builder.append(System.lineSeparator());
`lineSeparator()` 👍

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +    private Piece[][] pieces = new Piece[MAX_SIZE][MAX_SIZE];
2차원 배열로도 구현 가능하지만, 권장하지는 않습니다.
2차원 배열을 사용하면 코드의 가독성이 현저히 낮아지는데요, 다른 방법으로 구현할수 없는지도 고민해보세요~
당장 적용이 어렵다면 미션을 진행하며 천천히 고민하고 적용해도 좋습니다.

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +
representation을 표현하는 로직을 추상 메서드로 만드는것이 좋은 선택일까요?
representation은 Piece마다 갖고 있는 특성일 것 같은데 어떻게 하면 좋을까요?

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/pieces/Pawn.java
> +            return '?';
representation을 이렇게 하드코딩으로 표현해주는게 적절한지 고민해보세요🧐

2021-02-16 13:20 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +    }
이 메서드는 개선할 부분이 많아 보이는데요, representaion을 표현하는 로직을 개선하면 이 부분도 자연스럽게 변경될 것 같네요!

2021-02-17 02:37 UTC, isaac56 commented on src/main/java/net/isaac/Main.java
> +    }
Scanner 뿐만 아니라 외부 리소스는 사용이 끝나면 항상 반환해야 하군요.
다른 프로세스 또는 쓰레드에서 리소스를 사용할 수록 있도록요.
단일 콘솔 프로그램의 경우 프로그램이 종료되면 자동으로 리소스를 반환하지만, 서버에서 close를 안하고 있다면 계속해서 리소스를 갖고 있을테니까요.

try with resources를 사용하면 블럭이 끝났을때 자동으로 리소스를 반환해주니 편리한 구문같습니다.
좋은 정보 감사합니다~!

2021-02-17 03:03 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +
else if를 지양한다면 위 코드는 switch로 대체하는게 최선일 것 같습니다.
(if 블럭의 내용이 리턴이 아니기 때문에 [빠른 리턴을 통한 else 구문 제거](https://xly.kr/posts/54)는 힘들 것 같습니다.)
가독성을 위해서 else if 지양하라는 말씀이신가요?

2021-02-17 03:15 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +    private Piece[][] pieces = new Piece[MAX_SIZE][MAX_SIZE];
체스 게임을 진행하면서 보드의 크기가 변하지 않기 때문에 2차원 배열을 사용했습니다.
체스는 2차원 좌표를 기반으로 말을 이동하기 때문에, 2차원 배열 사용 시 가독성이 오히려 높아진다고 생각했거든요.

제 수준으로는 2차원 좌표상에서 말을 관리하려면 List<List<Piece>> 또는 Piece[][] 밖에 떠오르지 않았습니다.
List<List<Piece>>를 사용하는 것보다는 Piece[][]를 사용하는게 더 간단하다고 생각했습니다.

혹시, 제가 리뷰어님께서 얘기하신 '다른 방법'과 전혀 다른 방향으로 구상하고 있는 건지 알 수 있을까요..? ㅠㅠ

2021-02-17 03:41 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +    }
"보드에 존재하는 white piece의 representation 문자를 String으로 묶어 반환한다"는 메소드의 목적 자체가 개선할 점인가요?
아니면 그런 메소드를 만들기 위한 구현 방법이 개선할 점인가요?

representation을 표현하는 로직이 고쳐진다고 해도, 결국 클래스 외부에서는 getter로 속성을 얻어야 할 것 같습니다.
그러면 로직이 개선되어도 위 코드에 영향이 가진 않을 것 같거든요.

제가 부족하여 리뷰를 잘 알아듣지 못했는데 좀 더 자세히 설명 부탁드려도 될까요..?

2021-02-17 03:44 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Pawn.java
> +            return '?';
Piece 클래스 상수로 각 체스말의 representation을 선언한 후에 그 상수를 사용하려고 합니다.
감사합니다~!

2021-02-17 03:48 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +
representation은 모든 Piece가 갖고 있는 특성이기 때문에 멤버 변수로 갖고 있어야 할 것 같습니다.
대신 상속받는 각 체스 말이 Override하여 color에 따른 representation을 설정할 수 있도록 하려고 합니다.

```java
public abstract class Piece {
    Color color;
    char representation;

    public Piece(Color color){
        this.color = color;
        this.representation = getRepresentation(color);
    }

    abstract char getRepresentation(Color color);

    //Board 출력을 위한 문자 반환
    public char getRepresentation(){
        return representation;
    };

    public Color getColor() {
        return color;
    }

    public enum Color {
        BLACK,
        WHITE
    }
}
```

2021-02-17 15:34 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +    private Piece[][] pieces = new Piece[MAX_SIZE][MAX_SIZE];
아닙니다. 이차원 배열로 구현하셔도 괜찮습니다. 말씀하신대로 `List<List<Piece>>`형태로도 가능합니다. List와 같은 자바의 컬렉션을 사용하면 컬렉션 메서드인 add(), size() 등을 사용할 수 있는 장점이 있습니다. 또 다른 방식으로는 Map 과 같은 자료구조로도 구현할 수 있겠네요. 구현 방법은 다양합니다. 이차원 배열이 가독성이 높고 더 구현하기 편하다고 느끼신다면 사용하셔도 좋습니다!

2021-02-17 16:02 UTC, sonypark requested changes
질문 주신 부분에 대해 코멘트 남겼습니다.
말씀 드린 내용 중 이해가 안 되는 부분 있으면 질문 남겨주세요~
아이작의 생각도 가감없이 남겨주시면 감사하겠습니다!

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    public static final char UNKNOWN_REPRESENTATION = '?';
지금과 같은 구조라면 체스말의 종류가 늘어나는 만큼 자바 상수도 계속 추가될 것 같은데 맞나요?

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    char representation;
접근제어자를 default로 하신 이유가 있을까요?

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    }
필드로 representation을 두셨는데, 생성자를 통해 초기화 하는 방식은 어떨까요?

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/pieces/Pawn.java
> +    }
representation은 결국 화면에 표시하기 위한 부분입니다. 색상에 따라 출력이 달라지는 로직을 모든 Piece마다 각각 중복해서 갖고 있는게 좋은 구조일까라는 생각이 드네요. Piece의 representation을 결정짓는 부분, 즉 흰색이면 소문자, 검은색이면 대문자로 표시하는 로직은 어디에서 해주는게 좋을까요? 한 번 고민해보시고, 생각이 잘 나지 않는다면 추후에 변경해보셔도 좋습니다. 위와 같은 구조를 이어간다면 어떤 문제가 있을지 생각해보시고, 문제점이 보인다면 개선해주세요. 아직 잘 모르겠거나 큰 문제가 되지 않을 것 같다면 그대로 진행해주셔도 됩니다.

++ if 문에는 중괄호를 생갹하지 않고 사용해주세요

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +    }
메서드 내부의 로직이 개선될 필요가 있다는 말씀이었습니다:)
문자열을 연결하는 로직이라면 reduce 가 아닌 `Collectors.joining()` 사용하는 방법도 있습니다. [참고](https://tourspace.tistory.com/8)
그리고 결국 문자열로 표시될 representation이라면 char로 선언해서 다시 `String.valueOf()`로 형변환 하는것보다 처음부터 String 자료형을 사용하는 건 어떨까요?

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +            builder.append(System.lineSeparator());
출력 로직을 Board 클래스에서 갖고 있는게 맞는지도 생각해봐주세요~
예를 들어, 출력을 담당하는 객체에게 체스판을 넘겨주면 해당 객체가 체스판을 출력하는 흐름은 어떨까요?
이 부분은 당장 고치지 않으셔도 되고, 미션 진행하면서 필요성을 느낄 때 분리해주시면 됩니다.

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +            return false;
add 메서드의 반환 값을 boolean으로 하신 이유는 무엇인가요??

2021-02-17 16:02 UTC, sonypark commented on src/main/java/net/isaac/Main.java
> +        System.out.println("Game end.");
try with resource 👍

2021-02-17 16:17 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +
음 다시 보니 이 부분은 단순한 구조라 switch로 대체 하지 않고 else if로 가도 괜찮을 것 같네요..!
되도록이면 else if는 사용하지 말자라는 주의라 위와 같이 리뷰를 드렸네요😅
[호눅스의 말씀](https://github.com/codesquad-members-2021/java-chess/pull/98#issuecomment-780485071)처럼 제 말을 꼭 안 따르셔도 됩니다.

2021-02-18 01:40 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +
옙ㅎㅎ 사실 else if를 생각 없이 사용했었는데 덕분에 좀 더 고민하는 계기가 생겼습니다.
감사합니다~!

2021-02-18 01:55 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +    public static final char UNKNOWN_REPRESENTATION = '?';
옙! 체스말의 종류에 따라 representation은 달라집니다.
체스말 종류마다 representation을 적어도 한번은 지정해줘야 하기 때문에, 체스말 종류만큼 상수가 생겨야 할 것 같습니다.
다만 WHITE, BLACK까진 나누지 않고 검은색일땐 대문자, 흰색일땐 대문자로 바꾸는 로직을 추가하면 될 것 같습니다.

2021-02-18 02:02 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +    char representation;
Piece를 상속하는 체스말 클래스는 Pieces 패키지안에 위치하게 하려는 의도입니다.

protected로 할 경우 Pieces 패키지 밖에서도 상속받아 사용할 수 있기 때문에 default로 하였습니다.

2021-02-18 02:10 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +    }
생성자로 representation을 받아서 초기화하면, 생성자를 호출하는 코드에서 
```java
new Piece(Color.WHITE, '&')
```
와 같이 잘못된 문자를 넣을 수 있기 때문에, 추상메소드를 오버라이드하여 자체 로직을 통해 초기화하도록 했습니다.

다만 Piece의 정적 팩토리 메소드으로 각 체스말을 생성하게 한다면 위에 말한 문제는 없을 것 같아요!

2021-02-18 02:18 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +    }
char 자료형을 사용한 이유는, 개발자가 실수로 representation 값에 여러 문자를 넣는걸 방지하기 위해서였습니다.
체스판에 표시하는 representation 문자는 1개여야 한다고 생각했어요.(출력 형식을 맞추기 위해서)
representation = "AF"
이런식으로 들어가는 걸 방지하기 위해서 char 자료형으로 선언하였어요.

체스판에 존재하는 말의 개수가 수백만개가 아닌 이상 String.valueOf()로 형변환하는 오버헤드가 크지 않기 때문에,
보다 엄격하게 자료형을 제한해서 개발자의 실수를 방지하는게 낫다고 생각했습니다.

2021-02-18 02:21 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +            return false;
rowIdx나 colIdx가 잘못된 값으로 들어와, add에 실패했을 때를 알기 위해서 boolean을 반환했습니다.
add 실패하면 false 반환, 성공하면 true 반환하도록요.

2021-02-18 10:58 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    char representation;
`Piece 상속받는 체스말 클래스를, Pieces 패키지안에 만들게하려는 의도`
이 부분이 잘 이해되지 않습니다.
Piece가 가지고 있는 필드를 외부에서 사용하지 않고 Piece 클래스 내에서 사용하도록 로직을 구현하면 되지 않을까요? 

예를 들어, color 비교도 상속받는 클래스까지 안가더라도 Piece 클래스 안에서도 할 수 있을 것 같은데
```java
public boolean isSameColor(Color color) {
        return this.color == color;
    }
```
필드의 접근 제어자는 최소한으로 해주는게 좋습니다. 자식 클래스에서 부모 클래스의 필드를 가져다 쓰는게 좋은 설계인지도 생각해보셨으면 합니다.

2021-02-18 11:00 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    }
네 맞습니다. 잘못된 문자가 들어올 수 있는 경우가 생기겠네요. 그렇다면 체스말의 representation만 들어오도록 타입을 강제하는 방법은 없을까요? char라는 기본 자료형이 아니라 자기가 원하는 타입만 들어오도록 강제하도록 하고 싶다면 어떻게 해야할까요?

2021-02-18 11:06 UTC, sonypark commented on src/main/java/net/isaac/chess/Board.java
> +            return false;
add 메서드의 역할은 무엇일까요? add 메서드의 역할은 체스판에 체스말을 추가하는거라고 생각하는데요. 잘 추가가 되었는지는 add 메서드에서 하는게 아니라 조회를 통해 확인해야하는게 맞을 것 같습니다. 하나의 메서드는 하나의 역할만 하도록 최대한 분리해주세요.

그리고 현재 rowIdx와 colIdx가 체스판 범위를 벗어났을 때 아무 예외 메시지 없는데요. 사용자 입장에서 왜 add가 안 되었는지 알려줄 필요가 있다고 생각합니다.

2021-02-18 12:30 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +    char representation;
생각해보니 color나 representation 변수 모두 상속받는 클래스에서 사용할 필요가 없었네요!
왜인지는 모르게 상속받는 클래스에서 사용해야 한다고 생각하고 있었어요! 
좋은 지적 감사합니다ㅎㅎ

2021-02-18 12:34 UTC, isaac56 commented on src/main/java/net/isaac/chess/Board.java
> +            return false;
오늘 호눅스 수업에도 들었지만, 제가 '지금은 필요없지만 언젠가 필요하지 않을까?'라는 생각으로 코딩하고 있었던 것 같습니다.
나중에 필요할 때 refactoring을 해도 되는데, 안좋은 습관이었던 것 같아요.
소니 말씀대로 한 메서드가 하나의 역할만 하는게 더 자연스러운 것 같기도 합니다. 감사합니다!

2021-02-18 13:27 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Piece.java
> +    }
제 생각은 타입을 강제한다기 보다 값을 강제해야 할 것 같습니다.
Color처럼 Representation이라는 enum을 만들어도, Pawn 생성자에 Representation.QUEEN과 같이 이상한 값을 넣을 수 있기 때문에 같은 상황이라는 생각이 들어서요.

Pawn 생성자의 접근제어자를 default로 제한하고, Board 클래스의 static method로
```java
public Piece getPawn(Color color) { return new Pawn(color, Piece.PAWN_REPRESENTATION); }
```
이런식으로 정의해주려고 합니다.

2021-02-18 13:30 UTC, isaac56 commented on src/main/java/net/isaac/pieces/Pawn.java
> +    }
상속받는 체스말마다 위와 비슷한 코드가 중복되는 문제가 생길 것 같습니다.

저 추상메소드를 삭제하고 Piece에 정적 팩토리 메소드로 Pawn을 생성하게 하려고 합니다.
if 문에는 항상 중괄호 신경써서 넣도록 하겠습니다 감사합니다 :)

2021-02-18 14:16 UTC, sonypark commented on src/main/java/net/isaac/pieces/Piece.java
> +    }
네 이번 단계에서는 말씀하신대로 진행해주세요~

++ 참고로 타입을 사용하더라도 각 체스말의 생성자에서 자신의 representation을 강제할 수 있습니다.

```java
public Pawn(Color color) {
        super(color, Representation.PAWN);
    }
```

2021-02-18 15:47 UTC, honux77 commented
@sonypark 제가 머지할게요. 수고하셨습니다.

2021-02-18 15:47 UTC, merged