[Jane] 미션 4: 모든 기물 배치하기
codesquad-members-2021/java-chess pull request #98
Opened 2021-02-16 22:26 UTC by janeljs

안녕하세요! 제인입니다🙂
이번 미션 때 변경된 사항과 고민되었던 지점들에 대해 간단히 설명드리려고 합니다.

1. enum Color의 멤버 변수로 representation을 관리 &rarr; enum Type을 새로 선언하고 Type에서 representation을 관리하는 것으로 변경하였습니다. Color와 Type을 Piece의 내부 클래스로 두었더니 Piece 클래스가 너무 길어지는 문제가 있었는데 아예 밖으로 빼는 것이 좋을지 내부에 두는 것이 좋을지 고민입니다. 

2. Board의 구조에 대하여 고민하다가 blackPieces와 whitePieces 리스트 두 개를 선언하고 각 리스트에 색상별로 말을 넣는 식으로 구현하였습니다. blackPieces를 blackPiecesExceptPawn과 blackPawns로 나누어 구현할까도 생각했지만, 그렇게 되면 addBlackPiece를 addBlackPawn과 addBlackPiece로 나누는 등 메서드의 수가 거의 2배가 되어 분리하지 않았습니다. 
+) 지난 리뷰에서 일급 컬렉션에 대하여 언급해주셔서 PiecesList를 클래스로 만들어 `blackPieces = new PiecesList(Color.BLACK)`과 같은 형태로 구현해볼까 생각해봤었는데, 현재 보드의 실질적인 API는 initialize와 print이기 때문에 PiecesList를 만들지 않고 현재의 자료구조를 유지하였습니다.  #81 

3. StringUtils 클래스를 추가하고 appendNewLine 메서드를 정의하였습니다. blackPieces(또는 whitePieces) 리스트 안에 폰과 다른 말들을 함께 관리하기 때문에 매개변수로 받는 text 문자열의 길이가 8을 넘어가면 끝뿐만 아니라 가운데에도 개행문자가 추가되도록 구현하였습니다. 

4. 게임의 시작과 종료를 담당하는 ChessGame 클래스 안의 메인메서드의 로직을 수정하였습니다. 원래는 switch case문을 사용했었는데 절차지향적으로 구현했다는 피드백을 받아 if문으로 고쳐보았습니다. else와 else if문은 사용하지 않으려고 노력했는데, 아직 절차 지향이라는 말이 와닿지 않아 개선되었는지 모르겠습니다. 

5. 클래스 내부 메서드 순서 배치에 대해 고민하고 있습니다. 그룹 코드 리뷰를 하면서 public인 메서드를 위로 배치하고, private인 메서드를 아래로 배치하는 것이 좋다는 말을 들었는데, 그렇게 해놓으면 사용자 입장에서는 편하겠지만, 코드리뷰를 하실 때 위아래로 이동하셔야 할 것 같아 최대한 코딩했던 순서 그대로를 유지하였습니다. 

미션이 거듭될수록 코드도 길어지고 부족한 점이 더 많을 것 같은데 소중한 시간을 내어 리뷰해주셔서 감사합니다🙇‍♀️

2021-02-17 11:13 UTC, honux77 commented
수업 때도 말했지만 포비의 명언을 인용해서 "동의안되는 권위에 굴복하지 마라". 리뷰어의 조언을 적극 수용하는 건 좋지만, 굳이 왜? 라는 생각이 들 때는 안 해도 됩니다.

2021-02-17 11:16 UTC, honux77 commented
1. enum Color의 멤버 변수로 representation을 관리 → enum Type을 새로 선언하고 Type에서 representation을 관리하는 것으로 변경하였습니다. Color와 Type을 Piece의 내부 클래스로 두었더니 Piece 클래스가 너무 길어지는 문제가 있었는데 아예 밖으로 빼는 것이 좋을지 내부에 두는 것이 좋을지 고민입니다.
--> 저도 같은 고민했었는데, 저는 안에 넣었거든요. 나중에 보니까 빼내는게 더 깔끔한 거 같아요 ㅋㅋㅋ

Board의 구조에 대하여 고민하다가 blackPieces와 whitePieces 리스트 두 개를 선언하고 각 리스트에 색상별로 말을 넣는 식으로 구현하였습니다. 기존에는 흰색 말과 검은색 말을 추가하는 메서드를 각각 관리하였는데, 이를 addPiece 메서드로 통합하였습니다.
+) 지난 리뷰에서 일급 컬렉션에 대하여 언급해주셔서 PiecesList를 클래스로 만들어 blackPieces = new PiecesList(Color.BLACK)과 같은 형태로 구현해볼까 생각해봤었는데, 현재 보드의 실질적인 API는 initialize와 getResultToPrint이기 때문에 PiecesList를 만들지 않고 현재의 자료구조를 유지하였습니다. 지난 리뷰
--> 일급 객체 같은거 지금 단계에서 고민 안해도 됩니다.

StringUtils 클래스를 추가하고 appendNewLine 메서드를 정의하였습니다. blackPieces(또는 whitePieces) 리스트 안에 폰과 다른 말들을 함께 관리하기 때문에 매개변수로 받는 text 문자열의 길이가 8을 넘어가면 끝뿐만 아니라 가운데에도 개행문자가 추가되도록 구현하였습니다.

게임의 시작과 종료를 담당하는 ChessGame 클래스 안의 메인메서드의 로직을 수정하였습니다. 원래는 switch case문을 사용했었는데 절차지향적으로 구현했다는 피드백을 받아 if문으로 고쳐보았습니다. else와 else if문은 사용하지 않으려고 노력했는데, 아직 절차 지향이라는 말이 와닿지 않아 개선되었는지 모르겠습니다.
--> 이것도 그냥 놔두거나 else를 사용해도 될 것 같아요. 

클래스 내부 메서드 순서 배치에 대해 고민하고 있습니다. 그룹 코드 리뷰를 하면서 public인 메서드를 위로 배치하고, private인 메서드를 아래로 배치하는 것이 좋다는 말을 들었는데, 그렇게 해놓으면 사용자 입장에서는 편하겠지만, 코드리뷰를 하실 때 위아래로 이동하셔야 할 것 같아 최대한 코딩했던 순서 그대로를 유지하였습니다.
--> 사용자(?)가 누구인가요? ㅋㅋ public을 먼저 배치하는 건 맞는데 그것보다 가독성이 중요하죠. 관련있는 private 메소드를 가깝게 묶어놔도 좋은 것 같아요. 그리고 IDE가 있기 때문에 보통은 큰 상관이 없습니다.

2021-02-17 11:17 UTC, honux77 commented on src/main/java/chess/Board.java
> +import pieces.Piece;
패키지 이름은 아마 단수가 많을껄요? 확실하진 않습니다 ㅎㅎ

2021-02-17 11:18 UTC, honux77 commented on src/main/java/chess/Board.java
> +import static utils.StringUtils.*;
import static util.StringUtil.*;

2021-02-17 11:19 UTC, honux77 commented on src/main/java/chess/Board.java
> +    final int BOARD_SIZE = 8;
private?

2021-02-17 11:19 UTC, honux77 commented on src/main/java/chess/Board.java
> +        blackPieces = new ArrayList<>();
요렇게 두개 뿐이라면 생성자 밖으로 빼보는건 어때요? 선언과 동시 초기화.

2021-02-17 11:23 UTC, honux77 commented on src/main/java/chess/Board.java
> +    public int pieceNum() {
그냥 size()는 어때요? 제가 보기엔 보드 자체가 하나의 커다란 컨테이너라는 느낌이 들어요.

2021-02-17 11:23 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private void initializeWhitePieces() {
initializePieces(Color color) 로 중복을 제거할 수 있지 않을까요?

2021-02-17 11:24 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private void initializeWhitePieces() {
아 이것도 요구사항 때문인가요?? ㅋㅋㅋ 
아래쪽도 주욱 다 ㅎㅎㅎ 색깔별 메소드 통합이 가능할 것 같긴 한데요 ㅎㅎ

2021-02-17 11:24 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private void initializeWhitePieces() {
저도 이렇게 짰던 것 같은데 짜면서 약간 속터진 느낌이...

2021-02-17 11:40 UTC, honux77 requested changes
별로 고칠 건 없지만 한 번 더 개선해 보세요.
그런데 코드가 제가 짠 코드랑 많이 비슷한 느낌인데 혹시........

2021-02-17 11:40 UTC, honux77 commented on src/main/java/chess/ChessGame.java
>  }
main() 메소드 안에 로직이 너무 많이 들어가 있는걸 저는 선호하지 않는데요.
```
main() {
 init()
 loop()
bye()
}
```
요런 식으로 짜면 어떨까요?

2021-02-17 11:40 UTC, honux77 commented on src/main/java/pieces/Piece.java
> +    }
컬러는 괜찮은데 역시 타입이 약간 길어요. 밖으로 빼는 것도 괜찮을 것 같네요.

2021-02-17 11:40 UTC, honux77 commented on src/main/java/utils/StringUtils.java
> +    }
위쪽 호출한 코드를 보면서 뭔가 느낌이 이상했는데 이걸 이렇게 짰군요. 그냥 if문 없이 return text + NEWLINE;이 더 간결했을 것 같은 느낌이에요.  아아 두줄이라서 그렇군요.

1) 간단하게 만들고 블랙피스 생성을 블랙폰과 블랙나머지 두 개로 분리한다.  
2)  한번에 String 64개를 받아서 8줄마다 라인피드를 넣는 걸로 짠다. 

둘 중에 한가지 방법 적용을 제안해 봅니다.

2021-02-17 11:40 UTC, honux77 commented on src/test/java/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.createBlackKing(), Color.BLACK, 'K')
으으으으... 이것도 나중 단계에서 개선이 되겠죠???

2021-02-17 11:40 UTC, honux77 commented on src/test/java/pieces/PieceTest.java
> +        assertThat(whitePawn.isWhite()).isEqualTo(true);
isTrue() 가 있을 듯.

2021-02-17 11:51 UTC, janeljs commented
> 별로 고칠 건 없지만 한 번 더 개선해 보세요.
> 그런데 코드가 제가 짠 코드랑 많이 비슷한 느낌인데 혹시........

넵! 리뷰 감사합니다🙂 천천히 코멘트 읽으면서 수정해서 다시 리뷰 요청드리겠습니다ㅎㅎ

호눅스 코드도 오픈되어 있나요? 자바지기님 코드는 조금 참고했지만 호눅스 코드는 저희가 볼 수 있는지도 몰랐어요😂 요구사항이 세분화되어있고, 테스트 코드에 메서드 이름이랑 구조까지 이미 다 정해져있어서 비슷할 것 같습니다ㅎㅎ

2021-02-17 12:06 UTC, jypthemiracle reviewed
제가 이거 미션을 몰라서 그러는데 엄청 스텝이 많을 것만 같아요..
이번 스텝에서는 호눅스가 지적해주신 사항 외에는 크게 건드릴 게 없는 것 같아요.
스텝이 올라갈 수록 요구사항이 복잡해질텐데 그 때 어떻게 대처하면 좋을 지 같이 논의해봐요.
제인누나 화이팅..
나 그리고 휴가 못나가 이번에........

2021-02-17 12:06 UTC, sigridjineth commented on src/test/java/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.createWhitePawn(), Color.WHITE, 'p'),
```@BeforeEach``` 키워드를 학습해보세요.

2021-02-17 12:06 UTC, sigridjineth commented on src/main/java/chess/Board.java
> +        whitePieces = new ArrayList<>();
Lists.newArrayList() 라는 것이 있어요. new ArrayList와 비교해보세요.
https://stackoverflow.com/questions/9980915/lists-newarraylist-vs-new-arraylist

2021-02-17 12:06 UTC, jypthemiracle commented on src/main/java/pieces/Piece.java
> +        return new Piece(Color.BLACK, Type.KING);
저 같으면 PieceFactory.java 를 하나 만들 것 같아요.
Piece 객체 그 자체와, Piece를 생성하는 팩토리 메소드는 별도로 분리하는 것이 어떨까요?

2021-02-17 12:06 UTC, jypthemiracle commented on src/main/java/pieces/Piece.java
> +        return new Piece(Color.BLACK, Type.KING);
요구사항이 복잡해질 수록 PieceFactory의 정책을 경우에 따라 다르게 적용할 수 있게 해주는 인터페이스를 도입해야 할 것입니다. 지금 이야기 할 것은 아니니까 패스하죠.

2021-02-17 12:59 UTC, janeljs commented on src/main/java/chess/Board.java
> +import static utils.StringUtils.*;
루카스 요구사항에 "이 기능을 utils.StringUtils 클래스를 추가해 유틸리티 메소드로 분리한다"라고 되어있어 복수로 선언했습니다! 그런데 리뷰를 받다보니 요구사항에 나와있어도 네이밍에 있어서는 더 고민해보고 수정하는 것이 좋을 것 같습니다.

2021-02-17 13:09 UTC, janeljs commented on src/main/java/chess/Board.java
> +import pieces.Piece;
해당사항에 대하여 찾아보니 상황에 따라 복수를 써야한다는 입장도 있고, 단수만 사용해야 한다는 입장도 있는데, Google Cloud에서 공유한 문서를 보니 "패키지 이름은 단수와 복수 구성요소 이름이 혼용되지 않도록 단수 구성요소 이름을 사용해야 합니다"라고 나와 단수가 더 많이 쓰이는 것 같습니다. 해당 부분 수정하겠습니다ㅎㅎ

출처 
- [패키지 이름
](https://cloud.google.com/apis/design/naming_convention?hl=ko)
- [Should package names be singular or plural?](https://softwareengineering.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural)

2021-02-17 13:12 UTC, janeljs commented on src/main/java/chess/Board.java
> +    final int BOARD_SIZE = 8;
꼼꼼하게 확인한다고 했는데 private이 삭제되어 버렸네요ㅠㅠ BOARD_SIZE를 메서드 내 지역변수로 선언하라고 인텔리제이가 권유해서 말을 들었다가 다시 반항심이 들어 복구하는 과정에서 private이 없어진 것 같습니다. 주의하겠습니다.

2021-02-17 13:15 UTC, janeljs commented on src/main/java/chess/Board.java
> +        blackPieces = new ArrayList<>();
저번 [코드리뷰 ](https://github.com/codesquad-members-2021/java-chess/pull/31#discussion_r573555983)때 생성자 내부와 외부에서 초기화하는 것의 차이에 대해 학습했었는데, 지금 상황에서는 호눅스 말씀대로 외부에서의 초기화가 더 바람직할 것 같습니다. 수정하겠습니다🙂

2021-02-17 13:32 UTC, janeljs commented on src/main/java/chess/Board.java
> +        whitePieces = new ArrayList<>();
오 처음봤는데 공부할 키워드를 주셔서 감사합니다. 
1. Lists.newArrayList() 또한 내부적으로는 new ArrayList<E>()를 통해 객체를 생성하고 반환합니다.
2. 현 Java 버전에서는 new ArrayList<>() 또한 타입 파라미터를 생략해도 되지만, 이전에는 적어줘야 했기 때문에 Lists.newArrayList()를 사용할 경우 복잡한 제네릭을 간단하게 표현할 수 있다는 장점이 있었습니다.
3. 이외에 오버로딩된 생성자를 통해 매개변수로 받은 element들을 바로 초기화할 수 있다는 장점이 있습니다. 

현재 상황에서는 new ArrayList를 사용하는 것이 더 적합해 보이는데 제대로 이해한 걸까요?ㅎㅎ

2021-02-17 13:34 UTC, janeljs commented on src/main/java/chess/Board.java
> +import pieces.Piece;
추가로 패키지 이름을 복수로 선언하는 경우는 대부분 단수 형태가 예약어 또는 키워드로 사용되고 있기 때문이라고 합니다. [관련 토론](https://groups.google.com/g/golang-nuts/c/buBwLar1gNw)이 있는데 재밌네요 ㅎㅎ

2021-02-17 13:38 UTC, janeljs commented on src/main/java/chess/Board.java
> +    public int pieceNum() {
원래는 size()였는데 보드의 size()라고 하니까 8 또는 8*8=64이어야 할 것만 같은 느낌이 들어 조금 더 명확하게 pieceNum()으로 이름을 바꿔보았습니다. 또한 위에서 BOARD_SIZE라는 상수를 8로 선언해두어 size()로 이름을 바꿀 경우 충돌(?)이 있을 것 같은데 그래도 바꾸는 게 좋을까요?ㅎㅎ
+) 루카스에 예시로 나와있는 테스트코드에는 pieceCount로 정의되어 있습니다.

2021-02-17 13:42 UTC, janeljs commented on src/main/java/chess/Board.java
> +    private void initializeWhitePieces() {
넵 ㅠㅠ 요구사항에 아래와 같이 메서드 형태를 이미 정의해주셔서 그대로 따랐습니다.
```
흰색 Pawn을 생성하는 메소드: Piece.createWhitePawn()
검은 색 Knight를 생성하는 메소드: Piece.createBlackKnight()
```

2021-02-17 13:44 UTC, janeljs commented on src/main/java/chess/Board.java
> +    private void initializeWhitePieces() {
메서드 통합이 가능할 것 같은데 일단 저렇게 요구사항을 명시해주신 것은 다음단계 진행시 무슨 의미가 있지 않을까 싶어 통합하지 않았습니다. 다시 리뷰 요청드리기 전에 해당 부분 통합하여 중복을 제거할까요?

2021-02-17 13:51 UTC, janeljs commented on src/main/java/chess/ChessGame.java
>  }
말씀해주신대로 수정해보겠습니다!ㅎㅎ 최대한 간결하게 짠다고 while문이랑 if문을 한 번씩만 사용했는데 조금 더 고민해보겠습니다.

2021-02-17 13:55 UTC, janeljs commented on src/main/java/pieces/Piece.java
> +    }
저도 너무 긴 것 같아 고민하다가 Color랑 Type이 같은 층위에 있는데 길이만을 이유로 한 가지는 안에, 한 가지는 밖에 선언해도 되나 싶어 둘 다 내부에 정의하였습니다. 색상과 타입은 모두 Piece의 속성인데 길이를 기준으로 한 가지는 안에, 한 가지는 밖에 선언해도 되는 걸까요? 내부 클래스와 외부 클래스를 정의하는 기준이 헷갈립니다...

2021-02-17 14:01 UTC, janeljs commented on src/main/java/pieces/Piece.java
> +        return new Piece(Color.BLACK, Type.KING);
현재는 미션 요구사항에 클래스 구조 및 클래스 이름 변경까지 세세하게 나와있어 그대로 따르고 있습니다. 정의했던 구조를 사용하여 다음 단계의 미션이 진행되기 때문에 새로운 클래스를 만들기가 겁나네요😢 비효율적인 구조&rarr; 효율적인 구조로 점진적으로 나아가게끔 미션을 설계하신 것 같습니다.

2021-02-17 14:03 UTC, janeljs commented on src/main/java/utils/StringUtils.java
> +    }
저도 뭔가 마음에 들지 않았는데 블랙폰과 폰 이외의 기물을 따로 관리할 경우 보드 객체 내부의 필드에 선언되어 있는 리스트가 4개가 되고, 메서드의 종류도 2배가 되어 appendNewLine 메서드를 희생시키는(?) 방법을 취하였습니다😢

2번의 방법을 적용하여 리팩토링 해볼게요!ㅎㅎ

2021-02-17 14:08 UTC, janeljs commented on src/test/java/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.createWhitePawn(), Color.WHITE, 'p'),
BoardTest에서는 @BeforeEach를 사용하고 있고, 원래 PawnTest에서도 해당 애노테이션을 사용하고 있었는데 PieceTest로 바꾸면서 요구사항에 따른 테스트가 1개가 되어 `@BeforeEach`를 사용한 setup() 블럭을 지웠습니다. 그런데 추후 요구사항을 수행하면서 다시 Test가 3개가 되어버렸네요😂 수정 후 다시 전체적인 로직을 검토하고 중복을 제거하는 습관을 들여보겠습니다.

2021-02-17 14:09 UTC, janeljs commented on src/test/java/pieces/PieceTest.java
> +                () -> verifyPiece(Piece.createBlackKing(), Color.BLACK, 'K')
으으으으....😖 그럴 것 같아용... 지금은 정적 팩토리 메서드가 다 분리되어 구현되어 있어서 저게 최선이었어요...😭

2021-02-17 14:11 UTC, janeljs commented on src/test/java/pieces/PieceTest.java
> +        assertThat(whitePawn.isWhite()).isEqualTo(true);
정말로 있군요!ㅎㅎ 수정하겠습니다.
```
    @Test
    public void testAssertTrue() {
        assertThat(true).as("failure - should be true").isTrue();
    }
```

출처 : [JUnit Assertion에서 AssertJ로 갈아탈 때 소소한 팁](https://medium.com/@SlackBeck/junit-assertion%EC%97%90%EC%84%9C-assertj%EB%A1%9C-%EA%B0%88%EC%95%84%ED%83%88-%EB%95%8C-%EC%86%8C%EC%86%8C%ED%95%9C-%ED%8C%81-4d1ba5245942)

2021-02-17 14:14 UTC, janeljs commented
> 제가 이거 미션을 몰라서 그러는데 엄청 스텝이 많을 것만 같아요..
> 이번 스텝에서는 호눅스가 지적해주신 사항 외에는 크게 건드릴 게 없는 것 같아요.
> 스텝이 올라갈 수록 요구사항이 복잡해질텐데 그 때 어떻게 대처하면 좋을 지 같이 논의해봐요.
> 제인누나 화이팅..
> 나 그리고 휴가 못나가 이번에........

놀랍게도 7스텝이 끝이라 벌써 반 정도 왔어요ㅋㅋ 시그리드 군대에 있는데도 시간내어 리뷰해줘서 고마워요🙂

2021-02-17 14:16 UTC, janeljs commented
> 수업 때도 말했지만 포비의 명언을 인용해서 "동의안되는 권위에 굴복하지 마라". 리뷰어의 조언을 적극 수용하는 건 좋지만, 굳이 왜? 라는 생각이 들 때는 안 해도 됩니다.

굳이 왜?까지는 아니지만 의문이 생기는 부분들이 있어 코드 수정 전 질문들 남겼습니다ㅎㅎ 꼼꼼하게 리뷰해주셔서 감사드립니다🙇‍♀️

2021-02-20 12:03 UTC, merged

2021-02-20 12:39 UTC, janeljs commented
@honux77 아직 질문들에 대한 답변을 못 받아 수정을 못하고 있었는데 머지가 되어버렸네용.. 즉각적으로 수정하고 다시 리뷰 요청 못 드려서 죄송합니다ㅠㅠ 다음부터는 답변이 늦더라도 스스로 판단해서 머지 요청드릴게요! 개선할 필요가 없다고 느끼거나 동의되지 않는 권위라고 생각해서 수정을 안 했던 건 아니에요😢